export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / ER + Aero Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 46% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Spearback","echoSet":"MoonlitClouds","stat":"EnergyRegen","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"StonewallBracer","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"Cruisewing","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"SabyrBoar","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / ER + Aero Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 46% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"StonewallBracer","echoSet":"MoonlitClouds","stat":"EnergyRegen","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"ViridblazeSaurian","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"FissionJunrock","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"GlacioPrism","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    }
];

export const rotations: RotationPreset[] = [];