export const rotations: RotationPreset[] = [
  {
    name: `Encore Simple Rotation`,
    description: `Taken from Prydwen`,
    author: `oxmyo`,
    data: {
      name: "Encore Simple Rotation",
      description: "Taken from Prydwen",
      actions: [
        {
          order: 1,
          key: "SkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "CosmosRampageDamage",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "CosmosFrolickingStage1DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "CosmosFrolickingStage2DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "CosmosFrolickingStage3DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "CosmosFrolickingStage4DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "CosmosRampageDamage",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "CosmosFrolickingStage1DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "CosmosFrolickingStage2DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "CosmosFrolickingStage3DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "CosmosFrolickingStage4DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "CosmosRampageDamage",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "CosmosRuptureDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 14,
          key: "OutroSkillDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];

export const echoes = [
  {
    name: `Standard CR Build`,
    description: `43311 CR Molten Rift build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 25.2% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "NightmareInfernoRider",
          echoSet: "MoltenRift",
          stat: "CritRate",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "BasicAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "1": {
          type: 3,
          echo: "HavocDreadmane",
          echoSet: "MoltenRift",
          stat: "Fusion",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "BasicAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "2": {
          type: 3,
          echo: "VioletFeatheredHeron",
          echoSet: "MoltenRift",
          stat: "Fusion",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "3": {
          type: 1,
          echo: "BabyViridblazeSaurian",
          echoSet: "MoltenRift",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "FusionDreadmane",
          echoSet: "MoltenRift",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
      },
    },
  },
  {
    name: `Standard CD Build`,
    description: `43311 CD Molten Rift build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 25.2% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "NightmareInfernoRider",
          echoSet: "MoltenRift",
          stat: "CritDMG",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "BasicAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "1": {
          type: 3,
          echo: "HavocDreadmane",
          echoSet: "MoltenRift",
          stat: "Fusion",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "BasicAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "2": {
          type: 3,
          echo: "VioletFeatheredHeron",
          echoSet: "MoltenRift",
          stat: "Fusion",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "3": {
          type: 1,
          echo: "BabyViridblazeSaurian",
          echoSet: "MoltenRift",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "FusionDreadmane",
          echoSet: "MoltenRift",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 8.4,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
      },
    },
  },
];
