export const skillAttacks = {
  name: "Resonance Skill: Reunion of All the Fallen",
  description: `<div><span class="Title">Golden Reflux</span><br>Flash toward the target and deal <span class="Light">Spectro DMG</span>. Inflict <span class="Highlight" class="font-bold">Tune Strain - Shifting</span> on the target hit for 25s.<br><span class="Highlight" class="font-bold">Golden Reflux</span> has 2 charges.<br>Can be cast in mid-air.<br><br><span class="Title">Aureole of Execution</span><br>Casting <span class="Highlight" class="font-bold">Basic Attack Stage 4</span> or <span class="Highlight" class="font-bold">Mid-air Attack Stage 3</span> replaces <span class="Highlight" class="font-bold">Resonance Skill</span> with <span class="Highlight" class="font-bold">Aureole of Execution</span>, which deals Basic Attack DMG and inflicts <span class="Highlight" class="font-bold">Tune Strain - Shifting</span>< on the target hit for 25s.<br><span class="Highlight" class="font-bold">Aureole of Execution</span> has 3 forms, including <span class="Highlight" class="font-bold">Aureole of Execution: Ring</span>, <span class="Highlight" class="font-bold">Aureole of Execution: Breach</span>, and <span class="Highlight" class="font-bold">Aureole of Execution: Glare</span>.<br>Casting any form of <span class="Highlight" class="font-bold">Aureole of Execution</span> grants 1 stacks of <span class="Highlight" class="font-bold">Endnotes on the Endgame</span> and switches <span class="Highlight" class="font-bold">Aureole of Execution</span> to the next form in sequence.<br>Switching to another Resonator resets the cycle of <span class="Highlight" class="font-bold">Aureole of Execution</span> and <span class="Highlight" class="font-bold">Resonance Skill</span> is reset to <span class="Highlight" class="font-bold">Golden Reflux</span>.<br>Can be cast in mid-air.<br><br><span class="Title">Aureole of Execution: Ring</span><br>Deal <span class="Light">Spectro DMG</span>, and reset the <span class="Highlight" class="font-bold">Mid-air Attack</span> cycle to Stage 1.<br>The next <span class="Highlight" class="font-bold">Normal Attack</span> triggers <span class="Highlight" class="font-bold">Basic Attack - Golden Impale</span>.<br><span class="Highlight" class="font-bold">Basic Attack - Golden Impale</span> is no longer available if <span class="Highlight" class="font-bold">Dodge Counter</span> is cast in mid-air or Luuk Herssen is switched out in the duration.<br><br><span class="Title">Aureole of Execution: Breach</span><br>Spin and dash forward, dealing <span class="Light">Spectro DMG</span> to enemies along the path and resetting the <span class="Highlight" class="font-bold">Mid-air Attack</span> cycle to Stage 1. Then, hurl out an Ichor Blade</span>.<br>The next <span class="Highlight" class="font-bold">Normal Attack</span> triggers <span class="Highlight" class="font-bold">Basic Attack - Golden Impale</span>.<br><span class="Highlight" class="font-bold">Basic Attack - Golden Impale</span> is no longer available if <span class="Highlight" class="font-bold">Dodge Counter</span> is cast in air or Luuk Herssen is switched out in the duration.<br><br><span class="Title">Aureole of Execution: Glare</span><br>Hurl out Solid-State Ichor, dealing <span class="Light">Spectro DMG</span> and forming an <span class="Highlight" class="font-bold">Ichor Deposit</span> on the ground.<br><br><span class="Title">Basic Attack - Golden Impale</span><br>Flash toward the target and deal <span class="Light">Spectro DMG</span>, considered Basic Attack DMG.<br><br><span class="Title">Ichor Deposit</span><br><span class="Highlight" class="font-bold">Ichor Deposit</span> detonates automatically after 5s, dealing <span class="Light">Spectro DMG</span>, considered Basic Attack DMG.<br><br><span class="Title">Endnotes on the Endgame</span><br>Increase the DMG Multiplier of Resonance Liberation <span class="Highlight" class="font-bold">Rewritten in Winter's Margins</span> by 25%, stacking up to 3 times. Casting <span class="Highlight" class="font-bold">Rewritten in Winter's Margins</span> or switching to another Resonator removes all stacks.</div>`,
  attacks: [
    {
      key: "GoldenRefluxDMG",
      label: "Golden Reflux DMG",
      talents: {
        "1": "101.20%",
        "2": "109.50%",
        "3": "117.80%",
        "4": "129.42%",
        "5": "137.72%",
        "6": "147.26%",
        "7": "160.54%",
        "8": "173.82%",
        "9": "187.09%",
        "10": "201.20%",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionRingDMG",
      label: "Aureole of Execution: Ring DMG",
      talents: {
        "1": "13.36%*5+44.53%",
        "2": "14.46%*5+48.18%",
        "3": "15.55%*5+51.84%",
        "4": "17.09%*5+56.95%",
        "5": "18.18%*5+60.60%",
        "6": "19.44%*5+64.80%",
        "7": "21.20%*5+70.64%",
        "8": "22.95%*5+76.48%",
        "9": "24.70%*5+82.32%",
        "10": "26.56%*5+88.53%",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionBreachDMG",
      label: "Aureole of Execution: Breach DMG",
      talents: {
        "1": "48.24%*3",
        "2": "52.20%*3",
        "3": "56.15%*3",
        "4": "61.69%*3",
        "5": "65.65%*3",
        "6": "70.20%*3",
        "7": "76.53%*3",
        "8": "82.85%*3",
        "9": "89.18%*3",
        "10": "95.91%*3",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionGlareDMG",
      label: "Aureole of Execution: Glare DMG",
      talents: {
        "1": "178.12%",
        "2": "192.72%",
        "3": "207.33%",
        "4": "227.77%",
        "5": "242.38%",
        "6": "259.18%",
        "7": "282.54%",
        "8": "305.91%",
        "9": "329.28%",
        "10": "354.11%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackGoldenImpaleDMG",
      label: "Basic Attack - Golden Impale DMG",
      talents: {
        "1": "78.20%",
        "2": "84.62%",
        "3": "91.03%",
        "4": "100.01%",
        "5": "106.42%",
        "6": "113.79%",
        "7": "124.05%",
        "8": "134.31%",
        "9": "144.57%",
        "10": "155.47%",
      },
      type: "Basic",
    },
    {
      key: "IchorDepositDMG",
      label: "Ichor Deposit DMG",
      talents: {
        "1": "77.19%",
        "2": "83.52%",
        "3": "89.84%",
        "4": "98.71%",
        "5": "105.03%",
        "6": "112.31%",
        "7": "122.44%",
        "8": "132.56%",
        "9": "142.69%",
        "10": "153.45%",
      },
      type: "Basic",
    },
  ],
};
