export const forteCircuitAttacks = {
  name: "Forte Circuit: Mass-Energy Equivalence",
  description: `<div><span class="Title"><strong>Baseline Mode</strong></span><br>While in herault <span class="Highlight"><strong>Baseline Mode</strong></span>, Mornye gains <span class="Highlight"><strong></strong></span>.<br><br><span class="Title"><strong>Heavy Attack - Geopotential Shift</strong></span><br>When <span class="Highlight"><strong></strong></span> reaches 100 points, Heavy Attack is replaced with <span class="Highlight"><strong>Heavy Attack - Geopotential Shift</strong></span>.<br>Cast <span class="Highlight"><strong>Heavy Attack - Geopotential Shift</strong></span> to deal <span class="Fusion"><strong>Fusion DMG</strong></span>, considered Heavy Attack DMG. Afterward, Mornye jumps into mid-air, consumes all <span class="Highlight"><strong></strong></span> and enters <span class="Highlight"><strong></strong></span>.<br><br><span class="Title"><strong>Wide Field Observation Mode</strong></span><br><span class="Highlight"><strong>Wide Field Observation Mode</strong></span> lasts for 30s.<br>- Upon entering <span class="Highlight"><strong>Wide Field Observation Mode</strong></span>, Mornye generates a <span class="Highlight"><strong></strong></span>.<br>- While in <span class="Highlight"><strong>Wide Field Observation Mode</strong></span>, Mornye gains <span class="Highlight"><strong></strong></span>.<br>- If <span class="Highlight"><strong></strong></span> is below 100 when holding <span class="Highlight"><strong>Normal Attack</strong></span>, perform <span class="Highlight"><strong>Basic Attack - Wide Field Observation Mode Stage 1 to 3</strong></span> in sequence. If <span class="Highlight"><strong></strong></span> reaches 100 during this time, cast <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span> instead.<br>- While moving, Mornye continuously consumes STA. STA cannot be recovered while in <span class="Highlight"><strong>Wide Field Observation Mode</strong></span>.<br>- When <span class="Highlight"><strong>Dodging</strong></span> with directional input, Mornye starts to fly at speed, which lasts for up to 10s or until STA is depleted or until the <span class="Highlight"><strong>Wide Field Observation Mode</strong></span> ends.<br>- When Mornye is hit or launched into mid-air, press <span class="Highlight"><strong>Dodge</strong></span> to immediately recover from the attack, which is considered a successful Dodge. This effect can be triggered up to 3 times, which resets when <span class="Highlight"><strong>Wide Field Observation Mode</strong></span> ends.<br>- Press Jump and Mornye will slowly descend. Before she lands, <span class="Highlight"><strong>Basic Attack - Wide Field Observation Mode</strong></span>, <span class="Highlight"><strong>Resonance Skill - Distributed Array</strong></span>, and <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span> are unavailable. If Jump is pressed when Mornye runs out of STA, she will exit the <span class="Highlight"><strong>Wide Field Observation Mode</strong></span>. She will leave the <span class="Highlight"><strong>Wide Field Observation Mode</strong></span> also when she <span class="Highlight"><strong>Dodges</strong></span>, Jumps, or performs Mid-air Attacks.<br>Additionally, performing environmental interactions, using Utilities, or switching to another Resonator ends <span class="Highlight"><strong>Wide Field Observation Mode</strong></span>. The state also ends when Mornye is no longer airborne.<br><br><span class="Title"><strong>Syntony Field</strong></span><br>- <span class="Highlight"><strong>Syntony Field</strong></span> lasts for 25s.<br>- When the <span class="Highlight"><strong>Syntony Field</strong></span> is generated, deal <span class="Fusion"><strong>Fusion DMG</strong></span>, considered Resonance Liberation DMG.<br>- Continuously restores HP for nearby active Resonators in the team within the <span class="Highlight"><strong>Syntony Field</strong></span>, triggered once every 3s.<br>- Increases the <span class="Highlight"><strong>Off-Tune Buildup Rate</strong></span> of all nearby Resonators in the team within the <span class="Highlight"><strong>Syntony Field</strong></span> by 50%.<br>- Enhances the resistance to interruption of nearby active Resonators in the team within the <span class="Highlight"><strong>Syntony Field</strong></span>.<br><br><span class="Title"><strong>Heavy Attack - Inversion</strong></span><br>- When <span class="Highlight"><strong></strong></span> reaches 100 points, Heavy Attack is replaced with <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span>.<br>- Consume all <span class="Highlight"><strong></strong></span> to cast <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span>, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>, considered Heavy Attack DMG.<br>- <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span> inflicts <span class="Highlight"><strong></strong></span> upon the target on hit for 30s.<br><br><span class="Title"><strong>Observation Marker</strong></span><br>When a Resonator in the team deals <span class="Highlight"><strong></strong></span> DMG to a target inflicted with <span class="Highlight"><strong>Observation Marker</strong></span>, Mornye inflicts an <span class="Highlight"><strong></strong></span> on the target for 8s.<br><br><span class="Title"><strong>Interfered Marker</strong></span><br>Targets affected by <span class="Highlight"><strong></strong></span> or <span class="Highlight"><strong></strong></span> take increased DMG from all nearby Resonators in the team. For every 1% of Mornye's Energy Regen exceeding 100%, their DMG is increased by 0.25%, up to 40%.<br><br><span class="Title"><strong>Visual Field</strong></span><br>When a Resonator in the teameats a target inflicted with <span class="Highlight"><strong></strong></span> or <span class="Highlight"><strong></strong></span>, Mornye gains <span class="Highlight"><strong>Visual Field</strong></span> for 3s. While in this state, Mornye inflicts <span class="Highlight"><strong></strong></span> on the target hit whenever any Resonator in the team deals damage.<br><br><span class="Title"><strong>Tune Rupture Response - Particle Jet</strong></span><br>Mornye deals one instance of <span class="Fusion"><strong>Fusion DMG</strong></span> to targets in the <span class="Highlight"><strong></strong></span> state within range, considered <span class="Highlight"><strong>Tune Rupture DMG</strong></span>.<br><br><span class="Title"><strong>Rest Mass Energy</strong></span><br>Mornye can hold up to 100 points of <span class="Highlight"><strong>Rest Mass Energy</strong></span>.<br>While in <span class="Highlight"><strong></strong></span>, she gains <span class="Highlight"><strong>Rest Mass Energy</strong></span> when performing <span class="Highlight"><strong>Basic Attack</strong></span>, <span class="Highlight"><strong>Heavy Attack</strong></span>, <span class="Highlight"><strong>Dodge Counter</strong></span>, or when <span class="Highlight"><strong>Resonance Skill - Optimal Solution</strong></span> hits a target.<br><br><span class="Title"><strong>Relative Momentum</strong></span><br>Mornye can hold up to 100 points of <span class="Highlight"><strong>Relative Momentum</strong></span>.<br>While in <span class="Highlight"><strong></strong></span>, she gains <span class="Highlight"><strong>Relative Momentum</strong></span> when <span class="Highlight"><strong>Basic Attack - Wide Field Observation Mode</strong></span>, <span class="Highlight"><strong>Dodge Counter - Wide Field Observation Mode</strong></span> or <span class="Highlight"><strong>Resonance Skill - Distributed Array</strong></span> hits the target.<br>Mornye cannot gain <span class="Highlight"><strong>Relative Momentum</strong></span> during <span class="Highlight"><strong>Heavy Attack - Inversion</strong></span>.</div>`,
  attacks: [
    {
      key: "SyntonyFieldHealing",
      label: "Syntony Field Healing",
      type: "Healing",
      attribute: "defense",
      talents: {
        "1": "40+9.63%",
        "2": "44+10.02%",
        "3": "50+10.41%",
        "4": "56+10.98%",
        "5": "63+11.75%",
        "6": "70+12.53%",
        "7": "71+13.97%",
        "8": "73+15.61%",
        "9": "74+17.35%",
        "10": "76+20.24%",
      },
    },
    {
      key: "SyntonyFieldDMG",
      label: "Syntony Field DMG",
      type: "Liberation",
      talents: {
        "1": "20.00%*5",
        "2": "21.64%*5",
        "3": "23.28%*5",
        "4": "25.58%*5",
        "5": "27.22%*5",
        "6": "29.11%*5",
        "7": "31.73%*5",
        "8": "34.35%*5",
        "9": "36.98%*5",
        "10": "39.77%*5",
      },
    },
    {
      key: "HeavyAttackGeopotentialShiftDMG",
      label: "Heavy Attack - Geopotential Shift DMG",
      type: "Heavy",
      talents: {
        "1": "22.20%+49.81%",
        "2": "24.02%+53.89%",
        "3": "25.84%+57.97%",
        "4": "28.39%+63.69%",
        "5": "30.21%+67.78%",
        "6": "32.30%+72.47%",
        "7": "35.22%+79.01%",
        "8": "38.13%+85.54%",
        "9": "41.04%+92.07%",
        "10": "44.14%+99.02%",
      },
    },
    {
      key: "HeavyAttackInversionDMG",
      label: "Heavy Attack - Inversion DMG",
      type: "Heavy",
      talents: {
        "1": "130.00%",
        "2": "140.66%",
        "3": "151.32%",
        "4": "166.25%",
        "5": "176.91%",
        "6": "189.17%",
        "7": "206.22%",
        "8": "223.28%",
        "9": "240.34%",
        "10": "258.46%",
      },
    },
    {
      key: "TuneRuptureResponseParticleJetDMG",
      label: "Tune Rupture Response - Particle Jet DMG",
      type: "TuneBreak",
      talents: {
        "1": "150.00%",
        "2": "162.30%",
        "3": "174.60%",
        "4": "191.82%",
        "5": "204.12%",
        "6": "218.27%",
        "7": "237.95%",
        "8": "257.63%",
        "9": "277.31%",
        "10": "298.22%",
      },
    },
  ],
};
