export const rotations: RotationPreset[] = [
  {
    name: `Support Rotation`,
    description: `Basic 123 > Forte HA > Basic 123 > Skill > HA > Lib > Echo > Outro`,
    author: `Lavasnake`,
    data: {"name":"Support Rotation","description":"Basic 123 > Forte HA > Basic 123 > Skill > HA > Lib > Echo > Outro","actions":[{"order":1,"key":"BasicAttackStage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":2,"key":"BasicAttackStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":3,"key":"BasicAttackStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":4,"key":"HeavyAttackGeopotentialShiftDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":5,"key":"SyntonyFieldHealing","type":"forteCircuit","count":"8","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":6,"key":"BasicAttackWideFieldObservationModeStage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":7,"key":"BasicAttackWideFieldObservationModeStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":8,"key":"BasicAttackWideFieldObservationModeStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":9,"key":"DistributedArrayDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":10,"key":"DistributedArrayHealing","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":11,"key":"CriticalProtocolDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":12,"key":"HyvatiaLasersDMG","type":"echoAttacks","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"mainEcho":"ReactorHusk","mainEchoRank":5}],"echo":"ReactorHusk"},
  },
];

export const echoes = [];
