export const resonanceChains = [
  {
    key: "SequenceNode1TheSilentObserver",
    name: "Sequence Node 1: The Silent Observer",
    details: `<div><span class="Highlight"><strong>Basic Attack – Wide Field Observation Mode</strong></span> becomes immune to interruption.<br>The duration of <span class="Highlight"><strong>Interfered Marker</strong></span> is extended by 150%. <span class="Highlight"><strong>Interfered Marker</strong></span> now grants DMG increase even when the target is not affected by <span class="Highlight"><strong>Tune Rupture - Interfered</strong></span> or <span class="Highlight"><strong>Tune Strain - Interfered</strong></span>. When Mornye applies <span class="Highlight"><strong>Observation Marker</strong></span> on a target, she also inflicts <span class="Highlight"><strong>Interfered Marker</strong></span>.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode2MorningStarofEntropy",
    name: "Sequence Node 2: Morning Star of Entropy",
    details: `<div>All nearby Resonators in the team gain Crit. DMG increase against targets with <span class="Highlight"><strong>Interfered Marker</strong></span>: Every 1% of Mornye's Energy Regen over 100% grants 0.2% Crit. DMG increase, up to 32%.<br><span class="Highlight"><strong>Syntony Field</strong></span> and <span class="Highlight"><strong>High Syntony Field</strong></span> further increase the <span class="Highlight"><strong>Off-Tune Buildup Rate</strong></span> of all nearby Resonators in the team by 20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG:AdditionalBase",
        modifierValue: 0.002,
        maximumValue: 0.32,
        modifierStep: 1,
        modifierBasedOn: "EnergyRegen",
        modifierTargetAttr: "CritDMG",
        minStatValue: 1,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode3BlueprintofRecursion",
    name: "Sequence Node 3: Blueprint of Recursion",
    details: `<div>Casting <span class="Highlight"><strong>Resonance Skill - Distributed Array</strong></span> additionally restores 25 points of Concerto Energy and 100 <span class="Highlight"><strong>Relative Momentum<strong></strong></span>, triggered once every 25s.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode4LatentVariablesoftheCosmos",
    name: "Sequence Node 4: Latent Variables of the Cosmos",
    details: `<span class="skilldescription">The healing of <span class="Highlight"><strong>High Syntony Field</strong></span> is increased by 30%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HealingBonus",
        modifySpecificTalents: ["SyntonyFieldHealing"],
        modifierValue: 0.3,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode5TimeDilationEffect",
    name: "Sequence Node 5: Time Dilation Effect",
    details: `<div>The DMG Multiplier of <span class="Highlight"><strong>Resonance Liberation - Critical Protocol</strong></span> is increased by 40%.<br>The DMG Multiplier of <span class="Highlight"><strong>Tune Rupture Response - Particle Jet</strong></span> is increased by 160%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["CriticalProtocolDMG"],
        modifierValue: 0.4,
      },
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["TuneRuptureResponseParticleJetDMG"],
        modifierValue: 1.6,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode6TotheFarShoresoftheStars",
    name: "Sequence Node 6: To the Far Shores of the Stars",
    details: `<div><span class="Highlight"><strong>Resonance Liberation - Critical Protocol</strong></span> deals 400% more DMG. If Mornye has not engaged in combat for over 4s, she restores Resonance Energy equal to 10% of her Max Resonance Energy every 0.2s.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "specialMultiplier",
        modifySpecificTalents: ["CriticalProtocolDMG"],
        modifierValue: 4,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
