export const skillAttacks = {
  name: "Resonance Skill: Resolution",
  description: `<div><span class="Title"><strong>Expectation Error</strong></span><br>Heal all nearby Resonators in the team and enter the Parry state, during which DMG taken is reduced by 100% for a time. Switching to another Resonator ends this state immediately.<br>If attacked while in the Parry state, exit the state and cast <span class="Highlight"><strong>Resonance Skill - Optimal Solution</strong></span>.<br>If not attacked while in the Parry state, press <span class="Highlight"><strong>Normal Attack</strong></span> to exit the state and cast <span class="Highlight"><strong>Basic Attack Stage 2</strong></span>.<br><br><span class="Title"><strong>Optimal Solution</strong></span><br>Stagnate nearby targets and deal <span class="Fusion"><strong>Fusion DMG</strong></span>, reducing the cooldown of <span class="Highlight"><strong>Resonance Skill - Expectation Error</strong></span> by 2s.<br>Switching to another Resonator ends the Stagnation effect early.<br><br><span class="Title"><strong>Distributed Array</strong></span><br>While in <span class="Highlight"><strong></strong></span>, Resonance Skill is replaced with <span class="Highlight"><strong>Resonance Skill - Distributed Array</strong></span>.<br>Heal all nearby Resonators in the team and summon Hover Cannons to strike the target, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.</div>`,
  attacks: [
    {
      key: "DistributedArrayHealing",
      label: "Distributed Array Healing",
      type: "Healing",
      attribute: "def",
      talents: {
        "1": "225+54.00%",
        "2": "252+56.16%",
        "3": "281+58.32%",
        "4": "315+61.56%",
        "5": "355+65.88%",
        "6": "393+70.20%",
        "7": "400+78.30%",
        "8": "409+87.48%",
        "9": "416+97.20%",
        "10": "427+113.40%",
      },
    },
    {
      key: "ExpectationErrorHealing",
      label: "Expectation Error Healing",
      type: "Healing",
      attribute: "def",
      talents: {
        "1": "49+11.88%",
        "2": "55+12.35%",
        "3": "61+12.83%",
        "4": "69+13.54%",
        "5": "78+14.49%",
        "6": "86+15.44%",
        "7": "88+17.22%",
        "8": "90+19.24%",
        "9": "91+21.38%",
        "10": "94+24.94%",
      },
    },
    {
      key: "OptimalSolutionDMG",
      label: "Optimal Solution DMG",
      type: "Skill",
      talents: {
        "1": "90.40%",
        "2": "97.82%",
        "3": "105.23%",
        "4": "115.61%",
        "5": "123.02%",
        "6": "131.55%",
        "7": "143.41%",
        "8": "155.27%",
        "9": "167.13%",
        "10": "179.73%",
      },
    },
    {
      key: "DistributedArrayDMG",
      label: "Distributed Array DMG",
      type: "Skill",
      talents: {
        "1": "20.00%*4",
        "2": "21.64%*4",
        "3": "23.28%*4",
        "4": "25.58%*4",
        "5": "27.22%*4",
        "6": "29.11%*4",
        "7": "31.73%*4",
        "8": "34.35%*4",
        "9": "36.98%*4",
        "10": "39.77%*4",
      },
    },
  ],
};
