export interface ResistStats {
  Aero?: number;
  Electro?: number;
  Fusion?: number;
  Glacio?: number;
  Havoc?: number;
  Physical?: number;
  Spectro?: number;
}

export interface Enemy {
  imageUrl: string;
  name: string;
  type: string;
  resist: ResistStats;
}

const enemies: Record<string, Enemy> = {
  bellBorneGeochelone: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000020.webp",
    name: "Bell-Borne Geochelone",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  scarAberrantNightmare: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000050.webp",
    name: "Scar: Aberrant Nightmare",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  dreamless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000070.webp",
    name: "Dreamless",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  ju: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000090.webp",
    name: "Jué",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomDreamless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000090.webp",
    name: "Phantom: Dreamless",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  hecate: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000100.webp",
    name: "Hecate",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fleurdelys: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000120.webp",
    name: "Fleurdelys",
    type: "Calamity",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  reminiscenceFleurdelys: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000121.webp",
    name: "Reminiscence: Fleurdelys",
    type: "Calamity",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareHecate: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000160.webp",
    name: "Nightmare: Hecate",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  hecate2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000190.webp",
    name: "Hecate",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  threnodianLeviathan: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000200.webp",
    name: "Threnodian: Leviathan",
    type: "Calamity",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  reminiscenceThrenodianLeviathan: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000201.webp",
    name: "Reminiscence: Threnodian - Leviathan",
    type: "Calamity",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomSigillum: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000360.webp",
    name: "Phantom: Sigillum",
    type: "Calamity",
    resist: {
    },
  },
  sigillum: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000250.webp",
    name: "Sigillum",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  sigillum2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000251.webp",
    name: "Sigillum",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  voidworm: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000240.webp",
    name: "Voidworm",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  stayTuned: {
    imageUrl: "https://api-v2.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34027_UI.webp",
    name: "Stay tuned",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  stayTuned2: {
    imageUrl: "https://api-v2.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_34028_UI.webp",
    name: "Stay tuned",
    type: "Calamity",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  tempestMephis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000010.webp",
    name: "Tempest Mephis",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  crownless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000010.webp",
    name: "Crownless",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  infernoRider: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000020.webp",
    name: "Inferno Rider",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  impermanenceHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000030.webp",
    name: "Impermanence Heron",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  lampylumenMyriad: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000040.webp",
    name: "Lampylumen Myriad",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  feilianBeringal: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000050.webp",
    name: "Feilian Beringal",
    type: "Overlord",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  mourningAix: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000060.webp",
    name: "Mourning Aix",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  mechAbomination: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000060.webp",
    name: "Mech Abomination",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  thunderingMephis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000080.webp",
    name: "Thundering Mephis",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomMourningAix: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000010.webp",
    name: "Phantom: Mourning Aix",
    type: "Overlord",
    resist: {
    },
  },
  phantomThunderingMephis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000040.webp",
    name: "Phantom: Thundering Mephis",
    type: "Overlord",
    resist: {
    },
  },
  phantomFeilianBeringal: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000050.webp",
    name: "Phantom: Feilian Beringal",
    type: "Overlord",
    resist: {
    },
  },
  phantomImpermanenceHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000060.webp",
    name: "Phantom: Impermanence Heron",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  fallacyOfNoReturn: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000070.webp",
    name: "Fallacy of No Return",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomInfernoRider: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000120.webp",
    name: "Phantom: Inferno Rider",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  scarLightbaneReversal: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000100.webp",
    name: "Scar: Lightbane Reversal",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  lorelei: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000110.webp",
    name: "Lorelei",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  sentryConstruct: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000120.webp",
    name: "Sentry Construct",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  dragonOfDirge: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000130.webp",
    name: "Dragon of Dirge",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomSentryConstruct: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000160.webp",
    name: "Phantom: Sentry Construct",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomLorelei: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000170.webp",
    name: "Phantom: Lorelei",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomCrownless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000200.webp",
    name: "Phantom: Crownless",
    type: "Overlord",
    resist: {
    },
  },
  lionessOfGlory: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000140.webp",
    name: "Lioness of Glory",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fenrico: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000150.webp",
    name: "Fenrico",
    type: "Overlord",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomNightmareInfernoRider: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000250.webp",
    name: "Phantom: Nightmare Inferno Rider",
    type: "Overlord",
    resist: {
    },
  },
  theFalseSovereign: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000170.webp",
    name: "The False Sovereign",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  lionessOfGlory2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000141.webp",
    name: "Lioness of Glory",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  reminiscenceFenrico: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000151.webp",
    name: "Reminiscence: Fenrico",
    type: "Overlord",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  ladyOfTheSea: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000180.webp",
    name: "Lady of the Sea",
    type: "Overlord",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomNightmareMourningAix: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000260.webp",
    name: "Phantom: Nightmare Mourning Aix",
    type: "Overlord",
    resist: {
    },
  },
  phantomFallacyOfNoReturn: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000270.webp",
    name: "Phantom: Fallacy of No Return",
    type: "Overlord",
    resist: {
    },
  },
  phantomLionessOfGlory: {
    imageUrl: "https://api-v2.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Image/IconMonsterHead/T_IconMonsterHead_SG_33022_UI.webp",
    name: "Phantom: Lioness of Glory",
    type: "Overlord",
    resist: {
    },
  },
  phantomTheFalseSovereign: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000310.webp",
    name: "Phantom: The False Sovereign",
    type: "Overlord",
    resist: {
    },
  },
  fallacyOfNoReturn2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000230.webp",
    name: "Fallacy of No Return",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  hyvatia: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000210.webp",
    name: "Hyvatia",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  reactorHusk: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000220.webp",
    name: "Reactor Husk",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  theFalseSovereign2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000171.webp",
    name: "The False Sovereign",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  hyvatia2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000211.webp",
    name: "Hyvatia",
    type: "Overlord",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  namelessExplorer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000260.webp",
    name: "Nameless Explorer",
    type: "Overlord",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomReactorHusk: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000380.webp",
    name: "Phantom: Reactor Husk",
    type: "Overlord",
    resist: {
    },
  },
  stonewallBracer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000010.webp",
    name: "Stonewall Bracer",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  violetFeatheredHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000020.webp",
    name: "Violet-Feathered Heron",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  cyanFeatheredHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000030.webp",
    name: "Cyan-Feathered Heron",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  flautist: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000040.webp",
    name: "Flautist",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  tambourinist: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000050.webp",
    name: "Tambourinist",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  rocksteadyGuardian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000060.webp",
    name: "Rocksteady Guardian",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  chasmGuardian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000070.webp",
    name: "Chasm Guardian",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  viridblazeSaurian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000080.webp",
    name: "Viridblaze Saurian",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  roseshroom: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000090.webp",
    name: "Roseshroom",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  HavocDreadmane: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000100.webp",
    name: "Havoc Dreadmane",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  hoochiefCyclone: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000110.webp",
    name: "Hoochief Cyclone",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  spearback: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000120.webp",
    name: "Spearback",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  carapace: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000130.webp",
    name: "Carapace",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  exileLeader: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000140.webp",
    name: "Exile Leader",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  exileTechnician: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000150.webp",
    name: "Exile Technician",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  fractsidusExecutioner: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000160.webp",
    name: "Fractsidus Executioner",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  hoochiefMenace: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000170.webp",
    name: "Hoochief Menace",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  autopuppetScout: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000180.webp",
    name: "Autopuppet Scout",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomRocksteadyGuardian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000020.webp",
    name: "Phantom: Rocksteady Guardian",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  GlacioDreadmane: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000190.webp",
    name: "Glacio Dreadmane",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  lumiscaleConstruct: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000200.webp",
    name: "Lumiscale Construct",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  lightcrusher: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000210.webp",
    name: "Lightcrusher",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomLightcrusher: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000080.webp",
    name: "Phantom: Lightcrusher",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomLumiscaleConstruct: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000110.webp",
    name: "Phantom: Lumiscale Construct",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  questlessKnight: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000220.webp",
    name: "Questless Knight",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  diurnusKnight: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000230.webp",
    name: "Diurnus Knight",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  nocturnusKnight: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000240.webp",
    name: "Nocturnus Knight",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  abyssalPatricius: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000250.webp",
    name: "Abyssal Patricius",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  abyssalGladius: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000260.webp",
    name: "Abyssal Gladius",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  abyssalMercator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000270.webp",
    name: "Abyssal Mercator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  chopChop: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000280.webp",
    name: "Chop Chop",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  vitreumDancer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000290.webp",
    name: "Vitreum Dancer",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  cuddleWuddle: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000300.webp",
    name: "Cuddle Wuddle",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareFeilianBeringal: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000140.webp",
    name: "Nightmare: Feilian Beringal",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareImpermanenceHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000150.webp",
    name: "Nightmare: Impermanence Heron",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareThunderingMephis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000160.webp",
    name: "Nightmare: Thundering Mephis",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareTempestMephis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000170.webp",
    name: "Nightmare: Tempest Mephis",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareCrownless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000180.webp",
    name: "Nightmare: Crownless",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareInfernoRider: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000190.webp",
    name: "Nightmare: Inferno Rider",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareMourningAix: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/330000200.webp",
    name: "Nightmare: Mourning Aix",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomVitreumDancer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000140.webp",
    name: "Phantom: Vitreum Dancer",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomQuestlessKnight: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000150.webp",
    name: "Phantom: Questless Knight",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  rageAgainstTheStatue: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000310.webp",
    name: "Rage Against the Statue",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  hurriclaw: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000320.webp",
    name: "Hurriclaw",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  capitaneus: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000330.webp",
    name: "Capitaneus",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomCapitaneus: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000180.webp",
    name: "Phantom: Capitaneus",
    type: "Elite",
    resist: {
    },
  },
  nightmareLampylumenMyriad: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000130.webp",
    name: "Nightmare: Lampylumen Myriad",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomNightmareCrownless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000210.webp",
    name: "Phantom: Nightmare Crownless",
    type: "Elite",
    resist: {
    },
  },
  kerasaur: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000340.webp",
    name: "Kerasaur",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  pilgrimSShell: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000350.webp",
    name: "Pilgrim's Shell",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareKelpie: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/340000110.webp",
    name: "Nightmare: Kelpie",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomCuddleWuddle: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000240.webp",
    name: "Phantom: Cuddle Wuddle",
    type: "Elite",
    resist: {
    },
  },
  flamecrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000360.webp",
    name: "Flamecrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  galecrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000370.webp",
    name: "Galecrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  lightcrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000380.webp",
    name: "Lightcrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  frostcrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000390.webp",
    name: "Frostcrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  thundercrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000400.webp",
    name: "Thundercrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  abysscrestGladiator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000410.webp",
    name: "Abysscrest Gladiator",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusInspector: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000420.webp",
    name: "Fractsidus Inspector",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareTambourinist: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000430.webp",
    name: "Nightmare: Tambourinist",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  corrosaurus: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000440.webp",
    name: "Corrosaurus",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomKerasaur: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000280.webp",
    name: "Phantom: Kerasaur",
    type: "Elite",
    resist: {
    },
  },
  nightmareVioletFeatheredHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000450.webp",
    name: "Nightmare: Violet-Feathered Heron",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareCyanFeatheredHeron: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000460.webp",
    name: "Nightmare: Cyan-Feathered Heron",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareViridblazeSaurian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000470.webp",
    name: "Nightmare: Viridblaze Saurian",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareRoseshroom: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000480.webp",
    name: "Nightmare: Roseshroom",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  twinNovaNebulousCannon: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000490.webp",
    name: "Twin Nova: Nebulous Cannon",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  twinNovaCollapsarBlade: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000500.webp",
    name: "Twin Nova: Collapsar Blade",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  sabercatProwler: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000560.webp",
    name: "Sabercat Prowler",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  frostbiteColeoid: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000570.webp",
    name: "Frostbite Coleoid",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  windlashColeoid: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000580.webp",
    name: "Windlash Coleoid",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  floraReindeer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000510.webp",
    name: "Flora Reindeer",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  miningReindeer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000520.webp",
    name: "Mining Reindeer",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  ironhoof: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000530.webp",
    name: "Ironhoof",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  spacetrekExplorer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000540.webp",
    name: "Spacetrek Explorer",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  sabercatReaver: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000550.webp",
    name: "Sabercat Reaver",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomTwinNovaNebulousCannon: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000340.webp",
    name: "Phantom: Twin Nova - Nebulous Cannon",
    type: "Elite",
    resist: {
    },
  },
  phantomTwinNovaCollapsarBlade: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000350.webp",
    name: "Phantom: Twin Nova - Collapsar Blade",
    type: "Elite",
    resist: {
    },
  },
  phantomChopChop: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000300.webp",
    name: "Phantom: Chop Chop",
    type: "Elite",
    resist: {
    },
  },
  kronablight: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000590.webp",
    name: "Kronablight",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  kronaclaw: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000600.webp",
    name: "Kronaclaw",
    type: "Elite",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  glommoth: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000610.webp",
    name: "Glommoth",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusMilliner: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000620.webp",
    name: "Fractsidus Milliner",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  phagositeBipolarch: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000630.webp",
    name: "Phagosite: Bipolarch",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  phagositeHysterarch: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000640.webp",
    name: "Phagosite: Hysterarch",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phagositeMiserarch: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000650.webp",
    name: "Phagosite: Miserarch",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  voidwingMoth: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/320000660.webp",
    name: "Voidwing Moth",
    type: "Elite",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomKronaclaw: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000390.webp",
    name: "Phantom: Kronaclaw",
    type: "Elite",
    resist: {
    },
  },
  vanguardJunrock: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000010.webp",
    name: "Vanguard Junrock",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fissionJunrock: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000020.webp",
    name: "Fission Junrock",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  ElectroPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000030.webp",
    name: "Electro Predator",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  GlacioPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000040.webp",
    name: "Glacio Predator",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  AeroPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000050.webp",
    name: "Aero Predator",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  FusionWarrior: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000060.webp",
    name: "Fusion Warrior",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  HavocWarrior: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000070.webp",
    name: "Havoc Warrior",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  snipSnap: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000080.webp",
    name: "Snip Snap",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  zigZag: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000090.webp",
    name: "Zig Zag",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  whiffWhaff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000100.webp",
    name: "Whiff Whaff",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  tickTack: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000110.webp",
    name: "Tick Tack",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  gulpuff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000120.webp",
    name: "Gulpuff",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  chirpuff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000130.webp",
    name: "Chirpuff",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  GlacioPrism: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000140.webp",
    name: "Glacio Prism",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 100,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  FusionPrism: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000150.webp",
    name: "Fusion Prism",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 100,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  SpectroPrism: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000160.webp",
    name: "Spectro Prism",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 100,
    },
  },
  HavocPrism: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000170.webp",
    name: "Havoc Prism",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 100,
      Physical: 10,
      Spectro: 10,
    },
  },
  cruisewing: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000180.webp",
    name: "Cruisewing",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  sabyrBoar: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000190.webp",
    name: "Sabyr Boar",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  excarat: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000200.webp",
    name: "Excarat",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  babyViridblazeSaurian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000210.webp",
    name: "Baby Viridblaze Saurian",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  babyRoseshroom: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000220.webp",
    name: "Baby Roseshroom",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  exile: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000230.webp",
    name: "Exile",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  exile2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000240.webp",
    name: "Exile",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  hooscampFlinger: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000250.webp",
    name: "Hooscamp Flinger",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  diamondclaw: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000260.webp",
    name: "Diamondclaw",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  hoartoise: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000270.webp",
    name: "Hoartoise",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  FusionDreadmane: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000280.webp",
    name: "Fusion Dreadmane",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusThruster: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000290.webp",
    name: "Fractsidus Thruster",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  hooscampClapperclaw: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000300.webp",
    name: "Hooscamp Clapperclaw",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusCannoneer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000310.webp",
    name: "Fractsidus Cannoneer",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusGunmaster: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000320.webp",
    name: "Fractsidus Gunmaster",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  trafficIlluminator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000330.webp",
    name: "Traffic Illuminator",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  clangBang: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000340.webp",
    name: "Clang Bang",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomHoartoise: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000030.webp",
    name: "Phantom: Hoartoise",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  lavaLarva: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000350.webp",
    name: "Lava Larva",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  dwarfCassowary: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000360.webp",
    name: "Dwarf Cassowary",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomClangBang: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000070.webp",
    name: "Phantom: Clang Bang",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomGulpuff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000100.webp",
    name: "Phantom: Gulpuff",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  galescourgeStalker: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000370.webp",
    name: "Galescourge Stalker",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  voltscourgeStalker: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000380.webp",
    name: "Voltscourge Stalker",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  frostscourgeStalker: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000390.webp",
    name: "Frostscourge Stalker",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  chopChopHeadless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000400.webp",
    name: "Chop Chop: Headless",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  chopChopLeftless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000410.webp",
    name: "Chop Chop: Leftless",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  chopChopRightless: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000420.webp",
    name: "Chop Chop: Rightless",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  faeIgnis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000430.webp",
    name: "Fae Ignis",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nimbusWraith: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000440.webp",
    name: "Nimbus Wraith",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  hocusPocus: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000450.webp",
    name: "Hocus Pocus",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  lottieLost: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000460.webp",
    name: "Lottie Lost",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  diggyDuggy: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000470.webp",
    name: "Diggy Duggy",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  chestMimic: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000480.webp",
    name: "Chest Mimic",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  phantomDiggyDuggy: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000130.webp",
    name: "Phantom: Diggy Duggy",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  goldenJunrock: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000490.webp",
    name: "Golden Junrock",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  calcifiedJunrock: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000500.webp",
    name: "Calcified Junrock",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  AeroPrism: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000510.webp",
    name: "Aero Prism",
    type: "Standard",
    resist: {
      Aero: 100,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  laGuardia: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000520.webp",
    name: "La Guardia",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  sagittario: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000530.webp",
    name: "Sagittario",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  sacerdos: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000540.webp",
    name: "Sacerdos",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  AeroDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000550.webp",
    name: "Aero Drake",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  ElectroDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000560.webp",
    name: "Electro Drake",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  GlacioDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000570.webp",
    name: "Glacio Drake",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomNimbusWraith: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000190.webp",
    name: "Phantom: Nimbus Wraith",
    type: "Standard",
    resist: {
    },
  },
  phantomChestMimic: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000220.webp",
    name: "Phantom: Chest Mimic",
    type: "Standard",
    resist: {
    },
  },
  FusionDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000580.webp",
    name: "Fusion Drake",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  SpectroDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000590.webp",
    name: "Spectro Drake",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  HavocDrake: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000600.webp",
    name: "Havoc Drake",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  devoteeSFlesh: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000610.webp",
    name: "Devotee's Flesh",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomFaeIgnis: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000230.webp",
    name: "Phantom: Fae Ignis",
    type: "Standard",
    resist: {
    },
  },
  abyssalGunmaster: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000620.webp",
    name: "Abyssal Gunmaster",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareHavocWarrior: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000630.webp",
    name: "Nightmare: Havoc Warrior",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareGlacioPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000640.webp",
    name: "Nightmare: Glacio Predator",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareElectroPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000650.webp",
    name: "Nightmare: Electro Predator",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareAeroPredator: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000660.webp",
    name: "Nightmare: Aero Predator",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareGulpuff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000670.webp",
    name: "Nightmare: Gulpuff",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareChirpuff: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000680.webp",
    name: "Nightmare: Chirpuff",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  midnightRanger: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000690.webp",
    name: "Midnight Ranger",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  midnightRanger2: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000700.webp",
    name: "Midnight Ranger",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  gangMember: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000710.webp",
    name: "Gang Member",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareBabyViridblazeSaurian: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000720.webp",
    name: "Nightmare: Baby Viridblaze Saurian",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 40,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareBabyRoseshroom: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000730.webp",
    name: "Nightmare: Baby Roseshroom",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareTickTack: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000750.webp",
    name: "Nightmare: Tick Tack",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  nightmareDwarfCassowary: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000760.webp",
    name: "Nightmare: Dwarf Cassowary",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  tremorWarrior: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000740.webp",
    name: "Tremor Warrior",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  floraDrone: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000770.webp",
    name: "Flora Drone",
    type: "Standard",
    resist: {
      Aero: 40,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  miningDrone: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000780.webp",
    name: "Mining Drone",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  geospiderS4: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000790.webp",
    name: "Geospider S4",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 40,
    },
  },
  zipZap: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000820.webp",
    name: "Zip Zap",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  outcastExecutioner: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000800.webp",
    name: "Outcast Executioner",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  thundstaffOutcast: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000810.webp",
    name: "Thundstaff Outcast",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 40,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomIceglintDancer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000370.webp",
    name: "Phantom: Iceglint Dancer",
    type: "Standard",
    resist: {
    },
  },
  iceglintDancer: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000830.webp",
    name: "Iceglint Dancer",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 40,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  shadowStepper: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000840.webp",
    name: "Shadow Stepper",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 40,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusRipper: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000850.webp",
    name: "Fractsidus Ripper",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  fractsidusMawdoll: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/310000860.webp",
    name: "Fractsidus Mawdoll",
    type: "Standard",
    resist: {
      Aero: 10,
      Electro: 10,
      Fusion: 10,
      Glacio: 10,
      Havoc: 10,
      Physical: 10,
      Spectro: 10,
    },
  },
  phantomZipZap: {
    imageUrl: "https://ryanbenson.github.io/wuthering-waves-assets/images/enemies/350000330.webp",
    name: "Phantom: Zip Zap",
    type: "Standard",
    resist: {
    },
  },
};

/** UI / tune-break categories (database uses `Standard` for common mobs). */
export const ENEMY_BROWSER_UI_TYPES = [
  "Calamity",
  "Overlord",
  "Elite",
  "Common",
] as const;

export type EnemyBrowserUiType = (typeof ENEMY_BROWSER_UI_TYPES)[number];

export function mapEnemyTypeToBrowserCategory(
  type: string,
): EnemyBrowserUiType {
  if (type === "Standard") return "Common";
  if ((ENEMY_BROWSER_UI_TYPES as readonly string[]).includes(type)) {
    return type as EnemyBrowserUiType;
  }
  return "Common";
}

export interface ListedEnemy {
  key: string;
  name: string;
  type: string;
  browserType: EnemyBrowserUiType;
  imageUrl: string;
  resist: ResistStats;
}

export const allEnemiesList: ListedEnemy[] = (
  Object.entries(enemies) as [string, Enemy][]
).map(([key, e]) => ({
  key,
  name: e.name,
  type: e.type,
  browserType: mapEnemyTypeToBrowserCategory(e.type),
  imageUrl: e.imageUrl,
  resist: e.resist,
}));

/** Resist percent in data (e.g. 10) → fraction used by the calculator (e.g. 0.1). */
export function getEnemyResistFractionForElement(
  resist: ResistStats,
  element: string,
): number {
  const v = resist?.[element as keyof ResistStats];
  if (typeof v !== "number" || Number.isNaN(v)) {
    return 0.1;
  }
  return v / 100;
}

export default enemies;