export const introAttacks = {
  name: "Intro Skill: Cruise",
  description: `<div class="skilldescription"><span class="Title">Ripple</span><br>Attack the target, dealing <span class="Dark">Havoc DMG</span>.<br>Press <span class="Highlight">Normal Attack</span> shortly after casting this skill to start the Basic Attack combo from <span class="Highlight">Basic Attack Stage 3</span>.<br> <br><span class="Title">Tidal Surge</span><br>When in <span class="Highlight">Mirage</span>, <span class="Highlight">Intro Skill</span> becomes <span class="Highlight">Tidal Surge</span>, which triggers 3 coordinated attacks on hit, dealing <span class="Dark">Havoc DMG</span>.</div>`,
  attacks: [
    {
      key: "RippleDMG",
      label: "Ripple DMG",
      talents: {
        "1": "21.25%*4",
        "2": "23.00%*4",
        "3": "24.74%*4",
        "4": "27.18%*4",
        "5": "28.92%*4",
        "6": "30.93%*4",
        "7": "33.71%*4",
        "8": "36.50%*4",
        "9": "39.29%*4",
        "10": "42.25%*4",
      },
      type: "Intro",
    },
    {
      key: "TidalSurgeCoordinatedDMG",
      label: "Tidal Surge DMG (Coordinated)",
      talents: {
        "1": "8.50%*3",
        "2": "9.20%*3",
        "3": "9.90%*3",
        "4": "10.87%*3",
        "5": "11.57%*3",
        "6": "12.37%*3",
        "7": "13.49%*3",
        "8": "14.60%*3",
        "9": "15.72%*3",
        "10": "16.90%*3",
      },
      type: "Intro",
      subType: "Coordinated",
    },
    {
      key: "TidalSurgeDMG",
      label: "Tidal Surge DMG",
      talents: {
        "1": "59.50%",
        "2": "64.38%",
        "3": "69.26%",
        "4": "76.09%",
        "5": "80.97%",
        "6": "86.58%",
        "7": "94.39%",
        "8": "102.20%",
        "9": "110.00%",
        "10": "118.30%",
      },
      type: "Intro",
    },
  ],
};
