export const rotations: RotationPreset[] = [
    {
        name: `Quick Concerto`,
        description: `Standard Subdps Rotation. \nCan skip Skill 1 after the first rotation. May opt out of Lorelei before Outro to avoid interruption or extend Stasis.`,
        author: `vv ubFiish`,
        data: {"name":"Quick Concerto","description":"Standard Subdps Rotation. \nCan skip Skill 1 after the first rotation. May opt out of Lorelei before Outro to avoid interruption or extend Stasis.","actions":[{"order":1,"key":"RippleDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"Stage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"GracefulStepDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"DelusiveDiveDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"FlickeringReverieDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"JoltDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"FlowingSuffocationDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"PhantomStingStage1DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"PhantomStingStage2DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"PhantomStingStage3DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"PerceptionDrainDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"JoltDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":13,"key":"MidnightVeilDMG","type":"echoSetAttacks","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":14,"key":"DiffusionDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":15,"key":"PerceptionDrainHealing","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":16,"key":"HealingByConsumingTrance","type":"forteCircuit","count":"3","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    },
    {
        name: `Full Damage`,
        description: `6 Enhanced Basic rotation for maximum healing or Hypercarry.`,
        author: `vv ubFiish`,
        data: {"name":"Full Damage","description":"6 Enhanced Basic rotation for maximum healing or Hypercarry.","actions":[{"order":1,"key":"RippleDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"Stage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"GracefulStepDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"DelusiveDiveDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"PhantomStingStage1DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"PhantomStingStage2DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"FlickeringReverieDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"JoltDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"FlowingSuffocationDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"PhantomStingStage3DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"PhantomStingStage1DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"PhantomStingStage2DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":13,"key":"PhantomStingStage3DMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":14,"key":"PerceptionDrainDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":15,"key":"JoltDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":16,"key":"MidnightVeilDMG","type":"echoSetAttacks","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":17,"key":"DiffusionDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":18,"key":"PerceptionDrainHealing","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":19,"key":"HealingByConsumingTrance","type":"forteCircuit","count":6,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    },
];