export const forteCircuitAttacks = {
  name: "Forte Circuit: The Way of Ten Thousand Voices",
  description: `<span class="Title">Resonance Skill - Sword Stance Flow: Azure</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Feather's Edge</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span> and restoring 100 <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>, gain <span style="color:#ffd12f;" class="font-bold">Bated Breath</span>, which lasts 15s. While Yangyang: Xuanling is on the field, the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> has its Crit. DMG increased by 125%; <span style="color:#ffd12f;" class="font-bold">Bated Breath</span> is removed when <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> ends. <span style="color:#ffd12f;" class="font-bold">Bated Breath</span> can only be gained once every 25s.<br>When <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> hits a target, it consumes 1 stack of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> from the target.<br>After casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>, the combo will not reset for a short time. If <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> interrupts the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> combo, <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> is summoned to complete the current attack, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>, is not affected by DMG Bonus, and cannot apply <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the target.<br>Taking a hit within a short time after casting this skill can trigger a successful Dodge. Each successful Dodge consumes 50 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Resonance Skill - Sword Stance Flow: Feather</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Feather's Edge</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, switching to <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and dealing <span style="color:#fcc4db;">Havoc DMG</span>, restoring 100 <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, gain <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span>, which lasts 15s. While Yangyang: Xuanling is on the field, the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Havoc in Bloom</span> has its Crit. DMG increased by 125%; <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span> is removed when <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> Stage 3 or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Havoc in Bloom</span> Stage 3 ends. <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span> can only be gained once every 25s.<br>When <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> hits a target, it consumes 1 stack of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> from the target.<br>After casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, the combo will not reset for a short time. If <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> interrupts the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Azure Sword Stance</span> combo, <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> is summoned to complete the current attack, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>, is not affected by DMG Bonus, and cannot apply <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the target.<br>Taking a hit within a short time after casting this skill can trigger a successful Dodge. Each successful Dodge consumes 50 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Heavy Attack - Azure Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, hold Normal Attack to consume all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> and STA to cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, generating a massive cyclone that strikes the area in front, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br><span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> applies 2 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the targets it hits.<br><size=10></span><br><br><span class="Title">Heavy Attack - Feather Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and on the ground, hold Normal Attack to consume STA and cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. After it hits a target, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> is automatically cast.<br><span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> applies 2 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the targets it hits.<br><size=10></span><br><br><span class="Title">Mid-air Attack - Feather Fall</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and airborne, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>.<br>Press or hold Normal Attack to consume all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> and STA to cast <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. Casting <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> enters <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span> for 12s.<br><size=10></span><br><br><span class="Title">Hark the Wind</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, consuming STA to perform up to 3 stages of attacks, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br><span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> Stage 2 and Stage 3 can be cast in mid-air close to the ground. Casting Stage 3 exits <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>. The stage count of this combo will not be reset.<br>During <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span>, casting a Dodge Counter counts as casting the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> combo.<br><size=10></span><br><br><span class="Title">Feathered Oath</span></span><br><br>When Resonators in the team apply <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to a target, Xuanling gains 1 stack of <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span> for 8s. <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span> can be gained once every 1s, stacking up to 6 times. While Yangyang: Xuanling is on the field, each stack increases the Crit. DMG of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, and <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> by 30%, up to a maximum of 180%.<br><size=10></span><br><br><span class="Title">Refrain</span></span><br><br>Before Yangyang: Xuanling's <span style="color:#ffd12f;" class="font-bold">Basic Attack - Azure Sword Stance Stage 4</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance Stage 4</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> hits a target, record the highest stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> applied to targets within a certain range, and copy it to all targets within range.<br><size=10></span><br><br><span class="Title">Gaining Melody</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Melody</span> has a maximum of 100.<br>Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> or <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> restores 100 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br>Casting Resonance Liberation <span style="color:#ffd12f;" class="font-bold">Hush of a Thousand Voices</span> consumes all <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Basic Attack - Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span>, or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Feather Sword Stance</span> consumes <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Gaining Azure Plume</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Azure Plume</span> has a maximum of 2.<br>Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> or <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> restores 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Skybound Feather</span> restores 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> consumes all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>.`,
  attacks: [
    {
      key: "HeavyAttackAzureSwordStance",
      label: "Heavy Attack - Azure Sword Stance",
      talents: {
        "1": "67.99%+67.99%+90.65%",
        "2": "73.56%+73.56%+98.08%",
        "3": "79.14%+79.14%+105.51%",
        "4": "86.94%+86.94%+115.92%",
        "5": "92.52%+92.52%+123.35%",
        "6": "98.93%+98.93%+131.90%",
        "7": "107.85%+107.85%+143.79%",
        "8": "116.77%+116.77%+155.69%",
        "9": "125.69%+125.69%+167.58%",
        "10": "135.16%+135.16%+180.21%",
      },
      type: "Heavy",
    },
    {
      key: "SwordStanceFlowFeather",
      label: "Sword Stance Flow: Feather",
      talents: {
        "1": "16.88%*3",
        "2": "18.27%*3",
        "3": "19.65%*3",
        "4": "21.59%*3",
        "5": "22.98%*3",
        "6": "24.57%*3",
        "7": "26.78%*3",
        "8": "29.00%*3",
        "9": "31.21%*3",
        "10": "33.56%*3",
      },
      type: "Heavy",
    },
    {
      key: "HeavyAttackFeatherSwordStance",
      label: "Heavy Attack - Feather Sword Stance",
      talents: {
        "1": "8.40%+75.58%",
        "2": "9.09%+81.77%",
        "3": "9.78%+87.97%",
        "4": "10.74%+96.65%",
        "5": "11.43%+102.84%",
        "6": "12.22%+109.97%",
        "7": "13.33%+119.89%",
        "8": "14.43%+129.80%",
        "9": "15.53%+139.72%",
        "10": "16.70%+150.25%",
      },
      type: "Heavy",
    },
    {
      key: "FeatherSwordStanceEnhancedPlungingAttack",
      label: "Feather Sword Stance - Enhanced Plunging Attack",
      talents: {
        "1": "10.80%*3+48.60%",
        "2": "11.69%*3+52.59%",
        "3": "12.58%*3+56.58%",
        "4": "13.82%*3+62.15%",
        "5": "14.70%*3+66.14%",
        "6": "15.72%*3+70.72%",
        "7": "17.14%*3+77.10%",
        "8": "18.55%*3+83.48%",
        "9": "19.97%*3+89.85%",
        "10": "21.48%*3+96.63%",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage1",
      label: "Havoc in Bloom Stage 1",
      talents: {
        "1": "20.01%*3",
        "2": "21.66%*3",
        "3": "23.30%*3",
        "4": "25.59%*3",
        "5": "27.23%*3",
        "6": "29.12%*3",
        "7": "31.75%*3",
        "8": "34.37%*3",
        "9": "37.00%*3",
        "10": "39.79%*3",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage2",
      label: "Havoc in Bloom Stage 2",
      talents: {
        "1": "44.90%+33.67%+33.67%",
        "2": "48.58%+36.43%+36.43%",
        "3": "52.26%+39.20%+39.20%",
        "4": "57.41%+43.06%+43.06%",
        "5": "61.09%+45.82%+45.82%",
        "6": "65.33%+49.00%+49.00%",
        "7": "71.22%+53.41%+53.41%",
        "8": "77.11%+57.83%+57.83%",
        "9": "83.00%+62.25%+62.25%",
        "10": "89.25%+66.94%+66.94%",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage3",
      label: "Havoc in Bloom Stage 3",
      talents: {
        "1": "12.06%*5+140.68%",
        "2": "13.05%*5+152.22%",
        "3": "14.04%*5+163.76%",
        "4": "15.43%*5+179.91%",
        "5": "16.41%*5+191.44%",
        "6": "17.55%*5+204.71%",
        "7": "19.13%*5+223.16%",
        "8": "20.71%*5+241.62%",
        "9": "22.30%*5+260.08%",
        "10": "23.98%*5+279.69%",
      },
      type: "Heavy",
    },
    {
      key: "SwordStanceFlowAzure",
      label: "Sword Stance Flow: Azure",
      talents: {
        "1": "58.64%",
        "2": "63.45%",
        "3": "68.26%",
        "4": "74.99%",
        "5": "79.80%",
        "6": "85.33%",
        "7": "93.03%",
        "8": "100.72%",
        "9": "108.41%",
        "10": "116.59%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage1",
      label: "Dodge Counter - Havoc in Bloom Stage 1",
      talents: {
        "1": "20.01%*3",
        "2": "21.66%*3",
        "3": "23.30%*3",
        "4": "25.59%*3",
        "5": "27.23%*3",
        "6": "29.12%*3",
        "7": "31.75%*3",
        "8": "34.37%*3",
        "9": "37.00%*3",
        "10": "39.79%*3",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage2",
      label: "Dodge Counter - Havoc in Bloom Stage 2",
      talents: {
        "1": "44.90%+33.67%+33.67%",
        "2": "48.58%+36.43%+36.43%",
        "3": "52.26%+39.20%+39.20%",
        "4": "57.41%+43.06%+43.06%",
        "5": "61.09%+45.82%+45.82%",
        "6": "65.33%+49.00%+49.00%",
        "7": "71.22%+53.41%+53.41%",
        "8": "77.11%+57.83%+57.83%",
        "9": "83.00%+62.25%+62.25%",
        "10": "89.25%+66.94%+66.94%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage3",
      label: "Dodge Counter - Havoc in Bloom Stage 3",
      talents: {
        "1": "12.06%*5+140.68%",
        "2": "13.05%*5+152.22%",
        "3": "14.04%*5+163.76%",
        "4": "15.43%*5+179.91%",
        "5": "16.41%*5+191.44%",
        "6": "17.55%*5+204.71%",
        "7": "19.13%*5+223.16%",
        "8": "20.71%*5+241.62%",
        "9": "22.30%*5+260.08%",
        "10": "23.98%*5+279.69%",
      },
      type: "Heavy",
    }
  ],
};
