export const forteCircuitAttacks = {
  name: "Forte Circuit: The Way of Ten Thousand Voices",
  description: `<span class="Title">Resonance Skill - Sword Stance Flow: Azure</span></span><br><br>Yangyang: Xuanling is in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>. When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Feather's Edge</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span> and restoring 100 points of <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 points of <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> hits the target, consume 1 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> on the target.<br>The <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> cycle is not reset within a short time after casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>. If casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> resets the cycle, summon a <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> to finish the current attack and deal a fixed instance of <span style="color:#fcc4db;">Havoc DMG</span>, considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>, which is not affected by any DMG Bonus effects and does not inflict <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span>.<br>Successful Dodge can be triggered within a short time into the action of this skill, which consumes 50 points of <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Resonance Skill - Sword Stance Flow: Feather</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Feather's Edge</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, switching to <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and dealing <span style="color:#fcc4db;">Havoc DMG</span>, restoring 100 points of <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 points of <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This instance of DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> hits, consume 1 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> on the target.<br>The <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> cycle is not reset within a short time after casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>. If casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> resets the cycle, summon a <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> to finish the current attack and deal a fixed instance of <span style="color:#fcc4db;">Havoc DMG</span>, considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>, which is not affected by any DMG Bonus effects and does not inflict <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span>.<br>Successful Dodge can be triggered within a short time into the action of this skill, which consumes 50 points of <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Heavy Attack - Azure Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, hold Normal Attack to consume STA and all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> to cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, generating a massive cyclone that strikes the area in front, dealing <span style="color:#fcc4db;">Havoc DMG</span>, considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, gain <span style="color:#ffd12f;" class="font-bold">Bated Breath</span>: If Yangyang: Xuanling is the active Resonator in the field, the Crit. DMG of this <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> increases by 160%. When <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> ends, <span style="color:#ffd12f;" class="font-bold">Bated Breath</span> is removed. <span style="color:#ffd12f;" class="font-bold">Bated Breath</span> can be gained up to once every 25s.<br><span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> applies 2 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the targets it hits.<br><size=10></span><br><br><span class="Title">Heavy Attack - Feather Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, if Yangyang: Xuanling is on the ground and not in a  not in a <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> cycle, hold Normal Attack to consume STA and cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. After it hits a target, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> is automatically cast.<br>When casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, gain <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span>, which lasts 15s. While Yangyang: Xuanling is the active Resonator in the team, the Crit. DMG of the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Havoc in Bloom</span> is increased by 160%. <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span> is removed when <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> Stage 3 or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Havoc in Bloom</span> Stage 3 ends. <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span> can be gained up to once every 25s.<br><span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> applies <SapTag=A>2</SapTag> {Cus:Sap,S=stack P=stacks SapTag=A} stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the targets it hits.<br><size=10></span><br><br><span class="Title">Mid-air Attack - Feather Fall</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and airborne,  <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>. Switching to another Resonator automatically casts <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>.<br>Press or hold Normal Attack to consume STA and all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> to cast <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. Casting <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> enters <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span> for 12s.<br><size=10></span><br><br><span class="Title">Hark the Wind</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, consuming STA to perform up to 3 stages of attacks, dealing <span style="color:#fcc4db;">Havoc DMG</span>,  considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br><span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> Stage 2 and Stage 3 can be cast in mid-air close to the ground. Casting Stage 3 ends <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>. This attack cycle cannot be reset.<br>During <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span>, a Dodge Counter counts towards the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> cycle.<br><size=10></span><br><br><span class="Title">Feathered Oath</span></span><br><br>When Resonators in the team apply <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to a target, Yangyang: Xuanling gains 1 stack of <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span> for 4s. <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span> can be gained once every 1s, stacking up to 6 times. While Yangyang: Xuanling is the active Resonator in the team, each stack increases the Crit. DMG of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, and <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Havoc in Bloom</span> by 25%, up to 150%.<br><size=10></span><br><br><span class="Title">Refrain</span></span><br><br>Before Yangyang: Xuanling's <span style="color:#ffd12f;" class="font-bold">Basic Attack - Azure Sword Stance Stage 4</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance Stage 4</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> hits a target, record and propagate the highest stack count of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> on targets within a certain range to all targets within range.<br><size=10></span><br><br><span class="Title">Melody</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Melody</span> has a maximum of 100 points.<br>Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span> or <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span> restores 100 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br>Casting Resonance Liberation <span style="color:#ffd12f;" class="font-bold">Hush of a Thousand Voices</span> consumes all <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><span style="color:#ffd12f;" class="font-bold">Normal Attacks</span> consumes <span style="color:#ffd12f;" class="font-bold">Melody</span> upon dealing damage.<br><size=10></span><br><br><span class="Title">Azure Plume</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Azure Plume</span> has a maximum of 50 points.<br>Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Azure</span>,  <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Sword Stance Flow: Feather</span>, <span style="color:#ffd12f;" class="font-bold">Intro Skill - Skybound Feather</span> restores <SapTag=B>2</SapTag> {Cus:Sap,S=point P=points SapTag=B} of <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> consumes all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>.`,
  attacks: [
    {
      key: "HeavyAttackAzureSwordStanceDMG",
      label: "Heavy Attack - Azure Sword Stance DMG",
      talents: {
        "1": "67.99%+67.99%+90.65%",
        "2": "73.56%+73.56%+98.08%",
        "3": "79.14%+79.14%+105.51%",
        "4": "86.94%+86.94%+115.92%",
        "5": "92.52%+92.52%+123.35%",
        "6": "98.93%+98.93%+131.90%",
        "7": "107.85%+107.85%+143.79%",
        "8": "116.77%+116.77%+155.69%",
        "9": "125.69%+125.69%+167.58%",
        "10": "135.16%+135.16%+180.21%",
      },
      type: "Heavy",
    },
    {
      key: "ResonanceSkillSwordStanceFlowFeatherDMG",
      label: "Resonance Skill - Sword Stance Flow: Feather DMG",
      talents: {
        "1": "16.88%*3",
        "2": "18.27%*3",
        "3": "19.65%*3",
        "4": "21.59%*3",
        "5": "22.98%*3",
        "6": "24.57%*3",
        "7": "26.78%*3",
        "8": "29.00%*3",
        "9": "31.21%*3",
        "10": "33.56%*3",
      },
      type: "Heavy",
    },
    {
      key: "HeavyAttackFeatherSwordStanceDMG",
      label: "Heavy Attack - Feather Sword Stance DMG",
      talents: {
        "1": "10.92%+98.26%",
        "2": "11.82%+106.31%",
        "3": "12.71%+114.37%",
        "4": "13.97%+125.65%",
        "5": "14.86%+133.71%",
        "6": "15.89%+142.97%",
        "7": "17.32%+155.86%",
        "8": "18.75%+168.75%",
        "9": "20.19%+181.65%",
        "10": "21.71%+195.34%",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackFeatherSwordStanceFeatherFallDMG",
      label: "Mid-air Attack - Feather Sword Stance: Feather Fall DMG",
      talents: {
        "1": "7.44%*3+33.48%",
        "2": "8.06%*3+36.23%",
        "3": "8.67%*3+38.98%",
        "4": "9.52%*3+42.82%",
        "5": "10.13%*3+45.56%",
        "6": "10.83%*3+48.72%",
        "7": "11.81%*3+53.11%",
        "8": "12.78%*3+57.51%",
        "9": "13.76%*3+61.90%",
        "10": "14.80%*3+66.57%",
      },
      type: "Heavy",
    },
    {
      key: "BasicAttackBasicAttackHavocInBloomStage1DMGDMG",
      label: "Basic Attack - Havoc in Bloom Stage 1 DMG",
      talents: {
        "1": "20.01%*3",
        "2": "21.66%*3",
        "3": "23.30%*3",
        "4": "25.59%*3",
        "5": "27.23%*3",
        "6": "29.12%*3",
        "7": "31.75%*3",
        "8": "34.37%*3",
        "9": "37.00%*3",
        "10": "39.79%*3",
      },
      type: "Heavy",
    },
    {
      key: "BasicAttackBasicAttackHavocInBloomStage2DMGDMG",
      label: "Basic Attack - Havoc in Bloom Stage 2 DMG",
      talents: {
        "1": "44.90%+33.67%+33.67%",
        "2": "48.58%+36.43%+36.43%",
        "3": "52.26%+39.20%+39.20%",
        "4": "57.41%+43.06%+43.06%",
        "5": "61.09%+45.82%+45.82%",
        "6": "65.33%+49.00%+49.00%",
        "7": "71.22%+53.41%+53.41%",
        "8": "77.11%+57.83%+57.83%",
        "9": "83.00%+62.25%+62.25%",
        "10": "89.25%+66.94%+66.94%",
      },
      type: "Heavy",
    },
    {
      key: "BasicAttackBasicAttackHavocInBloomStage3DMGDMG",
      label: "Basic Attack - Havoc in Bloom Stage 3 DMG",
      talents: {
        "1": "12.06%*5+140.68%",
        "2": "13.05%*5+152.22%",
        "3": "14.04%*5+163.76%",
        "4": "15.43%*5+179.91%",
        "5": "16.41%*5+191.44%",
        "6": "17.55%*5+204.71%",
        "7": "19.13%*5+223.16%",
        "8": "20.71%*5+241.62%",
        "9": "22.30%*5+260.08%",
        "10": "23.98%*5+279.69%",
      },
      type: "Heavy",
    },
    {
      key: "ResonanceSkillResonanceSkillSwordStanceFlowAzureDMGDMG",
      label: "Resonance Skill - Sword Stance Flow: Azure DMG",
      talents: {
        "1": "35.19%+7.82%*3",
        "2": "38.07%+8.46%*3",
        "3": "40.96%+9.11%*3",
        "4": "45.00%+10.00%*3",
        "5": "47.88%+10.64%*3",
        "6": "51.20%+11.38%*3",
        "7": "55.82%+12.41%*3",
        "8": "60.43%+13.43%*3",
        "9": "65.05%+14.46%*3",
        "10": "69.95%+15.55%*3",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterBasicAttackHavocInBloomStage1DMGDMG",
      label: "Dodge Counter - Havoc in Bloom Stage 1 DMG",
      talents: {
        "1": "20.01%*3",
        "2": "21.66%*3",
        "3": "23.30%*3",
        "4": "25.59%*3",
        "5": "27.23%*3",
        "6": "29.12%*3",
        "7": "31.75%*3",
        "8": "34.37%*3",
        "9": "37.00%*3",
        "10": "39.79%*3",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterBasicAttackHavocInBloomStage2DMGDMG",
      label: "Dodge Counter - Havoc in Bloom Stage 2 DMG",
      talents: {
        "1": "44.90%+33.67%+33.67%",
        "2": "48.58%+36.43%+36.43%",
        "3": "52.26%+39.20%+39.20%",
        "4": "57.41%+43.06%+43.06%",
        "5": "61.09%+45.82%+45.82%",
        "6": "65.33%+49.00%+49.00%",
        "7": "71.22%+53.41%+53.41%",
        "8": "77.11%+57.83%+57.83%",
        "9": "83.00%+62.25%+62.25%",
        "10": "89.25%+66.94%+66.94%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterBasicAttackHavocInBloomStage3DMGDMG",
      label: "Dodge Counter - Havoc in Bloom Stage 3 DMG",
      talents: {
        "1": "12.06%*5+140.68%",
        "2": "13.05%*5+152.22%",
        "3": "14.04%*5+163.76%",
        "4": "15.43%*5+179.91%",
        "5": "16.41%*5+191.44%",
        "6": "17.55%*5+204.71%",
        "7": "19.13%*5+223.16%",
        "8": "20.71%*5+241.62%",
        "9": "22.30%*5+260.08%",
        "10": "23.98%*5+279.69%",
      },
      type: "Heavy",
    },
    {
      key: "WraithOfSoundDMG",
      label: "Wraith of Sound DMG",
      talents: {
        "1": "523",
        "2": "523",
        "3": "523",
        "4": "523",
        "5": "523",
        "6": "523",
        "7": "523",
        "8": "523",
        "9": "523",
        "10": "523",
      },
      isFixed: true,
      type: "Basic",
    },
    {
      key: `SequenceNode1AtTheWindSBreathTheBlossomsWake`,
      label: `S1: Shadow of Xuanling: Unfaltering`,
      talents: {
        "1": "337.98%",
        "2": "337.98%",
        "3": "337.98%",
        "4": "337.98%",
        "5": "337.98%",
        "6": "337.98%",
        "7": "337.98%",
        "8": "337.98%",
        "9": "337.98%",
        "10": "337.98%",
      },
      type: "Heavy",
      requiresResonanceChain: "SequenceNode6LetTheAzureKeepItsLight",
      alwaysCrit: true,
    },
    {
      key: `SequenceNode6LetTheAzureKeepItsLight`,
      label: `S6: Shadow of Xuanling: Still as Withered Wood`,
      talents: {
        "1": "337.98%",
        "2": "337.98%",
        "3": "337.98%",
        "4": "337.98%",
        "5": "337.98%",
        "6": "337.98%",
        "7": "337.98%",
        "8": "337.98%",
        "9": "337.98%",
        "10": "337.98%",
      },
      type: "Heavy",
      requiresResonanceChain: "SequenceNode6LetTheAzureKeepItsLight",
      alwaysCrit: true,
    },
  ],
};
