export const forteCircuitAttacks = {
  name: "Forte Circuit: The Way of Ten Thousand Voices",
  description: `<span class="Title">Sword Stance Flow - Azure</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, the Resonance Skill <span style="color:#ffd12f;" class="font-bold">Sword Stance Switch - Azure</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Azure</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Azure</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span> and restoring 100 <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Azure</span> hits a target, it consumes 1 stack of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> from the target and grants <span style="color:#ffd12f;" class="font-bold">Bated Breath</span>. While Yangyang: Xuanling is on the field, the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> has its Crit. DMG increased by 100%; <span style="color:#ffd12f;" class="font-bold">Bated Breath</span> is removed after <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> deals DMG. This effect can be gained once every 25s and lasts 15s.<br>After casting <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Azure</span>, the combo will not reset for a short time. If <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Azure</span> interrupts the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> combo, <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> is summoned to complete the current attack, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is not affected by DMG Bonus and is considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>.<br>Taking a hit within a short time after casting this skill can trigger a successful Dodge. Each successful Dodge consumes 50 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Sword Stance Flow - Feather</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Melody</span> is depleted while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, the Resonance Skill <span style="color:#ffd12f;" class="font-bold">Sword Stance Switch - Feather</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Feather</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to cast <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Feather</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span> and restoring 100 <span style="color:#ffd12f;" class="font-bold">Melody</span> and 1 <span style="color:#ffd12f;" class="font-bold">Azure Plume</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Feather</span> hits a target, it consumes 1 stack of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> from the target and grants <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span>. While Yangyang: Xuanling is on the field, the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, or <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> has its Crit. DMG increased by 100%; <span style="color:#ffd12f;" class="font-bold">Drifting Mist</span> is removed after <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> deals DMG. This effect can be gained once every 25s and lasts 15s.<br>After casting <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Feather</span>, the combo will not reset for a short time. If <span style="color:#ffd12f;" class="font-bold">Sword Stance Flow - Feather</span> interrupts the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Azure Sword Stance</span> combo, <span style="color:#ffd12f;" class="font-bold">Wraith of Sound</span> is summoned to complete the current attack, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is not affected by DMG Bonus and is considered <span style="color:#ffd12f;" class="font-bold">Basic Attack DMG</span>.<br>Taking a hit within a short time after casting this skill can trigger a successful Dodge. Each successful Dodge consumes 50 <span style="color:#ffd12f;" class="font-bold">Melody</span>.<br><size=10></span><br><br><span class="Title">Heavy Attack - Azure Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Azure Sword Stance</span>, hold Normal Attack to consume all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> and STA to cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, generating a massive cyclone that strikes the area in front, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span> hits a target, it applies 2 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the target.<br><size=10></span><br><br><span class="Title">Heavy Attack - Feather Sword Stance</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and on the ground, hold Normal Attack to consume STA and cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. After it hits a target, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> is automatically cast.<br>When <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span> hits a target, it applies 2 stacks of <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to the target.<br><size=10></span><br><br><span class="Title">Mid-air Attack - Feather Fall</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> is restored to its maximum while in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span> and airborne, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>.<br>Press or hold Normal Attack to consume all <span style="color:#ffd12f;" class="font-bold">Azure Plume</span> and STA to cast <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, dealing <span style="color:#fcc4db;">Havoc DMG</span>. Casting <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span> enters <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span> for 12s.<br><size=10></span><br><br><span class="Title">Hark the Wind</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Feather Sword Stance</span> is replaced by <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>, consuming STA to perform up to 3 stages of attacks, dealing <span style="color:#fcc4db;">Havoc DMG</span>. This DMG is considered <span style="color:#ffd12f;" class="font-bold">Heavy Attack DMG</span>.<br><span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> Stage 2 and Stage 3 can be cast in mid-air close to the ground. Casting Stage 3 exits <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span>. The stage count of this combo will not be reset.<br>During <span style="color:#ffd12f;" class="font-bold">Hark the Wind</span>, casting a Dodge Counter counts as casting the <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> combo.<br><size=10></span><br><br><span class="Title">Feathered Oath</span></span><br><br>When Resonators in the team apply <span style="color:#ffd12f;" class="font-bold">Havoc Bane</span> to a target, Xuanling gains 1 stack of <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span>. <span style="color:#ffd12f;" class="font-bold">Feathered Oath</span> can be gained once every 1s, stacking up to 6 times. While Yangyang: Xuanling is on the field, each stack increases the Crit. DMG of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Azure Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Feather Sword Stance</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Feather Fall</span>, and <span style="color:#ffd12f;" class="font-bold">Basic Attack - Havoc in Bloom</span> by 30%, up to a maximum of 180%.`,
  attacks: [
    {
      key: "HeavyAttackAzureSwordStance",
      label: "Heavy Attack - Azure Sword Stance",
      talents: {
        "1": "18.00%+18.00%+24.00%",
        "2": "19.48%+19.48%+25.97%",
        "3": "20.95%+20.95%+27.93%",
        "4": "23.02%+23.02%+30.69%",
        "5": "24.49%+24.49%+32.66%",
        "6": "26.19%+26.19%+34.92%",
        "7": "28.55%+28.55%+38.07%",
        "8": "30.91%+30.91%+41.21%",
        "9": "33.27%+33.27%+44.36%",
        "10": "35.78%+35.78%+47.71%",
      },
      type: "Heavy",
    },
    {
      key: "SwordStanceFlowFeather",
      label: "Sword Stance Flow - Feather",
      talents: {
        "1": "16.88%*3",
        "2": "18.27%*3",
        "3": "19.65%*3",
        "4": "21.59%*3",
        "5": "22.98%*3",
        "6": "24.57%*3",
        "7": "26.78%*3",
        "8": "29.00%*3",
        "9": "31.21%*3",
        "10": "33.56%*3",
      },
      type: "Heavy",
    },
    {
      key: "HeavyAttackFeatherSwordStance",
      label: "Heavy Attack - Feather Sword Stance",
      talents: {
        "1": "55.98%+55.98%",
        "2": "60.58%+60.58%",
        "3": "65.17%+65.17%",
        "4": "71.59%+71.59%",
        "5": "76.18%+76.18%",
        "6": "81.46%+81.46%",
        "7": "88.81%+88.81%",
        "8": "96.15%+96.15%",
        "9": "103.50%+103.50%",
        "10": "111.30%+111.30%",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackFeatherFall",
      label: "Mid-air Attack - Feather Fall",
      talents: {
        "1": "28.80%*3+129.60%",
        "2": "31.17%*3+140.23%",
        "3": "33.53%*3+150.86%",
        "4": "36.83%*3+165.74%",
        "5": "39.20%*3+176.36%",
        "6": "41.91%*3+188.59%",
        "7": "45.69%*3+205.59%",
        "8": "49.47%*3+222.59%",
        "9": "53.25%*3+239.60%",
        "10": "57.26%*3+257.66%",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage1",
      label: "Havoc in Bloom Stage 1",
      talents: {
        "1": "26.68%*3",
        "2": "28.87%*3",
        "3": "31.06%*3",
        "4": "34.12%*3",
        "5": "36.31%*3",
        "6": "38.83%*3",
        "7": "42.33%*3",
        "8": "45.83%*3",
        "9": "49.33%*3",
        "10": "53.05%*3",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage2",
      label: "Havoc in Bloom Stage 2",
      talents: {
        "1": "59.86%+44.90%+44.90%",
        "2": "64.77%+48.58%+48.58%",
        "3": "69.68%+52.26%+52.26%",
        "4": "76.55%+57.41%+57.41%",
        "5": "81.46%+61.09%+61.09%",
        "6": "87.10%+65.33%+65.33%",
        "7": "94.95%+71.22%+71.22%",
        "8": "102.81%+77.11%+77.11%",
        "9": "110.66%+83.00%+83.00%",
        "10": "119.00%+89.25%+89.25%",
      },
      type: "Heavy",
    },
    {
      key: "HavocInBloomStage3",
      label: "Havoc in Bloom Stage 3",
      talents: {
        "1": "9.60%*5+111.98%",
        "2": "10.39%*5+121.16%",
        "3": "11.18%*5+130.34%",
        "4": "12.28%*5+143.19%",
        "5": "13.07%*5+152.38%",
        "6": "13.97%*5+162.94%",
        "7": "15.23%*5+177.63%",
        "8": "16.49%*5+192.32%",
        "9": "17.75%*5+207.01%",
        "10": "19.09%*5+222.62%",
      },
      type: "Heavy",
    },
    {
      key: "SwordStanceFlowAzure",
      label: "Sword Stance Flow - Azure",
      talents: {
        "1": "58.64%",
        "2": "63.45%",
        "3": "68.26%",
        "4": "74.99%",
        "5": "79.80%",
        "6": "85.33%",
        "7": "93.03%",
        "8": "100.72%",
        "9": "108.41%",
        "10": "116.59%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage1",
      label: "Dodge Counter - Havoc in Bloom Stage 1",
      talents: {
        "1": "26.68%*3",
        "2": "28.87%*3",
        "3": "31.06%*3",
        "4": "34.12%*3",
        "5": "36.31%*3",
        "6": "38.83%*3",
        "7": "42.33%*3",
        "8": "45.83%*3",
        "9": "49.33%*3",
        "10": "53.05%*3",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage2",
      label: "Dodge Counter - Havoc in Bloom Stage 2",
      talents: {
        "1": "59.86%+44.90%+44.90%",
        "2": "64.77%+48.58%+48.58%",
        "3": "69.68%+52.26%+52.26%",
        "4": "76.55%+57.41%+57.41%",
        "5": "81.46%+61.09%+61.09%",
        "6": "87.10%+65.33%+65.33%",
        "7": "94.95%+71.22%+71.22%",
        "8": "102.81%+77.11%+77.11%",
        "9": "110.66%+83.00%+83.00%",
        "10": "119.00%+89.25%+89.25%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterHavocInBloomStage3",
      label: "Dodge Counter - Havoc in Bloom Stage 3",
      talents: {
        "1": "9.60%*5+111.98%",
        "2": "10.39%*5+121.16%",
        "3": "11.18%*5+130.34%",
        "4": "12.28%*5+143.19%",
        "5": "13.07%*5+152.38%",
        "6": "13.97%*5+162.94%",
        "7": "15.23%*5+177.63%",
        "8": "16.49%*5+192.32%",
        "9": "17.75%*5+207.01%",
        "10": "19.09%*5+222.62%",
      },
      type: "Heavy",
    }
  ],
};
