export const rotations: RotationPreset[] = [
  {
    name: `Standard`,
    description: `Intro can be Heavy 2 another Ground Skill. \nCan be broken up for quickswap.`,
    author: `vv ubFiish`,
    data: {
      name: "Standard",
      description:
        "Intro can be Heavy 2 another Ground Skill. \nCan be broken up for quickswap.",
      actions: [
        {
          order: 1,
          key: "RelentlessSquallDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "CloudburstDanceStage1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "CloudburstDanceStage2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "SkyfallSeveranceDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "OmegaStormDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "AwakeningGaleDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "CloudburstDanceStage1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "CloudburstDanceStage2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "MidAirAttackDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "UnboundFlowStage1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "UnboundFlowStage2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];
