export const rotations: RotationPreset[] = [
  {
    name: `DPS Rotation (On-Field Role)`,
    description: `Q (Swap) → Intro → E → Mid-Air Attacks ×12 → Dash into Mist (Trigger 2 Forte Mist Bullets) → R → BA12345 → Mid-Air Attacks ×12 → E → Mid-Air Attacks ×12 → Q → Outro`,
    author: `Namelag`,
    data: {
      name: "DPS Rotation (On-Field Role)",
      description:
        "Q (Swap) → Intro → E → Mid-Air Attacks ×12 → Dash into Mist (Trigger 2 Forte Mist Bullets) → R → BA12345 → Mid-Air Attacks ×12 → E → Mid-Air Attacks ×12 → Q → Outro",
      actions: [
        {
          order: 2,
          key: "FeintShotSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "MistBulletDamage",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "HalfTruthsMidAirAttackDMG",
          type: "basic",
          count: "12",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "MistBulletDMG",
          type: "forteCircuit",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "FlowerintheMistDamage",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "HalfTruthsStage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "HalfTruthsStage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "HalfTruthsStage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "HalfTruthsStage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "HalfTruthsStage5DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "HalfTruthsMidAirAttackDMG",
          type: "basic",
          count: "12",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "MistBulletDamage",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "HalfTruthsMidAirAttackDMG",
          type: "basic",
          count: "12",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 14,
          key: "FeintShotSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: `Sub-DPS Rotation (Off-Field Role`,
    description: `E → Q (Swap) → Intro → R → E → BA12345 → Mid-Air Attacks ×12 → Outro`,
    author: `Namelag`,
    data: {
      name: "Sub-DPS Rotation (Off-Field Role)",
      description:
        "E → Q (Swap) → Intro → R → E → BA12345 → Mid-Air Attacks ×12 → Outro",
      actions: [
        {
          order: 1,
          key: "MistBulletDamage",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "FeintShotSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "FlowerintheMistDamage",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "MistBulletDamage",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "HalfTruthsStage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "HalfTruthsStage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "HalfTruthsStage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "HalfTruthsStage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "HalfTruthsStage5DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "HalfTruthsMidAirAttackDMG",
          type: "basic",
          count: "12",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];
