interface Echo {
  key: string;
  name: string;
  class: string;
  image: string;
  details: string;
  modifiers: EchoModifier[];
}

interface EchoModifier {
  modifier?: string;
  modifierValue?: number;
}

type MainEchoes = Record<string, Echo>;

export const mainEchoesData: MainEchoes = {
  AeroPredator: {
    key: "AeroPredator",
    name: "Aero Predator",
    class: "Common",
    image: "/images/echoes/AeroPredator.png",
    details: ``,
    modifiers: [],
  },
  AlteredClangBang: {
    key: "AlteredClangBang",
    name: "Altered Clang Bang",
    class: "",
    image: "/images/echoes/AlteredClangBang.png",
    details: ``,
    modifiers: [],
  },
  AlteredLightcrusher: {
    key: "AlteredLightcrusher",
    name: "Altered Lightcrusher",
    class: "",
    image: "/images/echoes/AlteredLightcrusher.png",
    details: ``,
    modifiers: [],
  },
  AutopuppetScout: {
    key: "AutopuppetScout",
    name: "Autopuppet Scout",
    class: "Elite",
    image: "/images/echoes/AutopuppetScout.png",
    details: ``,
    modifiers: [],
  },
  BellBorneGeochelone: {
    key: "BellBorneGeochelone",
    name: "Bell-Borne Geochelone",
    class: "",
    image: "/images/echoes/BellBorneGeochelone.png",
    details: ``,
    modifiers: [],
  },
  Chaserazor: {
    key: "Chaserazor",
    name: "Chaserazor",
    class: "",
    image: "/images/echoes/Chaserazor.png",
    details: ``,
    modifiers: [],
  },
  ChasmGuardian: {
    key: "ChasmGuardian",
    name: "Chasm Guardian",
    class: "",
    image: "/images/echoes/ChasmGuardian.png",
    details: ``,
    modifiers: [],
  },
  Chirpuff: {
    key: "Chirpuff",
    name: "Chirpuff",
    class: "",
    image: "/images/echoes/Chirpuff.png",
    details: ``,
    modifiers: [],
  },
  ClangBang: {
    key: "ClangBang",
    name: "Clang Bang",
    class: "",
    image: "/images/echoes/ClangBang.png",
    details: ``,
    modifiers: [],
  },
  Crownless: {
    key: "Crownless",
    name: "Crownless",
    class: "",
    image: "/images/echoes/Crownless.png",
    details: ``,
    modifiers: [],
  },
  Cruisewing: {
    key: "Cruisewing",
    name: "Cruisewing",
    class: "",
    image: "/images/echoes/Cruisewing.png",
    details: ``,
    modifiers: [],
  },
  CyanFeatheredHeron: {
    key: "CyanFeatheredHeron",
    name: "Cyan-Feathered Heron",
    class: "",
    image: "/images/echoes/CyanFeatheredHeron.png",
    details: ``,
    modifiers: [],
  },
  Diamondclaw: {
    key: "Diamondclaw",
    name: "Diamondclaw",
    class: "",
    image: "/images/echoes/Diamondclaw.png",
    details: ``,
    modifiers: [],
  },
  Dreamless: {
    key: "Dreamless",
    name: "Dreamless",
    class: "",
    image: "/images/echoes/Dreamless.png",
    details: ``,
    modifiers: [],
  },
  DwarfCassowary: {
    key: "DwarfCassowary",
    name: "Dwarf Cassowary",
    class: "",
    image: "/images/echoes/DwarfCassowary.png",
    details: ``,
    modifiers: [],
  },
  ElectroPredator: {
    key: "ElectroPredator",
    name: "Electro Predator",
    class: "",
    image: "/images/echoes/ElectroPredator.png",
    details: ``,
    modifiers: [],
  },
  Excarat: {
    key: "Excarat",
    name: "Excarat",
    class: "",
    image: "/images/echoes/Excarat.png",
    details: ``,
    modifiers: [],
  },
  FissionJunrock: {
    key: "FissionJunrock",
    name: "Fission Junrock",
    class: "",
    image: "/images/echoes/FissionJunrock.png",
    details: ``,
    modifiers: [],
  },
  Flautist: {
    key: "Flautist",
    name: "Flautist",
    class: "",
    image: "/images/echoes/Flautist.png",
    details: ``,
    modifiers: [],
  },
  FusionDreadmane: {
    key: "FusionDreadmane",
    name: "Fusion Dreadmane",
    class: "",
    image: "/images/echoes/FusionDreadmane.png",
    details: ``,
    modifiers: [],
  },
  FusionPrism: {
    key: "FusionPrism",
    name: "Fusion Prism",
    class: "",
    image: "/images/echoes/FusionPrism.png",
    details: ``,
    modifiers: [],
  },
  FusionWarrior: {
    key: "FusionWarrior",
    name: "Fusion Warrior",
    class: "",
    image: "/images/echoes/FusionWarrior.png",
    details: ``,
    modifiers: [],
  },
  Gulpuff: {
    key: "Gulpuff",
    name: "Gulpuff",
    class: "",
    image: "/images/echoes/Gulpuff.png",
    details: ``,
    modifiers: [],
  },
  HavocDreadmane: {
    key: "HavocDreadmane",
    name: "Havoc Dreadmane",
    class: "",
    image: "/images/echoes/HavocDreadmane.png",
    details: ``,
    modifiers: [],
  },
  HavocPrism: {
    key: "HavocPrism",
    name: "Havoc Prism",
    class: "",
    image: "/images/echoes/HavocPrism.png",
    details: ``,
    modifiers: [],
  },
  HavocWarrior: {
    key: "HavocWarrior",
    name: "Havoc Warrior",
    class: "",
    image: "/images/echoes/HavocWarrior.png",
    details: ``,
    modifiers: [],
  },
  Hoartoise: {
    key: "Hoartoise",
    name: "Hoartoise",
    class: "",
    image: "/images/echoes/Hoartoise.png",
    details: ``,
    modifiers: [],
  },
  Hoochief: {
    key: "Hoochief",
    name: "Hoochief",
    class: "",
    image: "/images/echoes/Hoochief.png",
    details: ``,
    modifiers: [],
  },
  HoochiefCyclone: {
    key: "HoochiefCyclone",
    name: "Hoochief Cyclone",
    class: "",
    image: "/images/echoes/HoochiefCyclone.png",
    details: ``,
    modifiers: [],
  },
  HoochiefMenace: {
    key: "HoochiefMenace",
    name: "Hoochief Menace",
    class: "",
    image: "/images/echoes/HoochiefMenace.png",
    details: ``,
    modifiers: [],
  },
  Hooscamp: {
    key: "Hooscamp",
    name: "Hooscamp",
    class: "",
    image: "/images/echoes/Hooscamp.png",
    details: ``,
    modifiers: [],
  },
  HooscampClapperclaw: {
    key: "HooscampClapperclaw",
    name: "Hooscamp Clapperclaw",
    class: "",
    image: "/images/echoes/HooscampClapperclaw.png",
    details: ``,
    modifiers: [],
  },
  HooscampFlinger: {
    key: "HooscampFlinger",
    name: "Hooscamp Flinger",
    class: "",
    image: "/images/echoes/HooscampFlinger.png",
    details: ``,
    modifiers: [],
  },
  ImpermanenceHeron: {
    key: "ImpermanenceHeron",
    name: "Impermanence Heron",
    class: "",
    image: "/images/echoes/ImpermanenceHeron.png",
    details: ``,
    modifiers: [],
  },
  InfernoRider: {
    key: "InfernoRider",
    name: "Inferno Rider",
    class: "Overlord",
    image: "/images/echoes/InfernoRider.png",
    details: `<span class="description">Transform into Inferno Rider to launch up to 3 consecutive slashes in a row, each slash dealing <span class="param">151.50%/174.23%/196.95%/219.68%/242.40%</span>, <span class="param">176.75%/203.26%/229.78%/256.29%/282.80%</span>, and <span class="param">176.75%/203.26%/229.78%/256.29%/282.80%</span> Fusion DMG respectively.

    After the final hit, increase the current character’s Fusion DMG by <span class="param">12.00%</span> and Basic Attack DMG by <span class="param">12.00%</span> for <span class="param">15</span>s.
    
    Long press the Echo Skill to transform into Inferno Rider and enter the Riding Mode. When exiting the Riding Mode, deal <span class="param">176.75%/203.26%/229.78%/256.29%/282.80%</span> Fusion DMG to enemies in front.
    
    CD: <span class="param">20</span>s</span>`,
    modifiers: [
      {
        modifier: "Fusion",
        modifierValue: 0.12,
      },
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.12,
      },
    ],
  },
  Jué: {
    key: "Jué",
    name: "Jué",
    class: "Overlord",
    image: "/images/echoes/Jue.png",
    details: `<span class="description">Summon Jué to leap into the air, dealing <span class="param">30.40%/34.96%/39.52%/44.08%/48.64%</span> Spectro DMG to the enemies and bringing forth Lightthunder. Lightthunder hits up to 5 times in total, each dealing <span class="param">12.16%/13.98%/15.81%/17.63%/19.46%</span> Spectro DMG to the surrounding enemies. Then Jué spirals downward to attack the surrounding enemies, dealing <span class="param">30.40%/34.96%/39.52%/44.08%/48.64%</span> Spectro DMG two times in a row. 
    The Resonator equipped with this Echo Skill obtains 1 stack of "Blessing of Time" every 6s, stacking up to 3 times. When the Resonator performs Resonance Skill, 1 stack of "Blessing of Time" is consumed, dealing <span class="param">15</span> Spectro DMG to the surrounding enemies. The enemies hit receive <span class="param">16.00%</span> Spectro DMG per second over 6s, stacking up to 3 times and new stacks extending the effect period. The damage dealt through consuming the stacks of "Blessing of Time" is considered as Resonance Skill DMG.
    
    CD: <span class="param">10.00%/11.50%/13.00%/14.50%/16.00%</span>s</span>`,
    modifiers: [],
  },
  LampylumenMyriad: {
    key: "LampylumenMyriad",
    name: "Lampylumen Myriad",
    class: "",
    image: "/images/echoes/LampylumenMyriad.png",
    details: ``,
    modifiers: [],
  },
  Lightcrusher: {
    key: "Lightcrusher",
    name: "Lightcrusher",
    class: "",
    image: "/images/echoes/Lightcrusher.png",
    details: ``,
    modifiers: [],
  },
  LumiscaleConstruct: {
    key: "LumiscaleConstruct",
    name: "Lumiscale Construct",
    class: "",
    image: "/images/echoes/LumiscaleConstruct.png",
    details: ``,
    modifiers: [],
  },
  MechAbomination: {
    key: "MechAbomination",
    name: "Mech Abomination",
    class: "",
    image: "/images/echoes/MechAbomination.png",
    details: ``,
    modifiers: [],
  },
  MourningAix: {
    key: "MourningAix",
    name: "Mourning Aix",
    class: "",
    image: "/images/echoes/MourningAix.png",
    details: ``,
    modifiers: [],
  },
  PhantomFeilianBeringal: {
    key: "PhantomFeilianBeringal",
    name: "Phantom: Feilian Beringal",
    class: "",
    image: "/images/echoes/PhantomFeilianBeringal.png",
    details: ``,
    modifiers: [],
  },
  PhantomHoartoise: {
    key: "PhantomHoartoise",
    name: "Phantom: Hoartoise",
    class: "",
    image: "/images/echoes/PhantomHoartoise.png",
    details: ``,
    modifiers: [],
  },
  PhantomImpermanenceHeron: {
    key: "PhantomImpermanenceHeron",
    name: "Phantom: Impermanence Heron",
    class: "",
    image: "/images/echoes/PhantomImpermanenceHeron.png",
    details: ``,
    modifiers: [],
  },
  PhantomMourningAix: {
    key: "PhantomMourningAix",
    name: "Phantom: Mourning Aix",
    class: "",
    image: "/images/echoes/PhantomMourningAix.png",
    details: ``,
    modifiers: [],
  },
  PhantomRocksteadyGuardian: {
    key: "PhantomRocksteadyGuardian",
    name: "Phantom: Rocksteady Guardian",
    class: "",
    image: "/images/echoes/PhantomRocksteadyGuardian.png",
    details: ``,
    modifiers: [],
  },
  PhantomThunderingMephis: {
    key: "PhantomThunderingMephis",
    name: "Phantom: Thundering Mephis",
    class: "",
    image: "/images/echoes/PhantomThunderingMephis.png",
    details: ``,
    modifiers: [],
  },
  RocksteadyGuardian: {
    key: "RocksteadyGuardian",
    name: "Rocksteady Guardian",
    class: "",
    image: "/images/echoes/RocksteadyGuardian.png",
    details: ``,
    modifiers: [],
  },
  Roseshroom: {
    key: "Roseshroom",
    name: "Roseshroom",
    class: "",
    image: "/images/echoes/Roseshroom.png",
    details: ``,
    modifiers: [],
  },
  SabyrBoar: {
    key: "SabyrBoar",
    name: "Sabyr Boar",
    class: "",
    image: "/images/echoes/SabyrBoar.png",
    details: ``,
    modifiers: [],
  },
  Scar: {
    key: "Scar",
    name: "Scar",
    class: "",
    image: "/images/echoes/Scar.png",
    details: ``,
    modifiers: [],
  },
  SnipSnap: {
    key: "SnipSnap",
    name: "Snip Snap",
    class: "",
    image: "/images/echoes/SnipSnap.png",
    details: ``,
    modifiers: [],
  },
  Spearback: {
    key: "Spearback",
    name: "Spearback",
    class: "",
    image: "/images/echoes/Spearback.png",
    details: ``,
    modifiers: [],
  },
  SpectroPrism: {
    key: "SpectroPrism",
    name: "Spectro Prism",
    class: "",
    image: "/images/echoes/SpectroPrism.png",
    details: ``,
    modifiers: [],
  },
  StonewallBracer: {
    key: "StonewallBracer",
    name: "Stonewall Bracer",
    class: "",
    image: "/images/echoes/StonewallBracer.png",
    details: ``,
    modifiers: [],
  },
  TempestMephis: {
    key: "TempestMephis",
    name: "Tempest Mephis",
    class: "",
    image: "/images/echoes/TempestMephis.png",
    details: ``,
    modifiers: [],
  },
  ThunderingMephis: {
    key: "ThunderingMephis",
    name: "Thundering Mephis",
    class: "",
    image: "/images/echoes/ThunderingMephis.png",
    details: ``,
    modifiers: [],
  },
  TickTack: {
    key: "TickTack",
    name: "Tick Tack",
    class: "",
    image: "/images/echoes/TickTack.png",
    details: ``,
    modifiers: [],
  },
  TrafficIlluminator: {
    key: "TrafficIlluminator",
    name: "Traffic Illuminator",
    class: "",
    image: "/images/echoes/TrafficIlluminator.png",
    details: ``,
    modifiers: [],
  },
  VanguardJunrock: {
    key: "VanguardJunrock",
    name: "Vanguard Junrock",
    class: "",
    image: "/images/echoes/VanguardJunrock.png",
    details: ``,
    modifiers: [],
  },
  VioletFeatheredHeron: {
    key: "VioletFeatheredHeron",
    name: "Violet-Feathered Heron",
    class: "",
    image: "/images/echoes/VioletFeatheredHeron.png",
    details: ``,
    modifiers: [],
  },
  WhiffWhaff: {
    key: "WhiffWhaff",
    name: "Whiff Whaff",
    class: "",
    image: "/images/echoes/WhiffWhaff.png",
    details: ``,
    modifiers: [],
  },
  YoungGeohideSaurian: {
    key: "YoungGeohideSaurian",
    name: "Young Geohide Saurian",
    class: "",
    image: "/images/echoes/YoungGeohideSaurian.png",
    details: ``,
    modifiers: [],
  },
  YoungRoseshroom: {
    key: "YoungRoseshroom",
    name: "Young Roseshroom",
    class: "",
    image: "/images/echoes/YoungRoseshroom.png",
    details: ``,
    modifiers: [],
  },
  ZigZag: {
    key: "ZigZag",
    name: "Zig Zag",
    class: "",
    image: "/images/echoes/ZigZag.png",
    details: ``,
    modifiers: [],
  },
};

export const allEchoes: string[] = [
  "Aero Predator",
  "Altered Clang Bang",
  "Altered Lightcrusher",
  "Autopuppet Scout",
  "Bell-Borne Geochelone",
  "Chaserazor",
  "Chasm Guardian",
  "Chirpuff",
  "Clang Bang",
  "Crownless",
  "Cruisewing",
  "Cyan-Feathered Heron",
  "Diamondclaw",
  "Dreamless",
  "Dwarf Cassowary",
  "Electro Predator",
  "Excarat",
  "Feilian Beringal",
  "Firebug",
  "Fission Junrock",
  "Flautist",
  "Fusion Dreadmane",
  "Fusion Prism",
  "Fusion Warrior",
  "Geohide Saurian",
  "Glacio Dreadmane",
  "Glacio Predator",
  "Glacio Prism",
  "Gulpuff",
  "Havoc Dreadmane",
  "Havoc Prism",
  "Havoc Warrior",
  "Hoartoise",
  "Hoochief",
  "Hoochief Cyclone",
  "Hoochief Menace",
  "Hooscamp",
  "Hooscamp Clapperclaw",
  "Hooscamp Flinger",
  "Impermanence Heron",
  "Inferno Rider",
  "Jué",
  "Lampylumen Myriad",
  "Lightcrusher",
  "Lumiscale Construct",
  "Mech Abomination",
  "Mourning Aix",
  "Phantom: Feilian Beringal",
  "Phantom: Hoartoise",
  "Phantom: Impermanence Heron",
  "Phantom: Mourning Aix",
  "Phantom: Rocksteady Guardian",
  "Phantom: Thundering Mephis",
  "Rocksteady Guardian",
  "Roseshroom",
  "Sabyr Boar",
  "Scar",
  "Snip Snap",
  "Spearback",
  "Spectro Prism",
  "Stonewall Bracer",
  "Tambourinist",
  "Tempest Mephis",
  "Thundering Mephis",
  "Tick Tack",
  "Traffic Illuminator",
  "Vanguard Junrock",
  "Violet-Feathered Heron",
  "Whiff Whaff",
  "Young Geohide Saurian",
  "Young Roseshroom",
  "Zig Zag",
];
