export const skillAttacks = {
  name: "Resonance Skill: Magnetic Roar",
  description: `<div class="skilldescription"><span class="Title">Magnetic Roar</span><br>The puppet "Zapstring" deals <span class="Thunder">Electro DMG</span> to the target, and puts Yinlin in Resonance Skill <span class="Highlight">Execution Mode</span>.<br> <br><span class="Title">Execution Mode</span><br><span class="Highlight">Basic Attack</span> and <span class="Highlight">Dodge Counter</span> will trigger 1 <span class="Highlight">Electromagnetic Blast</span> when hitting a target.<br>Each stage of <span class="Highlight">Basic Attack</span> or <span class="Highlight">Dodge Counter</span> can only trigger 1 <span class="Highlight">Electromagnetic Blast</span>, up to 4 times.<br> <br><span class="Title">Electromagnetic Blast</span><br>Attack all targets marked with Forte Circuit <span class="Highlight">Sinner's Mark</span>, dealing <span class="Thunder">Electro DMG</span>.<br> <br><span class="Title">Lightning Execution</span><br>Use Resonance Skill after casting Resonance Skill <span class="Highlight">Magnetic Roar</span> to cast <span class="Highlight">Lightning Execution</span> to attack the target, dealing <span class="Thunder">Electro DMG</span>.<br>If Resonance Skill <span class="Highlight">Lightning Execution</span> is not activated in a while or this Character is switched, this Skill will be put on Cooldown.</div>`,
  attacks: [
    {
      key: "MagneticRoarDamage",
      label: "Magnetic Roar Damage",
      talents: {
        "1": "30%*3",
        "2": "32.46%*3",
        "3": "34.92%*3",
        "4": "38.37%*3",
        "5": "40.83%*3",
        "6": "43.66%*3",
        "7": "47.59%*3",
        "8": "51.53%*3",
        "9": "55.47%*3",
        "10": "59.65%*3",
      },
      type: "Skill",
    },
    {
      key: "LightningExecutionDamage",
      label: "Lightning Execution Damage",
      talents: {
        "1": "45%*4",
        "2": "48.69%*4",
        "3": "52.38%*4",
        "4": "57.55%*4",
        "5": "61.24%*4",
        "6": "65.48%*4",
        "7": "71.39%*4",
        "8": "77.29%*4",
        "9": "83.2%*4",
        "10": "89.47%*4",
      },
      type: "Skill",
    },
    {
      key: "ElectromagneticBlastDamage",
      label: "Electromagnetic Blast Damage",
      talents: {
        "1": "10%",
        "2": "10.82%",
        "3": "11.64%",
        "4": "12.79%",
        "5": "13.61%",
        "6": "14.56%",
        "7": "15.87%",
        "8": "17.18%",
        "9": "18.49%",
        "10": "19.89%",
      },
      type: "Skill",
    },
  ],
};
