export const resonanceChains = [
  {
    key: "SequenceNode1SolitaryEtude",
    name: "Sequence Node 1: Solitary Etude",
    details: `<span class="skilldescription">During Resonance Liberation <span class="Highlight">Burning Rhapsody</span>, Mortefi launches Coordinated Attacks when the on-field character performs their Resonance Skills, firing 2 Resonance Liberation's <span class="Highlight">Marcato</span> hits, dealing <span class="Fire">Fusion DMG</span>.</span>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode2HypocriticalHymn",
    name: "Sequence Node 2: Hypocritical Hymn",
    details: `After using the Echo Skill, Mortefi restores an additional 10 Resonance Energy. This can be triggered once every 20 second.`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode3FlamingRecitativo",
    name: "Sequence Node 3: Flaming Recitativo",
    details: `<span class="skilldescription">During Resonance Liberation <span class="Highlight">Burning Rhapsody</span>, the Crit. DMG of Resonance Liberation's <span class="Highlight">Marcato</span> is increased by 30%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifySpecificTalents: ["MarcatoDamage", "SequenceNodeFuneraryQuartet"],
        modifierValue: 0.3,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode4CatharticWaltz",
    name: "Sequence Node 4: Cathartic Waltz",
    details: `<span class="skilldescription">The duration of Resonance Liberation <span class="Highlight">Burning Rhapsody</span> is extended by 7s.</span>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNodeFuneraryQuartet",
    name: "Sequence Node 5: Funerary Quartet",
    details: `<span class="skilldescription">When Resonance Skill <span class="Highlight">Passionate Variation</span> or Resonance Skill <span class="Highlight">Fury Fugue</span> hits a target, Coordinated Attacks will be triggered to fire 4 Resonance Liberation's <span class="Highlight">Marcato</span> hit(s), dealing <span class="Fire">Fusion Damage</span>. DMG of Resonance Liberation's <span class="Highlight">Marcato</span> fired in this way is reduced by 50%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "EnableAttack",
        modifierValue: ["SequenceNodeFuneraryQuartet"],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode6ApoplecticInstrumental",
    name: "Sequence Node 6: Apoplectic Instrumental",
    details: `<span class="skilldescription">When Resonance Liberation <span class="Highlight">Violent Finale</span> is cast, ATK of all team members is increased by 20% for 20s.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
