export const forteCircuitAttacks = {
  name: "Forte Circuit: Cycle of Wind",
  description: `<div class="skilldescription"><span class="Title">Mid-air Attack - Cloudburst Dance</span><br>Perform up to 2 consecutive attacks, dealing <span class="Wind">Aero DMG</span> (considered Resonance Skill DMG) and healing all nearby Resonators in the team. Cast through the following 3 ways:<br>- Press <span class="Highlight">Normal Attack</span> right after casting Resonance Skill <span class="Highlight">Awakening Gale</span>.<br>- Press <span class="Highlight">Normal Attack</span> right after casting <span class="Highlight">Intro Skill</span>.<br>- Press <span class="Highlight">Normal Attack</span> right after casting Heavy Attack <span class="Highlight">Razor Wind</span>.<br>When casting Mid-air Attack <span class="Highlight">Cloudburst Dance</span>, hold <span class="Highlight">Normal Attack</span> to perform <span class="Highlight">Mid-air Attack</span>.<br><br><span class="Title">Resonance Skill - Unbound Flow</span><br>At max Windstrings, Resonance Skill <span class="Highlight">Awakening Gale</span> becomes Resonance Skill <span class="Highlight">Unbound Flow</span>: Perform up to 2 consecutive attacks. Each attack consumes 60 Windstrings, dealing <span class="Wind">Aero DMG</span>, considered Resonance Skill DMG.<br>Switching to another Resonator after Stage 1 automatically triggers Stage 2 of this skill. <br><br><span class="Title">Windstring</span><br>Rover can hold up to 120 Windstrings.<br>Each stage of Mid-air Attack <span class="Highlight">Cloudburst Dance</span> restores 25 Windstrings on hit.<br>Casting <span class="Highlight">Intro Skill</span> restores 20 Windstrings.<br>Hitting a target with <span class="Highlight">Basic Attack Stage 3 or 4</span> or <span class="Highlight">Dodge Counter</span> restores 10 Windstrings.</div>`,
  attacks: [
    {
      key: "CloudburstDanceStage1DMG",
      label: "Cloudburst Dance Stage 1 DMG",
      talents: {
        "1": "64.79%",
        "2": "70.10%",
        "3": "75.41%",
        "4": "82.85%",
        "5": "88.16%",
        "6": "94.27%",
        "7": "102.77%",
        "8": "111.27%",
        "9": "119.77%",
        "10": "128.80%",
      },
      type: "Skill",
    },
    {
      key: "CloudburstDanceStage2DMG",
      label: "Cloudburst Dance Stage 2 DMG",
      talents: {
        "1": "71.16%",
        "2": "76.99%",
        "3": "82.83%",
        "4": "91.00%",
        "5": "96.83%",
        "6": "103.54%",
        "7": "112.88%",
        "8": "122.21%",
        "9": "131.55%",
        "10": "141.47%",
      },
      type: "Skill",
    },
    {
      key: "CloudburstDanceHealing",
      label: "Cloudburst Dance Healing",
      talents: {
        "1": "330 + 11.00%",
        "2": "369 + 11.44%",
        "3": "412 + 11.88%",
        "4": "462 + 12.54%",
        "5": "521 + 13.42%",
        "6": "577 + 14.30%",
        "7": "587 + 15.95%",
        "8": "600 + 17.82%",
        "9": "610 + 19.80%",
        "10": "627 + 23.10%",
      },
      type: "Healing",
    },
    {
      key: "UnboundFlowStage1DMG",
      label: "Unbound Flow Stage 1 DMG",
      talents: {
        "1": "17.26%*5",
        "2": "18.67%*5",
        "3": "20.09%*5",
        "4": "22.07%*5",
        "5": "23.48%*5",
        "6": "25.11%*5",
        "7": "27.37%*5",
        "8": "29.63%*5",
        "9": "31.90%*5",
        "10": "34.30%*5",
      },
      type: "Skill",
    },
    {
      key: "UnboundFlowStage2DMG",
      label: "Unbound Flow Stage 2 DMG",
      talents: {
        "1": "363.68%",
        "2": "393.50%",
        "3": "423.32%",
        "4": "465.07%",
        "5": "494.90%",
        "6": "529.19%",
        "7": "576.90%",
        "8": "624.62%",
        "9": "672.33%",
        "10": "723.03%",
      },
      type: "Skill",
    }
  ],  
};
