export const rotations: RotationPreset[] = [
    {
        name: `Danjin rotation`,
        description: `Standard rotation`,
        author: `Val`,
        data: {"name":"Danjin rotation","description":"","actions":[{"order":1,"key":"Part1DMG","type":"basic","count":1,"buffs":[]},{"order":2,"key":"Part2DMG","type":"basic","count":1,"buffs":[]},{"order":3,"key":"CrimsonErosion1","type":"skill","count":1,"buffs":[]},{"order":4,"key":"CrimsonErosion2","type":"skill","count":1,"buffs":[]},{"order":5,"key":"Part1DMG","type":"basic","count":1,"buffs":[]},{"order":6,"key":"Part2DMG","type":"basic","count":1,"buffs":[]},{"order":7,"key":"Part3DMG","type":"basic","count":1,"buffs":[]},{"order":8,"key":"SanguinePulse1","type":"skill","count":1,"buffs":[]},{"order":9,"key":"SanguinePulse2","type":"skill","count":1,"buffs":[]},{"order":10,"key":"SanguinePulse3","type":"skill","count":1,"buffs":[]},{"order":11,"key":"CrimsonBloomContinuousATKDMG","type":"liberation","count":1,"buffs":[]},{"order":12,"key":"CrimsonBloomScarletBurstDMG","type":"liberation","count":1,"buffs":[]},{"order":13,"key":"SkillDMG","type":"intro","count":1,"buffs":[]},{"order":14,"key":"Part1DMG","type":"basic","count":1,"buffs":[]},{"order":15,"key":"Part2DMG","type":"basic","count":1,"buffs":[]},{"order":16,"key":"CrimsonErosion1","type":"skill","count":1,"buffs":[]},{"order":17,"key":"CrimsonErosion2","type":"skill","count":1,"buffs":[]},{"order":18,"key":"Part1DMG","type":"basic","count":1,"buffs":[]},{"order":19,"key":"Part2DMG","type":"basic","count":1,"buffs":[]},{"order":20,"key":"Part3DMG","type":"basic","count":1,"buffs":[]},{"order":21,"key":"SanguinePulse1","type":"skill","count":1,"buffs":[]},{"order":22,"key":"SanguinePulse2","type":"skill","count":1,"buffs":[]},{"order":23,"key":"SanguinePulse3","type":"skill","count":1,"buffs":[]},{"order":24,"key":"FullScatterbloomDamage","type":"forteCircuit","count":1,"buffs":[]},{"order":25,"key":"FullChaoscleaveDamage","type":"forteCircuit","count":1,"buffs":[]}]}
    },
];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR Havoc Eclipse build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 15.2% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"NightmareCrownless","echoSet":"SunSinkingEclipse","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"HavocDreadmane","echoSet":"SunSinkingEclipse","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Tambourinist","echoSet":"SunSinkingEclipse","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":7.6,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"Chirpuff","echoSet":"SunSinkingEclipse","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":7.6,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"HavocPrism","echoSet":"SunSinkingEclipse","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}}}
    },
];