export const basicAttacks = {
  name: "Normal Attack: Hunter's Path",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Basic Attack</span></span><br>Perform up to 4 consecutive attacks, dealing <span class="ingame-Thunder">Electro DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Steelclash</span></span><br>Consume STA to attack the target, dealing <span class="ingame-Thunder">Electro DMG</span>. <span class="ingame-Highlight">Press Normal Attack</span> shortly after performing Heavy Attack to perform <span class="ingame-Highlight">Basic Attack Stage 2</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Mid-air Attack</span></span><br>Consume STA to perform Plunging Attack from mid-air, dealing <span class="ingame-Thunder">Electro DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter</span></span><br><span class="ingame-Highlight">Press Normal Attack</span> after a successful Dodge to attack the target, dealing <span class="ingame-Thunder">Electro DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Mid-air Dodge Counter</span></span><br><span class="ingame-Highlight">Press Normal Attack</span> after a successful Mid-air Dodge to perform Plunging Attack at the cost of STA, dealing <span class="ingame-Thunder">Electro DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Thunderoar: Backstep</span></span><br>When <a onclick="showTermExplan(130602)" class="ingame-term-desc">Prowess</a> is full, <span class="ingame-Highlight">Heavy Attack - Steelclash</span> is replaced with <span class="ingame-Highlight">Heavy Attack - Thunderoar: Backstep</span>, dealing <span class="ingame-Thunder">Electro DMG</span> and consuming all Prowess.<br>- While in action, <span class="ingame-Highlight">release</span> or <span class="ingame-Highlight">press Normal Attack</span> again within a certain period to perform <span class="ingame-Highlight">Heavy Attack - Thunderoar: Spinslash</span>.<br>- <span class="ingame-Highlight">Heavy Attack - Thunderoar: Spinslash</span> is available if Augusta remains on the ground for a certain period after this skill is interrupted.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Thunderoar: Spinslash</span></span><br>Augusta whirls and lashes out with her Broadblade, dealing <span class="ingame-Thunder">Electro DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Thunderoar: Uppercut</span></span><br><span class="ingame-Highlight">Press Jump</span> when <a onclick="showTermExplan(130602)" class="ingame-term-desc">Prowess</a> is full to perform <span class="ingame-Highlight">Heavy Attack - Thunderoar: Uppercut</span>, dealing <span class="ingame-Thunder">Electro DMG</span> and consuming all Prowess.<br>If Prowess is full when casting <span class="ingame-Highlight">Resonance Skill - Warrior's Blade</span>, <span class="ingame-Highlight">press Resonance Skill</span> or <span class="ingame-Highlight">Jump</span> to perform <span class="ingame-Highlight">Heavy Attack - Thunderoar: Uppercut</span>, dealing <span class="ingame-Thunder">Electro DMG</span> and consuming all Prowess.<br>If Prowess is full when casting <span class="ingame-Highlight">Heavy Attack - Steelclash</span> or <span class="ingame-Highlight">Dodge Counter – Heavy Attack: Steelclash</span>, <span class="ingame-Highlight">release Normal Attack</span> after a certain period or <span class="ingame-Highlight">press Normal Attack</span> or <span class="ingame-Highlight">Jump</span> again to perform <span class="ingame-Highlight">Heavy Attack - Thunderoar: Uppercut</span>, dealing, <span class="ingame-Thunder">Electro DMG</span> and consuming all Prowess.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter - Heavy Attack: Steelclash</span></span><br>When <a onclick="showTermExplan(130602)" class="ingame-term-desc">Prowess</a> is full, <span class="ingame-Highlight">Dodge Counter</span> is replaced with <span class="ingame-Highlight">Dodge Counter - Heavy Attack: Steelclash</span>, dealing <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter - Thunderoar: Backstep</span></span><br>When <a onclick="showTermExplan(130603)" class="ingame-term-desc">Ascendancy</a> is full, <span class="ingame-Highlight">press Normal Attack</span> following a successful Dodge on the ground to cast <span class="ingame-Highlight">Dodge Counter - Thunderoar: Backstep</span> in place of <span class="ingame-Highlight">Dodge Counter</span> and <span class="ingame-Highlight">Dodge Counter - Heavy Attack: Steelclash</span>, dealing <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG.<br>- <span class="ingame-Highlight">Release</span> or <span class="ingame-Highlight">press Normal Attack</span> again within a certain period into the action to perform <span class="ingame-Highlight">Heavy Attack - Thunderoar: Spinslash</span>.<br>- <span class="ingame-Highlight">Heavy Attack - Thunderoar: Spinslash</span> is available if Augusta remains on the ground for a certain period after this skill is interrupted.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Prowess</span></span><br>Augusta can hold up to 100 points of Prowess.<br>- Prowess is obtained when <span class="ingame-Highlight">Basic Attack</span>, <span class="ingame-Highlight">Heavy Attack - Steelclash</span>, <span class="ingame-Highlight">Mid-air Attack</span>, <span class="ingame-Highlight">Mid-air Dodge Counter</span>, <span class="ingame-Highlight">Resonance Skill - Warrior's Blade</span>, <span class="ingame-Highlight">Dodge Counter</span>, or <span class="ingame-Highlight">Dodge Counter - Heavy Attack: Steelclash</span> deals damage.<br>- Prowess is fully restored when casting <span class="ingame-Highlight">Intro Skill - Stride of Goldenflare</span>.</div>`,
  attacks: [
    {
      key: "Stage1DMG",
      label: "Stage 1 DMG",
      talents: {
        "1": "28.90%",
        "2": "31.27%",
        "3": "33.64%",
        "4": "36.96%",
        "5": "39.33%",
        "6": "42.06%",
        "7": "45.85%",
        "8": "49.64%",
        "9": "53.43%",
        "10": "57.46%",
      },
      type: "Basic",
    },
    {
      key: "Stage2DMG",
      label: "Stage 2 DMG",
      talents: {
        "1": "33.70%*2",
        "2": "36.47%*2",
        "3": "39.23%*2",
        "4": "43.10%*2",
        "5": "45.86%*2",
        "6": "49.04%*2",
        "7": "53.46%*2",
        "8": "57.88%*2",
        "9": "62.31%*2",
        "10": "67.00%*2",
      },
      type: "Basic",
    },
    {
      key: "Stage3DMG",
      label: "Stage 3 DMG",
      talents: {
        "1": "33.00%*3",
        "2": "35.71%*3",
        "3": "38.42%*3",
        "4": "42.21%*3",
        "5": "44.91%*3",
        "6": "48.02%*3",
        "7": "52.35%*3",
        "8": "56.68%*3",
        "9": "61.01%*3",
        "10": "65.61%*3",
      },
      type: "Basic",
    },
    {
      key: "Stage4DMG",
      label: "Stage 4 DMG",
      talents: {
        "1": "32.51%*3",
        "2": "35.18%*3",
        "3": "37.84%*3",
        "4": "41.57%*3",
        "5": "44.24%*3",
        "6": "47.30%*3",
        "7": "51.57%*3",
        "8": "55.83%*3",
        "9": "60.10%*3",
        "10": "64.63%*3",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackSteelclashDMG",
      label: "Heavy Attack: Steelclash DMG",
      talents: {
        "1": "23.34%*3",
        "2": "25.25%*3",
        "3": "27.16%*3",
        "4": "29.84%*3",
        "5": "31.76%*3",
        "6": "33.96%*3",
        "7": "37.02%*3",
        "8": "40.08%*3",
        "9": "43.14%*3",
        "10": "46.39%*3",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackDMG",
      label: "Mid-air Attack DMG",
      talents: {
        "1": "30.00%*2",
        "2": "32.46%*2",
        "3": "34.92%*2",
        "4": "38.37%*2",
        "5": "40.83%*2",
        "6": "43.66%*2",
        "7": "47.59%*2",
        "8": "51.53%*2",
        "9": "55.47%*2",
        "10": "59.65%*2",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterDMG",
      label: "Dodge Counter DMG",
      talents: {
        "1": "33.70%*2",
        "2": "36.47%*2",
        "3": "39.23%*2",
        "4": "43.10%*2",
        "5": "45.86%*2",
        "6": "49.04%*2",
        "7": "53.46%*2",
        "8": "57.88%*2",
        "9": "62.31%*2",
        "10": "67.00%*2",
      },
      type: "Basic",
    },
    {
      key: "MidairDodgeCounterDMG",
      label: "Mid-air Dodge Counter DMG",
      talents: {
        "1": "30.00%*2",
        "2": "32.46%*2",
        "3": "34.92%*2",
        "4": "38.37%*2",
        "5": "40.83%*2",
        "6": "43.66%*2",
        "7": "47.59%*2",
        "8": "51.53%*2",
        "9": "55.47%*2",
        "10": "59.65%*2",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackThunderoarBackstepDMG",
      label: "Heavy Attack - Thunderoar: Backstep DMG",
      talents: {
        "1": "27.00%",
        "2": "29.22%",
        "3": "31.43%",
        "4": "34.53%",
        "5": "36.75%",
        "6": "39.29%",
        "7": "42.84%",
        "8": "46.38%",
        "9": "49.92%",
        "10": "53.68%",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackThunderoarSpinslashDMG",
      label: "Heavy Attack - Thunderoar: Spinslash DMG",
      talents: {
        "1": "71.28%*3",
        "2": "77.13%*3",
        "3": "82.97%*3",
        "4": "91.16%*3",
        "5": "97.00%*3",
        "6": "103.72%*3",
        "7": "113.08%*3",
        "8": "122.43%*3",
        "9": "131.78%*3",
        "10": "141.72%*3",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackThunderoarUppercutDMG",
      label: "Heavy Attack - Thunderoar: Uppercut DMG",
      talents: {
        "1": "90.00%*2",
        "2": "97.38%*2",
        "3": "104.76%*2",
        "4": "115.10%*2",
        "5": "122.48%*2",
        "6": "130.96%*2",
        "7": "142.77%*2",
        "8": "154.58%*2",
        "9": "166.39%*2",
        "10": "178.93%*2",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterHeavyAttackSteelclashDMG",
      label: "Dodge Counter - Heavy Attack: Steelclash DMG",
      talents: {
        "1": "23.34%*3",
        "2": "25.25%*3",
        "3": "27.16%*3",
        "4": "29.84%*3",
        "5": "31.76%*3",
        "6": "33.96%*3",
        "7": "37.02%*3",
        "8": "40.08%*3",
        "9": "43.14%*3",
        "10": "46.39%*3",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterThunderoarBackstepDMG",
      label: "Dodge Counter - Thunderoar: Backstep DMG",
      talents: {
        "1": "27.00%",
        "2": "29.22%",
        "3": "31.43%",
        "4": "34.53%",
        "5": "36.75%",
        "6": "39.29%",
        "7": "42.84%",
        "8": "46.38%",
        "9": "49.92%",
        "10": "53.68%",
      },
      type: "Basic",
    }
  ],
};
