export const forteCircuitAttacks = {
  name: "Forte Circuit: Call Me By the Sun",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Skill - Undying Sunlight: Strike</span></span><br>When <a onclick="showTermExplan(130603)" class="ingame-term-desc">Ascendancy</a> is full, <span class="ingame-Highlight">Resonance Skill - Warrior's Blade</span> is replaced with <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Strike</span>, dealing <span class="ingame-Thunder">Electro DMG</span>.<br>- <span class="ingame-Highlight">Press Normal Attack or Resonance Skill</span> during the action to cast <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Leap</span>.<br>- <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Strike</span> can be re-cast shortly after being interrupted.<br>- <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Leap</span> can be cast some time again after being interrupted.<br>- Can be cast mid-air.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Skill - Undying Sunlight: Leap</span></span><br>Deal <span class="ingame-Thunder">Electro DMG</span>.<br>- <span class="ingame-Highlight">Press Normal Attack or Resonance Skill</span> during the action to cast <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Plunge</span>.<br>- <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Leap</span> can be re-cast shortly after being interrupted.<br>- <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Plunge</span> can be cast some time again after being interrupted.<br>- Can only be cast mid-air.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Skill - Undying Sunlight: Plunge</span></span><br>Consume all <a onclick="showTermExplan(130603)" class="ingame-term-desc">Ascendancy</a> to cast this skill, dealing <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG.<br>- Casting this skill grants 1 stack of <a onclick="showTermExplan(130604)" class="ingame-term-desc">Majesty</a>.<br>- Can only be cast mid-air.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter - Undying Sunlight: Strike</span></span><br>When <a onclick="showTermExplan(130603)" class="ingame-term-desc">Ascendancy</a> is full, <span class="ingame-Highlight">press Resonance Skill</span> after a successful ground Dodge or <span class="ingame-Highlight">press Normal Attack or Resonance Skill</span> after successful Mid-air Dodge to cast <span class="ingame-Highlight">Dodge Counter - Undying Sunlight: Strike</span>, dealing <span class="ingame-Thunder">Electro DMG</span>, considered as Resonance Skill DMG.<br>- <span class="ingame-Highlight">Press Normal Attack or Resonance Skill</span> during the action to cast <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Leap</span>.<br>- <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Leap</span> can be cast again some time after being interrupted.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Ascendancy</span></span><br>Augusta can hold up to 100 points of Ascendancy.<br>- Ascendancy is obtained when <span class="ingame-Highlight">Normal Attacks</span> deal damage.<br>- Casting <span class="ingame-Highlight">Intro Skill - Stride of Goldenflare</span> restores 20% Ascendancy.<br>- Casting <span class="ingame-Highlight">Resonance Skill - Warrior's Blade</span> restores 10% Ascendancy.<br>- Casting <span class="ingame-Highlight">Resonance Liberation - Sword of Eternal Oath</span> restores 40% Ascendancy.</div>`,
  attacks: [
    {
      key: "ResonanceSkillUndyingSunlightStrikeDMG",
      label: "Resonance Skill - Undying Sunlight: Strike DMG",
      talents: {
        "1": "70.00%*2",
        "2": "75.74%*2",
        "3": "81.48%*2",
        "4": "89.52%*2",
        "5": "95.26%*2",
        "6": "101.86%*2",
        "7": "111.05%*2",
        "8": "120.23%*2",
        "9": "129.41%*2",
        "10": "139.17%*2",
      },
      type: "Skill",
    },
    {
      key: "ResonanceSkillUndyingSunlightLeapDMG",
      label: "Resonance Skill - Undying Sunlight: Leap DMG",
      talents: {
        "1": "112.00% + 14.00%*2",
        "2": "121.19% + 15.15%*2",
        "3": "130.37% + 16.30%*2",
        "4": "143.23% + 17.91%*2",
        "5": "152.41% + 19.06%*2",
        "6": "162.98% + 20.38%*2",
        "7": "177.67% + 22.21%*2",
        "8": "192.36% + 24.05%*2",
        "9": "207.06% + 25.89%*2",
        "10": "222.67% + 27.84%*2",
      },
      type: "Skill",
    },
    {
      key: "ResonanceSkillUndyingSunlightPlungeDMG",
      label: "Resonance Skill - Undying Sunlight: Plunge DMG",
      talents: {
        "1": "43.55% + 391.95%",
        "2": "47.13% + 424.09%",
        "3": "50.70% + 456.23%",
        "4": "55.70% + 501.23%",
        "5": "59.27% + 533.37%",
        "6": "63.37% + 570.33%",
        "7": "69.09% + 621.76%",
        "8": "74.80% + 673.18%",
        "9": "80.52% + 724.60%",
        "10": "86.59% + 779.24%",
      },
      type: "Heavy",
    },
    {
      key: "MidairDodgeCounterUndyingSunlightStrikeDMG",
      label: "Mid-air Dodge Counter - Undying Sunlight: Strike DMG",
      talents: {
        "1": "70.00%*2",
        "2": "75.74%*2",
        "3": "81.48%*2",
        "4": "89.52%*2",
        "5": "95.26%*2",
        "6": "101.86%*2",
        "7": "111.05%*2",
        "8": "120.23%*2",
        "9": "129.41%*2",
        "10": "139.17%*2",
      },
      type: "Skill",
    },
    {
      key: "RulersRealm",
      label: "Rulers Realm",
      talents: {
        "1": "650 + 5%",
        "2": "650 + 5%",
        "3": "650 + 5%",
        "4": "650 + 5%",
        "5": "650 + 5%",
        "6": "650 + 5%",
        "7": "650 + 5%",
        "8": "650 + 5%",
        "9": "650 + 5%",
        "10": "650 + 5%",
      },
      type: "Shield",
      attribute: "hp",
      requiresResonanceChain: "RulersRealm",
    },
  ],
};
