export const skillAttacks = {
  name: "Resonance Skill: Shewolf's Hunt",
  description: `<div class="skilldescription">Lupa throws her Wildfire Banner at the target, dealing <span class="Fire">Fusion DMG</span> and restoring 15 points of Wolflame. <span class="Highlight">Mark</span> the target for 8s. After performing Resonance Skill <span class="Highlight">Shewolf's Hunt</span>, Lupa can perform <span class="Highlight">Feral Fang</span>.<br>Can be performed in mid-air close to the ground.<br>- Hold Resonance Skill to leap into the air, then follow up with <span class="Highlight">Basic Attack</span> to cast <span class="Highlight">Mid-air Attack Stage 1</span>.<br><span class="Title">Resonance Skill - Feral Fang</span><br>Lupa presses on the target relentlessly, dealing <span class="Fire">Fusion DMG</span> and restoring 15 points of Wolflame. The DMG Multiplier to <span class="Highlight">marked</span> targets is increased by 50%. If Resonance Skill - Feral Fang is not performed or Lupa is switched out, it enters cooldown.<br>Can be performed in mid-air close to the ground.</div>`,
  attacks: [
    {
      key: "ShewolfsHuntDMG",
      label: "Shewolf's Hunt DMG",
      talents: {
        "1": "70.81%",
        "2": "76.62%",
        "3": "82.42%",
        "4": "90.55%",
        "5": "96.36%",
        "6": "103.03%",
        "7": "112.32%",
        "8": "121.61%",
        "9": "130.90%",
        "10": "140.77%",
      },
      type: "Skill",
    },
    {
      key: "FeralFangDMG",
      label: "Feral Fang DMG",
      talents: {
        "1": "157.74%",
        "2": "170.68%",
        "3": "183.61%",
        "4": "201.72%",
        "5": "214.66%",
        "6": "229.53%",
        "7": "250.23%",
        "8": "270.92%",
        "9": "291.62%",
        "10": "313.61%",
      },
      type: "Skill",
    },
  ],
};
