export const liberationAttacks = {
  name: "Resonance Liberation: Ultimate Tactics",
  description: `<span class="Title">Resonance Liberation</span></span><br><br>Launch the <span style="color:#ffd12f;" class="font-bold">Thundershock Quietus</span>, dealing <span style="color:#ebb0ff;">Electro DMG</span>.`,
  attacks: [
    {
      key: "ThrumOfAllSoundsAeroDMG",
      label: "Thrum of All Sounds: Aero DMG",
      talents: {
        "1": "600.00%",
        "2": "649.20%",
        "3": "698.40%",
        "4": "767.28%",
        "5": "816.48%",
        "6": "873.06%",
        "7": "951.78%",
        "8": "1030.50%",
        "9": "1109.22%",
        "10": "1192.86%",
      },
      type: "Liberation",
    },
    {
      key: "ThrumOfAllSoundsSpectroStage1DMG",
      label: "Thrum of All Sounds: Spectro Stage 1 DMG",
      talents: {
        "1": "25",
        "2": "25",
        "3": "25",
        "4": "25",
        "5": "25",
        "6": "25",
        "7": "25",
        "8": "25",
        "9": "25",
        "10": "25",
      },
      type: "Liberation",
    },
    {
      key: "ThrumOfAllSoundsSpectroStage2DMG",
      label: "Thrum of All Sounds: Spectro Stage 2 DMG",
      talents: {
        "1": "125",
        "2": "125",
        "3": "125",
        "4": "125",
        "5": "125",
        "6": "125",
        "7": "125",
        "8": "125",
        "9": "125",
        "10": "125",
      },
      type: "Liberation",
    },
    {
      key: "ThrumOfAllSoundsHavocStage1DMG",
      label: "Thrum of All Sounds: Havoc Stage 1 DMG",
      talents: {
        "1": "20",
        "2": "20",
        "3": "20",
        "4": "20",
        "5": "20",
        "6": "20",
        "7": "20",
        "8": "20",
        "9": "20",
        "10": "20",
      },
      type: "Liberation",
    }
  ],
};
