export const liberationAttacks = {
  name: "Resonance Liberation: Era of New Wave",
  description: `<div class="skilldescription">Deal <span class="Ice">Glacio DMG</span> to all targets in an area (considered Resonance Skill DMG) and inflict <span class="Highlight">Deconstruction</span> on targets hit, then activate <span class="Highlight">Twilight Tango</span>.<br>Can be cast in mid-air close to the ground.<br> <br><span class="Title">Deconstruction</span><br>Dealing DMG to targets inflicted with <span class="Highlight">Deconstruction</span> ignores 18% of their DEF.<br> <br><span class="Title">Twilight Tango</span><br>While in <span class="Highlight">Twilight Tango</span>, press <span class="Highlight">Normal Attack</span> or <span class="Highlight">Resonance Liberation</span> to cast <span class="Highlight">Death Knell</span>.<br>Each <span class="Highlight">Death Knell</span> grants <saptag=3>1 Meta Vector.<br>With 4 Meta Vectors, press <span class="Highlight">Normal Attack</span> or <span class="Highlight">Resonance Liberation</span> to cast <span class="Highlight">Fatal Finale</span>. <br>- All Substance is removed when activating and ending <span class="Highlight">Twilight Tango</span>. Cannot perform Basic Attack <span class="Highlight">Necessary Measures</span>, Heavy Attack <span class="Highlight">Containment Tactics</span>, and Heavy Attack <span class="Highlight">Imminent Oblivion</span> while in <span class="Highlight">Twilight Tango</span>.<br> <br><span class="Title">Death Knell</span><br>Carlotta fires powerful shots with her musket and summons 4 crystal shards to attack the target, dealing <span class="Ice">Glacio DMG</span>, considered Resonance Skill DMG.<br>- Carlotta moves in the direction of the movement input with each shot of <span class="Highlight">Death Knell</span>.<br> <br><span class="Title">Fatal Finale</span><br>Deal <span class="Ice">Glacio DMG</span> to an area, considered Resonance Skill DMG.<br>- <span class="Highlight">Twilight Tango</span> ends after casting <span class="Highlight">Fatal Finale</span>.</saptag=3></div>`,
  attacks: [
    {
      key: "EraofNewWaveDMG",
      label: "Era of New Wave DMG",
      talents: {
        "1": "202.56%",
        "2": "219.17%",
        "3": "235.78%",
        "4": "259.03%",
        "5": "275.64%",
        "6": "294.74%",
        "7": "321.32%",
        "8": "347.89%",
        "9": "374.47%",
        "10": "402.71%",
      },
      type: "Skill",
    },
    {
      key: "DeathKnellDMG",
      label: "Death Knell DMG",
      talents: {
        "1": "92.37%+7.30%*4",
        "2": "99.94%+7.89%*4",
        "3": "107.52%+8.49%*4",
        "4": "118.12%+9.33%*4",
        "5": "125.70%+9.93%*4",
        "6": "134.41%+10.62%*4",
        "7": "146.52%+11.57%*4",
        "8": "158.64%+12.53%*4",
        "9": "170.76%+13.49%*4",
        "10": "183.64%+14.50%*4",
      },
      type: "Skill",
    },
    {
      key: "FatalFinaleDMG",
      label: "Fatal Finale DMG",
      talents: {
        "1": "324.09%",
        "2": "350.67%",
        "3": "377.24%",
        "4": "414.45%",
        "5": "441.03%",
        "6": "471.59%",
        "7": "514.11%",
        "8": "556.63%",
        "9": "599.15%",
        "10": "644.33%",
      },
      type: "Skill",
    },
  ],
};
