export const rotations: RotationPreset[] = [
    {
        name: `Kushy was here :3`,
        description: `Prydwen rotation (No buffs)`,
        author: `TacticalKush`,
        data: {"name":"Kushy was here :3","description":"Prydwen rotation (No buffs)","actions":[{"order":1,"key":"WintertimeAriaDMG","type":"intro","count":1,"buffs":[]},{"order":2,"key":"ArtofViolenceDMG","type":"skill","count":1,"buffs":[]},{"order":3,"key":"ChromaticSplendorDMG","type":"skill","count":1,"buffs":[]},{"order":4,"key":"MidairAttackDMG","type":"basic","count":1,"buffs":[]},{"order":5,"key":"ImminentOblivionDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":6,"key":"EraofNewWaveDMG","type":"liberation","count":1,"buffs":[]},{"order":7,"key":"DeathKnellDMG","type":"liberation","count":"4","buffs":[]},{"order":8,"key":"FatalFinaleDMG","type":"liberation","count":1,"buffs":[]},{"order":9,"key":"ArtofViolenceDMG","type":"skill","count":1,"buffs":[]},{"order":10,"key":"ChromaticSplendorDMG","type":"skill","count":1,"buffs":[]},{"order":11,"key":"ClosingRemarkDMG","type":"outro","count":1,"buffs":[]}]}
    },
    {
        name: `DPS Rotation (On-Field Role)`,
        description: `EE → Intro → EE → Forte HA → R ×6 → EE → Outro`,
        author: `Namelag`,
        data: {"name":"DPS Rotation (On-Field Role)","description":"EE → Intro → EE → Forte HA → R ×6 → EE → Outro","actions":[{"order":1,"key":"ArtofViolenceDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"ChromaticSplendorDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"WintertimeAriaDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"ArtofViolenceDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"ChromaticSplendorDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"ImminentOblivionDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"EraofNewWaveDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"DeathKnellDMG","type":"liberation","count":"4","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"FatalFinaleDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"ArtofViolenceDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"ChromaticSplendorDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"ClosingRemarkDMG","type":"outro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    },
];
export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Glacio Frosty Resolve Build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 18.4% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"SentryConstruct","echoSet":"FrostyResolve","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"AbyssalMercator","echoSet":"FrostyResolve","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"AbyssalPatricius","echoSet":"FrostyResolve","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"GalescourgeStalker","echoSet":"FrostyResolve","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"HocusPocus","echoSet":"FrostyResolve","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}}}
    },
];