export const resonanceChains = [
  {
    key: "SequenceNode1BeautyorDeathBrillianceFadesintoWithering",
    name: "Sequence Node 1: Beauty or Death, Brilliance Fades into Withering",
    details: `<span class="skilldescription">When Carlotta casts the Intro Skill "Winter's Lament," she restores 3 units of 【Amorphous Prism】 and increases her Glacio damage bonus by 30% for 15 seconds. When casting the Resonance Skill "Brilliant Will" on a target in the Chroma state, and hitting it, she additionally restores 30 points of 【Spiritual Extract】.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.2,
      },
      {
        modifier: "ResonanceSkillDMGBonus",
        modifierValue: 0.1,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode2SilenceandDeathDecayBecomesRebirth",
    name: "Sequence Node 2: Silence and Death, Decay Becomes Rebirth",
    details: `<span class="skilldescription">When Carlotta attacks a target with the Dissociation effect, the critical hit chance of that damage increases by 15%, and critical hit damage is increased by 20%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "Glacio",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode3StepForwardEleganceinProgression",
    name: "Sequence Node 3: Step Forward, Elegance in Progression",
    details: `<span class="skilldescription">After casting the Outro Skill "Final Address," Carlotta performs an additional attack, dealing 779.67% of her Attack as Glacio damage. The damage multiplier for the Heavy Attack "End of the Road" is increased by 80%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "EnableAttack",
        modifierValue: ["SequenceNode5SevenStarsShineSteppeduponHigh"],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode4WithOldRainaHymnofBitterWine",
    name: "Sequence Node 4: With Old Rain, a Hymn of Bitter Wine",
    details: `<span class="skilldescription">When Carlotta casts Heavy Attack, Heavy Attack Restrictive Strategy, or Heavy Attack "End of the Road," all nearby allies’ Basic Attack damage is increased by 25% for 30 seconds.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifySpecificTalents: [
          "FeralGyrateStage1DMG",
          "FeralGyrateStage2DMG",
          "StormyKicksDMG",
          "TailStrikeDMG",
        ],
        modifierValue: 1,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode5SalutingtheNightPastTodayandThatMoment",
    name: "Sequence Node 5: Saluting the Night Past, Today, and That Moment",
    details: `<span class="skilldescription">When Carlotta casts the Resonance Skill "Aesthetic Violence," her attack is increased by 10% for 20 seconds.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifySpecificTalents: [
          "FeralGyrateStage1DMG",
          "FeralGyrateStage2DMG",
          "StormyKicksDMG",
          "TailStrikeDMG",
        ],
        modifierValue: 1,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SequenceNode6IRemaintheSameAttheEndoftheCurtain",
    name: "Sequence Node 6: I Remain the Same, At the End of the Curtain",
    details: `<span class="skilldescription">The damage multiplier of "Funeral" in the Death Omen skill is increased by 109%, and each bullet generated by the Death Omen "Rest" increases by 1. When the Resonance Liberation "Funeral" hits a target, it applies the Iridescent effect, which prevents any actions from being performed during its duration. The effect is removed if damage is taken or after 1 second.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifySpecificTalents: [
          "FeralGyrateStage1DMG",
          "FeralGyrateStage2DMG",
          "StormyKicksDMG",
          "TailStrikeDMG",
        ],
        modifierValue: 1,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
