export const basicAttacks = {
  name: "Normal Attack: Snapshot",
  description: `<div><span style="color:#a89969"><strong>Basic Attack</strong></span><br>Perform up to 3 consecutive attacks, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>While casting <span style="color:#f7ca2f"><strong>Basic Attack Stage 3</strong></span>, hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to deploy <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>. A cursor will move around the <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>. <br>- Releasing the <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> button when the cursor falls outside of <span style="color:#f7ca2f"><strong>Perfect Focus</strong></span> will trigger <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Unremarkable</strong></span>, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and restoring <span style="color:#f7ca2f"><strong><span class="Highlight">Trace</span></strong></span>.<br>- Releasing the <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> button when the cursor falls within <span style="color:#f7ca2f"><strong>Perfect Focus</strong></span> will trigger <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Commendable</strong></span>, dealing increased <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and restoring additional <span style="color:#f7ca2f"><strong><span class="Highlight">Trace</span></strong></span>.<br>Pressing <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span> will trigger <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Unremarkable</strong></span> instead of deploying <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>.<br>When <span style="color:#f7ca2f"><strong>Focus Ring</strong></span> is deployed, the <span style="color:#f7ca2f"><strong>Perfect Focus</strong></span> zone continues to fill the ring. Once <span style="color:#f7ca2f"><strong>Focus Ring</strong></span> is completely filled, it automatically collapses and triggers <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Commendable</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 1, 2, and 3</strong></span> in sequence, and deploy <span style="color:#f7ca2f"><strong>Focus Ring</strong></span> during <span style="color:#f7ca2f"><strong>Basic Attack Stage 3</strong></span>.<br><br><span style="color:#a89969"><strong>Mid-air Attack</strong></span><br>Consume STA to perform Plunging Attack, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>. Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter</strong></span><br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after a successful Dodge to attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>. Shortly after performing this attack, press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to perform <span style="color:#f7ca2f"><strong>Basic Attack Stage 3</strong></span>.</div>`,
  attacks: [
    {
      key: "BasicAttackStage1DMG",
      label: "Basic Attack Stage 1 DMG",
      talents: {
        "1": "29.82%",
        "2": "29.82%",
        "3": "34.72%",
        "4": "38.14%",
        "5": "40.58%",
        "6": "43.40%",
        "7": "47.31%",
        "8": "51.22%",
        "9": "55.13%",
        "10": "59.29%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage2DMG",
      label: "Basic Attack Stage 2 DMG",
      talents: {
        "1": "13.53%+20.29%",
        "2": "13.53%+20.29%",
        "3": "15.75%+23.62%",
        "4": "17.30%+25.95%",
        "5": "18.41%+27.61%",
        "6": "19.68%+29.52%",
        "7": "21.46%+32.18%",
        "8": "23.23%+34.85%",
        "9": "25.01%+37.51%",
        "10": "26.89%+40.34%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage3UnremarkableDMG",
      label: "Basic Attack Stage 3 - Unremarkable DMG",
      talents: {
        "1": "80.25%",
        "2": "80.25%",
        "3": "93.41%",
        "4": "102.63%",
        "5": "109.21%",
        "6": "116.77%",
        "7": "127.30%",
        "8": "137.83%",
        "9": "148.36%",
        "10": "159.55%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage3CommendableDMG",
      label: "Basic Attack Stage 3 - Commendable DMG",
      talents: {
        "1": "118.34%",
        "2": "118.34%",
        "3": "137.75%",
        "4": "151.33%",
        "5": "161.04%",
        "6": "172.19%",
        "7": "187.72%",
        "8": "203.25%",
        "9": "218.77%",
        "10": "235.27%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackDMG",
      label: "Mid-air Attack DMG",
      talents: {
        "1": "43.40%",
        "2": "43.40%",
        "3": "50.52%",
        "4": "55.50%",
        "5": "59.06%",
        "6": "63.16%",
        "7": "68.85%",
        "8": "74.54%",
        "9": "80.24%",
        "10": "86.29%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterDMG",
      label: "Dodge Counter DMG",
      talents: {
        "1": "34.12%+41.70%",
        "2": "34.12%+41.70%",
        "3": "39.71%+48.54%",
        "4": "43.63%+53.33%",
        "5": "46.43%+56.74%",
        "6": "49.65%+60.68%",
        "7": "54.12%+66.15%",
        "8": "58.60%+71.62%",
        "9": "63.07%+77.09%",
        "10": "67.83%+82.90%",
      },
      type: "Basic",
    },
  ],
};
