export const buffs = [
  {
    key: "ClearAsDayGlacioChafe",
    name: "Clear As Day",
    details: `<div>When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, the DMG dealt is considered Basic Attack DMG. Casting this skill grants Lucilla 30% Basic Attack DMG Bonus for 10s.</div>`,
    hasStacks: false,
    stance: "Glacio Chafe",
    modifiers: [
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.3,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "ClearAsDayEcho",
    name: "Clear As Day",
    details: `<div>When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, the DMG dealt is considered Echo Skill DMG. Casting this skill grants Lucilla 30% Echo Skill DMG Bonus for 10s.</div>`,
    hasStacks: false,
    stance: "Echo",
    modifiers: [
      {
        modifier: "EchoDMGBonus",
        modifierValue: 0.3,
      },
      {
        modifier: "talentTypeOverride",
        modifySpecificTalents: ["ClearAsDayDMG"],
        modifierValue: "Echo",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "LettingItGoGlacioChafe",
    name: "Letting It Go",
    details: `<div>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span> to targets within the range. When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>/<span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, DMG dealt is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>/<span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>.<br>Lucilla is immune to interruption and damage during <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, and Resonator switching is disabled while casting.<br>While casting <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, Lucilla additionally restores 20 points of Concerto Energy.</div>`,
    hasStacks: false,
    stance: "Glacio Chafe",
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "LettingItGoEcho",
    name: "Letting It Go",
    details: `<div>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span> to targets within the range. When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>/<span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, DMG dealt is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>/<span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>.<br>Lucilla is immune to interruption and damage during <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, and Resonator switching is disabled while casting.<br>While casting <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, Lucilla additionally restores 20 points of Concerto Energy.</div>`,
    hasStacks: false,
    stance: "Echo",
    modifiers: [
      {
        modifier: "talentTypeOverride",
        modifySpecificTalents: ["LettingItGoDMG"],
        modifierValue: "Echo",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "OblivionGlacioChafe",
    name: "Oblivion",
    details: `<div><span style="color:#a89969"><strong>Oblivion</strong></span><br>During <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>, Lucilla consumes 1 <span style="color:#f7ca2f"><strong><a href="#WwLink110902" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110902">Photo</a></strong></span> intermittently to perform <span style="color:#f7ca2f"><strong>Oblivion</strong></span>, dealing 1 instance of <span style="color:#41aefb"><strong>Glacio DMG</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, this instance of DMG is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>. The skill inflicts <saptag=b>1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on the target.</div>`,
    hasStacks: false,
    stance: "Glacio Chafe",
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "OblivionEcho",
    name: "Oblivion",
    details: `<div><span style="color:#a89969"><strong>Oblivion</strong></span><br>During <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>, Lucilla consumes 1 <span style="color:#f7ca2f"><strong><a href="#WwLink110902" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110902">Photo</a></strong></span> intermittently to perform <span style="color:#f7ca2f"><strong>Oblivion</strong></span>, dealing 1 instance of <span style="color:#41aefb"><strong>Glacio DMG</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, this instance of DMG is considered <span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>. Each cast of <span style="color:#f7ca2f"><strong>Oblivion</strong></span> is considered as casting a different Echo Skill.</div>`,
    hasStacks: false,
    stance: "Echo",
    modifiers: [
      {
        modifier: "talentTypeOverride",
        modifySpecificTalents: ["OblivionDMG"],
        modifierValue: "Echo",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "Zoom",
    name: "Zoom",
    details: `<div>Each stack of <span style="color:#f7ca2f"><strong>Zoom</strong></span> increases the Crit. DMG of the active Resonator's Echo Skill by 10%.</div>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "CritDMG:Echo",
        modifierValue: .1,
      },
    ],
    minStacks: 0,
    maxStacks: 4,
    alwaysEnabled: false,
  },
  {
    key: "MontageGlacioChafe",
    name: "Montage",
    details: `<div>When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> DMG against targets within a certain range around the active Resonator is Amplified by 60% for 30s.
This effect ends when Lucilla switches Resonance Modes.</div>`,
    hasStacks: false,
    stance: "Glacio Chafe",
    modifiers: [
      {
        modifier: "DMGDeepen:GlacioChafe",
        modifierValue: 0.6,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillSlowMotionGlacioChafe`,
    name: `Inherent Skill: Slow Motion`,
    details: `<div>When <span style="color:#f7ca2f"><strong>Focus Ring</strong></span> is deployed, Lucilla slows targets within her shot.<br>While casting <span style="color:#f7ca2f"><strong>Resonance Skill - Spotlight</strong></span>, Lucilla grants the following enhancements based on her <span style="color:#f7ca2f"><strong>Resonance Mode</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, Glacio RES of targets within a certain range around the active Resonator is reduced by 8% for 30s. If an enemy falls to <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> DMG during this time, it counts as caused by the nearest active Resonator.<br>These enhancements end when Lucilla switches the Resonance Mode.</div>`,
    hasStacks: false,
    stance: "Glacio Chafe",
    modifiers: [
      {
        modifier: "ResistShred:Glacio",
        modifierValue: 0.08,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillSlowMotionEcho`,
    name: `Inherent Skill: Slow Motion`,
    details: `<div>When <span style="color:#f7ca2f"><strong>Focus Ring</strong></span> is deployed, Lucilla slows targets within her shot.<br>While casting <span style="color:#f7ca2f"><strong>Resonance Skill - Spotlight</strong></span>, Lucilla grants the following enhancements based on her <span style="color:#f7ca2f"><strong>Resonance Mode</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, Resonators in the team gain 25% Echo Skill DMG Bonus for 30s.<br>These enhancements end when Lucilla switches the Resonance Mode.</div>`,
    hasStacks: false,
    stance: "Echo",
    modifiers: [
      {
        modifier: "EchoDMGBonus",
        modifierValue: 0.25,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillRemembrance`,
    name: `Inherent Skill: Remembrance`,
    details: `<div><span style="color:#f7ca2f"><strong><a href="#WwLink110903" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110903">Film Roll</a></strong></span> can now be stacked up to 10 stacks, and <span style="color:#f7ca2f"><strong><a href="#WwLink110904" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110904">Zoom</a></strong></span> up to 4 stacks.<br>Each time Lucilla consumes <span style="color:#f7ca2f"><strong><a href="#WwLink110902" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110902">Photo</a></strong></span> when in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>/<span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, she gains 2 stacks of <span style="color:#f7ca2f"><strong><a href="#WwLink110903" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110903">Film Roll</a></strong></span>/1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink110904" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110904">Zoom</a></strong></span>.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "Spectro",
        modifierValue: 0.25,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate1",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate2",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate3",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate4",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK1",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK2",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK3",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK4",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
