export const forteCircuitAttacks = {
  name: "Forte Circuit: Memory Palace",
  description: `<div class="mt-3 text-sm leading-relaxed text-slate-200"><span style="color:#a89969"><strong>Déjà Vu</strong></span><br>While casting <span style="color:#f7ca2f"><strong>Resonance Liberation - Clear As Day</strong></span>, Lucilla grants the following enhancements based on her <span style="color:#f7ca2f"><strong>Resonance Mode</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, gain 4 stacks of <span style="color:#f7ca2f"><strong><a href="#WwLink110903" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110903">Film Roll</a></strong></span> for 30s, stacking up 4 times. All stacks are removed when the duration ends.<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, gain 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink110904" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110904">Zoom</a></strong></span> for 30s, stacking up 1 time. All stacks are removed when the duration ends.<br>The above effects end early when Lucilla switches Resonance Mode.<br><br><span style="color:#a89969"><strong>Film Roll</strong></span><br>When an active Resonator in the team other than Lucilla inflicts <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> onto the target, Lucilla consumes 1 stack of <span style="color:#f7ca2f"><strong>Film Roll</strong></span> to inflict <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> 2 time on nearby targets. This effect can be triggered once every 0.5s.<br><br><span style="color:#a89969"><strong>Zoom</strong></span><br>Each stack of <span style="color:#f7ca2f"><strong>Zoom</strong></span> increases the Crit. DMG of the active Resonator's Echo Skill by 10%.<br><br><span style="color:#a89969"><strong>Oblivion</strong></span><br>During <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>, Lucilla consumes 1 <span style="color:#f7ca2f"><strong><a href="#WwLink110902" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110902">Photo</a></strong></span> intermittently to perform <span style="color:#f7ca2f"><strong>Oblivion</strong></span>, dealing 1 instance of <span style="color:#41aefb"><strong>Glacio DMG</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, this instance of DMG is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>. The skill inflicts <saptag=b>1 {Cus:Sap,S=stack P=stacks SapTag=B} of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on the target.<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, this instance of DMG is considered <span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>. Each cast of <span style="color:#f7ca2f"><strong>Oblivion</strong></span> is considered as casting a different Echo Skill.<br><br><span style="color:#a89969"><strong>Quick Glance</strong></span><br>Press Aim to enter the camera mode. During this mode, Reverberations, environmental collectibles, and special collectibles within a certain range of Lucilla's shot will be marked. Press the shutter button to capture the moment, and the marked items will be gathered.<br><br><span style="color:#a89969"><strong>Trace</strong></span><br>Lucilla can hold up to 150 points of <span style="color:#f7ca2f"><strong>Trace</strong></span>.<br>Restore <saptag=c>100 {Cus:Sap,S=point P=points SapTag=C} of <span style="color:#f7ca2f"><strong>Trace</strong></span> while casting <span style="color:#f7ca2f"><strong>Intro Skill - Clip It</strong></span>.<br>Restore <saptag=d>50 {Cus:Sap,S=point P=points SapTag=D} of <span style="color:#f7ca2f"><strong>Trace</strong></span> while casting <span style="color:#f7ca2f"><strong>Resonance Skill - Spotlight</strong></span>.<br>Restore <saptag=d>50 {Cus:Sap,S=point P=points SapTag=D} of <span style="color:#f7ca2f"><strong>Trace</strong></span> while casting <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Commendable</strong></span>.<br>Restore <saptag=e>25 {Cus:Sap,S=point P=points SapTag=E} of <span style="color:#f7ca2f"><strong>Trace</strong></span> while casting <span style="color:#f7ca2f"><strong>Resonance Skill - Compensate</strong></span> or <span style="color:#f7ca2f"><strong>Basic Attack Stage 3 - Unremarkable</strong></span>.<br><br><span style="color:#a89969"><strong>Photos</strong></span><br>Lucilla can hold up to 3 <span style="color:#f7ca2f"><strong>Photos</strong></span>.<br>Every <saptag=f>50 {Cus:Sap,S=point P=points SapTag=F} of <span style="color:#f7ca2f"><strong><a href="#WwLink110901" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110901">Trace</a></strong></span> restored generates 1 <span style="color:#f7ca2f"><strong>Photo</strong></span>.</saptag=f></saptag=e></saptag=d></saptag=d></saptag=c></saptag=b></div>`,
  attacks: [
    {
      key: "BasicAttackIridescentSplashDMG",
      label: "Basic Attack - Iridescent Splash DMG",
      type: "Basic",
      talents: {
        "1": "153.00%",
        "2": "165.55%",
        "3": "178.10%",
        "4": "195.66%",
        "5": "208.21%",
        "6": "222.64%",
        "7": "242.71%",
        "8": "262.78%",
        "9": "282.86%",
        "10": "304.18%",
      },
    },
    {
      key: "BasicAttackVisualImpactDMG",
      label: "Basic Attack - Visual Impact DMG",
      type: "Basic",
      talents: {
        "1": "612.00%",
        "2": "662.19%",
        "3": "712.37%",
        "4": "782.63%",
        "5": "832.81%",
        "6": "890.53%",
        "7": "970.82%",
        "8": "1051.11%",
        "9": "1131.41%",
        "10": "1216.72%",
      },
    },
    {
      key: "BasicAttackPolychromeLeap1",
      label: "Basic Attack - Polychrome Leap 1",
      type: "Basic",
      talents: {
        "1": "17.00%*3",
        "2": "18.40%*3",
        "3": "19.79%*3",
        "4": "21.74%*3",
        "5": "23.14%*3",
        "6": "24.74%*3",
        "7": "26.97%*3",
        "8": "29.20%*3",
        "9": "31.43%*3",
        "10": "33.80%*3",
      },
    },
    {
      key: "BasicAttackPolychromeLeap2",
      label: "Basic Attack - Polychrome Leap 2",
      type: "Basic",
      talents: {
        "1": "8.50%*6",
        "2": "9.20%*6",
        "3": "9.90%*6",
        "4": "10.87%*6",
        "5": "11.57%*6",
        "6": "12.37%*6",
        "7": "13.49%*6",
        "8": "14.60%*6",
        "9": "15.72%*6",
        "10": "16.90%*6",
      },
    },
    {
      key: "BasicAttackPolychromeLeap3",
      label: "Basic Attack - Polychrome Leap 3",
      type: "Basic",
      talents: {
        "1": "6.59%*8",
        "2": "7.13%*8",
        "3": "7.67%*8",
        "4": "8.43%*8",
        "5": "8.97%*8",
        "6": "9.59%*8",
        "7": "10.45%*8",
        "8": "11.32%*8",
        "9": "12.18%*8",
        "10": "13.10%*8",
      },
    },
    {
      key: "TuneRuptureResponseSpectralAnalysisDMG",
      label: "Tune Rupture Response - Spectral Analysis DMG",
      type: "TuneBreak",
      talents: {
        "1": "946.00%",
        "2": "1023.58%",
        "3": "1101.15%",
        "4": "1209.75%",
        "5": "1287.32%",
        "6": "1376.53%",
        "7": "1500.64%",
        "8": "1624.76%",
        "9": "1748.88%",
        "10": "1880.75%",
      },
    },
  ],
};
