export const liberationAttacks = {
  name: "Resonance Liberation: Clear As Day",
  description: `<div>Lucilla's holds up to 0 Resonance Energy. <span style="color:#f7ca2f"><strong>Clear As Day</strong></span> consumes no Resonance Energy.<br><span style="color:#f7ca2f"><strong>Clear As Day</strong></span> unlocks when Lucilla holds all 3 <span style="color:#f7ca2f"><strong><span class="Highlight">Photos</span></strong></span>.<br><br><span style="color:#a89969"><strong>Clear As Day</strong></span><br>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and enter <span style="color:#f7ca2f"><strong>Reminiscence</strong></span>:<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>, the DMG dealt is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>. Casting this skill grants Lucilla 30% Basic Attack DMG Bonus for 10s.<br>- When in <span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, the DMG dealt is considered <span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>. Casting this skill grants Lucilla 30% Echo Skill DMG Bonus for 10s.<br>When in <span style="color:#f7ca2f"><strong>Reminiscence</strong></span>, Lucilla's resistance to interruption is increased, and she cannot cast <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> and <span style="color:#f7ca2f"><strong>Resonance Liberation</strong></span>. Her <span style="color:#f7ca2f"><strong>Basic Attack</strong></span>, <span style="color:#f7ca2f"><strong>Dodge Counter</strong></span>, <span style="color:#f7ca2f"><strong>Mid-air Attack</strong></span>, and <span style="color:#f7ca2f"><strong>Intro Skill - Clip It</strong></span> are replaced with <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms</strong></span>, <span style="color:#f7ca2f"><strong>Dodge Counter - Reminiscence</strong></span>, <span style="color:#f7ca2f"><strong>Mid-air Attack - Reminiscence</strong></span>, and <span style="color:#f7ca2f"><strong>Intro Skill - Clip It: Hard Cut</strong></span> respectively.<br>Can be performed in mid-air close to the ground.<br><br><span style="color:#a89969"><strong>Basic Attack - Tracing Forms</strong></span><br>Perform up to 3 consecutive attacks, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to cast <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 1, 2, &amp; 3</strong></span> consecutively.<br>While casting <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>, consecutively press or hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to continuously attack the target.<br>While casting <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>, release the <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> button or finish the whole <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span> to automatically perform <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>.<br><br><span style="color:#a89969"><strong>Letting It Go</strong></span><br>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span> to targets within the range. When in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>/<span style="color:#f7ca2f"><strong>Resonance Mode - Echo</strong></span>, DMG dealt is considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>/<span style="color:#f7ca2f"><strong>Echo Skill DMG</strong></span>.<br>Lucilla is immune to interruption and damage during <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, and Resonator switching is disabled while casting.<br>While casting <span style="color:#f7ca2f"><strong>Letting It Go</strong></span>, Lucilla additionally restores 20 points of Concerto Energy.<br>Casting <span style="color:#f7ca2f"><strong>Letting It Go</strong></span> ends <span style="color:#f7ca2f"><strong><span class="Highlight">Reminiscence</span></strong></span>.<br><br><span style="color:#a89969"><strong>Mid-air Attack - Reminiscence</strong></span><br>Consume STA to perform Plunging Attack, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>. <br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter - Reminiscence</strong></span><br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after a successful Dodge to attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered <span style="color:#f7ca2f"><strong>Basic Attack DMG</strong></span>. <br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Tracing Forms Stage 3</strong></span>.</div>`,
  attacks: [
    {
      key: "ClearAsDayDMG",
      label: "Clear As Day DMG",
      talents: {
        "1": "71.80%",
        "2": "71.80%",
        "3": "83.57%",
        "4": "91.82%",
        "5": "97.70%",
        "6": "104.47%",
        "7": "113.89%",
        "8": "123.31%",
        "9": "132.73%",
        "10": "142.74%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackTracingFormsStage1DMG",
      label: "Basic Attack - Tracing Forms Stage 1 DMG",
      talents: {
        "1": "15.41%+23.12%",
        "2": "15.41%+23.12%",
        "3": "17.94%+26.91%",
        "4": "19.71%+29.56%",
        "5": "20.97%+31.46%",
        "6": "22.43%+33.64%",
        "7": "24.45%+36.67%",
        "8": "26.47%+39.70%",
        "9": "28.49%+42.73%",
        "10": "30.64%+45.95%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackTracingFormsStage2DMG",
      label: "Basic Attack - Tracing Forms Stage 2 DMG",
      talents: {
        "1": "30.06%+45.09%",
        "2": "30.06%+45.09%",
        "3": "34.99%+52.49%",
        "4": "38.45%+57.67%",
        "5": "40.91%+61.36%",
        "6": "43.75%+65.62%",
        "7": "47.69%+71.53%",
        "8": "51.63%+77.45%",
        "9": "55.58%+83.36%",
        "10": "59.77%+89.65%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackTracingFormsStage3DMG",
      label: "Basic Attack - Tracing Forms Stage 3 DMG",
      talents: {
        "1": "26.22%*8",
        "2": "26.22%*8",
        "3": "30.52%*8",
        "4": "33.53%*8",
        "5": "35.67%*8",
        "6": "38.15%*8",
        "7": "41.59%*8",
        "8": "45.02%*8",
        "9": "48.46%*8",
        "10": "52.12%*8",
      },
      type: "Basic",
    },
    {
      key: "LettingItGoDMG",
      label: "Letting It Go DMG",
      talents: {
        "1": "42.66%*3+298.60%",
        "2": "42.66%*3+298.60%",
        "3": "49.66%*3+347.57%",
        "4": "54.55%*3+381.84%",
        "5": "58.05%*3+406.33%",
        "6": "62.07%*3+434.49%",
        "7": "67.67%*3+473.66%",
        "8": "73.27%*3+512.84%",
        "9": "78.86%*3+552.01%",
        "10": "84.81%*3+593.64%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackReminiscenceDMG",
      label: "Mid-air Attack - Reminiscence DMG",
      talents: {
        "1": "55.80%",
        "2": "55.80%",
        "3": "64.96%",
        "4": "71.36%",
        "5": "75.94%",
        "6": "81.20%",
        "7": "88.52%",
        "8": "95.84%",
        "9": "103.16%",
        "10": "110.94%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterReminiscenceDMG",
      label: "Dodge Counter - Reminiscence DMG",
      talents: {
        "1": "58.12%+71.04%",
        "2": "58.12%+71.04%",
        "3": "67.65%+82.69%",
        "4": "74.33%+90.84%",
        "5": "79.09%+96.67%",
        "6": "84.57%+103.36%",
        "7": "92.20%+112.68%",
        "8": "99.82%+122.00%",
        "9": "107.45%+131.32%",
        "10": "115.55%+141.22%",
      },
      type: "Basic",
    },
  ],
};
