export const rotations: RotationPreset[] = [];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Glacio Wishes of Quiet Snowfall Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 0% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":3,"echo":"Glommoth","echoSet":"WishesofQuietSnowfall","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"FrostbiteColeoid","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Ironhoof","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"TremorWarrior","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"ShadowStepper","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"Glommoth","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Glacio Wishes of Quiet Snowfall Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 0% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":3,"echo":"Glommoth","echoSet":"WishesofQuietSnowfall","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"FrostbiteColeoid","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"WindlashColeoid","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"ShadowStepper","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF","echoSubStatsValue3":10.9,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"TremorWarrior","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"Glommoth","rank":5}}
    },
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Glacio Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 0% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Spearback","echoSet":"MoonlitClouds","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"ViridblazeSaurian","echoSet":"MoonlitClouds","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF","echoSubStatsValue3":10.9,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"SabyrBoar","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF","echoSubStatsValue3":10.9,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"ZigZag","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Glacio Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 0% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"ViridblazeSaurian","echoSet":"MoonlitClouds","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"BasicAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"GlacioDreadmane","echoSet":"MoonlitClouds","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"ZigZag","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"WhiffWhaff","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    }
];
