export const skillAttacks = {
  name: "Resonance Skill: Phantom Frame",
  description: `<div>Pull in nearby targets, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>While casting this skill, hold <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> to deploy <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>. A cursor will move around the <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>.<br>- Releasing the <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> button when the cursor falls outside of <span style="color:#f7ca2f"><strong>Perfect Focus</strong></span> will trigger <span style="color:#f7ca2f"><strong>Compensate</strong></span>, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and restoring <span style="color:#f7ca2f"><strong><a href="#WwLink110901" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110901">Trace</a></strong></span>.<br>- Releasing the <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> button when the cursor falls within <span style="color:#f7ca2f"><strong>Perfect Focus</strong></span> will trigger <span style="color:#f7ca2f"><strong>Spotlight</strong></span>, dealing increased <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and restoring additional <span style="color:#f7ca2f"><strong><a href="#WwLink110901" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110901">Trace</a></strong></span>.<br>If Lucilla casts the skill on-field without holding <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span>, she directly casts <span style="color:#f7ca2f"><strong>Compensate</strong></span> instead of deploying <span style="color:#f7ca2f"><strong>Focus Ring</strong></span>.<br><br><span style="color:#a89969"><strong>Compensate</strong></span><br>Attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span> and reducing the Cooldown of Lucilla's <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> by 8s.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Spotlight</strong></span><br>Attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>While casting <span style="color:#f7ca2f"><strong>Spotlight</strong></span>, Lucilla additionally restores 20 points of Concerto Energy, and inflicts 1 extra stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> onto the target if she is in <span style="color:#f7ca2f"><strong>Resonance Mode - Glacio Chafe</strong></span>.<br><span style="color:#f7ca2f"><strong>Spotlight</strong></span> is immune to interruptions. Switching to another Resonator while casting <span style="color:#f7ca2f"><strong>Spotlight</strong></span> ends the skill early.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.</div>`,
  attacks: [
    {
      key: "PhantomFrameDMG",
      label: "Phantom Frame DMG",
      talents: {
        "1": "6.67%*3",
        "2": "7.22%*3",
        "3": "7.76%*3",
        "4": "8.53%*3",
        "5": "9.08%*3",
        "6": "9.71%*3",
        "7": "10.58%*3",
        "8": "11.45%*3",
        "9": "12.33%*3",
        "10": "12.33%*3",
      },
      type: "Skill",
    },
    {
      key: "CompensateDMG",
      label: "Compensate DMG",
      talents: {
        "1": "125.28%",
        "2": "135.56%",
        "3": "145.83%",
        "4": "160.21%",
        "5": "170.49%",
        "6": "182.30%",
        "7": "198.74%",
        "8": "215.17%",
        "9": "231.61%",
        "10": "231.61%",
      },
      type: "Skill",
    },
    {
      key: "SpotlightDMG",
      label: "Spotlight DMG",
      talents: {
        "1": "41.42%+41.42%+138.06%+55.23%",
        "2": "44.82%+44.82%+149.39%+59.76%",
        "3": "48.22%+48.22%+160.71%+64.29%",
        "4": "52.97%+52.97%+176.56%+70.63%",
        "5": "56.37%+56.37%+187.88%+75.15%",
        "6": "60.27%+60.27%+200.90%+80.36%",
        "7": "65.71%+65.71%+219.01%+87.61%",
        "8": "71.14%+71.14%+237.12%+94.85%",
        "9": "76.57%+76.57%+255.24%+102.10%",
        "10": "76.57%+76.57%+255.24%+102.10%",
      },
      type: "Skill",
    },
  ],
};
