export const buffs = [
  {
    key: `InherentSkillHarkTheDust`,
    name: `Inherent Skill: Hark the Dust`,
    details: `<div>Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Question the Tombs</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Encroaching Yin</span> and <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Scorching Yang</span> grants<span style="color:#ffd12f;" class="font-bold">Earth Charm</span>.<br></span><br><br><span class="Title">Earth Charm</span><br>For 15, if Jingran is the active Resonator in the team, gain an unstackable Shield equal to 1.6% Max HP+700 that lasts for 5s every 0.5s when dealing damage. This Shield will not be passed on to the incoming Resonator.<br>While Jingran is in the <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> state, if he is the active Resonator in the team, he gains a unstackable Shield equal to 0.8% Max HP+350, for 5s. This effect can be triggered once every 0.5s. This Shield will not be passed on to the incoming Resonator.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "EnableAttack",
        modifierValue: ["EarthCharmShield"],
      },
      {
        modifier: "EnableAttack",
        modifierValue: ["EarthCharmYinghuoShield"],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillTraceTheVestige`,
    name: `Inherent Skill: Trace the Vestige`,
    details: `<div>Upon engaging in combat, if Jingran's <span style="color:#ffd12f;" class="font-bold">Ghost Shroud</span> is below 25 points, restore it to 25 points. This effect can be triggered once every 4s.<br>When nearby Resonators in the team other than Jingran gains a Shield, Jingran gains 2 points of <span style="color:#ffd12f;" class="font-bold">Ghost Shroud</span>. This effect can be triggered once every 0.5s.<br></span><br><br><span class="Title">Fixation</span></span><br><br>Upon engaging in combat, Jingran gains <span style="color:#ffd12f;" class="font-bold">Fixation</span>. This effect can be triggered once every 4s.<br>Casting <span style="color:#ffd12f;" class="font-bold">Outro Skill - Rising Fortune and Ebbing Sha</span> grants <span style="color:#ffd12f;" class="font-bold">Fixation</span>.<br>When nearby Resonators in the team other than Jingran gains a Shield, Jingran gains 15 points of <span style="color:#ffd12f;" class="font-bold">Ghost Shroud</span>, removing <span style="color:#ffd12f;" class="font-bold">Fixation</span>.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `NetherToLight`,
    name: `Nether to Light`,
    details: `<div><span class="Title">Nether to Light</span><br><br>- Jingran's DEF remains 0 at all times.<br>- Jingran gains bonus Healing based on Max HP: For every 1000 of Max HP, Jingran receives 6.2% bonus Healing, up to 310%.<br>- Jingran gains <span style="color:#fbcaad;">Fusion DMG Bonus</span> based on Max HP: For every 1000 of Max HP, Jingran receives 1.5% bonus <span style="color:#fbcaad;">Fusion DMG Bonus</span>, up to 75%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HealingBonus:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 0,
        modifierStep: 1000,
        modifierValue: 0.062,
        maximumValue: 3.1,
        modifierTargetAttr: "HealingBonus",
      },
      {
        modifier: "Fusion:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 0,
        modifierStep: 1000,
        modifierValue: 0.015,
        maximumValue: 0.75,
        modifierTargetAttr: "Fusion",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `YangChangesYinUnites`,
    name: `Yang Changes, Yin Unites`,
    details: `<div><span class="Title">Yang Changes, Yin Unites</span><br><br>Gain additional ATK based on Max HP: For every 1000 of Max HP, Jingran gains 36 additional ATK, up to 1800.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK_FLAT:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 0,
        modifierStep: 1000,
        modifierValue: 36,
        maximumValue: 1800,
        modifierTargetAttr: "ATK_FLAT",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `FireOfLife`,
    name: `Fire of Life`,
    details: `<div><span class="Title">Fire of Life</span><br><br>Max 100 points.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Burial of Thousand Souls</span> grants 100 points of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span>.<br>- All <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> is cleared when <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> ends.<br>While in <span style="color:#ffd12f;" class="font-bold">Yinghuo</span>, if <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> is not at 0, casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> consumes 25 points of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> and the DMG Multiplier of this <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> is increased based on Jingran's Max HP: increased for every 1000 points of Max HP over 25000, up to 25000 points of Max HP counting toward this effect.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiplyAdd:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 25000,
        modifierStep: 1000,
        maxSteps: 25,
        modifierValue: {
          "1": 0.1064,
          "2": 0.1151,
          "3": 0.1239,
          "4": 0.136,
          "5": 0.1446,
          "6": 0.1546,
          "7": 0.1685,
          "8": 0.1823,
          "9": 0.1964,
          "10": 0.211,
        },
        modifierValueTalentRef: "forte",
        maximumValue: 5.275,
        modifierTargetAttr: "talentModifierMultiplyAdd",
        modifySpecificTalents: ["HeavyAttackSoulRaidDMG"],
      },
      {
        modifier: "talentModifierMultiplyAdd:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 25000,
        modifierStep: 1000,
        maxSteps: 25,
        modifierValue: {
          "1": 0.1089,
          "2": 0.1179,
          "3": 0.1268,
          "4": 0.1394,
          "5": 0.1484,
          "6": 0.1585,
          "7": 0.1728,
          "8": 0.187,
          "9": 0.2014,
          "10": 0.2165,
        },
        modifierValueTalentRef: "forte",
        maximumValue: 5.4125,
        modifierTargetAttr: "talentModifierMultiplyAdd",
        modifySpecificTalents: ["HeavyAttackStardomeMeanderDMG"],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `FortuneInDisguise`,
    name: `Fortune in Disguise`,
    details: `<div><span class="Title">Fortune in Disguise</span><br><br>Max 50 stacks. Each stack of <span style="color:#ffd12f;" class="font-bold">Fortune in Disguise</span> grants additional <span style="color:#fbcaad;">Fusion DMG Bonus</span> based on Jingran's Max HP: For every 1000 points of Max HP, Jingran gains 0.05% additional <span style="color:#fbcaad;">Fusion DMG Bonus</span> for 15s, up to 2.5% for each stack of <span style="color:#ffd12f;" class="font-bold">Fortune in Disguise</span>.<br>Switching to another Resonator ends the effect.</div>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "Fusion:AdditionalBase",
        modifierBasedOn: "HP",
        minStatValue: 0,
        modifierStep: 1000,
        modifierValue: 0.0005,
        perStackMaximumValue: 0.025,
        maximumValue: 1.25,
        modifierTargetAttr: "Fusion",
      },
    ],
    minStacks: 0,
    maxStacks: 50,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusCritRate1`,
    name: `Stat Bonus: Crit. Rate+`,
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusCritRate2`,
    name: `Stat Bonus: Crit. Rate+`,
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusCritRate3`,
    name: `Stat Bonus: Crit. Rate+`,
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusCritRate4`,
    name: `Stat Bonus: Crit. Rate+`,
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusHP1`,
    name: `Stat Bonus: HP+`,
    details: `<div class="skilldescription">HP increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HP",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusHP2`,
    name: `Stat Bonus: HP+`,
    details: `<div class="skilldescription">HP increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HP",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusHP3`,
    name: `Stat Bonus: HP+`,
    details: `<div class="skilldescription">HP increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HP",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `StatBonusHP4`,
    name: `Stat Bonus: HP+`,
    details: `<div class="skilldescription">HP increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "HP",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  }
];
