export const forteCircuitAttacks = {
  name: "Forte Circuit: Upstream Along Santu",
  description: `<div><span class="Title">Qi Modulation</span></span><br><br>Jingran switches between the <span style="color:#ffd12f;" class="font-bold">Yin Vessel</span> and <span style="color:#ffd12f;" class="font-bold">Yang Font</span> states by casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span>. Jingran is in the <span style="color:#ffd12f;" class="font-bold">Yang Font</span> state by default.</span><br><br><span class="Title">Heavy Attack - Soul Raid</span></span><br><br>When Jingran holds 300 points of <span style="color:#ffd12f;" class="font-bold">Qi</span> while in the <span style="color:#ffd12f;" class="font-bold">Yin Vessel</span> state, <span style="color:#ffd12f;" class="font-bold">hold Normal Attack</span> to consume 300 points of <span style="color:#ffd12f;" class="font-bold">Qi</span> to cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span>, dealing <span style="color:#fbcaad;">Fusion DMG</span>.<br>After casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span>, Jingran switches to the <span style="color:#ffd12f;" class="font-bold">Yang Font</span> state.<br>Press or hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> shortly after casting this skill to cast <span style="color:#ffd12f;" class="font-bold">Basic Attack - Devil's Bane Stage 2</span>.</span><br><br><span class="Title">Heavy Attack - Stardome Meander</span></span><br><br>When Jingran holds 300 points of <span style="color:#ffd12f;" class="font-bold">Qi</span> while in the <span style="color:#ffd12f;" class="font-bold">Yang Font</span> state, <span style="color:#ffd12f;" class="font-bold">hold Normal Attack</span> to consume 300 points of <span style="color:#ffd12f;" class="font-bold">Qi</span> to cast <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span>, dealing <span style="color:#fbcaad;">Fusion DMG</span>.<br>After casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span>, Jingran switches to the <span style="color:#ffd12f;" class="font-bold">Yin Vessel</span> state.<br>Press or hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> shortly after casting this skill to cast <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drink Soul Stage 2</span>.<br><span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> can be cast in mid-air.</span><br><br><span class="Title">Qi</span></span><br><br>Max 300 points.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drink Soul Stage 3</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drink Soul Stage 4</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Devil's Bane Stage 3</span>, or <span style="color:#ffd12f;" class="font-bold">Basic Attack - Devil's Bane Stage 4</span> restores 50 points of <span style="color:#ffd12f;" class="font-bold">Qi</span>.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Nether Dive</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Light Watch</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Netherworld Traverse</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Afterlife's Guide</span>, or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Question the Tombs</span> restores 100 points of <span style="color:#ffd12f;" class="font-bold">Qi</span>.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Burial of Thousand Souls</span> or casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> with <span style="color:#ffd12f;" class="font-bold">Wayfarer's Mark</span> restores 200 points of <span style="color:#ffd12f;" class="font-bold">Qi</span>.</span><br><br><span class="Title">Fire of Life</span></span><br><br>Max 100 points.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Burial of Thousand Souls</span> grants 100 points of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span>.<br>- All <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> is cleared when <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> ends.<br>While in <span style="color:#ffd12f;" class="font-bold">Yinghuo</span>, if <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> is not at <SapTag=A>0</SapTag> {Cus:Sap,S=point P=points SapTag=A}, casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> consumes <SapTag=B>25</SapTag> {Cus:Sap,S=point P=points SapTag=B} of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span>, and the DMG Multiplier of this <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> is increased based on Jingran's Max HP: The DMG Multiplier of this <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> is increased for every <SapTag=C>1000</SapTag> {Cus:Sap,S=point P=points SapTag=C} of Jingran's Max HP over 25000. Up to 25000 points of Jingran's Max HP count towards this effect.</span><br><br><span class="Title">Nether to Light</span></span><br><br>- Jingran's DEF is fixed at 0.<br>- Jingran gains Incoming Healing Bonus based on Max HP: For every <SapTag=D>1000</SapTag> {Cus:Sap,S=point P=points SapTag=D} of Max HP, Jingran receives 6.2% Incoming Healing Bonus, up to 310%.<br>- Jingran gains Fusion DMG Bonus based on Max HP: For every <SapTag=E>1000</SapTag> {Cus:Sap,S=point P=points SapTag=E} of Max HP, Jingran receives 1.5% Fusion DMG Bonus, up to 75%.</span><br><br><span class="Title">Yang Changes, Yin Unites</span></span><br><br>Jingran gains additional ATK based on Max HP: For every <SapTag=F>1000</SapTag> {Cus:Sap,S=point P=points SapTag=F} of Max HP, Jingran gains 36 additional ATK, up to 1800.</div>`,
  icon: "https://api.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Atlas/SkillIcon/SkillIconJingran/SP_IconJingranY.webp",
  attacks: [
    {
      key: "HeavyAttackSoulRaidDMG",
      label: "Heavy Attack - Soul Raid DMG",
      talents: {
        "1": "8.25%*2+10.61%*3+69.53%",
        "2": "8.93%*2+11.48%*3+75.23%",
        "3": "9.61%*2+12.35%*3+80.93%",
        "4": "10.55%*2+13.57%*3+88.91%",
        "5": "11.23%*2+14.44%*3+94.61%",
        "6": "12.01%*2+15.44%*3+101.16%",
        "7": "13.09%*2+16.83%*3+110.29%",
        "8": "14.17%*2+18.22%*3+119.41%",
        "9": "15.25%*2+19.61%*3+128.53%",
        "10": "16.40%*2+21.09%*3+138.22%",
      },
      type: "Heavy",
    },
    {
      key: "HeavyAttackStardomeMeanderDMG",
      label: "Heavy Attack - Stardome Meander DMG",
      talents: {
        "1": "12.09%+12.09%+24.18%+72.54%",
        "2": "13.09%+13.09%+26.17%+78.49%",
        "3": "14.08%+14.08%+28.15%+84.44%",
        "4": "15.47%+15.47%+30.93%+92.77%",
        "5": "16.46%+16.46%+32.91%+98.72%",
        "6": "17.60%+17.60%+35.19%+105.56%",
        "7": "19.18%+19.18%+38.36%+115.08%",
        "8": "20.77%+20.77%+41.53%+124.59%",
        "9": "22.36%+22.36%+44.71%+134.11%",
        "10": "24.04%+24.04%+48.08%+144.22%",
      },
      type: "Heavy",
    },
    // {
    //   key: "HeavyAttackSoulRaidDMGIncreasePer1000MaxHP",
    //   label: "Heavy Attack - Soul Raid DMG Increase per 1,000 Max HP",
    //   talents: {
    //     "1": "0.75%*2+0.96%*3+6.26%",
    //     "2": "0.81%*2+1.04%*3+6.77%",
    //     "3": "0.87%*2+1.12%*3+7.29%",
    //     "4": "0.95%*2+1.23%*3+8.01%",
    //     "5": "1.02%*2+1.30%*3+8.52%",
    //     "6": "1.09%*2+1.39%*3+9.11%",
    //     "7": "1.18%*2+1.52%*3+9.93%",
    //     "8": "1.28%*2+1.64%*3+10.75%",
    //     "9": "1.38%*2+1.77%*3+11.57%",
    //     "10": "1.48%*2+1.90%*3+12.44%",
    //   },
    //   type: "Basic",
    // },
    // {
    //   key: "HeavyAttackStardomeMeanderDMGIncreasePer1000MaxHP",
    //   label: "Heavy Attack - Stardome Meander DMG Increase per 1,000 Max HP",
    //   talents: {
    //     "1": "1.09%+1.09%+2.18%+6.53%",
    //     "2": "1.18%+1.18%+2.36%+7.07%",
    //     "3": "1.27%+1.27%+2.54%+7.60%",
    //     "4": "1.40%+1.40%+2.79%+8.35%",
    //     "5": "1.49%+1.49%+2.97%+8.89%",
    //     "6": "1.59%+1.59%+3.17%+9.50%",
    //     "7": "1.73%+1.73%+3.46%+10.36%",
    //     "8": "1.87%+1.87%+3.74%+11.22%",
    //     "9": "2.02%+2.02%+4.03%+12.07%",
    //     "10": "2.17%+2.17%+4.33%+12.98%",
    //   },
    //   type: "Basic",
    // }
  ],
};
