export const liberationAttacks = {
  name: "Resonance Liberation: Burial of Thousand Souls",
  description: `<div><span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Burial of Thousand Souls</span> can be cast in mid-air.<br>Attack the target, dealing <span style="color:#fbcaad;">Fusion DMG</span>, considered Heavy Attack DMG, and granting the following effects:<br>- Reduce HP to 75% of the Max HP.<br>- Gain 200 points of <span style="color:#ffd12f;" class="font-bold">Qi</span>.<br>- Gain 3 stacks of <span style="color:#ffd12f;" class="font-bold">Wayfarer's Mark</span>.<br>- Gain 100 points of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span>.<br>- Enter the <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> state for 15s.<br><size=10></span><br><br><span class="Title">Wayfarer's Mark</span></span><br><br>Max 3 stacks.<br>Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> restores 200 points of <span style="color:#ffd12f;" class="font-bold">Qi</span> and reduces 1 stacks of <span style="color:#ffd12f;" class="font-bold">Wayfarer's Mark</span>. This effect lasts for 15s.<br><size=10></span><br><br><span class="Title">Fire of Life</span></span><br><br>While in the <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> state and <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> is not at 0, when casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span>, the DMG Multiplier of this cast of <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> increases by every 1000 points of Max HP, up to 35000. <SapTag=A>25</SapTag> {Cus:Sap,S=point P=points SapTag=A} of <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> will be consumed.<br><size=10></span><br><br><span class="Title">Yinghuo</span></span><br><br>- Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Soul Raid</span> and <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stardome Meander</span> summons <span style="color:#ffd12f;" class="font-bold">Chimei Wangliang</span> to attack the targets, dealing <span style="color:#fbcaad;">Fusion DMG</span>, considered Heavy Attack DMG.<br>- All <span style="color:#ffd12f;" class="font-bold">Fire of Life</span> will be removed as <span style="color:#ffd12f;" class="font-bold">Yinghuo</span> ends.</div>`,
  attacks: [
    {
      key: "BurialOfThousandSoulsDMG",
      label: "Burial of Thousand Souls DMG",
      talents: {
        "1": "46.86%*8",
        "2": "50.70%*8",
        "3": "54.54%*8",
        "4": "59.92%*8",
        "5": "63.76%*8",
        "6": "68.18%*8",
        "7": "74.33%*8",
        "8": "80.47%*8",
        "9": "86.62%*8",
        "10": "93.15%*8",
      },
      type: "Heavy",
    },
    {
      key: "ChimeiWangliangDMG",
      label: "Chimei Wangliang DMG",
      talents: {
        "1": "42.00%",
        "2": "45.45%",
        "3": "48.89%",
        "4": "53.71%",
        "5": "57.16%",
        "6": "61.12%",
        "7": "66.63%",
        "8": "72.14%",
        "9": "77.65%",
        "10": "83.51%",
      },
      type: "Heavy",
    },
    {
      key: "AerialEncroachingYinDMG",
      label: "Aerial Encroaching Yin DMG",
      talents: {
        "1": "0.56%*2+0.72%*3+4.68%",
        "2": "0.60%*2+0.78%*3+5.06%",
        "3": "0.65%*2+0.83%*3+5.44%",
        "4": "0.71%*2+0.92%*3+5.98%",
        "5": "0.76%*2+0.97%*3+6.36%",
        "6": "0.81%*2+1.04%*3+6.80%",
        "7": "0.88%*2+1.14%*3+7.42%",
        "8": "0.96%*2+1.23%*3+8.03%",
        "9": "1.03%*2+1.32%*3+8.64%",
        "10": "1.11%*2+1.42%*3+9.29%",
      },
      type: "Liberation",
    },
    {
      key: "AerialScorchingYangDMG",
      label: "Aerial Scorching Yang DMG",
      talents: {
        "1": "0.82%+0.82%+1.63%+4.88%",
        "2": "0.88%+0.88%+1.76%+5.28%",
        "3": "0.95%+0.95%+1.90%+5.68%",
        "4": "1.04%+1.04%+2.08%+6.24%",
        "5": "1.11%+1.11%+2.22%+6.64%",
        "6": "1.19%+1.19%+2.37%+7.10%",
        "7": "1.29%+1.29%+2.58%+7.74%",
        "8": "1.40%+1.40%+2.80%+8.38%",
        "9": "1.51%+1.51%+3.01%+9.02%",
        "10": "1.62%+1.62%+3.24%+9.70%",
      },
      type: "Liberation",
    }
  ],
};
