export const liberationAttacks = {
  name: "Resonance Liberation: Blazing Might",
  description: `<div class="skilldescription">Awaken the power of thunder and provide Forte Circuit <span class="Highlight">Lightning Infused</span> status to all characters on a nearby team for 10s, then perform a powerful blow that deals <span class="Thunder">Electro DMG</span>.<br> </div>`,
  attacks: [
    {
      key: "BlazingMightSkillDMG",
      label: "Blazing Might DMG",
      talents: {
        "1": "88.00%*2",
        "2": "95.22%*2",
        "3": "102.44%*2",
        "4": "112.54%*2",
        "5": "119.76%*2",
        "6": "128.05%*2",
        "7": "139.60%*2",
        "8": "151.14%*2",
        "9": "162.69%*2",
        "10": "174.96%*2",
      },
      type: "Liberation",
      attribute: "defense",
    },
    {
      key: "RetributiveKnucklesShield",
      label: "Retributive Knuckles Shield",
      talents: {
        "1": "200%",
        "2": "200%",
        "3": "200%",
        "4": "200%",
        "5": "200%",
        "6": "200%",
        "7": "200%",
        "8": "200%",
        "9": "200%",
        "10": "200%",
      },
      type: "Shield",
      attribute: "defense",
      requiresResonanceChain: "SequenceNode4RetributiveKnuckles",
    },
  ],
};
