export const skillAttacks = {
  name: "Resonance Skill: Leihuang Master",
  description: `<div class="skilldescription"><span class="Title">Thunder Wedge</span><br>Yuanwu summons <span class="Highlight">Thunder Wedge</span>, dealing <span class="Thunder">Electro DMG</span>, and forms a <span class="Highlight">Thunder Field</span> centered on the <span class="Highlight">Thunder Wedge</span>. <span class="Highlight">Thunder Wedge</span> lasts for 12s.<br>Forte Circuit <span class="Highlight">Rumbling Spark</span> and Resonance Liberation <span class="Highlight">Blazing Might</span> will immediately detonate Resonance Skill <span class="Highlight">Thunder Wedge</span> on the field, dealing <span class="Thunder">Electro DMG</span>, considered as Resonance Skill DMG.<br> <br><span class="Title">Thunder Field</span><br>The active character gains the effects below when in the <span class="Highlight">Thunder Field</span>: a Coordinated Attack from Resonance Skill <span class="Highlight">Thunder Wedge</span> is triggered when attacks hit a target, dealing <span class="Thunder">Electro DMG</span>. This can be triggered once every 1.2s. The effect lasts for 1.5s.</div>`,
  attacks: [
    {
      key: "LeihuangMasterSkillDMG",
      label: "Skill DMG",
      talents: {
        "1": "12.00%",
        "2": "12.99%",
        "3": "13.97%",
        "4": "15.35%",
        "5": "16.33%",
        "6": "17.47%",
        "7": "19.04%",
        "8": "20.61%",
        "9": "22.19%",
        "10": "23.86%",
      },
      type: "Skill",
      attribute: "defense",
    },
    {
      key: "ThunderWedgeCoordinatedAttackDMG",
      label: "Thunder Wedge Coordinated Attack DMG",
      talents: {
        "1": "4.00%",
        "2": "4.33%",
        "3": "4.66%",
        "4": "5.12%",
        "5": "5.45%",
        "6": "5.83%",
        "7": "6.35%",
        "8": "6.87%",
        "9": "7.40%",
        "10": "7.96%",
      },
      type: "Skill",
      attribute: "defense",
    },
    {
      key: "ThunderWedgeDetonationDMG",
      label: "Thunder Wedge Detonation Damage",
      talents: {
        "1": "30.00%",
        "2": "32.46%",
        "3": "34.92%",
        "4": "38.37%",
        "5": "40.83%",
        "6": "43.66%",
        "7": "47.59%",
        "8": "51.53%",
        "9": "55.47%",
        "10": "59.65%",
      },
      type: "Skill",
      attribute: "defense",
    },
    {
      key: "RumblingSparkDMG",
      label: "Rumbling Spark Damage",
      talents: {
        "1": "54.60%",
        "2": "59.07%",
        "3": "63.55%",
        "4": "69.82%",
        "5": "74.29%",
        "6": "79.44%",
        "7": "86.60%",
        "8": "93.76%",
        "9": "100.93%",
        "10": "108.54%",
      },
      type: "Skill",
      attribute: "defense",
    },
  ],
};
