export const rotations: RotationPreset[] = [
    {
        name: `TacticalKush was here :3`,
        description: `Standard rotation`,
        author: `TacticalKush`,
        data: {"name":"TacticalKush was here :3","description":"","actions":[{"type":"intro","order":1,"count":1,"buffs":[{"modifier":null,"modifierValue":null}],"key":"LoongsHalo"},{"order":2,"key":"OverflowingRadianceDMG","type":"skill","count":1,"buffs":[{"modifier":null,"modifierValue":null}]},{"order":3,"key":"CrescentDivinityDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":4,"key":"BasicAttack1DMG","type":"forteCircuit","count":"1","buffs":[]},{"order":5,"key":"BasicAttack2DMG","type":"forteCircuit","count":1,"buffs":[]},{"order":6,"key":"BasicAttack3DMG","type":"forteCircuit","count":1,"buffs":[]},{"order":7,"key":"BasicAttack4DMG","type":"forteCircuit","count":1,"buffs":[]},{"order":8,"key":"SolarFlareDMG","type":"forteCircuit","count":1,"buffs":[{"modifier":null,"modifierValue":null}]},{"order":9,"key":"StarGlamourDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":10,"key":"PurgeOfLight","type":"liberation","count":1,"buffs":[]}]}
    },
];

export const echoes = [
    {
        name: `Standard CD Build`,
        description: `43311 CD 2x Spectro Celestial Light build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% SKill, 100 ATK, 25.2% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"Jué","echoSet":"CelestialLight","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"CyanFeatheredHeron","echoSet":"CelestialLight","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Lightcrusher","echoSet":"CelestialLight","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":8.4,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":430,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":60},"3":{"type":1,"echo":"GlacioPredator","echoSet":"CelestialLight","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":8.4,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"4":{"type":1,"echo":"SpectroPrism","echoSet":"CelestialLight","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":8.4,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}}}
    },
];