export const rotations: RotationPreset[] = [
    {
        name: `Prydwen Rotation`,
        description: `Prydwen rotation (No buffs)`,
        author: `Prydwen`,
        data: {"name":"Prydwen Rotation","description":"","actions":[{"order":1,"key":"ObedienceofRulesSkillDMG","type":"intro","count":"1","buffs":[]},{"order":2,"key":"TrueSightChargeDMG","type":"skill","count":1,"buffs":[]},{"order":3,"key":"HeavyAttackDMG","type":"basic","count":1,"buffs":[]},{"order":4,"key":"BasicAttack3DMG","type":"basic","count":1,"buffs":[]},{"order":5,"key":"BasicAttack4DMG","type":"basic","count":1,"buffs":[]},{"order":6,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":7,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[]},{"order":8,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":9,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[]},{"order":10,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":11,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":12,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[]},{"order":13,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]}]}
    },
    {
        name: `Quick swap rot`,
        description: `Quick swap rot`,
        author: `dragonhunter0782`,
        data: {"name":"Quick swap rot","description":"","actions":[{"order":1,"key":"ObedienceofRulesSkillDMG","type":"intro","count":1,"buffs":[]},{"order":2,"key":"TrueSightCaptureDMG","type":"skill","count":"2","buffs":[]},{"type":"intro","order":3,"count":1,"buffs":[],"key":"ObedienceofRulesSkillDMG"},{"order":4,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":5,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":6,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[]},{"order":7,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]}]}
    },
    {
        name: `Hybrid Rotation (Off-Field Role)`,
        description: `E → R → Forte Heavy → BA1 → E → BA1 → Intro → [(E → BA1) or (BA1234 → BA1)] → Forte Heavy → R → Forte Heavy → Outro`,
        author: `Namelag`,
        data: {"name":"Hybrid Rotation (Off-Field Role)","description":"E → R → Forte Heavy → BA1 → E → BA1 → Intro → [(E → BA1) or (BA1234 → BA1)] → Forte Heavy → R → Forte Heavy → Outro","actions":[{"order":1,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"BasicAttack1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"ObedienceofRulesSkillDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    }
];