export const rotations: RotationPreset[] = [
    {
        name: `Prydwen Rotation`,
        description: `Prydwen rotation (No buffs)`,
        author: `Prydwen`,
        data: {"name":"Prydwen Rotation","description":"","actions":[{"order":1,"key":"ObedienceofRulesSkillDMG","type":"intro","count":"1","buffs":[]},{"order":2,"key":"TrueSightChargeDMG","type":"skill","count":1,"buffs":[]},{"order":3,"key":"HeavyAttackDMG","type":"basic","count":1,"buffs":[]},{"order":4,"key":"BasicAttack3DMG","type":"basic","count":1,"buffs":[]},{"order":5,"key":"BasicAttack4DMG","type":"basic","count":1,"buffs":[]},{"order":6,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":7,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[]},{"order":8,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":9,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[]},{"order":10,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":11,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":12,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[]},{"order":13,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]}]}
    },
    {
        name: `Quick swap rot`,
        description: `Quick swap rot`,
        author: `dragonhunter0782`,
        data: {"name":"Quick swap rot","description":"","actions":[{"order":1,"key":"ObedienceofRulesSkillDMG","type":"intro","count":1,"buffs":[]},{"order":2,"key":"TrueSightCaptureDMG","type":"skill","count":"2","buffs":[]},{"type":"intro","order":3,"count":1,"buffs":[],"key":"ObedienceofRulesSkillDMG"},{"order":4,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[]},{"order":5,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":6,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[]},{"order":7,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[]}]}
    },
    {
        name: `Hybrid Rotation (Off-Field Role)`,
        description: `E → R → Forte Heavy → BA1 → E → BA1 → Intro → [(E → BA1) or (BA1234 → BA1)] → Forte Heavy → R → Forte Heavy → Outro`,
        author: `Namelag`,
        data: {"name":"Hybrid Rotation (Off-Field Role)","description":"E → R → Forte Heavy → BA1 → E → BA1 → Intro → [(E → BA1) or (BA1234 → BA1)] → Forte Heavy → R → Forte Heavy → Outro","actions":[{"order":1,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"BasicAttack1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"ObedienceofRulesSkillDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"TrueSightCaptureDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"TrueSightConquestDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"RadianceofFealty","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"FlamingVowDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    }
];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR Molten Rift build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 15.2% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"NightmareInfernoRider","echoSet":"MoltenRift","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"HavocDreadmane","echoSet":"MoltenRift","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceSkillDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"VioletFeatheredHeron","echoSet":"MoltenRift","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":7.6,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"FusionDreadmane","echoSet":"MoltenRift","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":7.6,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"FusionPrism","echoSet":"MoltenRift","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":60}}}
    },
];