export const forteCircuitAttacks = {
  name: "Forte Circuit: Forms Turn, Heart Abides",
  description: `<div><span class="Title">Forms Born of Heart</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Answering Form</span>, Hsin can gain and consume <span style="color:#ffd12f;" class="font-bold">Answering Heart</span>.<br>While in <span style="color:#ffd12f;" class="font-bold">Illumining Form</span>, Hsin can gain and consume <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span>.<br><br><span class="Title">Answering Form: Realm Wanderer</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Answering Form</span>, when Hsin's <span style="color:#ffd12f;" class="font-bold">Answering Heart</span> reaches 100 points, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Answering Form</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Answering Form: Realm Wanderer</span>.<br>Hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to cast the skill at the cost of STA. Hsin is immune to DMG and interruption during the action, and deals <span style="color:#ebb0ff;">Electro DMG</span> to the target, considered <span style="color:#ffd12f;" class="font-bold">Resonance Skill DMG</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Answering Form: Realm Wanderer</span> grants Hsin <span style="color:#ffd12f;" class="font-bold">Resolution of Wishes</span>. This <span style="color:#ffd12f;" class="font-bold">Answering Form: Realm Wanderer</span> consumes <span style="color:#ffd12f;" class="font-bold">Resolution of Wishes</span> to become <span style="color:#ffd12f;" class="font-bold">Answering Form: Realm Protector</span>, dealing greater DMG. <span style="color:#ffd12f;" class="font-bold">Resolution of Wishes</span> can only be gained once every 25s.<br>While casting <span style="color:#ffd12f;" class="font-bold">Answering Form: Realm Wanderer</span>, if Hsin is not in the <span style="color:#ffd12f;" class="font-bold">Heart Manifest</span> state, consume 100 points of <span style="color:#ffd12f;" class="font-bold">Answering Heart</span> and unlock <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span>.<br><br><span class="Title">Illumining Form: Beholding All Horizons</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Illumining Form</span>, when Hsin consumes all of her <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span> during the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Illumining Form</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Illumining Form: Beholding All Horizons</span>.<br>Hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to cast the skill at the cost of STA, dealing <span style="color:#ebb0ff;">Electro DMG</span> to the target, considered <span style="color:#ffd12f;" class="font-bold">Resonance Skill DMG</span>.<br>Casting <span style="color:#ffd12f;" class="font-bold">Illumining Form: Beholding All Horizons</span> grants Hsin <span style="color:#ffd12f;" class="font-bold">Law of Heaven</span>. This <span style="color:#ffd12f;" class="font-bold">Illumining Form: Beholding All Horizons</span> consumes <span style="color:#ffd12f;" class="font-bold">Law of Heaven</span> to become <span style="color:#ffd12f;" class="font-bold">Illumining Form: Stilling All Horizons</span>, dealing greater DMG. <span style="color:#ffd12f;" class="font-bold">Law of Heaven</span> can only be gained once every 25s.<br>After casting <span style="color:#ffd12f;" class="font-bold">Illumining Form: Beholding All Horizons</span>, Hsin exits the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state and <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Pillars Across Heaven</span> is unlocked.<br><br><span class="Title">Illumining Form: Pillars Aligned</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Illumining Form</span>, when Hsin's <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span> reaches 300 points, <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Illumining Form: Pillars Aligned</span>.<br>When Hsin is on the ground, press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to deal <span style="color:#ebb0ff;">Electro DMG</span> to surrounding targets, considered <span style="color:#ffd12f;" class="font-bold">Resonance Skill DMG</span>.<br>After casting <span style="color:#ffd12f;" class="font-bold">Illumining Form: Pillars Aligned</span>, Hsin enters the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state.<br><br><span class="Title">Mechanism Dominion</span></span><br><br>The <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state lasts 13s.<br>While this state is active, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form</span> is further enhanced into <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form: Pillars Aligned</span>, and <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Illumining Form</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Illumining Form: Pillars Aligned</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form: Pillars Aligned</span> or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Illumining Form: Pillars Aligned</span> hits a target, <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span> is consumed if Hsin is on the field.<br><br><span class="Title">Resonance Mode - Unison</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span>, Hsin gains the following effects:<br>- Hsin can trigger <span style="color:#ffd12f;" class="font-bold">Unison Response</span>.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span> grants Hsin <span style="color:#ffd12f;" class="font-bold">Unison</span> for 5s.<br>- When Hsin triggers <span style="color:#ffd12f;" class="font-bold">Unison Response</span>, She gains <span style="color:#ffd12f;" class="font-bold">Source Intent</span>, and the <span style="color:#ffd12f;" class="font-bold">Intro Skill</span> cast this time is replaced with <span style="color:#ffd12f;" class="font-bold">Intro Skill - Manifold Unison</span>, dealing greater DMG.<br>When Hsin casts an <span style="color:#ffd12f;" class="font-bold">Intro Skill</span> without triggering <span style="color:#ffd12f;" class="font-bold">Unison Response</span> while holding <span style="color:#ffd12f;" class="font-bold">Source Intent</span>, She consumes <span style="color:#ffd12f;" class="font-bold">Source Intent</span> instead, and the <span style="color:#ffd12f;" class="font-bold">Intro Skill</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Intro Skill - Manifold Unison</span>, dealing greater DMG.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form</span> or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form: Manifold Unison</span> sends Hsin directly into the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state.<br>- When Hsin swiches Resonance Mode, <span style="color:#ffd12f;" class="font-bold">Source Intent</span>, <span style="color:#ffd12f;" class="font-bold">Unison</span>, and <span style="color:#ffd12f;" class="font-bold">【Unison Boon】</span> are removed.<br><br><span class="Title">Resonance Mode - Electro Flare</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Electro Flare</span>, Hsin gains the following effects:<br>- After Resonators in the team inflict <span style="color:#ffd12f;" class="font-bold">Electro Rage</span> to a target, every 1 stacks of <span style="color:#ffd12f;" class="font-bold">Electro Rage</span> inflicted grants Hsin 1 stacks of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span>, stacking up to 100 times, and consumes all <span style="color:#ffd12f;" class="font-bold">Electro Rage</span> stacks from that target. <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span> is removed when Hsin switches Resonance Mode.<br>- When <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Illumining Form</span>hits a target, if Hsin has at least 5 stacks of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span>, then consume 5 stacks of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span> to trigger 1 instance of <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> DMG, with its DMG Multiplier equal to 200% times the <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> DMG Multiplier corresponding to the current <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> stacks on the target.<br>Some time after casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Illumining Form</span>, Hsin consumes all remaining stacks of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span> at once to trigger 1 instance of <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> DMG. Its DMG Multiplier equals to 40% x (the number of <span style="color:#ffd12f;" class="font-bold">Heart of Thunder</span> stacks consumed this time) x (the <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> DMG Multiplier corresponding to the target's current <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> stacks).<br>While casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Illumining Form</span>, switching to another Resonator or ending the skill early will end the above effects early.<br>- After <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span> is cast, inflict <SapTag=E>5</SapTag> {Cus:Sap,S=stack P=stacks SapTag=E} of <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> on the nearby targets within a certain range. When <span style="color:#ffd12f;" class="font-bold">Illumining Form: Pillars Aligned</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form: Pillars Aligned</span>, or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Illumining Form: Pillars Aligned</span> hits a target, Hsin inflicts <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> to that target. This can take effect up to 5 times. Each time Hsin casts <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span>, the number of times it can take effect is reset. When Hsin switches Resonance Mode, the number of times it can take effect is removed.<br><span style="color:#ffd12f;" class="font-bold">Illumining Form: Pillars Aligned</span> and <span style="color:#ffd12f;" class="font-bold">Illumining Form: Stilling All Horizons</span> inflict <SapTag=E>5</SapTag> {Cus:Sap,S=stack P=stacks SapTag=E} of <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> on the target hit. <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form</span> and <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form</span> inflict <SapTag=F>1</SapTag> {Cus:Sap,S=stack P=stacks SapTag=F} of <span style="color:#ffd12f;" class="font-bold">Electro Flare</span> on the target hit.<br><br><span class="Title">Unison</span></span><br><br>While Hsin is in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span> with <span style="color:#ffd12f;" class="font-bold">Unison</span>, switching to another Resonator will remove Hsin's <span style="color:#ffd12f;" class="font-bold">Unison</span> to trigger Hsin's Outro Skill and the incoming Resonator's Intro Skill. If Hsin has full Concerto Energy and <span style="color:#ffd12f;" class="font-bold">Unison</span> at the same time, only <span style="color:#ffd12f;" class="font-bold">Unison</span> is consumed to trigger the effect.<br><br><span class="Title">Unison Response</span></span><br><br>While Hsin is in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span> and another Resonator in the team has <span style="color:#ffd12f;" class="font-bold">Unison</span>, switching to Hsin grants <SapTag=G>1</SapTag> {Cus:Sap,S=stack P=stacks SapTag=G} of <span style="color:#ffd12f;" class="font-bold">Unison Boon</span> to all Resonators in the team for 30s.<br>Hsin can only grant up to <SapTag=G>1</SapTag> {Cus:Sap,S=stack P=stacks SapTag=G} of <span style="color:#ffd12f;" class="font-bold">Unison Boon</span> in this way. Retriggering the effect resets the duration.<br><br><span class="Title">Unison Boon</span></span><br><br>Each stack of <span style="color:#ffd12f;" class="font-bold">Unison Boon</span> increase the total DMG dealt by Resonators with the <span style="color:#ffd12f;" class="font-bold">Unison Response</span> ability in the team by 3%, stacking up to 2 times.<br><br><span class="Title">Answering Heart</span></span><br><br>Can hold up to 100 points of <span style="color:#ffd12f;" class="font-bold">Answering Heart</span>.<br>While in <span style="color:#ffd12f;" class="font-bold">Answering Form</span>, when <span style="color:#ffd12f;" class="font-bold">Normal Attack - Answering Form</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Answering Form</span>, <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form</span>, or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form: Manifold Unison</span> hits a target, Hsin gains <span style="color:#ffd12f;" class="font-bold">Answering Heart</span> if She is on the field.<br>Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form</span> or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Answering Form: Manifold Unison</span> grants 60 points of <span style="color:#ffd12f;" class="font-bold">Answering Heart</span>.<br><br><span class="Title">Illumining Heart</span></span><br><br>Can hold up to 300 points of <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span>.<br>While in <span style="color:#ffd12f;" class="font-bold">Illumining Form</span> and not in the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state, when <span style="color:#ffd12f;" class="font-bold">Normal Attack - Illumining Form</span>, or <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Illumining Form</span> hits a target, Hsin gains <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span> if She is on the field.<br>- While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Unison</span>, casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form</span> or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Illumining Form: Manifold Unison</span> directly sends Hsin into the <span style="color:#ffd12f;" class="font-bold">Mechanism Dominion</span> state and grants 300 points of <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span>.<br>- While in <span style="color:#ffd12f;" class="font-bold">Resonance Mode - Electro Flare</span>, after casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span>, the next time the <span style="color:#ffd12f;" class="font-bold">Modular Heartlock</span> generated by <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form Stage 1</span> is collapsed by <span style="color:#ffd12f;" class="font-bold">Basic Attack - Illumining Form Stage 2</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Illumining Form</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Illumining Form</span>, or <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Illumining Form</span>, gain 150 points of <span style="color:#ffd12f;" class="font-bold">Illumining Heart</span> if Hsin is on the field. This effect can only be triggered once before the next cast of <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Formshift</span> resets it, and is disabled when switched to the other Resonance Mode.</div>`,
  icon: "https://api.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Atlas/SkillIcon/SkillIconXin/SP_IconXinY.webp",
  attacks: [
    {
      key: "AnsweringFormRealmWandererDMG",
      label: "Answering Form: Realm Wanderer DMG",
      talents: {
        "1": "22.96%+5.74%*6+229.59%",
        "2": "24.85%+6.22%*6+248.42%",
        "3": "26.73%+6.69%*6+267.25%",
        "4": "29.36%+7.34%*6+293.60%",
        "5": "31.25%+7.82%*6+312.43%",
        "6": "33.41%+8.36%*6+334.08%",
        "7": "36.42%+9.11%*6+364.20%",
        "8": "39.44%+9.86%*6+394.32%",
        "9": "42.45%+10.62%*6+424.45%",
        "10": "45.65%+11.42%*6+456.45%",
      },
      type: "Skill",
    },
    {
      key: "AnsweringFormRealmProtectorDMG",
      label: "Answering Form: Realm Protector DMG",
      talents: {
        "1": "49.96%+12.49%*6+499.55%",
        "2": "54.06%+13.52%*6+540.51%",
        "3": "58.15%+14.54%*6+581.48%",
        "4": "63.89%+15.98%*6+638.83%",
        "5": "67.98%+17.00%*6+679.79%",
        "6": "72.69%+18.18%*6+726.90%",
        "7": "79.25%+19.82%*6+792.44%",
        "8": "85.80%+21.45%*6+857.98%",
        "9": "92.36%+23.09%*6+923.52%",
        "10": "99.32%+24.83%*6+993.15%",
      },
      type: "Skill",
    },
    {
      key: "IlluminingFormBeholdingAllHorizonsDMG",
      label: "Illumining Form: Beholding All Horizons DMG",
      talents: {
        "1": "5.17%*4+185.96%",
        "2": "5.59%*4+201.20%",
        "3": "6.02%*4+216.45%",
        "4": "6.61%*4+237.80%",
        "5": "7.03%*4+253.05%",
        "6": "7.52%*4+270.58%",
        "7": "8.20%*4+294.98%",
        "8": "8.88%*4+319.38%",
        "9": "9.55%*4+343.77%",
        "10": "10.27%*4+369.70%",
      },
      type: "Skill",
    },
    {
      key: "IlluminingFormStillingAllHorizonsDMG",
      label: "Illumining Form: Stilling All Horizons DMG",
      talents: {
        "1": "13.61%*4+489.66%",
        "2": "14.72%*4+529.81%",
        "3": "15.84%*4+569.96%",
        "4": "17.40%*4+626.18%",
        "5": "18.51%*4+666.33%",
        "6": "19.80%*4+712.50%",
        "7": "21.58%*4+776.75%",
        "8": "23.37%*4+840.99%",
        "9": "25.15%*4+905.23%",
        "10": "27.05%*4+973.49%",
      },
      type: "Skill",
    },
    {
      key: "IlluminingFormPillarsAlignedDMG",
      label: "Illumining Form: Pillars Aligned DMG",
      talents: {
        "1": "90.26%*4+9.03%+18.06%*2+22.57%*2",
        "2": "97.66%*4+9.77%+19.54%*2+24.42%*2",
        "3": "105.06%*4+10.51%+21.02%*2+26.27%*2",
        "4": "115.42%*4+11.55%+23.09%*2+28.86%*2",
        "5": "122.82%*4+12.29%+24.57%*2+30.71%*2",
        "6": "131.33%*4+13.14%+26.27%*2+32.84%*2",
        "7": "143.17%*4+14.32%+28.64%*2+35.80%*2",
        "8": "155.01%*4+15.51%+31.01%*2+38.76%*2",
        "9": "166.85%*4+16.69%+33.37%*2+41.72%*2",
        "10": "179.43%*4+17.95%+35.89%*2+44.86%*2",
      },
      type: "Skill",
    },
    {
      key: "HeartOfThunderInstantDMG",
      label: "Heart of Thunder: Instant Electro Flare DMG",
      type: "ElementalEffect",
      element: "Electro",
      subType: "ElectroFlare",
      talent: "",
      requiresResonanceChain: "ResonanceModeElectroFlareHeartOfThunderInstantDMG",
    },
    {
      key: "HeartOfThunderDelayedDMG",
      label: "Heart of Thunder: Delayed Electro Flare DMG",
      type: "ElementalEffect",
      element: "Electro",
      subType: "ElectroFlare",
      talent: "",
      requiresResonanceChain: "ResonanceModeElectroFlareHeartOfThunderDelayedDMG",
    },
    {
      key: "SequenceNode3PillarsAcrossHeavenElectroFlareDMG",
      label: "Sequence Node 3: Pillars Across Heaven Electro Flare DMG",
      type: "ElementalEffect",
      element: "Electro",
      subType: "ElectroFlare",
      talent: "",
      requiresResonanceChain: "SequenceNode3ADreamOfReturnAmongTheHillsElectroFlare",
    }
  ],
};
