export const basicAttacks = {
  name: "Normal Attack: Flaming Sakura Blade Art",
  description: `<div><span style="color:#a89969"><strong>Basic Attack - Present Self</strong></span><br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> consecutively or hold it down to perform up to 3 consecutive attacks, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br><span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span> applies 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on hit.<br><br><span style="color:#a89969"><strong>Heavy Attack - Frost Splinter: Present Self</strong></span><br>When <span style="color:#f7ca2f"><strong><a href="#WwLink110801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110801">Dedication</a></strong></span> reaches 300 points, <span style="color:#f7ca2f"><strong>Heavy Attack - Frost Splinter: Present Self</strong></span> becomes available.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to shoot out 3 arrows one by one at the cost of STA, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG. Hiyuki is immune to interruptions in the duration.<br>When the last arrow is shot, 300 points of <span style="color:#f7ca2f"><strong><a href="#WwLink110801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110801">Dedication</a></strong></span> is consumed and <span style="color:#f7ca2f"><strong>Foreclaiming: Inward Vision</strong></span> becomes available. The arrow applies 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on hit.<br><br><span style="color:#a89969"><strong>Mid-air Attack - Present Self</strong></span><br>Consume STA to perform a Plunging Attack from Mid-air, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter - Present Self</strong></span><br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after a successful Dodge to attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>.<br><br><span style="color:#a89969"><strong>Basic Attack - Foreclaimed Self</strong></span><br>While in <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, <span style="color:#f7ca2f"><strong>Basic Attack - Present Self</strong></span> is replaced by <span style="color:#f7ca2f"><strong>Basic Attack - Foreclaimed Self</strong></span>.<br>Perform up to 5 consecutive attacks, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG.<br><span style="color:#f7ca2f"><strong>Basic Attack - Foreclaimed Self Stage 3, 4, and 5</strong></span> each applies 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on hit.<br><br><span style="color:#a89969"><strong>Heavy Attack - Foreclaimed Self</strong></span><br>In <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> to enter <span style="color:#f7ca2f"><strong>Hold Breath</strong></span>, continuously consuming STA. When <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> is released or STA is depleted, Hiyuki leaves the <span style="color:#f7ca2f"><strong>Hold Breath</strong></span> state and thrusts forward, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG. Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Foreclaimed Self Stage 2</strong></span>.<br>If Hiyuki is attacked by an enemy within a certain period during the thrust, neutralize that instance of damage, Stagnate nearby targets, and become immune to interruptions for a certain period afterward while reducing all incoming damage by 100%. Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to chain into <span style="color:#f7ca2f"><strong>Basic Attack - Foreclaimed Self Stage 4</strong></span> instead.<br><br><span style="color:#a89969"><strong>Heavy Attack - Bitterfrost: Foreclaimed Self</strong></span><br>When <span style="color:#f7ca2f"><strong><a href="#WwLink110804" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110804">Whiteout Bitterfrost</a></strong></span> is full, <span style="color:#f7ca2f"><strong>Heavy Attack - Foreclaimed Self</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Heavy Attack - Bitterfrost: Foreclaimed Self</strong></span>. <br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> and consume STA and 3 stacks of <span style="color:#f7ca2f"><strong><a href="#WwLink110804" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110804">Whiteout Bitterfrost</a></strong></span> to gain 1 point of <span style="color:#f7ca2f"><strong><a href="#WwLink110805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110805">Snowforged Blade</a></strong></span>, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG.<br><span style="color:#f7ca2f"><strong>Heavy Attack - Bitterfrost: Foreclaimed Self</strong></span> applies 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on hit.<br>If Hiyuki is airborne while casting this skill, she'll land on the ground first.<br><br><span style="color:#a89969"><strong>Mid-air Attack - Foreclaimed Self</strong></span><br>While in <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, <span style="color:#f7ca2f"><strong>Mid-air Attack - Present Self</strong></span> is replaced by <span style="color:#f7ca2f"><strong>Mid-air Attack - Foreclaimed Self</strong></span>.<br>Consume STA to perform up to 3 consecutive attacks in Mid-air, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG. Stage 3 is a Plunging Attack.<br><span style="color:#f7ca2f"><strong>Mid-air Attack - Foreclaimed Self Stage 2 &amp; 3</strong></span> apply 1 stack of <span style="color:#f7ca2f"><strong><a href="#WwLink850010" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="850010">Glacio Chafe</a></strong></span> on hit.<br>The <span style="color:#f7ca2f"><strong>Mid-air Attack - Foreclaimed Self</strong></span> combo will not be reset by casting skills other than <span style="color:#f7ca2f"><strong>Basic Attack - Iai</strong></span> within a short period.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> while airborne to perform a Plunging Attack at the cost of STA.<br><br><span style="color:#a89969"><strong>Dodge Counter - Foreclaimed Self</strong></span><br>While in <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, <span style="color:#f7ca2f"><strong>Dodge Counter - Present Self</strong></span> is replaced by <span style="color:#f7ca2f"><strong>Dodge Counter - Foreclaimed Self</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after a successful Dodge to attack the target, dealing <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, considered Resonance Liberation DMG.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Foreclaimed Self Stage 3</strong></span>.</div>`,
  attacks: [
    {
      key: "BasicAttackStage1DMG",
      label: "Basic Attack Stage 1 DMG",
      talents: {
        "1": "20.40%+20.40%",
        "2": "22.08%+22.08%",
        "3": "23.75%+23.75%",
        "4": "26.09%+26.09%",
        "5": "27.77%+27.77%",
        "6": "29.69%+29.69%",
        "7": "32.37%+32.37%",
        "8": "35.04%+35.04%",
        "9": "37.72%+37.72%",
        "10": "40.56%+40.56%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage2DMG",
      label: "Basic Attack Stage 2 DMG",
      talents: {
        "1": "30.26%+45.39%",
        "2": "32.75%+49.12%",
        "3": "35.23%+52.84%",
        "4": "38.70%+58.05%",
        "5": "41.18%+61.77%",
        "6": "44.04%+66.05%",
        "7": "48.01%+72.01%",
        "8": "51.98%+77.96%",
        "9": "55.95%+83.92%",
        "10": "60.16%+90.24%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage3DMG",
      label: "Basic Attack Stage 3 DMG",
      talents: {
        "1": "2.53%*30",
        "2": "2.73%*30",
        "3": "2.94%*30",
        "4": "3.23%*30",
        "5": "3.44%*30",
        "6": "3.67%*30",
        "7": "4.01%*30",
        "8": "4.34%*30",
        "9": "4.67%*30",
        "10": "5.02%*30",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStage4DMG",
      label: "Basic Attack Stage 4 DMG",
      talents: {
        "1": "48.45%",
        "2": "52.43%",
        "3": "56.40%",
        "4": "61.96%",
        "5": "65.94%",
        "6": "70.50%",
        "7": "76.86%",
        "8": "83.22%",
        "9": "89.57%",
        "10": "96.33%",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackDMG",
      label: "Heavy Attack DMG",
      talents: {
        "1": "45.90%",
        "2": "49.67%",
        "3": "53.43%",
        "4": "58.70%",
        "5": "62.47%",
        "6": "66.79%",
        "7": "72.82%",
        "8": "78.84%",
        "9": "84.86%",
        "10": "91.26%",
      },
      type: "Heavy",
    },
    {
      key: "MidairAttackStage1DMG",
      label: "Mid-air Attack Stage 1 DMG",
      talents: {
        "1": "28.90%",
        "2": "31.27%",
        "3": "33.64%",
        "4": "36.96%",
        "5": "39.33%",
        "6": "42.06%",
        "7": "45.85%",
        "8": "49.64%",
        "9": "53.43%",
        "10": "57.46%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackStage2ScytheDissectionDMG",
      label: "Mid-air Attack Stage 2 Scythe: Dissection DMG",
      talents: {
        "1": "14.20%+14.20%+18.93%",
        "2": "15.36%+15.36%+20.48%",
        "3": "16.53%+16.53%+22.04%",
        "4": "18.16%+18.16%+24.21%",
        "5": "19.32%+19.32%+25.76%",
        "6": "20.66%+20.66%+27.55%",
        "7": "22.52%+22.52%+30.03%",
        "8": "24.38%+24.38%+32.51%",
        "9": "26.25%+26.25%+34.99%",
        "10": "28.23%+28.23%+37.63%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackStage3ScytheDissectionDMG",
      label: "Mid-air Attack Stage 3 Scythe: Dissection DMG",
      talents: {
        "1": "21.59%+21.59%+28.79%",
        "2": "23.37%+23.37%+31.15%",
        "3": "25.14%+25.14%+33.51%",
        "4": "27.61%+27.61%+36.82%",
        "5": "29.38%+29.38%+39.18%",
        "6": "31.42%+31.42%+41.89%",
        "7": "34.25%+34.25%+45.67%",
        "8": "37.09%+37.09%+49.45%",
        "9": "39.92%+39.92%+53.22%",
        "10": "42.93%+42.93%+57.24%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackStage2ScytheResctionDMG",
      label: "Mid-air Attack Stage 2 Scythe: Resction DMG",
      talents: {
        "1": "25.36%+25.36%",
        "2": "27.44%+27.44%",
        "3": "29.52%+29.52%",
        "4": "32.43%+32.43%",
        "5": "34.51%+34.51%",
        "6": "36.90%+36.90%",
        "7": "40.23%+40.23%",
        "8": "43.56%+43.56%",
        "9": "46.88%+46.88%",
        "10": "50.42%+50.42%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackStage3ScytheResctionDMG",
      label: "Mid-air Attack Stage 3 Scythe: Resction DMG",
      talents: {
        "1": "37.69%+37.69%",
        "2": "40.78%+40.78%",
        "3": "43.87%+43.87%",
        "4": "48.19%+48.19%",
        "5": "51.28%+51.28%",
        "6": "54.84%+54.84%",
        "7": "59.78%+59.78%",
        "8": "64.73%+64.73%",
        "9": "69.67%+69.67%",
        "10": "74.92%+74.92%",
      },
      type: "Basic",
    },
    {
      key: "MidairAttackStage4DMG",
      label: "Mid-air Attack Stage 4 DMG",
      talents: {
        "1": "52.70%",
        "2": "57.03%",
        "3": "61.35%",
        "4": "67.40%",
        "5": "71.72%",
        "6": "76.69%",
        "7": "83.60%",
        "8": "90.52%",
        "9": "97.43%",
        "10": "104.78%",
      },
      type: "Basic",
    },
    {
      key: "GroundDodgeCounterDMG",
      label: "Ground Dodge Counter DMG",
      talents: {
        "1": "63.33%+63.33%",
        "2": "68.52%+68.52%",
        "3": "73.72%+73.72%",
        "4": "80.99%+80.99%",
        "5": "86.18%+86.18%",
        "6": "92.15%+92.15%",
        "7": "100.46%+100.46%",
        "8": "108.77%+108.77%",
        "9": "117.07%+117.07%",
        "10": "125.90%+125.90%",
      },
      type: "Basic",
    },
    {
      key: "MidairDodgeCounterDMG",
      label: "Mid-air Dodge Counter DMG",
      talents: {
        "1": "129.20%",
        "2": "139.80%",
        "3": "150.39%",
        "4": "165.23%",
        "5": "175.82%",
        "6": "188.00%",
        "7": "204.95%",
        "8": "221.91%",
        "9": "238.86%",
        "10": "256.87%",
      },
      type: "Basic",
    },
  ],
};
