export const rotations: RotationPreset[] = [];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Glacio Wishes of Quiet Snowfall Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceThrenodianVoidborneConstruct","echoSet":"WishesofQuietSnowfall","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"FrostbiteColeoid","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Glommoth","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"TremorWarrior","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"IceglintDancer","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}},"mainEcho":{"echo":"ReminiscenceThrenodianVoidborneConstruct","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Glacio Wishes of Quiet Snowfall Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceThrenodianVoidborneConstruct","echoSet":"WishesofQuietSnowfall","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"WindlashColeoid","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Glommoth","echoSet":"WishesofQuietSnowfall","stat":"Glacio","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"IceglintDancer","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"ShadowStepper","echoSet":"WishesofQuietSnowfall","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"ReminiscenceThrenodianVoidborneConstruct","rank":5}}
    }
];

