export const skillAttacks = {
  name: "Resonance Skill: Frostblight",
  description: `<div><span style="color:#a89969"><strong>Resonance Skill - Present Self</strong></span><br>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>Casting this skill enhances the next <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>, which now restores 100 points of <span style="color:#f7ca2f"><strong><a href="#WwLink110801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110801">Dedication</a></strong></span> when cast. Switching to another Resonator ends this effect.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>.<br>If <span style="color:#f7ca2f"><strong><a href="#WwLink110801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110801">Dedication</a></strong></span> is below 300 points, hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform  <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>.<br><br>While in <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, <span style="color:#f7ca2f"><strong>Resonance Skill - Present Self</strong></span> is replaced by <span style="color:#f7ca2f"><strong>Frostblight: Jade Cleave</strong></span> and <span style="color:#f7ca2f"><strong>Frostblight: Petalfall</strong></span>:<br><br><span style="color:#a89969"><strong>Frostblight: Jade Cleave</strong></span><br>While on the ground, press <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> to pull in nearby targets and deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, removing the targets' <span style="color:#f7ca2f"><strong><a href="#WwLink110808" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110808">Frostbind</a></strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Frostblight: Petalfall</strong></span>.<br><br><span style="color:#a89969"><strong>Frostblight: Petalfall</strong></span><br>While in mid-air, press <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> to pull in nearby targets and deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, removing the targets' <span style="color:#f7ca2f"><strong><a href="#WwLink110808" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="110808">Frostbind</a></strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Frostblight: Jade Cleave</strong></span>.</div>`,
  attacks: [
    {
      key: "GoldenRefluxDMG",
      label: "Golden Reflux DMG",
      talents: {
        "1": "101.20%",
        "2": "109.50%",
        "3": "117.80%",
        "4": "129.42%",
        "5": "137.72%",
        "6": "147.26%",
        "7": "160.54%",
        "8": "173.82%",
        "9": "187.09%",
        "10": "201.20%",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionRingDMG",
      label: "Aureole of Execution: Ring DMG",
      talents: {
        "1": "13.36%*5+44.53%",
        "2": "14.46%*5+48.18%",
        "3": "15.55%*5+51.84%",
        "4": "17.09%*5+56.95%",
        "5": "18.18%*5+60.60%",
        "6": "19.44%*5+64.80%",
        "7": "21.20%*5+70.64%",
        "8": "22.95%*5+76.48%",
        "9": "24.70%*5+82.32%",
        "10": "26.56%*5+88.53%",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionBreachDMG",
      label: "Aureole of Execution: Breach DMG",
      talents: {
        "1": "48.24%*3",
        "2": "52.20%*3",
        "3": "56.15%*3",
        "4": "61.69%*3",
        "5": "65.65%*3",
        "6": "70.20%*3",
        "7": "76.53%*3",
        "8": "82.85%*3",
        "9": "89.18%*3",
        "10": "95.91%*3",
      },
      type: "Basic",
    },
    {
      key: "AureoleofExecutionGlareDMG",
      label: "Aureole of Execution: Glare DMG",
      talents: {
        "1": "178.12%",
        "2": "192.72%",
        "3": "207.33%",
        "4": "227.77%",
        "5": "242.38%",
        "6": "259.18%",
        "7": "282.54%",
        "8": "305.91%",
        "9": "329.28%",
        "10": "354.11%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackGoldenImpaleDMG",
      label: "Basic Attack - Golden Impale DMG",
      talents: {
        "1": "78.20%",
        "2": "84.62%",
        "3": "91.03%",
        "4": "100.01%",
        "5": "106.42%",
        "6": "113.79%",
        "7": "124.05%",
        "8": "134.31%",
        "9": "144.57%",
        "10": "155.47%",
      },
      type: "Basic",
    },
    {
      key: "IchorDepositDMG",
      label: "Ichor Deposit DMG",
      talents: {
        "1": "77.19%",
        "2": "83.52%",
        "3": "89.84%",
        "4": "98.71%",
        "5": "105.03%",
        "6": "112.31%",
        "7": "122.44%",
        "8": "132.56%",
        "9": "142.69%",
        "10": "153.45%",
      },
      type: "Basic",
    },
  ],
};
