export const skillAttacks = {
  name: "Resonance Skill: Frostblight",
  description: `<div><span style="color:#a89969"><strong>Resonance Skill - Present Self</strong></span><br>Deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>.<br>Casting this skill enhances the next <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>, which now restores 100 points of <span style="color:#f7ca2f"><strong><a href="#WwLink110801" data-ww-link-id="110801">Dedication</a></strong></span> when cast. Switching to another Resonator ends this effect.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>.<br>If <span style="color:#f7ca2f"><strong><a href="#WwLink110801" data-ww-link-id="110801">Dedication</a></strong></span> is below 300 points, hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain period after casting this skill to perform  <span style="color:#f7ca2f"><strong>Basic Attack - Present Self Stage 3</strong></span>.<br><br>While in <span style="color:#f7ca2f"><strong>Foreclaimed Self</strong></span>, <span style="color:#f7ca2f"><strong>Resonance Skill - Present Self</strong></span> is replaced by <span style="color:#f7ca2f"><strong>Frostblight: Jade Cleave</strong></span> and <span style="color:#f7ca2f"><strong>Frostblight: Petalfall</strong></span>:<br><br><span style="color:#a89969"><strong>Frostblight: Jade Cleave</strong></span><br>While on the ground, press <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> to pull in nearby targets and deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, removing the targets' <span style="color:#f7ca2f"><strong><a href="#WwLink110808" data-ww-link-id="110808">Frostbind</a></strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Frostblight: Petalfall</strong></span>.<br><br><span style="color:#a89969"><strong>Frostblight: Petalfall</strong></span><br>While in mid-air, press <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> to pull in nearby targets and deal <span style="color:#41aefb"><strong>Glacio DMG</strong></span>, removing the targets' <span style="color:#f7ca2f"><strong><a href="#WwLink110808" data-ww-link-id="110808">Frostbind</a></strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Frostblight: Jade Cleave</strong></span>.</div>`,
  attacks: [
    {
      key: "ResonanceSkillPresentSelfDMG",
      label: "Resonance Skill - Present Self DMG",
      talents: {
        "1": "12.32%*4+49.28%",
        "2": "13.34%*4+53.33%",
        "3": "14.35%*4+57.37%",
        "4": "15.76%*4+63.02%",
        "5": "16.77%*4+67.07%",
        "6": "17.93%*4+71.71%",
        "7": "19.55%*4+78.18%",
        "8": "21.16%*4+84.64%",
        "9": "22.78%*4+91.11%",
        "10": "24.50%*4+97.98%",
      },
      type: "Skill",
    },
    {
      key: "FrostblightJadeCleaveDMG",
      label: "Frostblight: Jade Cleave DMG",
      talents: {
        "1": "33.20%*4",
        "2": "35.93%*4",
        "3": "38.65%*4",
        "4": "42.46%*4",
        "5": "45.18%*4",
        "6": "48.31%*4",
        "7": "52.67%*4",
        "8": "57.03%*4",
        "9": "61.38%*4",
        "10": "66.01%*4",
      },
      type: "Skill",
    },
    {
      key: "FrostblightPetalfallDMG",
      label: "Frostblight: Petalfall DMG",
      talents: {
        "1": "32.20%*4+32.20%",
        "2": "34.85%*4+34.85%",
        "3": "37.49%*4+37.49%",
        "4": "41.18%*4+41.18%",
        "5": "43.82%*4+43.82%",
        "6": "46.86%*4+46.86%",
        "7": "51.08%*4+51.08%",
        "8": "55.31%*4+55.31%",
        "9": "59.53%*4+59.53%",
        "10": "64.02%*4+64.02%",
      },
      type: "Skill",
    },
  ],
};
