export const rotations: RotationPreset[] = [
  {
    name: `Yar har fiddle dee dee`,
    description: `Standard s0 rotation`,
    author: `vv ubFiish`,
    data: {
      name: "Yar har fiddle dee dee",
      description: "",
      actions: [
        {
          order: 1,
          key: "ApplaudforMeDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "TotheHorizonDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "MidAirAttackStage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "MidairAttackStage2ChargedAttackDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "MidairAttackStage2FlipDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "MidairAttackStage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "MidairAttackStage3FlipDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "MidairAttackStage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "HeavyAttackRhapsodicRiffDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "ReturnedfromAshesDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: `Intro + Ult + Forte + S2 Outro`,
    description: `Intro -> Full Mid-Air rotation, Stage 1 hold, no Stage 4 cancel, into Forte and swap out with Outro (S2). My Moment buff active`,
    author: `JanJanJan`,
    data: {
      name: "Intro + Ult + Forte + S2 Outro",
      description:
        "Intro -> Full Mid-Air rotation, Stage 1 hold, no Stage 4 cancel, into Forte and swap out with Outro (S2). My Moment buff active",
      actions: [
        {
          order: 1,
          key: "ApplaudforMeDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "TotheHorizonDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "MidairAttackStage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "MidAirAttackStage1ChargedAttackDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "MidairAttackStage2FlipDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "MidairAttackStage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "MidairAttackStage3FlipDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "MidairAttackStage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "ReturnedfromAshesDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "SequenceNode2ForSmilesandCheersBlastDMG",
          type: "outro",
          count: 2,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];

export const echoes = [
  {
    name: `Standard CR Build`,
    description: `43311 2x ER CR Tidebreaking Courage build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 27.6% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "DragonofDirge",
          echoSet: "TidebreakingCourage",
          stat: "CritRate",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "BasicAttackDMGBonus",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "EnergyRegen",
          echoSubStatsValue5: 9.2,
        },
        "1": {
          type: 3,
          echo: "AbyssalGladius",
          echoSet: "TidebreakingCourage",
          stat: "EnergyRegen",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "BasicAttackDMGBonus",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "EnergyRegen",
          echoSubStatsValue5: 9.2,
        },
        "2": {
          type: 3,
          echo: "DiurnusKnight",
          echoSet: "TidebreakingCourage",
          stat: "EnergyRegen",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK_FLAT",
          echoSubStatsValue3: 50,
          echoSubStatsType4: "DEF",
          echoSubStatsValue4: 10.9,
          echoSubStatsType5: "EnergyRegen",
          echoSubStatsValue5: 9.2,
        },
        "3": {
          type: 1,
          echo: "AeroDrake",
          echoSet: "TidebreakingCourage",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "DEF",
          echoSubStatsValue3: 10.9,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "HP",
          echoSubStatsValue5: 8.6,
        },
        "4": {
          type: 1,
          echo: "CalcifiedJunrock",
          echoSet: "TidebreakingCourage",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "DEF_FLAT",
          echoSubStatsValue3: 60,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
      },
    },
  },
];
