export const rotations: RotationPreset[] = [
    {
        name: `Yar har fiddle dee dee`,
        description: `Standard s0 rotation`,
        author: `vv ubFiish`,
        data: {"name":"Yar har fiddle dee dee","description":"","actions":[{"order":1,"key":"ApplaudforMeDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":3,"key":"MidairAttackStage2FlipDMG","type":"basic","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":4,"key":"MidairAttackStage2ChargedAttackDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":5,"key":"MidairAttackStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":6,"key":"MidairAttackStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":7,"key":"HeavyAttackRhapsodicRiffDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":8,"key":"ReturnedfromAshesDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false},{"order":8,"key":"TotheHorizonDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false}]}
    },
    {
        name: `Intro + Ult + Forte + S2 Outro`,
        description: `Intro -> Full Mid-Air rotation, Stage 1 hold, no Stage 4 cancel, into Forte and swap out with Outro (S2). My Moment buff active`,
        author: `JanJanJan`,
        data: {"name":"Intro + Ult + Forte + S2 Outro","description":"Intro -> Full Mid-Air rotation, Stage 1 hold, no Stage 4 cancel, into Forte and swap out with Outro (S2). My Moment buff active","actions":[{"order":1,"key":"ApplaudforMeDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"TotheHorizonDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"MidairAttackStage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"MidAirAttackStage1ChargedAttackDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"MidairAttackStage2FlipDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"MidairAttackStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"MidairAttackStage3FlipDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"MidairAttackStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"ReturnedfromAshesDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"SequenceNode2ForSmilesandCheersBlastDMG","type":"outro","count":2,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    }
];