export const rotations: RotationPreset[] = [];
export const echoes = [
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Havoc Song of Feathered Trace Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 9.2% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ThousandPuppetPavilion","echoSet":"SongofFeatheredTrace","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"ForbiddenBastion","echoSet":"SongofFeatheredTrace","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"FogLionarch","echoSet":"SongofFeatheredTrace","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"Smolder","echoSet":"SongofFeatheredTrace","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"Smiter","echoSet":"SongofFeatheredTrace","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"ThousandPuppetPavilion","rank":5}}
    },
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Havoc Song of Feathered Trace Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 9.2% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ThousandPuppetPavilion","echoSet":"SongofFeatheredTrace","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"ForbiddenBastion","echoSet":"SongofFeatheredTrace","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"FogLionarch","echoSet":"SongofFeatheredTrace","stat":"Havoc","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"KernelPuppetJoy","echoSet":"SongofFeatheredTrace","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"Smolder","echoSet":"SongofFeatheredTrace","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}},"mainEcho":{"echo":"ThousandPuppetPavilion","rank":5}}
    }
];
