export const forteCircuitAttacks = {
  name: "Forte Circuit: World in a Grain of Sand",
  description: `<div class="skilldescription"><span class="Title">Resonance Skill: Resonating Spin</span><br>If "Diminutive Sound" exceeds 50 when <span class="Highlight">Resonance Skill</span> is used, Rover consumes 50 "Diminutive Sound" to cast <span class="Highlight">Resonating Spin</span>, dealing <span class="Light">Spectro DMG</span>, considered as Resonance Skill DMG.<br> <br><span class="Title">Basic Attack: Resonating Echoes</span><br>After Resonance Skill <span class="Highlight">Resonating Spin</span> ends, Rover performs <span class="Highlight">Resonating Echoes</span> upon using <span class="Highlight">Basic Attack</span> button.<br>Launch attacks forward, dealing <span class="Light">Spectro DMG</span>, considered as Resonance Skill DMG.<br> <br><span class="Title">Diminutive Sound</span><br>Rover can hold up to 100 "Diminutive Sounds".<br>Rover obtains "Diminutive Sound" for every Normal Attack <span class="Highlight">Vibration Manifestation</span> on hit.<br>Rover obtains "Diminutive Sound" for every Heavy Attack <span class="Highlight"> Aftertune</span> on hit.<br>Rover obtains "Diminutive Sound" upon casting Intro Skill <span class="Highlight">Waveshock</span>.</div>`,
  attacks: [
    {
      key: "ResonatingSpinDMG",
      label: "Resonating Spin DMG",
      talents: {
        "1": "64.93%*2",
        "2": "70.25%*2",
        "3": "75.58%*2",
        "4": "83.03%*2",
        "5": "88.35%*2",
        "6": "94.48%*2",
        "7": "103.00%*2",
        "8": "111.51%*2",
        "9": "120.03%*2",
        "10": "129.08%*2",
      },
      type: "Skill",
    },
    {
      key: "ResonatingWhirlDMG",
      label: "Resonating Whirl DMG",
      talents: {
        "1": "20.00%",
        "2": "21.64%",
        "3": "23.28%",
        "4": "25.58%",
        "5": "27.22%",
        "6": "29.11%",
        "7": "31.73%",
        "8": "34.35%",
        "9": "36.98%",
        "10": "39.77%",
      },
      type: "Skill",
    },
    {
      key: "ResonatingEchoesStage1DMG",
      label: "Resonating Echoes Stage 1 DMG",
      talents: {
        "1": "40.00%",
        "2": "43.28%",
        "3": "46.56%",
        "4": "51.16%",
        "5": "54.44%",
        "6": "58.21%",
        "7": "63.46%",
        "8": "68.70%",
        "9": "73.95%",
        "10": "79.53%",
      },
      type: "Skill",
    },
    {
      key: "ResonatingEchoesStage2DMG",
      label: "Resonating Echoes Stage 2 DMG",
      talents: {
        "1": "80.00%",
        "2": "86.56%",
        "3": "93.12%",
        "4": "102.31%",
        "5": "108.87%",
        "6": "116.41%",
        "7": "126.91%",
        "8": "137.40%",
        "9": "147.90%",
        "10": "159.05%",
      },
      type: "Skill",
    },
  ],
};
