export const buffs = [
  {
    key: `RingofChainsaw`,
    name: `Ring of Chainsaw`,
    details: `<div>Every 1 point of <span class="Highlight">Ring of Chainsaw</span> consumed by <span class="Highlight">Sawring - Blitz</span> and <span class="Highlight">Chainsaw Mode - Dodge Counter</span> increases the DMG Multiplier of the next <span class="Highlight">Sawring - Eradication</span>. Up to 100 points will be counted toward this effect.</ddiv>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "Talent",
        modifierTalentKey: "SawringEradicationDMG",
        modifierValue: {
          "1": 0.013,
          "2": 0.0142,
          "3": 0.0152,
          "4": 0.0167,
          "5": 0.0178,
          "6": 0.0189,
          "7": 0.0207,
          "8": 0.0224,
          "9": 0.0240,
          "10": 0.0259,
        },
        modifierValueTalentRef: "forte",
      },
    ],
    minStacks: 0,
    maxStacks: 100,
    alwaysEnabled: false,
  },
  {
    key: `WovenMyriadConvergence`,
    name: `Woven Myriad - Convergence`,
    details: `<span class="Title">Woven Myriad - Convergence</span><br>The DMG Multipliers of <span class="Highlight">Sawring - Blitz</span>, <span class="Highlight">Chainsaw Mode - Dodge Counter</span>, and <span class="Highlight">Sawring - Eradication</span> are increased by 120%. <br>The bonus DMG Multiplier for <span class="Highlight">Sawring - Eradication</span> granted by <span class="Highlight">Sawring- Blitz</span> and <span class="Highlight">Chainsaw Mode - Dodge Counter</span> when <span class="Highlight">Ring of Chainsaw</span> is consumed additionally increases by 120%.`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "SawringBlitzStage1DMG",
          "SawringBlitzStage2DMG",
          "SawringBlitzStage2HoldDMG",
          "SawringBlitzStage2DiscordanceDMG",
          "SawringBlitzStage3DMG",
          "SawringBlitzStage3HoldDMG",
          "SawringBlitzStage3FalltoneDMG",
          "SawringEradicationDMG",
          "ChainsawModeDodgeCounterDMG",
          "ChainsawModeDodgeCounterHoldDMG",
        ],
        modifierValue: 1.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `ThreadofBane`,
    name: `Thread of Bane`,
    details: `<div>When dealing damage to targets affected by <span class="Highlight">Unseen Snare</span>, ignore 18% of their DEF.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "DEFIgnore",
        modifierValue: 0.18,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillInescapableFate`,
    name: `Inherent Skill: Inescapable Fate`,
    details: `<div>When a Resonator in the team defeats a target marked by <span class="Highlight">Unseen Snare</span>, the Cooldown of Chisa's Resonance Skill <span class="Highlight">Eye of Unraveling</span> is reset, triggered up to once every 3s.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillAllEndsHere`,
    name: `Inherent Skill: All Ends Here`,
    details: `<div>Casting Intro Skill <span class="Highlight">Reverberance - Return</span> or Resonance Liberation <span class="Highlight">Moment of Nihility</span> grants 20% Havoc DMG Bonus and 20% Healing Bonus for 12s.<br>When Resonators in the team with <span class="Highlight"">Unseen Snare</span>, Chisa gains Sight of Unraveling, lasting 3s.<br>While in Sight of Unraveling, Chisa inflicts <span  class="Highlight">Thread of Bane</span> that lasts for 30s on the targets damaged by Resonators in the team with Thread of Bane.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "Havoc",
        modifierValue: 0.2,
      },
      {
        modifier: "HealingBonus",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate1",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate2",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate3",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate4",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK1",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK2",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK3",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK4",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
