export const forteCircuitAttacks = {
  name: "Forte Circuit: Chromaticity Modeling",
  description: `<div><size=40><span class="Title"><strong>Optical Sampling Stage</strong></span><br>Lynae is in <span class="Highlight"><strong>Optical Sampling Stage</strong></span> by default. While in this state, <span class="Highlight"><strong>Overflow</strong></span> recovers during certain skills.<br><size=10><br><size=40><span class="Title"><strong>Kaleidoscopic Parade</strong></span><br>Casting <span class="Highlight"><strong>Basic Attack - Spark Collision</strong></span> sends Lynae into <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span>. In this state, Lynae continuously recovers <span class="Highlight"><strong>Lumiflow</strong></span> while moving on the ground or casting certain skills. Lynae will not Walk during this state, and her Running and Sprinting will be replaced by the faster <span class="Highlight"><strong>Free Skating</strong></span> and <span class="Highlight"><strong>Speed Skating</strong></span>.<br><size=10><br><size=40><span class="Title"><strong>Basic Attack - Polychrome Leap</strong></span><br>While in <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span>, with at least 1/3 of the max <span class="Highlight"><strong>Lumiflow</strong></span>, Jump is replaced by <span class="Highlight"><strong>Basic Attack - Polychrome Leap</strong></span>.<br>Consume 1/3 of the max <span class="Highlight"><strong>Lumiflow</strong></span> to deal <span class="Light"><strong>Spectro DMG</strong></span>. Inflict <span class="Highlight"><strong>Photochromic Flux</strong></span> on targets hit. Successful Dodges can be triggered within a certain time after casting this skill. While airborne, <span class="Highlight"><strong>Basic Attack - Polychrome Leap</strong></span> chains up to 3 stages. Switching to another Resonator resets the combo.<br>While in combat, each stage of <span class="Highlight"><strong>Basic Attack - Polychrome Leap</strong></span> cast recovers 1 point of <span class="Highlight"><strong>True Color</strong></span>.<br>Within a certain time after <span class="Highlight"><strong>Basic Attack - Polychrome Leap Stage 1</strong></span> press Normal Attack on the ground to cast <span class="Highlight"><strong>Kaleidoscopic Parade - Basic Attack Stage 2</strong></span>.<br>Casting <span class="Highlight"><strong>Basic Attack - Polychrome Leap Stage 2</strong></span> also pulls in nearby targets.<br><size=10><br><size=40><span class="Title"><strong>Basic Attack - Iridescent Splash</strong></span><br>During <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span>, when Lynae is in mid-air, holding 3 points of <span class="Highlight"><strong>True Color</strong></span>, if <span class="Highlight"><strong>Basic Attack - Visual Impact</strong></span> is on cooldown, press Normal Attack or Resonance Skill to deal <span class="Light"><strong>Spectro DMG</strong></span>, and inflict <span class="Highlight"><strong>Photochromic Flux</strong></span> on targets hit.<br>This skill consumes 3 points of <span class="Highlight"><strong>True Color</strong></span>.<br>Press Normal Attack within a certain time after this skill to cast <span class="Highlight"><strong>Kaleidoscopic Parade - Basic Attack Stage 2</strong></span> <br><size=10><br><size=40><span class="Title"><strong>Basic Attack - Visual Impact</strong></span><br>During <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span>, when Lynae is in mid-air, holding 3 points of <span class="Highlight"><strong>True Color</strong></span>, if this skill is not on cooldown, press Normal Attack or Resonance Skill to deal <span class="Light"><strong>Spectro DMG</strong></span>,  inflicting <span class="Highlight"><strong>Photochromic Flux</strong></span> on targets hit.<br>This skill consumes 3 points of <span class="Highlight"><strong>True Color</strong></span> and grants all nearby Resonators in the team 40 points of Tune Break Boost for 30s.<br>Press Normal Attack within a certain time after this skill to cast <span class="Highlight"><strong>Kaleidoscopic Parade - Basic Attack Stage 2</strong></span> <br><size=10><br><size=40><span class="Title"><strong>Resonance Mode</strong></span><br>Inflict <span class="Highlight"><strong>Photochromic Flux</strong></span> when hitting a target with <span class="Highlight"><strong>Basic Attack - Polychrome Leap</strong></span>, <span class="Highlight"><strong>Basic Attack - Iridescent Splash</strong></span>, <span class="Highlight"><strong>Basic Attack - Visual Impact</strong></span> and <span class="Highlight"><strong>Intro Skill - Time to Show Some Colors!</strong></span>.<br>Lynae can switch between <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span> and <span class="Highlight"><strong>Resonance Mode - Tune Strain</strong></span>:<br>- When in <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>, <span class="Highlight"><strong>Photochromic Flux</strong></span> inflicts <span class="Highlight"><strong>Tune Rupture - Shifting</strong></span> on targets for 25s.<br>- When in <span class="Highlight"><strong>Resonance Mode - Tune Strain</strong></span>, <span class="Highlight"><strong>Photochromic Flux</strong></span> inflicts <span class="Highlight"><strong>Tune Strain - Shifting</strong></span> on targets for 25s.<br><size=10><br><size=40><span class="Title"><strong>Tune Rupture Response - Spectral Analysis</strong></span><br>Deal an instance of <span class="Light"><strong>Spectro DMG</strong></span>, considered Tune Rupture DMG, to targets within range affected by <span class="Highlight"><strong>Tune Rupture - Interfered</strong></span>.<br><size=10><br><size=40><span class="Title"><strong>Overflow</strong></span><br>Lynae can hold up to 120 points of Overflow.<br>While in <span class="Highlight"><strong>Optical Sampling Stage</strong></span>, <span class="Highlight"><strong>Overflow</strong></span> recovers during Basic Attack, Lynae-Style Palettes, Mid-air Attack, and Dodge Counter.<br>When <span class="Highlight"><strong>Overflow</strong></span> is full, <span class="Highlight"><strong>Basic Attack - Spark Collision</strong></span> becomes available.<br>Exiting <span class="Highlight"><strong>Optical Sampling Stage</strong></span> removes all <span class="Highlight"><strong>Overflow</strong></span>.<br><size=10><br><size=40><span class="Title"><strong>Lumiflow</strong></span><br>Lynae can hold up to 120 points of Lumiflow.<br>During <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span>:<br>- Restore 20% of <span class="Highlight"><strong>Lumiflow</strong></span> per second when Lynae is moving on the ground/climbing, or performs a successful Dodge on the ground, or casts <span class="Highlight"><strong>Kaleidoscopic Parade - Basic Attack</strong></span>, <span class="Highlight"><strong>Kaleidoscopic Parade - Ground Heavy Attack</strong></span>, <span class="Highlight"><strong>Kaleidoscopic Parade - Mid-air Heavy Attack</strong></span>, <span class="Highlight"><strong>Kaleidoscopic Parade - Dodge Counter</strong></span>, <span class="Highlight"><strong>Additive Color</strong></span>, ground Dodge, Intro Skill, or <span class="Highlight"><strong>Basic Attack - To a Vivid Tomorrow!</strong></span>.<br>- <span class="Highlight"><strong>Lumiflow</strong></span> starts to deplete by 20% per second while Lynae is staying still on the ground/climbing/swimming or off the field, or after a certain time after the skills listed above are cast.<br>- <span class="Highlight"><strong>Lumiflow</strong></span> does not change while Lynae is not in any of the states described above.<br>Exiting <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span> removes all <span class="Highlight"><strong>Lumiflow</strong></span>.<br>With 120 points of <span class="Highlight"><strong>Lumiflow</strong></span>, Lynae's roller skating <span class="Highlight"><strong>speed further increases</strong></span> at the cost of STA over time.<br><size=10><br><size=40><span class="Title"><strong>True Color</strong></span><br>Lynae can hold up to 3 points of True Color.<br>During combat, each time <span class="Highlight"><strong>Basic Attack - Polychrome Leap</strong></span> is cast, gain 1 point of <span class="Highlight"><strong>True Color</strong></span>. With 3 points of <span class="Highlight"><strong>True Color</strong></span>, <span class="Highlight"><strong>Basic Attack - Iridescent Splash</strong></span> and <span class="Highlight"><strong>Basic Attack - Visual Impact</strong></span> become available.<br>Exiting <span class="Highlight"><strong>Kaleidoscopic Parade</strong></span> removes all <span class="Highlight"><strong>True Color</strong></span>.</size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></size=10></size=40></div>`,
  attacks: [
    {
      key: "BasicAttackIridescentSplashDMG",
      label: "Basic Attack - Iridescent Splash DMG",
      type: "Basic",
      talents: {
        "1": "153.00%",
        "2": "165.55%",
        "3": "178.10%",
        "4": "195.66%",
        "5": "208.21%",
        "6": "222.64%",
        "7": "242.71%",
        "8": "262.78%",
        "9": "282.86%",
        "10": "304.18%",
      },
    },
    {
      key: "BasicAttackVisualImpactDMG",
      label: "Basic Attack - Visual Impact DMG",
      type: "Basic",
      talents: {
        "1": "612.00%",
        "2": "662.19%",
        "3": "712.37%",
        "4": "782.63%",
        "5": "832.81%",
        "6": "890.53%",
        "7": "970.82%",
        "8": "1051.11%",
        "9": "1131.41%",
        "10": "1216.72%",
      },
    },
    {
      key: "BasicAttackPolychromeLeap1",
      label: "Basic Attack - Polychrome Leap 1",
      type: "Basic",
      talents: {
        "1": "17.00%*3",
        "2": "18.40%*3",
        "3": "19.79%*3",
        "4": "21.74%*3",
        "5": "23.14%*3",
        "6": "24.74%*3",
        "7": "26.97%*3",
        "8": "29.20%*3",
        "9": "31.43%*3",
        "10": "33.80%*3",
      },
    },
    {
      key: "BasicAttackPolychromeLeap2",
      label: "Basic Attack - Polychrome Leap 2",
      type: "Basic",
      talents: {
        "1": "8.50%*6",
        "2": "9.20%*6",
        "3": "9.90%*6",
        "4": "10.87%*6",
        "5": "11.57%*6",
        "6": "12.37%*6",
        "7": "13.49%*6",
        "8": "14.60%*6",
        "9": "15.72%*6",
        "10": "16.90%*6",
      },
    },
    {
      key: "BasicAttackPolychromeLeap3",
      label: "Basic Attack - Polychrome Leap 3",
      type: "Basic",
      talents: {
        "1": "6.59%*8",
        "2": "7.13%*8",
        "3": "7.67%*8",
        "4": "8.43%*8",
        "5": "8.97%*8",
        "6": "9.59%*8",
        "7": "10.45%*8",
        "8": "11.32%*8",
        "9": "12.18%*8",
        "10": "13.10%*8",
      },
    },
    {
      key: "TuneRuptureResponseSpectralAnalysisDMG",
      label: "Tune Rupture Response - Spectral Analysis DMG",
      type: "TuneBreak",
      talents: {
        "1": "946.00%",
        "2": "1023.58%",
        "3": "1101.15%",
        "4": "1209.75%",
        "5": "1287.32%",
        "6": "1376.53%",
        "7": "1500.64%",
        "8": "1624.76%",
        "9": "1748.88%",
        "10": "1880.75%",
      },
    },
  ],
};
