export const rotations: RotationPreset[] = [
  {
    name: `Kashi69h was here :p`,
    description: ``,
    author: `Kashi69h`,
    data: {
      name: "Kashi69h was here :p",
      description: "",
      actions: [
        {
          order: 1,
          key: "TimetoShowSomeColorsDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "PrismaticOverblastDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "LynaeStylePalettesDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "BasicAttackSparkCollisionLv1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "BasicAttackSparkCollisionLv2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "BasicAttackSparkCollisionLv3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "BasicAttackPolychromeLeap1",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "BasicAttackPolychromeLeap2",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "BasicAttackPolychromeLeap3",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "BasicAttackVisualImpactDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "LetsHittheRoadDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "TuneRuptureResponseSpectralAnalysisDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
      echo: "ImpermanenceHeron",
    },
  },
];

export const echoes = [];
