export const buffs = [
  {
    key: "InherentSkillSeedbed",
    name: "Inherent Skill: Seedbed",
    details: `<div class="skilldescription">Gain 15% Havoc DMG Bonus. DMG dealt by Heavy Attack <span class="Highlight">Pruning</span> is now considered Basic Attack DMG.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "Havoc",
        modifierValue: 0.15,
      },
      {
        modifier: "talentTypeOverride",
        modifySpecificTalents: ["HeavyAttackDMG"],
        modifierValue: "Basic",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "InherentSkillEpiphyte",
    name: "Inherent Skill: Epiphyte",
    details: `<div class="skilldescription">Gain 15% Basic DMG Bonus. Gain increased resistance to interruption when casting <span class="Highlight">Basic Attack</span>, Basic Attack <span class="Highlight">Vining Waltz</span>, and Basic Attack <span class="Highlight">Blazing Waltz</span>.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.15,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SweetDreamMultiplier",
    name: "Sweet Dream",
    details: `<div class="skilldescription"><span class="Highlight">Sweet Dream</span>: Increase the DMG Multiplier of <span class="Highlight">Normal Attack</span>, Basic Attack <span class="Highlight">Vining Waltz</span>, Basic Attack <span class="Highlight">Blazing Waltz</span>, Basic Attack <span class="Highlight">Vining Ronde</span>, Dodge Counter <span class="Highlight">Atonement</span>, Resonance Skill <span class="Highlight">Crimson Blossom</span>, and Resonance Skill <span class="Highlight">Floral Ravage</span> by 50%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "BasicAttack1DMG",
          "BasicAttack2DMG",
          "BasicAttack3DMG",
          "BasicAttack4DMG",
          "BasicAttack5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "ViningWaltz1DMG",
          "ViningWaltz2DMG",
          "ViningWaltz3DMG",
          "ViningWaltz4DMG",
          "ViningRondeDMG",
          "BlazingWaltzDMG",
          "AtonementDMG",
          "CrimsonBlossomDMG",
          "FloralRavageDMG",
        ],
        modifierValue: 0.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "SweetDreamEphemeralMultiplier",
    name: "Sweet Dream Ephemeral",
    details: `<div class="skilldescription">Casting <span class="Highlight">Ephemeral</span> consumes all Crimson Buds. Each Crimson Bud consumed additionally increases the DMG Multiplier of <span class="Highlight">Sweet Dream</span> by 5%, up to 50%. </div>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "BasicAttack1DMG",
          "BasicAttack2DMG",
          "BasicAttack3DMG",
          "BasicAttack4DMG",
          "BasicAttack5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "ViningWaltz1DMG",
          "ViningWaltz2DMG",
          "ViningWaltz3DMG",
          "ViningWaltz4DMG",
          "ViningRondeDMG",
          "BlazingWaltzDMG",
          "AtonementDMG",
          "CrimsonBlossomDMG",
          "FloralRavageDMG",
        ],
        modifierValue: 0.05,
      },
    ],
    minStacks: 0,
    maxStacks: 10,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG1",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 2.40%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.024,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG2",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 2.40%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.024,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG3",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 5.60%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.056,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG4",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 5.60%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.056,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK1",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK2",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK3",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK4",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
