export const forteCircuitAttacks = {
  name: "Forte Circuit: Vegetative Universe",
  description: `<div class="skilldescription">Hitting a target with <span class="Highlight">Normal Attack</span>, Basic Attack <span class="Highlight">Vining Waltz</span>, Basic Attack <span class="Highlight">Blazing Waltz</span>, Basic Attack <span class="Highlight">Vining Ronde</span>, Dodge Counter <span class="Highlight">Atonement </span>, Resonance Skill <span class="Highlight">Crimson Blossom</span>, and Resonance Skill <span class="Highlight">Floral Ravage</span> consumes Crimson Pistils. The Energy Regen Multiplier of this attack is increased by 150%.<br>Consuming 10 Crimson Pistils recovers 4 Concerto Energy and obtains <saptag=3>1 Crimson Bud. Each bud lasts for 15s, stacking up to 10 times.<br> <br><span class="Title">Forte Circuit: Ephemeral</span><br>When Concerto Energy is fully recovered, and <span class="Highlight">Ephemeral</span> is not on Cooldown, Resonance Skill is replaced with <span class="Highlight">Ephemeral</span>.<br>Casting <span class="Highlight">Ephemeral</span> consumes 70 Concerto Energy and deals <span class="Dark">Havoc DMG</span> to the targets. This damage is considered Basic Attack DMG.<br>Camellya enters <span class="Highlight">Budding Mode</span> after casting <span class="Highlight">Ephemeral</span>.<br>This can be cast in mid-air.<br> <br><span class="Title">Budding Mode</span><br>- <span class="Highlight">Sweet Dream</span>: Increase the DMG Multiplier of <span class="Highlight">Normal Attack</span>, Basic Attack <span class="Highlight">Vining Waltz</span>, Basic Attack <span class="Highlight">Blazing Waltz</span>, Basic Attack <span class="Highlight">Vining Ronde</span>, Dodge Counter <span class="Highlight">Atonement</span>, Resonance Skill <span class="Highlight">Crimson Blossom</span>, and Resonance Skill <span class="Highlight">Floral Ravage</span> by 50%.<br>- Casting <span class="Highlight">Ephemeral</span> consumes all Crimson Buds. Each Crimson Bud consumed additionally increases the DMG Multiplier of <span class="Highlight">Sweet Dream</span> by 5%, up to 50%. <br>- When in <span class="Highlight">Budding Mode</span>, Camellya cannot gain Crimson Buds.<br>- When in <span class="Highlight">Budding Mode</span>, the Energy Regen Multiplier of <span class="Highlight">Normal Attack</span>, Basic Attack <span class="Highlight">Vining Waltz</span>, Basic Attack <span class="Highlight">Blazing Waltz</span>, Basic Attack <span class="Highlight">Vining Ronde</span>, Dodge Counter <span class="Highlight">Atonement</span>, Resonance Skill <span class="Highlight">Crimson Blossom</span>, and Resonance Skill <span class="Highlight">Floral Ravage</span> is reduced to 0%.<br>- <span class="Highlight">Budding Mode</span> ends when Camellya is switched off the field.<br>- <span class="Highlight">Budding Mode</span> ends when all Crimson Pistils are consumed.<br> <br><span class="Title">Crimson Pistil</span><br>Camellya can hold up to 100 Crimson Pistils.<br>- Casting Intro Skill <span class="Highlight">Everblooming</span> recovers 100 Crimson Pistils.<br>- Activating Forte Circuit's <span class="Highlight">Ephemeral</span> recovers 100 Crimson Pistils.</saptag=3></div>`,
  attacks: [
    {
      key: "EphemeralDMG",
      label: "Ephemeral DMG",
      talents: {
        "1": "635.00%",
        "2": "687.07%",
        "3": "739.14%",
        "4": "812.04%",
        "5": "864.11%",
        "6": "923.99%",
        "7": "1007.31%",
        "8": "1090.62%",
        "9": "1173.93%",
        "10": "1262.45%",
      },
      type: "Basic",
    },
    {
      key: "SequenceNode6PerennialDMG",
      label: "S6 Perennial Flower",
      talents: {
        "1": "635.00%",
        "2": "687.07%",
        "3": "739.14%",
        "4": "812.04%",
        "5": "864.11%",
        "6": "923.99%",
        "7": "1007.31%",
        "8": "1090.62%",
        "9": "1173.93%",
        "10": "1262.45%",
      },
      type: "Basic",
      requiresResonanceChain: "SequenceNode6PerennialDMG",
    },
  ],
};
