export const resonanceChains = [
  {
    key: "S1OnASecretPathNoOneKnowsFlat",
    name: "Sequence Node 1: On a Secret Path No One Knows",
    details: `<span class="skilldescription">When casting <span class="Highlight">Intro Skill</span>, <span class="Highlight">Critical Damage</span> increases by <span class="Highlight">18%</span><br>Lasting for <span class="Highlight">18s</span>, can trigger once every <span class="Highlight">25s</span>
When casting <span class="Highlight">Intro Skill</span>, additionally restores 50 points of <span class="Dark">【Red Camellia·Pistil】</span>, can trigger once every <span class="Highlight">25s</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.18,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S1OnASecretPathNoOneKnowsStacks",
    name: "Sequence Node 1: On a Secret Path No One Knows",
    details: `<span class="skilldescription">For every remaining 1 point of <span class="Dark">【Red Camellia·Pistil】</span>, additionally increase the <span class="Highlight">Critical Damage</span> by <span class="Highlight">0.2%</span>, up to <span class="Highlight">10%</span>; Lasting for <span class="Highlight">18s</span>, can trigger once every <span class="Highlight">25s</span>.`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.002,
      },
    ],
    minStacks: 0,
    maxStacks: 50,
    alwaysEnabled: false,
  },
  {
    key: "S2CallingfortheFragranceoftheSilentFlower",
    name: "Sequence Node 2: Calling for the Fragrance of the Silent Flower",
    details: `<span class="skilldescription"><span class="Highlight">Resonance Skill Dayflower</span> damage multiplier increases by <span class="Highlight">120%</span>. <span class="Highlight">Heavy Attack</span> counts as <span class="Highlight">Basic Attack</span> damage.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["DayflowerDMG"],
        modifierValue: 1.2,
      },
      {
        modifier: "talentTypeOverride",
        modifySpecificTalents: ["HeavyAttackDMG"],
        modifierValue: "Basic",
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S3AThornisBetterThanaThousandFlowerSeedsLiberation",
    name: "Sequence Node 3: A Thorn is Better Than a Thousand Flower Seeds",
    details: `<span class="skilldescription"><span class="Highlight">Resonance Liberation</span> damage multiplier increases by <span class="Highlight">50%</span>.
    </span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["TheEmbersofYouthDMG"],
        modifierValue: 0.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S3AThornisBetterThanaThousandFlowerSeedsATK",
    name: "Sequence Node 3: A Thorn is Better Than a Thousand Flower Seeds",
    details: `<span class="skilldescription">During Bud state, Camellya’s attack power increases by <span class="Highlight">58%</span>.
    </span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifySpecificTalents: [
          "NormalAttackStage1DMG",
          "NormalAttackStage2DMG",
          "NormalAttackStage3DMG",
          "NormalAttackStage4DMG",
          "NormalAttackStage5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "VineDanceStage1DMG",
          "VineDanceStage2DMG",
          "VineDanceStage3DMG",
          "VineDanceStage4DMG",
          "AshenBlossomVineDanceDMG",
          "WhirlingDanceDMG",
          "AtonementDMG",
          "FullBloomDMG",
          "DarkPistilSeekerDMG",
          "TheEmbersofYouthDMG",
          "EntangleDMG",
          "EntangleDayflowerDMG",
        ],
        modifierValue: 0.58,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S4ItsRootsContinueIntoEternity",
    name: "Sequence Node 4: Its Roots Continue Into Eternity",
    details: `<span class="skilldescription">After casting <span class="Highlight">Intro Skill</span>, the Resonators in the team receive a <span class="Highlight">25%</span> increase in <span class="Highlight">Basic Attack</span> damage, lasting for <span class="Highlight">30s</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.25,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S5PuttheInfiniteinthePalmofYourHand",
    name: "Sequence Node 5: Put the Infinite in the Palm of Your Hand",
    details: `<span class="skilldescription"><span class="Highlight">Intro Skill</span> damage multiplier additionally increases by <span class="Highlight">303%</span>. <span class="Highlight">Outro Skill Entangle</span> damage multiplier increases by <span class="Highlight">68%</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["EightThousandYearsDMG"],
        modifierValue: 3.03,
      },
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["EntangleDMG", "EntangleDayflowerDMG"],
        modifierValue: 0.68,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S6Blooming orYouThousandsofTimesDeepSlumberBuff",
    name: "Sequence Node 6: Blooming for You Thousands of Times",
    details: `<span class="skilldescription"><span class="Highlight">Resonance Circuit Deep Slumber</span> damage multiplier additionally increases by <span class="Highlight">150%</span>;<br>
<span class="Highlight">Resonance Circuit Eternal Flower</span>: Within <span class="Highlight">15s</span> after casting <span class="Highlight">Resonance Circuit Dayflower</span>, if Concerto Energy is fully filled, <span class="Highlight">Eternal Flower</span> can be casted, consuming <span class="Highlight">50</span> Concerto points, restoring <span class="Highlight">50</span> points of <span class="Dark">【Red Camellia·Pistil】</span>, can be casted once every <span class="Highlight">25s</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "NormalAttackStage1DMG",
          "NormalAttackStage2DMG",
          "NormalAttackStage3DMG",
          "NormalAttackStage4DMG",
          "NormalAttackStage5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "VineDanceStage1DMG",
          "VineDanceStage2DMG",
          "VineDanceStage3DMG",
          "VineDanceStage4DMG",
          "WhirlingDanceDMG",
          "AshenBlossomVineDanceDMG",
          "AtonementDMG",
          "FullBloomDMG",
          "DarkPistilSeekerDMG",
        ],
        modifierValue: 1.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S6Blooming orYouThousandsofTimesDeepSlumberEternalFlowerBuff",
    name: "Sequence Node 6: Blooming for You Thousands of Times",
    details: `<span class="skilldescription">After casting <span class="Highlight">Eternal Flower</span>, enters the Bud state, removing all <span class="Highlight">Red Camellia·Bud</span>, then increases <span class="Highlight">Resonance Circuit Deep Slumber’s</span> damage multiplier to <span class="Highlight">250%</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "NormalAttackStage1DMG",
          "NormalAttackStage2DMG",
          "NormalAttackStage3DMG",
          "NormalAttackStage4DMG",
          "NormalAttackStage5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "VineDanceStage1DMG",
          "VineDanceStage2DMG",
          "VineDanceStage3DMG",
          "VineDanceStage4DMG",
          "WhirlingDanceDMG",
          "AshenBlossomVineDanceDMG",
          "AtonementDMG",
          "FullBloomDMG",
          "DarkPistilSeekerDMG",
        ],
        modifierValue: 2.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
