export const resonanceChains = [
  {
    key: "S1SomewhereNoOneTravelled",
    name: "Sequence Node 1: Somewhere No One Travelled",
    details: `<span class="skilldescription">Casting Intro Skill <span class="Highlight">Everblooming</span> increases Camellya's Crit. DMG by 28% for 18s. This effect can be triggered once every 25s.<br>Immune to interruptions while casting <span class="Highlight">Ephemeral</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.28,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S2CallingUpontheSilentRose",
    name: "Sequence Node 2: Calling Upon the Silent Rose",
    details: `<span class="skilldescription">The DMG Multiplier of Resonance Skill <span class="Highlight">Ephemeral</span> is increased by 120%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["EphemeralDMG", "SequenceNode6PerennialDMG"],
        modifierValue: 1.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S3ABudAdornedbyThornsDMG",
    name: "Sequence Node 3: A Bud Adorned by Thorns",
    details: `<span class="skilldescription">The DMG Multiplier of Resonance Liberation <span class="Highlight">Fervor Efflorescent</span> is increased by 50%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["FervorEfflorescentDMG"],
        modifierValue: 0.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S3ABudAdornedbyThornsATK",
    name: "Sequence Node 3: A Bud Adorned by Thorns",
    details: `<span class="skilldescription">When in <span class="Highlight">Budding Mode</span>, Camellya's ATK is increased by 58%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifySpecificTalents: [
          "BasicAttack1DMG",
          "BasicAttack2DMG",
          "BasicAttack3DMG",
          "BasicAttack4DMG",
          "BasicAttack5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "ViningWaltz1DMG",
          "ViningWaltz2DMG",
          "ViningWaltz3DMG",
          "ViningWaltz4DMG",
          "BlazingWaltzDMG",
          "ViningRondeDMG",
          "AtonementDMG",
          "CrimsonBlossomDMG",
          "FloralRavageDMG",
          "FervorEfflorescentDMG",
          "TwiningDMG",
          "TwiningEphemeralDMG",
          "EphemeralDMG",
          "SequenceNode6PerennialDMG",
        ],
        modifierValue: 0.58,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S4RootsSetDeepInEternity",
    name: "Sequence Node 4: Roots Set Deep In Eternity",
    details: `<span class="skilldescription">Casting <span class="Highlight">Everblooming</span> gives all team members 25% Basic Attack DMG Bonus for 30s.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "BasicAttackDMGBonus",
        modifierValue: 0.25,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S5InfinityHeldinYourPalm",
    name: "Sequence Node 5: Infinity Held in Your Palm",
    details: `<span class="skilldescription">The DMG Multipliers of Outro Skill <span class="Highlight">Everblooming</span> is increased by 303% and Intro Skill <span class="Highlight">Twining</span> is increased by 68%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["EverbloomingDMG"],
        modifierValue: 3.03,
      },
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: ["TwiningDMG", "TwiningEphemeralDMG"],
        modifierValue: 0.68,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S6BBloomForYouThousandTimesOverDeepSlumberBuff",
    name: "Sequence Node 6: Bloom For You Thousand Times Over",
    details: `<span class="skilldescription">The DMG Multiplier of Forte Circuit's <span class="Highlight">Sweet Dream</span> is additionally increased by 150%. <br>Forte Circuit <span class="Highlight">Perennial</span>: Within 15s after casting <span class="Highlight">Ephemeral</span>, if Concerto Energy is full and <span class="Highlight">Perennial</span> is not on cooldown, Resonance Skill is replaced with <span class="Highlight">Perennial</span>.<br>Casting <span class="Highlight">Perennial</span> consumes 50 Concerto Energy and recovers 50 Crimson Pistils, dealing <span class="Dark">Havoc DMG</span> equal to 100% of <span class="Highlight">Ephemeral</span> DMG, considered Basic Attack DMG. This skill can be cast once every 25s.<br>Immune to interruptions when casting <span class="Highlight">Perennial</span>.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "BasicAttack1DMG",
          "BasicAttack2DMG",
          "BasicAttack3DMG",
          "BasicAttack4DMG",
          "BasicAttack5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "ViningWaltz1DMG",
          "ViningWaltz2DMG",
          "ViningWaltz3DMG",
          "ViningWaltz4DMG",
          "ViningRondeDMG",
          "BlazingWaltzDMG",
          "AtonementDMG",
          "CrimsonBlossomDMG",
          "FloralRavageDMG",
        ],
        modifierValue: 1.5,
      },
      {
        modifier: "EnableAttack",
        modifierValue: [
          "SequenceNode6PerennialDMG",
        ],
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "S6Blooming orYouThousandsofTimesDeepSlumberEternalFlowerBuff",
    name: "Sequence Node 6: Blooming for You Thousands of Times",
    details: `<span class="skilldescription">Camellya enters <span class="Highlight">Budding Mode</span> after casting <span class="Highlight">Perennial</span> and removes all Crimson Buds. The bonus DMG Multiplier granted by Forte Circuit's <span class="Highlight">Sweet Dream</span> is increased to 250%.</span>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiplySetValue",
        modifySpecificTalents: [
          "BasicAttack1DMG",
          "BasicAttack2DMG",
          "BasicAttack3DMG",
          "BasicAttack4DMG",
          "BasicAttack5DMG",
          "MidAirAttackDMG",
          "DodgeCounterDMG",
          "ViningWaltz1DMG",
          "ViningWaltz2DMG",
          "ViningWaltz3DMG",
          "ViningWaltz4DMG",
          "ViningRondeDMG",
          "BlazingWaltzDMG",
          "AtonementDMG",
          "CrimsonBlossomDMG",
          "FloralRavageDMG",
        ],
        modifierValue: 2.5,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
