export const skillAttacks = {
  name: "Resonance Skill: Valse of Bloom and Blight",
  description: `<div class="skilldescription"><span class="Title">Crimson Blossom</span><br>Attack the target, dealing <span class="Dark">Havoc DMG</span> (considered Basic Attack DMG), then enter <span class="Highlight">Blossom Mode</span>.<br>This attack can be performed in mid-air.<br> <br><span class="Title">Blossom Mode</span><br>- Unable to move while suspended on vines.<br>- <span class="Highlight">Basic Attack</span> and Heavy Attack <span class="Highlight">Pruning</span> are replaced by Basic Attack <span class="Highlight">Vining Waltz</span>: chain together 4 consecutive attacks, dealing <span class="Dark">Havoc DMG</span>, considered Basic Attack DMG.<br>- When performing <span class="Highlight">Vining Waltz Stage 3</span>, hold <span class="Highlight">Normal Attack Button</span> to cast <span class="Highlight">Blazing Waltz</span> that deals <span class="Dark">Havoc DMG</span> before automatically performing <span class="Highlight">Vining Waltz Stage 4</span>.<br>- <span class="Highlight">Dodge Counter</span> is replaced by Dodge Counter <span class="Highlight">Atonement</span>. Press <span class="Highlight">Normal Attack Button</span> right after a successful <span class="Highlight">Dodge</span> to attack the target, dealing <span class="Dark">Havoc DMG</span>, considered Basic Attack DMG.<br>- Resonance Skill is replaced by Resonance Skill <span class="Highlight">Floral Ravage</span>. Casting <span class="Highlight">Floral Ravage</span> deals <span class="Dark">Havoc DMG</span>, considered Basic Attack DMG.<br>- Resonance Skill <span class="Highlight">Floral Ravage</span> can be cast in mid-air.<br>- <span class="Highlight">Blossom Mode</span> ends after casting Resonance Skill <span class="Highlight">Floral Ravage</span>.<br>- <span class="Highlight">Blossom Mode</span> ends after using the <span class="Highlight">Levitator</span>.<br>- Jump is replaced with Basic Attack <span class="Highlight">Vining Ronde</span>. Press Jump to attack the target at the cost of STA, dealing <span class="Dark">Havoc DMG</span> (considered Basic Attack DMG). This ends the <span class="Highlight">Blossom Mode</span>.<br>- Using Basic Attack <span class="Highlight">Vining Waltz</span> and Basic Attack <span class="Highlight">Blazing Waltz</span> in mid-air consumes STA.<br>- Casting Resonance Skill <span class="Highlight">Floral Ravage</span> doesn't restore STA.<br>- Consume STA continuously to stay suspended on the vines.</div>`,
  attacks: [
    {
      key: "CrimsonBlossomDMG",
      label: "Crimson Blossom DMG",
      talents: {
        "1": "57.15%*2",
        "2": "61.84%*2",
        "3": "66.53%*2",
        "4": "73.09%*2",
        "5": "77.77%*2",
        "6": "83.16%*2",
        "7": "90.66%*2",
        "8": "98.16%*2",
        "9": "105.66%*2",
        "10": "113.62%*2",
      },
      type: "Basic",
    },
    {
      key: "ViningWaltz1DMG",
      label: "Vining Waltz 1 DMG",
      talents: {
        "1": "48.45%",
        "2": "52.43%",
        "3": "56.40%",
        "4": "61.96%",
        "5": "65.94%",
        "6": "70.50%",
        "7": "76.86%",
        "8": "83.22%",
        "9": "89.57%",
        "10": "96.33%",
      },
      type: "Basic",
    },
    {
      key: "ViningWaltz2DMG",
      label: "Vining Waltz 2 DMG",
      talents: {
        "1": "22.95%*2",
        "2": "24.84%*2",
        "3": "26.72%*2",
        "4": "29.35%*2",
        "5": "31.24%*2",
        "6": "33.40%*2",
        "7": "36.41%*2",
        "8": "39.42%*2",
        "9": "42.43%*2",
        "10": "45.63%*2",
      },
      type: "Basic",
    },
    {
      key: "ViningWaltz3DMG",
      label: "Vining Waltz 3 DMG",
      talents: {
        "1": "11.04%*6",
        "2": "11.95%*6",
        "3": "12.86%*6",
        "4": "14.12%*6",
        "5": "15.03%*6",
        "6": "16.07%*6",
        "7": "17.52%*6",
        "8": "18.97%*6",
        "9": "20.41%*6",
        "10": "21.95%*6",
      },
      type: "Basic",
    },
    {
      key: "ViningWaltz4DMG",
      label: "Vining Waltz 4 DMG",
      talents: {
        "1": "34.00%*3",
        "2": "36.79%*3",
        "3": "39.58%*3",
        "4": "43.48%*3",
        "5": "46.27%*3",
        "6": "49.47%*3",
        "7": "53.93%*3",
        "8": "58.39%*3",
        "9": "62.85%*3",
        "10": "67.59%*3",
      },
      type: "Basic",
    },
    {
      key: "BlazingWaltzDMG",
      label: "Blazing Waltz DMG",
      talents: {
        "1": "11.04%*19",
        "2": "11.95%*19",
        "3": "12.86%*19",
        "4": "14.12%*19",
        "5": "15.03%*19",
        "6": "16.07%*19",
        "7": "17.52%*19",
        "8": "18.97%*19",
        "9": "20.41%*19",
        "10": "21.95%*19",
      },
      type: "Basic",
    },
    {
      key: "FloralRavageDMG",
      label: "Floral Ravage DMG",
      talents: {
        "1": "26.46%*5",
        "2": "28.63%*5",
        "3": "30.80%*5",
        "4": "33.84%*5",
        "5": "36.01%*5",
        "6": "38.51%*5",
        "7": "41.98%*5",
        "8": "45.45%*5",
        "9": "48.92%*5",
        "10": "52.61%*5",
      },
      type: "Basic",
    },
    {
      key: "ViningRondeDMG",
      label: "Vining Ronde DMG",
      talents: {
        "1": "26.64%*3",
        "2": "28.82%*3",
        "3": "31.00%*3",
        "4": "34.06%*3",
        "5": "36.24%*3",
        "6": "38.76%*3",
        "7": "42.25%*3",
        "8": "45.74%*3",
        "9": "49.24%*3",
        "10": "52.95%*3",
      },
      type: "Basic",
    },
    {
      key: "AtonementDMG",
      label: "Atonement DMG",
      talents: {
        "1": "57.00%*2",
        "2": "61.68%*2",
        "3": "66.35%*2",
        "4": "72.90%*2",
        "5": "77.57%*2",
        "6": "82.95%*2",
        "7": "90.42%*2",
        "8": "97.90%*2",
        "9": "105.38%*2",
        "10": "113.33%*2",
      },
      type: "Basic",
    },
  ],
};
