export const basicAttacks = {
  name: "Normal Attack: Origin Calculus",
  description: `<div class="skilldescription"><span class="Title">Basic Attack</span><br>Perform up to 4 consecutive attacks, dealing <span class="Light">Spectro DMG</span>. When the attack hits a target, generate one <span class="Highlight">Collapsed Core</span>.<br> <br><span class="Title">Heavy Attack</span><br>Hold the <span class="Highlight">Normal Attack Button</span> at the cost of STA and enter <span class="Highlight">Release Form</span>, which enables the Shorekeeper to<br>   Accumulate a segment of <span class="Highlight">Speculative Data</span> every second;<br>   Automatically collect plant collectibles within a certain range.<br>Tap the <span class="Highlight">Normal Attack Button</span> or use up all STA to end <span class="Highlight">Release Form</span> while dealing <span class="Light">Spectro DMG</span> to the target. Meanwhile, every accumulated <span class="Highlight">Speculative Data</span> segment transforms into [Actual Data] segment with one <span class="Highlight">Collapsed Core</span>.<br> <br><span class="Title">Mid-air Attack</span><br>Consume STA to perform a Plunging Attack. When the attack hits a target, generate one <span class="Highlight">Collapsed Core</span>. Tap the <span class="Highlight">Normal Attack Button</span> within a certain range of time to perform <span class="Highlight">Basic Attack Stage 2</span>.<br> <br><span class="Title">Dodge Counter</span><br>Tap the <span class="Highlight">Normal Attack Button</span> after a successful Dodge to attack a target, dealing <span class="Light">Spectro DMG</span>.</div>`,
  attacks: [
    {
      key: "OriginCalculusStage1DMG",
      label: "Stage 1 DMG",
      talents: {
        "1": "15.99%",
        "2": "17.30%",
        "3": "18.61%",
        "4": "20.45%",
        "5": "21.76%",
        "6": "23.26%",
        "7": "25.36%",
        "8": "27.46%",
        "9": "29.55%",
        "10": "31.78%",
      },
      type: "Basic",
    },
    {
      key: "OriginCalculusStage2DMG",
      label: "Stage 2 DMG",
      talents: {
        "1": "12.00%*2",
        "2": "12.99%*2",
        "3": "13.97%*2",
        "4": "15.35%*2",
        "5": "16.33%*2",
        "6": "17.47%*2",
        "7": "19.04%*2",
        "8": "20.61%*2",
        "9": "22.19%*2",
        "10": "23.86%*2",
      },
      type: "Basic",
    },
    {
      key: "OriginCalculusStage3DMG",
      label: "Stage 3 DMG",
      talents: {
        "1": "11.73%*3",
        "2": "12.69%*3",
        "3": "13.66%*3",
        "4": "15.00%*3",
        "5": "15.96%*3",
        "6": "17.07%*3",
        "7": "18.61%*3",
        "8": "20.15%*3",
        "9": "21.69%*3",
        "10": "23.32%*3",
      },
      type: "Basic",
    },
    {
      key: "OriginCalculusStage4DMG",
      label: "Stage 4 DMG",
      talents: {
        "1": "36.58%",
        "2": "39.58%",
        "3": "42.58%",
        "4": "46.78%",
        "5": "49.78%",
        "6": "53.23%",
        "7": "58.03%",
        "8": "62.82%",
        "9": "67.62%",
        "10": "72.72%",
      },
      type: "Basic",
    },
    {
      key: "OriginCalculusHeavyAttackDMG",
      label: "Heavy Attack DMG",
      talents: {
        "1": "23.04%",
        "2": "24.93%",
        "3": "26.82%",
        "4": "29.47%",
        "5": "31.36%",
        "6": "33.53%",
        "7": "36.55%",
        "8": "39.58%",
        "9": "42.60%",
        "10": "45.81%",
      },
      type: "Heavy",
    },
    {
      key: "OriginCalculusPlungingAttackDMG",
      label: "Plunging Attack DMG",
      talents: {
        "1": "37.20%",
        "2": "40.26%",
        "3": "43.31%",
        "4": "47.58%",
        "5": "50.63%",
        "6": "54.13%",
        "7": "59.02%",
        "8": "63.90%",
        "9": "68.78%",
        "10": "73.96%",
      },
      type: "Basic",
    },
    {
      key: "OriginCalculusDodgeCounterDMG",
      label: "Dodge Counter DMG",
      talents: {
        "1": "44.00%*3",
        "2": "47.61%*3",
        "3": "51.22%*3",
        "4": "56.27%*3",
        "5": "59.88%*3",
        "6": "64.03%*3",
        "7": "69.80%*3",
        "8": "75.57%*3",
        "9": "81.35%*3",
        "10": "87.48%*3",
      },
      type: "Basic",
    },
  ],
};
