export const forteCircuitAttacks = {
  name: "Forte Circuit: Astral Chord",
  description: `<div class="skilldescription"><span class="Title">Flare Star Butterfly</span><br>Hitting a target with a Normal Attack generates a <span class="Highlight">Collapsed Core</span>, which transforms into a <span class="Highlight">Flare Star Butterfly</span> after 6s. <span class="Highlight">Flare Star Butterflies</span> automatically track and attack a target, dealing <span class="Light">Spectro DMG</span>. If there are already 5 <span class="Highlight">Collapsed Cores</span>, Shorekeeper's next <span class="Highlight">Basic Attack</span> hit will instantly convert a <span class="Highlight">Collapsed Core</span> into a <span class="Highlight">Flare Star Butterfly</span>.<br> <br><span class="Title">Illation</span><br>When Shorekeeper has 5 segments of Empirical Data, casting <span class="Highlight">Heavy Attack</span> will consume all segments to pull in nearby targets, dealing <span class="Light">Spectro DMG</span>. Meanwhile, all generated <span class="Highlight">Collapsed Cores</span> will instantly transform into <span class="Highlight">Flare Star Butterflies</span>.<br> <br><span class="Title">Transmutation</span><br>When Shorekeeper has 5 segments of Empirical Data, casting <span class="Highlight">Mid-air Attack</span> will consume all segments to deal <span class="Light">Spectro DMG</span>. Meanwhile, all generated <span class="Highlight">Collapsed Cores</span> will instantly transform into <span class="Highlight">Flare Star Butterflies</span>. Quickly press the <span class="Highlight">Normal Attack Button</span> afterward to perform <span class="Highlight">Basic Attack Stage 2</span>.<br> <br><span class="Title">Empirical Data</span><br>Shorekeeper can hold up to 5 segments of Empirical Data.<br>- Obtain 1 segment of Empirical Data when <span class="Highlight">Basic Attack Stage 1, 2, or 4</span> hits a target.<br>- Obtain 2 segments of Empirical Data when <span class="Highlight">Basic Attack Stage 3</span> hits a target.<br>- Obtain 1 segment of Empirical Data when <span class="Highlight">Mid-air Attack</span> hits a target.<br>- Obtain 1 segment of Empirical Data when <span class="Highlight">Dodge Counter</span> hits a target.</div>`,
  attacks: [
    {
      key: "FlareStarButterflyDMG",
      label: "Flare Star Butterfly DMG",
      talents: {
        "1": "18.76%",
        "2": "20.29%",
        "3": "21.83%",
        "4": "23.99%",
        "5": "25.52%",
        "6": "27.29%",
        "7": "29.75%",
        "8": "32.21%",
        "9": "34.67%",
        "10": "37.29%",
      },
      type: "Basic",
    },
    {
      key: "DeductionDMG",
      label: "Deduction DMG",
      talents: {
        "1": "9.54%*5",
        "2": "10.33%*5",
        "3": "11.11%*5",
        "4": "12.20%*5",
        "5": "12.99%*5",
        "6": "13.89%*5",
        "7": "15.14%*5",
        "8": "16.39%*5",
        "9": "17.64%*5",
        "10": "18.97%*5",
      },
      type: "Heavy",
    },
    {
      key: "TransmutationDMG",
      label: "Transmutation DMG",
      talents: {
        "1": "37.20%",
        "2": "40.26%",
        "3": "43.31%",
        "4": "47.58%",
        "5": "50.63%",
        "6": "54.13%",
        "7": "59.02%",
        "8": "63.90%",
        "9": "68.78%",
        "10": "73.96%",
      },
      type: "Basic",
    },
    {
      key: "SequenceNode2NightsGiftandRefusal",
      label: "S2: Night's Gift and Refusal Healing",
      talents: {
        "1": "2.00%",
        "2": "2.00%",
        "3": "2.00%",
        "4": "2.00%",
        "5": "2.00%",
        "6": "2.00%",
        "7": "2.00%",
        "8": "2.00%",
        "9": "2.00%",
        "10": "2.00%",
      },
      type: "Healing",
      attribute: "hp",
      requiresResonanceChain: "SequenceNode2NightsGiftandRefusal",
    },
  ],
};
