export const introAttacks = {
  name: "Intro Skill: Proof of Existence",
  description: `<div class="skilldescription"><span class="Title">Enlightenment</span><br>Shorekeeper appears to restore HP for all nearby party members and summon 5 <span class="Highlight">Dim Star Butterflies</span>, which automatically track and attack a target, dealing <span class="Light">Spectro DMG</span>. This is considered Resonance Skill DMG.<br> <br><span class="Title">Discernment</span><br>When a <span class="Highlight">Supernal Stellarealm</span> is generated, Shorekeeper's first Intro Skill triggered in its duration will be replaced with Intro Skill <span class="Highlight">Discernment</span>.  Casting Discernment ends the current Stellarealm, restores HP for all nearby party members, and deals <span class="Light">Spectro DMG</span> to the targets. This attack is guaranteed to be a Critical Hit dealing Resonance Liberation DMG. The Intro Skill <span class="Highlight">Discernment</span> can only be triggered once each time a <span class="Highlight">Supernal Stellarealm</span> is generated.</div>`,
  attacks: [
    {
      key: "EnlightenmentDMG",
      label: "Enlightenment DMG",
      talents: {
        "1": "15.75%*5",
        "2": "17.04%*5",
        "3": "18.33%*5",
        "4": "20.14%*5",
        "5": "21.43%*5",
        "6": "22.91%*5",
        "7": "24.98%*5",
        "8": "27.05%*5",
        "9": "29.11%*5",
        "10": "31.31%*5",
      },
      type: "Skill",
    },
    {
      key: "DiscernmentDMG",
      label: "Discernment DMG",
      talents: {
        "1": "9.88%*3",
        "2": "10.69%*3",
        "3": "11.50%*3",
        "4": "12.64%*3",
        "5": "13.45%*3",
        "6": "14.38%*3",
        "7": "15.67%*3",
        "8": "16.97%*3",
        "9": "18.26%*3",
        "10": "19.64%*3",
      },
      type: "Liberation",
      attribute: "hp",
      alwaysCrit: true,
    },
    {
      key: "EnlightenmentHealing",
      label: "Enlightenment Healing",
      talents: {
        "1": "130 + 0.60%",
        "2": "141 + 0.65%",
        "3": "152 + 0.70%",
        "4": "167 + 0.77%",
        "5": "177 + 0.82%",
        "6": "190 + 0.88%",
        "7": "207 + 0.96%",
        "8": "224 + 1.04%",
        "9": "241 + 1.11%",
        "10": "259 + 1.20%",
      },
      type: "Healing",
      attribute: "hp",
    },
    {
      key: "DiscernmentHealing",
      label: "Discernment Healing",
      talents: {
        "1": "145 + 0.66%",
        "2": "157 + 0.72%",
        "3": "169 + 0.77%",
        "4": "186 + 0.85%",
        "5": "198 + 0.90%",
        "6": "211 + 0.97%",
        "7": "231 + 1.05%",
        "8": "250 + 1.14%",
        "9": "269 + 1.23%",
        "10": "289 + 1.32%",
      },
      type: "Healing",
      attribute: "hp",
    },
  ],
};
