export const rotations: RotationPreset[] = [
    {
        name: `TacticalKush was here :3`,
        description: `Standard rotation`,
        author: `TacticalKush`,
        data: {"name":"TacticalKush was here :3","description":"","actions":[{"order":1,"key":"DiscernmentDMG","type":"intro","count":1,"buffs":[]},{"order":2,"key":"DiscernmentHealing","type":"intro","count":1,"buffs":[]},{"order":3,"key":"OriginCalculusStage1DMG","type":"basic","count":1,"buffs":[]},{"order":4,"key":"OriginCalculusStage2DMG","type":"basic","count":"1","buffs":[]},{"order":5,"key":"OriginCalculusStage3DMG","type":"basic","count":"1","buffs":[]},{"order":6,"key":"OriginCalculusStage4DMG","type":"basic","count":"1","buffs":[]},{"order":7,"key":"FlareStarButterflyDMG","type":"forteCircuit","count":"1","buffs":[]},{"order":8,"key":"DeductionDMG","type":"forteCircuit","count":"1","buffs":[]},{"order":9,"key":"TransmutationDMG","type":"forteCircuit","count":1,"buffs":[]},{"order":10,"key":"DimStarButterflyDMG","type":"skill","count":1,"buffs":[]},{"order":11,"key":"ChaosTheoryHealing","type":"skill","count":1,"buffs":[]},{"order":12,"key":"EndLoopDMG","type":"liberation","count":1,"buffs":[]}]}
    },
    {
        name: `Healer Rotation`,
        description: `BA1234 → Forte (Heavy) → E → BA1234 → Forte (Heavy) → Q → R → Outro`,
        author: `Namelag`,
        data: {"name":"Healer Rotation","description":"BA1234 → Forte (Heavy) → E → BA1234 → Forte (Heavy) → Q → R → Outro","actions":[{"order":1,"key":"OriginCalculusStage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"OriginCalculusStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"OriginCalculusStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"OriginCalculusStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"DeductionDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"DimStarButterflyDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"ChaosTheoryHealing","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"OriginCalculusStage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"OriginCalculusStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"OriginCalculusStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"OriginCalculusStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"DeductionDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":13,"key":"EndLoopDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    }
];