export const forteCircuitAttacks = {
  name: "Forte Circuit: Ink and Wash",
  description: `<div class="skilldescription"><span class="Title">Spiritual Sketch</span><size><br>Up to 1 of each of <span class="Highlight">Spiritual Sketch: Left</span>, <span class="Highlight">Spiritual Sketch: Middle</span>, and <span class="Highlight">Spiritual Sketch: Right</span> can exist at the same time, each lasting for 15s.<br><br><span class="Title">Heavy Attack: Conjuration</span><br>The 5 moves below consume STA to perform <span class="Highlight">Conjuration</span> to attack the target, dealing <span class="Ice">Glacio DMG</span>.<br>-Hold the <span class="Highlight">Basic Attack button</span> shortly after <span class="Hightlight">Basic Attack Stage 3</span>;<br>-Press the <span class="Highlight">Basic Attack button</span> shortly after casting Resonance Skill <span class="Highlight">Manifestation</span>;<br>-Hold the <span class="Highlight">Basic Attack button</span> shortly after casting Resonance Skill <span class="Highlight">Stroke of Genius</span> or Resonance Skill <span class="Highlight">Creation's Zenith</span>;<br>-Hold the <span class="Highlight">Basic Attack button</span> while in mid-air; or<br>-Hold the <span class="Highlight">Basic Attack button</span> after a Dodge.<br>If Zhezhi has at least 30 "Afflatus" when performing any of these, consume 30 "Afflatus" to summon <span class="Highlight">Phantasmic Imprint: Middle</span><br><br><span class="Title">Resonance Skill: Stroke of Genius</span><br>When a <span class="Highlight">Phatasmic Imprint</span> is nearby, the Resonance Skill is replaced with <span class="Highlight">Stroke of Genius</span>. When it is cast, Zhezhi will:<br>-Blink to the location of the <span class="Highlight">Phatasmic Imprint</span> and remove it, then summon a crane spirit to attack the target, dealing <span class="Ice">Glacio DMG</span>, considered as Basic Attack DMG. Refresh the mid-air Dodge counter if the target <span class="Highlight">Phatasmic Imprint</span> is in mid-air.<br>-Gain 1 stack of "Painter's Delight", lasting for 8s and stacking up to 2 times.<br><br><span class="Title">Resonance Skill: Creation's Zenith</span><br>When a <span class="Highlight">Phantasmic Imprint</span> is nearby and there are 2 stacks of "Painter's Delight", <span class="Highlight">Stroke of Genius</span> is replaced with <span class="Highlight">Creation's Zenith</span>, which can be cast while in mid-air. When it is cast, Zhezhi will:<br>-Blink to the location of the <span class="Highlight">Phantasmic Imprint</span> and remove it, then summon a crane spirit to attack the target, dealing greater <span class="Ice">Glacio DMG</span>, considered as Basic Attack DMG, and additionally increasing the Basic Attack DMG Multiplier by 18% for 25s. Refresh the mid-air Dodge counter if the target <span class="Highlight">Phatasmic Imprint</span> is in mid-air.<br><br><span class="Title">"Afflatus"</span><br>Zhezhi can hold up to 90 "Afflatus".<br>Normal Attacks grant "Afflatus".<br>Intro Skill grants "Afflatus".</size></div>`,
  attacks: [
    {
      key: "CompositionDMG",
      label: "HA: Composition DMG",
      talents: {
        "1": "41.75%*3",
        "2": "45.18%*3",
        "3": "48.60%*3",
        "4": "53.39%*3",
        "5": "56.82%*3",
        "6": "60.76%*3",
        "7": "66.23%*3",
        "8": "71.71%*3",
        "9": "77.19%*3",
        "10": "83.01%*3",
      },
      type: "Heavy",
    },
    {
      key: "StrokeOfGeniusDMG",
      label: "Stroke of Genius DMG",
      talents: {
        "1": "150.00%",
        "2": "162.30%",
        "3": "174.60%",
        "4": "191.82%",
        "5": "204.12%",
        "6": "218.27%",
        "7": "237.95%",
        "8": "257.63%",
        "9": "277.31%",
        "10": "298.22%",
      },
      type: "Basic",
    },
    {
      key: "StrokeOfMaestroDMG",
      label: "Stroke of Maestro DMG",
      talents: {
        "1": "60.00%*3",
        "2": "64.92%*3",
        "3": "69.84%*3",
        "4": "76.73%*3",
        "5": "81.65%*3",
        "6": "87.31%*3",
        "7": "95.18%*3",
        "8": "103.05%*3",
        "9": "110.93%*3",
        "10": "119.29%*3",
      },
      type: "Basic",
    },
  ],
};
