export const skillAttacks = {
  name: "Resonance Skill: Depiction",
  description: `<div class="skilldescription"><span class="Title">Press</span><br>Deal <span class="Ice">Glacio DMG</span>. If "Afflatus" is higher than 60, additionally consume 60 "Afflatus" to summon <span class="Highlight">Phatasmic Imprint: Left</span> and <span class="Highlight">Phatasmic Imprint: Right</span> on the ground.<br><br><span class="Title">Hold</span><br>Deal <span class="Ice">Glacio DMG</span>. If "Afflatus" is higher than 60, additionally consume 60 "Afflatus" to summon <span class="Highlight">Phatasmic Imprint: Left</span> and <span class="Highlight">Phatasmic Imprint: Right</span> in the air.<br><br><span class="Title">Press while in Mid-air</span><br>Deal <span class="Ice">Glacio DMG</span>. If "Afflatus" is higher than 60, additionally consume 60 "Afflatus" to summon <span class="Highlight">Phatasmic Imprint: Left</span> and <span class="Highlight">Phatasmic Imprint: Right</span> in the air.</div>`,
  attacks: [
    {
      key: "DepictionPressDMG",
      label: "Press DMG",
      talents: {
        "1": "49.50%*3",
        "2": "53.56%*3",
        "3": "57.62%*3",
        "4": "63.31%*3",
        "5": "67.36%*3",
        "6": "72.03%*3",
        "7": "78.53%*3",
        "8": "85.02%*3",
        "9": "91.52%*3",
        "10": "98.42%*3",
      },
      type: "Skill",
    },
    {
      key: "DepictionHoldDMG",
      label: "Hold DMG",
      talents: {
        "1": "49.50%*3",
        "2": "53.56%*3",
        "3": "57.62%*3",
        "4": "63.31%*3",
        "5": "67.36%*3",
        "6": "72.03%*3",
        "7": "78.53%*3",
        "8": "85.02%*3",
        "9": "91.52%*3",
        "10": "98.42%*3",
      },
      type: "Skill",
    },
    {
      key: "DepictionMidAirDMG",
      label: "Mid Air DMG",
      talents: {
        "1": "49.50%*3",
        "2": "53.56%*3",
        "3": "57.62%*3",
        "4": "63.31%*3",
        "5": "67.36%*3",
        "6": "72.03%*3",
        "7": "78.53%*3",
        "8": "85.02%*3",
        "9": "91.52%*3",
        "10": "98.42%*3",
      },
      type: "Skill",
    },
    {
      key: "SequenceNode6ImitationandInheritance",
      label: "Sequence Node 6: Imitation and Inheritance",
      talents: {
        "1": "240.00%",
        "2": "259.68%",
        "3": "279.36%",
        "4": "306.91%",
        "5": "326.59%",
        "6": "349.23%",
        "7": "380.72%",
        "8": "412.21%",
        "9": "443.70%",
        "10": "477.15%",
      },
      type: "Basic",
      requiresResonanceChain: "SequenceNode6ImitationandInheritance",
    },
  ],
};
