export const forteCircuitAttacks = {
  name: "Forte Circuit: Thunder Begets Life",
  description: `<div><size=40><span class="Title"><strong>Yin-Yang Balance</strong></span><br>When Buling obtains Minor Yin and Minor Yang, she enters the <span class="Highlight"><strong>Yin-Yang Balance</strong></span> state, replacing her <span class="Highlight"><strong>Resonance Liberation - Flashing Thunder Spell</strong></span> with <span class="Highlight"><strong>Resonance Liberation - Flashing Thunder Spell: Harmony</strong></span>.<br><size=10><br><size=40><span class="Title"><strong>Flashing Thunder Spell - Harmony</strong></span><br>Attack the target, dealing <span class="Thunder"><strong>Electro DMG</strong></span> and generating a <span class="Highlight"><strong>Five Thunders Spell Array</strong></span> at the target area. The array deals <span class="Thunder"><strong>Electro DMG</strong></span> and inflicts 2 stacks of <span class="Highlight"><strong>Electro Flare</strong></span> on all targets within it every 2s, lasting for 24s. When <span class="Highlight"><strong>Five Thunders Spell Array</strong></span> is active, all Resonators in the team enter the <span class="Highlight"><strong>Thunder Spell - Primordial Qi</strong></span> state.<br>- While in the <span class="Highlight"><strong>Thunder Spell - Primordial Qi</strong></span> state, when any Resonator in the team casts <span class="Highlight"><strong>Intro Skill</strong></span>,  <span class="Highlight"><strong>Thunder Spell - Primordial Qi</strong></span> becomes <span class="Highlight"><strong>Thunder Spell - Yin and Yang</strong></span>.<br>- <span class="Highlight"><strong>Thunder Spell - Yin and Yang</strong></span> grants 10% <span class="Highlight"><strong>Resonance Skill</strong></span> DMG Bonus to all active Resonators in the team. When any Resonator in the team casts <span class="Highlight"><strong>Intro Skill</strong></span> during this state, <span class="Highlight"><strong>Thunder Spell - Yin and Yang</strong></span> becomes <span class="Highlight"><strong>Thunder Spell - Heaven, Earth, Mind</strong></span>.<br>- <span class="Highlight"><strong>Thunder Spell - Heaven, Earth, Mind</strong></span> grants 25% <span class="Highlight"><strong>Resonance Skill</strong></span> DMG Bonus to all active Resonators in the team.<br><size=10><br><size=40><span class="Title"><strong>Minor Yang and Minor Yin</strong></span><br>- Minor Yang is obtained after casting <span class="Highlight"><strong>Heavy Attack - Mountain Over Thunder</strong></span> or <span class="Highlight"><strong>Heavy Attack - Thunder Over Mountain</strong></span>.<br>- Minor Yin is obtained after casting <span class="Highlight"><strong>Heavy Attack - Twin Mountains</strong></span> or <span class="Highlight"><strong>Heavy Attack - Twin Thunders</strong></span>.</size=40></size=10></size=40></size=10></size=40></div>`,
  attacks: [
    {
      key: "FlashingThunderSpellHarmonyDMG",
      label: "Flashing Thunder Spell - Harmony DMG",
      type: "Liberation",
      talents: {
        "1": "270.00%",
        "2": "292.14%",
        "3": "314.28%",
        "4": "345.28%",
        "5": "367.42%",
        "6": "392.88%",
        "7": "428.31%",
        "8": "463.73%",
        "9": "499.15%",
        "10": "536.79%",
      },
    },
    {
      key: "FiveThundersSpellArrayContinuousDMG",
      label: "Five Thunders Spell Array Continuous DMG",
      type: "Liberation",
      talents: {
        "1": "10.00%",
        "2": "10.82%",
        "3": "11.64%",
        "4": "12.79%",
        "5": "13.61%",
        "6": "14.56%",
        "7": "15.87%",
        "8": "17.18%",
        "9": "18.49%",
        "10": "19.89%",
      },
    },
    {
      key: "SequenceNode3SummonerofSpiritsSeekerofFate",
      label: "S3 Summoner of Spirits, Seeker of Fate Healing",
      type: "Healing",
      talents: {
        "1": "350+150%",
        "2": "350+150%",
        "3": "350+150%",
        "4": "350+150%",
        "5": "350+150%",
        "6": "350+150%",
        "7": "350+150%",
        "8": "350+150%",
        "9": "350+150%",
        "10": "350+150%",
      },
      requiresResonanceChain: "SequenceNode3SummonerofSpiritsSeekerofFate",
    },
  ],
};
