export const forteCircuitAttacks = {
  name: "Forte Circuit: A Prop Master Prepares",
  description: `<div class="skilldescription"><span class="Title">Beyond Imagination</span><br>- When Roccia is in <span class="Highlight">Beyond Imagination</span> with at least 100 Imagination, press the <span class="Highlight">Basic Attack</span> button to consume 100 Imagination to cast Basic Attack <span class="Highlight">Real Fantasy</span>.<br>- Roccia exits this state when she is not airborne or when switched off the field.<br> <br><span class="Title">Basic Attack - Real Fantasy</span><br>- Perform up to 3 consecutive attacks, dealing <span class="Dark">Havoc DMG</span>, considered Heavy Attack DMG. When Roccia lands after Stage 1 and Stage 2 attacks with over 100 Imagination, she will launch into mid-air and activate <span class="Highlight">Beyond Imagination</span>.<br> <br><span class="Title">Imagination</span><br>Roccia can hold up to 300 Imagination.<br>- Dealing DMG with Normal Attacks restores Imagination.<br>- Hold <span class="Highlight">Normal Attack</span> to charge the next attack while restoring Imagination.<br>- Casting Resonance Skill <span class="Highlight">Acrobatic Trick</span> restores 100 Imagination.<br>- Casting Intro Skill <span class="Highlight">Pero, Help</span> restores 100 Imagination.</div>`,
  attacks: [
    {
      key: "RealFantasyStage1DMG",
      label: "Real Fantasy Stage 1 DMG",
      talents: {
        "1": "162.00%",
        "2": "175.29%",
        "3": "188.57%",
        "4": "207.17%",
        "5": "220.45%",
        "6": "235.73%",
        "7": "256.99%",
        "8": "278.24%",
        "9": "299.49%",
        "10": "322.08%",
      },
      type: "Heavy",
    },
    {
      key: "RealFantasyStage2DMG",
      label: "Real Fantasy Stage 2 DMG",
      talents: {
        "1": "171.00%",
        "2": "185.03%",
        "3": "199.05%",
        "4": "218.68%",
        "5": "232.70%",
        "6": "248.83%",
        "7": "271.26%",
        "8": "293.70%",
        "9": "316.13%",
        "10": "339.97%",
      },
      type: "Heavy",
    },
    {
      key: "RealFantasyStage3DMG",
      label: "Real Fantasy Stage 3 DMG",
      talents: {
        "1": "180.00%",
        "2": "194.76%",
        "3": "209.52%",
        "4": "230.19%",
        "5": "244.95%",
        "6": "261.92%",
        "7": "285.54%",
        "8": "309.15%",
        "9": "332.77%",
        "10": "357.86%",
      },
      type: "Heavy",
    },
    {
      key: "SequenceNode6WhentheGoldenWingsFlyDMG",
      label: "S6: Reality Recreation DMG",
      talents: {
        "1": "180.00%",
        "2": "194.76%",
        "3": "209.52%",
        "4": "230.19%",
        "5": "244.95%",
        "6": "261.92%",
        "7": "285.54%",
        "8": "309.15%",
        "9": "332.77%",
        "10": "357.86%",
      },
      type: "Heavy",
      requiresResonanceChain: "SequenceNode6WhentheGoldenWingsFlyDMG",
    },
  ],
};
