export const rotations: RotationPreset[] = [
  {
    name: `Standard Rotation`,
    description: `Prydwen Standard Rotation`,
    author: `LavaSnake`,
    data: {
      name: "Standard Rotation",
      description: "Prydwen Standard Rotation",
      actions: [
        {
          order: 1,
          key: "PerloHelpDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "BasicAttackStage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "AcrobaticTrickDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "RealFantasyStage1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "RealFantasyStage2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "RealFantasyStage3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "CommediaImprovvisoDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "MidnightVeilDMG",
          type: "echoSetAttacks",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];
