export const forteCircuitAttacks = {
  name: "Forte Circuit: Radiant Invocation",
  description: `<div class="skilldescription">When Phoebe's Prayer is full, consume all Prayer to cast one of the following skills:<br>- Hold <span class="Highlight">Basic Attack</span> to cast Heavy Attack <span class="Highlight">Absolution Litany</span>, dealing <span class="Light">Spectro DMG</span> and applying <saptag=0>1 stack of <span class="Highlight">Spectro Frazzle</span> to the targets hit. Phoebe enters <span class="Highlight">Absolution</span> status, which allows her to deal more DMG.<br>- Hold <span class="Highlight">Resonance Skill</span> to cast Resonance Skill <span class="Highlight">Utter Confession</span>, dealing <span class="Light">Spectro DMG</span> and applying <saptag=0>1 stack of <span class="Highlight">Spectro Frazzle</span> to the targets hit. Phoebe enters <span class="Highlight">Confession</span> status, which allows her to better exploit Spectro Frazzle.<br>- <span class="Highlight">Absolution</span> and <span class="Highlight">Confession</span> cannot coexist. Entering into one will end the other.<br>- When Divine Voice is not exhausted, Phoebe is unable to cast Heavy Attack <span class="Highlight">Absolution Litany</span> and Resonance Skill <span class="Highlight">Utter Confession</span>.<br>- When Divine Voice is exhausted, Phoebe will not exit the <span class="Highlight">Absolution</span> or <span class="Highlight">Confession</span> status.<br> <br><span class="Title">Heavy Attack: Starflash</span><br>When Phoebe has Divine Voice, casting <span class="Highlight">Basic Attack Stage 3</span> or <span class="Highlight">Dodge Counter</span> replaces the next <span class="Highlight">Heavy Attack</span> with <span class="Highlight">Heavy Attack: Starflash</span>, which deals <span class="Light">Spectro DMG</span> at the cost of 30 Divine Voice.<br>- <span class="Highlight">Absolution</span> Enhancement: Reduce the cost of Divine Voice by 15. When the targets hit have <span class="Highlight">Spectro Frazzle</span>, the skill gains 256% DMG Amplification.<br>- <span class="Highlight">Confession</span> Enhancement: Apply <saptag=5>5 stack of <span class="Highlight">Spectro Frazzle</span> to the targets hit.<br> <br><span class="Title">Prayer </span><br>Phoebe can hold up to 120 Prayer.<br>Phoebe automatically gains 5 Prayer every second.<br> <br><span class="Title">Divine Voice</span><br>Phoebe can hold up to 60 Divine Voice.<br>Casting Heavy Attack <span class="Highlight">Absolution Litany</span> or Resonance Skill <span class="Highlight">Utter Confession</span> restores 60 Divine Voice.</saptag=5></saptag=0></saptag=0></div>`,
  attacks: [
    {
      key: "AbsolutionLitanyDMG",
      label: "Absolution Litany DMG",
      talents: {
        "1": "321.00%",
        "2": "347.33%",
        "3": "373.65%",
        "4": "410.50%",
        "5": "436.82%",
        "6": "467.09%",
        "7": "509.21%",
        "8": "551.32%",
        "9": "593.44%",
        "10": "638.19%",
      },
      type: "Heavy",
    },
    {
      key: "UtterConfessionDMG",
      label: "Utter Confession DMG",
      talents: {
        "1": "94.50%",
        "2": "102.25%",
        "3": "110.00%",
        "4": "120.85%",
        "5": "128.60%",
        "6": "137.51%",
        "7": "149.91%",
        "8": "162.31%",
        "9": "174.71%",
        "10": "187.88%",
      },
      type: "Skill",
    },
    {
      key: "HeavyAttackStarflashDMG",
      label: "Heavy Attack: Starflash DMG",
      talents: {
        "1": "41.59%*3",
        "2": "45.00%*3",
        "3": "48.41%*3",
        "4": "53.19%*3",
        "5": "56.60%*3",
        "6": "60.52%*3",
        "7": "65.98%*3",
        "8": "71.43%*3",
        "9": "76.89%*3",
        "10": "82.69%*3",
      },
      type: "Heavy",
    },
  ],
};
