export const skillAttacks = {
  name: "Resonance Skill: To Where Light Shines",
  description: `<div class="skilldescription">Summon a Ring of Mirrors at the target location, making the target hit stagnate for 2s and dealing <span class="Light">Spectro DMG</span>. The stagnation effect can be applied to 12 targets max for each Ring of Mirrors. Using <span class="Highlight">Resonance Skill</span> again shortly after the summoning teleports Phoebe to the Ring of Mirrors' location, dealing <span class="Light">Spectro DMG</span>.<br>Unable to teleport if Phoebe is too far from the Ring of Mirrors.<br> <br><span class="Title">Ring of Mirrors</span><br>- Ring of Mirrors lasts for 30s. When Phoebe summons a new Ring of Mirrors, the existing Ring of Mirrors disappears.<br>- When Phoebe is outside of the Ring of Mirrors, a <span class="Highlight">Basic Attack</span> or <span class="Highlight">Dodge Counter</span> that hits the Ring of Mirrors will refract Holy Light, which deals <span class="Light">Spectro DMG</span> to targets inside the <span class="Highlight">Ring of Mirrors</span> and pulls the targets hit to the center of the ring. The DMG dealt is considered Basic Attack DMG. Can be triggered once every 0.5s.<br>- When Phoebe is inside the Ring of Mirrors, <span class="Highlight">Basic Attack</span> becomes Basic Attack <span class="Highlight">Chamuel's Star</span>, which performs up to 3 consecutive attacks, dealing <span class="Light">Spectro DMG</span>, considered Basic Attack DMG.</div>`,
  attacks: [
    {
      key: "ToWhereLightShinesDMG",
      label: "To Where Light Shines DMG",
      talents: {
        "1": "31.50%*2",
        "2": "34.09%*2",
        "3": "36.67%*2",
        "4": "40.29%*2",
        "5": "42.87%*2",
        "6": "45.84%*2",
        "7": "49.97%*2",
        "8": "54.11%*2",
        "9": "58.24%*2",
        "10": "62.63%*2",
      },
      type: "Skill",
    },
    {
      key: "RingofMirrorsRefractedHolyLightDMG",
      label: "Ring of Mirrors: Refracted Holy Light DMG",
      talents: {
        "1": "7.50%*2",
        "2": "8.12%*2",
        "3": "8.73%*2",
        "4": "9.60%*2",
        "5": "10.21%*2",
        "6": "10.92%*2",
        "7": "11.90%*2",
        "8": "12.89%*2",
        "9": "13.87%*2",
        "10": "14.92%*2",
      },
      type: "Basic",
    },
    {
      key: "ChamuelsStarStage1DMG",
      label: "Chamuel's Star: Stage 1 DMG",
      talents: {
        "1": "29.85%",
        "2": "32.30%",
        "3": "34.75%",
        "4": "38.18%",
        "5": "40.62%",
        "6": "43.44%",
        "7": "47.36%",
        "8": "51.27%",
        "9": "55.19%",
        "10": "59.35%",
      },
      type: "Basic",
    },
    {
      key: "ChamuelsStarStage2DMG",
      label: "Chamuel's Star: Stage 2 DMG",
      talents: {
        "1": "20.00%*2",
        "2": "21.64%*2",
        "3": "23.28%*2",
        "4": "25.58%*2",
        "5": "27.22%*2",
        "6": "29.11%*2",
        "7": "31.73%*2",
        "8": "34.35%*2",
        "9": "36.98%*2",
        "10": "39.77%*2",
      },
      type: "Basic",
    },
    {
      key: "ChamuelsStarStage3DMG",
      label: "Chamuel's Star: Stage 3 DMG",
      talents: {
        "1": "14.55%*6",
        "2": "15.75%*6",
        "3": "16.94%*6",
        "4": "18.61%*6",
        "5": "19.80%*6",
        "6": "21.18%*6",
        "7": "23.09%*6",
        "8": "24.99%*6",
        "9": "26.90%*6",
        "10": "28.93%*6",
      },
      type: "Basic",
    },
  ],
};
