export const forteCircuitAttacks = {
  name: "Forte Circuit: Clarity of Mind",
  description: `<div class="skilldescription"><span class="Title">Heavy Attack: Detonate</span><br>When holding <span class="Highlight">Basic Attack</span>, a cursor moves back and forth on the Forte Gauge. Release <span class="Highlight">Basic Attack</span> while cursor falls in the "Frostbite" area, to perform Heavy Attack <span class="Highlight">Detonate</span>, dealing <span class="Ice">Glacio DMG</span> considered as Heavy Attack DMG.<br> <br><span class="Title">Ice Burst</span><br>Sanhua’s Heavy Attack <span class="Highlight">Detonate</span> detonates all "Ice Thorns", "Ice Prisms" and "Glaciers" within her attack range, dealing <span class="Ice">Glacio DMG</span>. <span class="Highlight">Ice Burst</span> deals Resonance Skill DMG.<br> <br><span class="Title">Frostbite Area</span><br>The "Frostbite" area expands with every 1 stack of "Clarity". "Clarity" stacks up to 2 times.<br>Sanhua obtains 1 stack of "Clarity" upon performing <span class="Highlight">Basic Attack 5</span>.<br>Sanhua obtains 1 stack of "Clarity" upon casting Intro Skill <span class="Highlight">Freezing Thorns</span>.<br>Sanhua obtains 1 stack of "Clarity" upon casting Resonance Skill <span class="Highlight">Eternal Frost</span>.<br>Sanhua obtains 2 stack(s) of "Clarity" upon casting Resonance Liberation <span class="Highlight">Glacial Gaze</span>.<br>Upon casting Heavy Attack <span class="Highlight">Detonate</span>, all "Clarity" is removed.</div>`,
  attacks: [
    {
      key: "DetonateDMG",
      label: "Detonate Damage",
      talents: {
        "1": "93.70%*2",
        "2": "101.39%*2",
        "3": "109.07%*2",
        "4": "119.83%*2",
        "5": "127.51%*2",
        "6": "136.35%*2",
        "7": "148.64%*2",
        "8": "160.93%*2",
        "9": "173.23%*2",
        "10": "186.29%*2",
      },
      type: "Heavy",
    },
    {
      key: "GlacierBurstDMG",
      label: "Glacier Burst Damage",
      talents: {
        "1": "70.00%",
        "2": "75.74%",
        "3": "81.48%",
        "4": "89.52%",
        "5": "95.26%",
        "6": "101.86%",
        "7": "111.05%",
        "8": "120.23%",
        "9": "129.41%",
        "10": "139.17%",
      },
      type: "Skill",
    },
    {
      key: "IcePrismBurstDMG",
      label: "Ice Prism Burst Damage",
      talents: {
        "1": "40.00%",
        "2": "43.28%",
        "3": "46.56%",
        "4": "51.16%",
        "5": "54.44%",
        "6": "58.21%",
        "7": "63.46%",
        "8": "68.70%",
        "9": "73.95%",
        "10": "79.53%",
      },
      type: "Skill",
    },
    {
      key: "IceThornBurstDMG",
      label: "Ice Thorn Burst Damage",
      talents: {
        "1": "30.00%",
        "2": "32.46%",
        "3": "34.92%",
        "4": "38.37%",
        "5": "40.83%",
        "6": "43.66%",
        "7": "47.59%",
        "8": "51.53%",
        "9": "55.47%",
        "10": "59.65%",
      },
      type: "Skill",
    },
  ],
};
