export const introAttacks = {
  name: "Intro Skill: Formal Greetings",
  description: `<div><span style="color:#a89969"><strong>It's Been A While!</strong></span><br>Available in <span style="color:#f7ca2f"><strong>Stagecraft Form</strong></span>, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Stagecraft Form Stage 4</strong></span>.<br><br><span style="color:#a89969"><strong>Knock Knock</strong></span><br>Available in <span style="color:#f7ca2f"><strong>Breakdown Form</strong></span>, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br>Casting this skill grants <span style="color:#f7ca2f"><strong><span class="Highlight">Entropy Shift: Breakdown Form</span></strong></span> for 12s.</div>`,
  attacks: [
    {
      key: "ItsBeenAWhileDMG",
      label: "It's Been A While! DMG",
      talents: {
        "1": "52.62%",
        "2": "56.94%",
        "3": "61.25%",
        "4": "67.30%",
        "5": "71.61%",
        "6": "76.57%",
        "7": "83.48%",
        "8": "90.38%",
        "9": "97.28%",
        "10": "104.62%",
      },
      type: "Intro",
    },
    {
      key: "KnockKnockDMG",
      label: "Knock Knock DMG",
      talents: {
        "1": "26.02%*3",
        "2": "28.16%*3",
        "3": "30.29%*3",
        "4": "33.28%*3",
        "5": "35.41%*3",
        "6": "37.87%*3",
        "7": "41.28%*3",
        "8": "44.69%*3",
        "9": "48.11%*3",
        "10": "51.74%*3",
      },
      type: "Intro",
    },
  ],
};
