export const rotations: RotationPreset[] = [];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Fusion Chromatic Foam Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceDenia","echoSet":"ChromaticFoam","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"SpacetrekExplorer","echoSet":"ChromaticFoam","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"TwinNovaNebulousCannon","echoSet":"ChromaticFoam","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"ShadowStepper","echoSet":"ChromaticFoam","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"4":{"type":1,"echo":"ZipZap","echoSet":"ChromaticFoam","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ReminiscenceDenia","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Fusion Chromatic Foam Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceDenia","echoSet":"ChromaticFoam","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"TwinNovaNebulousCannon","echoSet":"ChromaticFoam","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"SpacetrekExplorer","echoSet":"ChromaticFoam","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"ZipZap","echoSet":"ChromaticFoam","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"ShadowStepper","echoSet":"ChromaticFoam","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50}},"mainEcho":{"echo":"ReminiscenceDenia","rank":5}}
    },
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Fusion Reel of Spliced Memories Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":3,"echo":"VoidwingMoth","echoSet":"ReelofSplicedMemories","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"MiningReindeer","echoSet":"ReelofSplicedMemories","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Ironhoof","echoSet":"ReelofSplicedMemories","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"MiningDrone","echoSet":"ReelofSplicedMemories","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"FloraDrone","echoSet":"ReelofSplicedMemories","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50}},"mainEcho":{"echo":"VoidwingMoth","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Fusion Reel of Spliced Memories Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 18.4% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":3,"echo":"VoidwingMoth","echoSet":"ReelofSplicedMemories","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Ironhoof","echoSet":"ReelofSplicedMemories","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"MiningReindeer","echoSet":"ReelofSplicedMemories","stat":"Fusion","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"IceglintDancer","echoSet":"ReelofSplicedMemories","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"MiningDrone","echoSet":"ReelofSplicedMemories","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"VoidwingMoth","rank":5}}
    }
];

