export const skillAttacks = {
  name: "Resonance Skill: Bubbles and Baits",
  description: `<div><span style="color:#a89969"><strong>Phantom Bubble - Stagecraft Form</strong></span><br>Pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Beckon - Breakdown Form</strong></span><br>Pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Banish - Breakdown Form</strong></span>.<br>Can be cast in mid-air.<br><br><span style="color:#a89969"><strong>Banish - Breakdown Form</strong></span><br>While holding a <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Core</span></strong></span>, replace <span style="color:#f7ca2f"><strong>Beckon - Breakdown Form</strong></span> with <span style="color:#f7ca2f"><strong>Banish - Breakdown Form</strong></span>.<br>Cast <span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 1</strong></span> to pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>. Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> shortly after to cast <span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 2</strong></span>.<br><span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 2</strong></span> consumes all <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Cores</span></strong></span>, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>. For each <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Core</span></strong></span> consumed, the DMG Multiplier of the attack is increased by 150%.<br>The skill deals Resonance Liberation DMG.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Beckon - Breakdown Form</strong></span>.<br>Can be cast in mid-air.</div>`,
  attacks: [
    {
      key: "PhantomBubbleStagecraftFormDMG",
      label: "Phantom Bubble - Stagecraft Form DMG",
      talents: {
        "1": "8.76%*3+26.28%",
        "2": "9.48%*3+28.44%",
        "3": "10.20%*3+30.59%",
        "4": "11.21%*3+33.61%",
        "5": "11.93%*3+35.77%",
        "6": "12.75%*3+38.25%",
        "7": "13.90%*3+41.69%",
        "8": "15.05%*3+45.14%",
        "9": "16.20%*3+48.59%",
        "10": "17.42%*3+52.25%",
      },
      type: "Skill",
    },
    {
      key: "BeckonBreakdownFormDMG",
      label: "Beckon - Breakdown Form DMG",
      talents: {
        "1": "15.65%+7.30%*5",
        "2": "16.93%+7.90%*5",
        "3": "18.21%+8.50%*5",
        "4": "20.01%+9.34%*5",
        "5": "21.29%+9.94%*5",
        "6": "22.77%+10.63%*5",
        "7": "24.82%+11.58%*5",
        "8": "26.87%+12.54%*5",
        "9": "28.92%+13.50%*5",
        "10": "31.10%+14.52%*5",
      },
      type: "Skill",
    },
    {
      key: "BanishBreakdownFormStage1DMG",
      label: "Banish - Breakdown Form Stage 1 DMG",
      talents: {
        "1": "17.44%*3",
        "2": "18.88%*3",
        "3": "20.31%*3",
        "4": "22.31%*3",
        "5": "23.74%*3",
        "6": "25.38%*3",
        "7": "27.67%*3",
        "8": "29.96%*3",
        "9": "32.25%*3",
        "10": "34.68%*3",
      },
      type: "Liberation",
    },
    {
      key: "BanishBreakdownFormStage2DMG",
      label: "Banish - Breakdown Form Stage 2 DMG",
      talents: {
        "1": "56.34%",
        "2": "60.96%",
        "3": "65.58%",
        "4": "72.05%",
        "5": "76.67%",
        "6": "81.99%",
        "7": "89.38%",
        "8": "96.77%",
        "9": "104.16%",
        "10": "112.01%",
      },
      type: "Liberation",
    },
  ],
};
