export const skillAttacks = {
  name: "Resonance Skill: Bubbles and Baits",
  description: `<div><span style="color:#a89969"><strong>Phantom Bubble - Stagecraft Form</strong></span><br>Pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Beckon - Breakdown Form</strong></span><br>Pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Banish - Breakdown Form</strong></span>.<br>Can be cast in mid-air.<br><br><span style="color:#a89969"><strong>Banish - Breakdown Form</strong></span><br>While holding a <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Core</span></strong></span>, replace <span style="color:#f7ca2f"><strong>Beckon - Breakdown Form</strong></span> with <span style="color:#f7ca2f"><strong>Banish - Breakdown Form</strong></span>.<br>Cast <span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 1</strong></span> to pull in nearby targets, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>. Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> shortly after to cast <span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 2</strong></span>.<br><span style="color:#f7ca2f"><strong>Banish - Breakdown Form Stage 2</strong></span> consumes all <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Cores</span></strong></span>, dealing <span style="color:#f0744e"><strong>Fusion DMG</strong></span>. For each <span style="color:#f7ca2f"><strong><span class="Highlight">Dark Core</span></strong></span> consumed, the DMG Multiplier of the attack is increased by 150%.<br>The skill deals Resonance Liberation DMG.<br>This skill shares a Cooldown with <span style="color:#f7ca2f"><strong>Beckon - Breakdown Form</strong></span>.<br>Can be cast in mid-air.</div>`,
  attacks: [
    {
      key: "ResonanceSkillPresentSelfDMG",
      label: "Resonance Skill - Present Self DMG",
      talents: {
        "1": "12.32%*4+49.28%",
        "2": "13.34%*4+53.33%",
        "3": "14.35%*4+57.37%",
        "4": "15.76%*4+63.02%",
        "5": "16.77%*4+67.07%",
        "6": "17.93%*4+71.71%",
        "7": "19.55%*4+78.18%",
        "8": "21.16%*4+84.64%",
        "9": "22.78%*4+91.11%",
        "10": "24.50%*4+97.98%",
      },
      type: "Skill",
    },
    {
      key: "FrostblightJadeCleaveDMG",
      label: "Frostblight: Jade Cleave DMG",
      talents: {
        "1": "33.20%*4",
        "2": "35.93%*4",
        "3": "38.65%*4",
        "4": "42.46%*4",
        "5": "45.18%*4",
        "6": "48.31%*4",
        "7": "52.67%*4",
        "8": "57.03%*4",
        "9": "61.38%*4",
        "10": "66.01%*4",
      },
      type: "Skill",
    },
    {
      key: "FrostblightPetalfallDMG",
      label: "Frostblight: Petalfall DMG",
      talents: {
        "1": "32.20%*4+32.20%",
        "2": "34.85%*4+34.85%",
        "3": "37.49%*4+37.49%",
        "4": "41.18%*4+41.18%",
        "5": "43.82%*4+43.82%",
        "6": "46.86%*4+46.86%",
        "7": "51.08%*4+51.08%",
        "8": "55.31%*4+55.31%",
        "9": "59.53%*4+59.53%",
        "10": "64.02%*4+64.02%",
      },
      type: "Skill",
    },
    {
      key: "SequenceNode4LikeReedsonTides",
      label: "S4: Frostblight: Healing",
      talents: {
        "1": "18%",
        "2": "18%",
        "3": "18%",
        "4": "18%",
        "5": "18%",
        "6": "18%",
        "7": "18%",
        "8": "18%",
        "9": "18%",
        "10": "18%",
      },
      type: "Healing",
      attribute: "hp",
      requiresResonanceChain: "SequenceNode4LikeReedsonTides",
    },
  ],
};
