export const liberationAttacks = {
  name: "Resonance Liberation: Moment of Nihility",
  description: `<div><div class="text-sm font-normal">Deal <span style="color: #e649a6;"><strong>Havoc DMG</strong></span> and recover HP for all nearby Resonators in the team. <br>Casting this skill sends Chisa into <span class="Highlight"><strong>Woven Myriad - Convergence</strong></span> for 15s.<br>While not in <span class="Highlight"><strong>Chainsaw Mode</strong></span>, press <span class="Highlight"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span class="Highlight"><strong>Basic Attack Stage 2</strong></span>.<br>Can be cast in mid-air close to the ground.<br><size=10><br><size=40><span class="Title"><strong>Woven Myriad - Convergence</strong></span><br>The DMG Multipliers of <span class="Highlight"><strong>Sawring - Blitz</strong></span>, <span class="Highlight"><strong>Chainsaw Mode - Dodge Counter</strong></span>, and <span class="Highlight"><strong>Sawring - Eradication</strong></span> are increased by 120%.<br>The bonus DMG Multiplier for <span class="Highlight"><strong>Sawring - Eradication</strong></span> granted by <span class="Highlight"><strong>Sawring- Blitz</strong></span> and <span class="Highlight"><strong>Chainsaw Mode - Dodge Counter</strong></span> when <span class="Highlight"><strong>Ring of Chainsaw</strong></span> is consumed additionally increases by 120%.<br>Casting <span class="Highlight"><strong>Sawring - Eradication</strong></span> ends <span class="Highlight"><strong>Woven Myriad - Convergence</strong></span>.</size=40></size=10></div></div>`,
  attacks: [
    {
      key: "MomentofNihilityDMG",
      label: "Moment of Nihility DMG",
      type: "Liberation",
      talents: {
        "1": "480.00%",
        "2": "519.36%",
        "3": "558.72%",
        "4": "613.83%",
        "5": "653.19%",
        "6": "698.45%",
        "7": "761.43%",
        "8": "824.40%",
        "9": "887.38%",
        "10": "954.29%",
      },
    },
    {
      key: "MomentofNihilityHealing",
      label: "Moment of Nihility Healing",
      type: "Healing",
      talents: {
        "1": "1400+56.00%",
        "2": "1568+58.24%",
        "3": "1750+60.48%",
        "4": "1960+63.84%",
        "5": "2212+68.32%",
        "6": "2450+72.80%",
        "7": "2492+81.20%",
        "8": "2548+90.72%",
        "9": "2590+100.80%",
        "10": "2660+117.60%",
      },
    },
  ],
};
