export const skillAttacks = {
  name: "Resonance Skill: Fractured Composition",
  description: `<div><size=40><span class="Title"><strong>Eye of Unraveling</strong></span><br>Stagnate and deal <span class="Dark"><strong>Havoc DMG</strong></span>.<br>- While not in <span class="Highlight"><strong>Chainsaw Mode</strong></span>, after casting this skill, press <span class="Highlight"><strong>Normal Attack</strong></span> on the ground or use <span class="Highlight"><strong>Normal Attack</strong></span> in mid-air to cast <span class="Highlight"><strong>Rending Lunge</strong></span>. This effect is removed when Chisa enters <span class="Highlight"><strong>Chainsaw Mode</strong></span>.<br>- While in <span class="Highlight"><strong>Chainsaw Mode</strong></span> and on the ground, press <span class="Highlight"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span class="Highlight"><strong>Sawring - Blitz Stage 2</strong></span>.<br>Can be cast in mid-air.<br><size=10><br><size=40><span class="Title"><strong>Serrated Loop</strong></span><br>While on the ground and <span class="Highlight"><strong>Ring of Chainsaw</strong></span> is full, <span class="Highlight"><strong>Resonance Skill</strong></span> is replaced with <span class="Highlight"><strong>Serrated Loop</strong></span>.<br>Stagnate targets, and deal <span class="Dark"><strong>Havoc DMG</strong></span> and pull in nearby targets.<br>Casting this skill sends Chisa into <span class="Highlight"><strong>Chainsaw Mode</strong></span> and replaces <span class="Highlight"><strong>Resonance Skill</strong></span> with <span class="Highlight"><strong>Eye of Unraveling</strong></span>.<br>Press <span class="Highlight"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span class="Highlight"><strong>Sawring - Blitz Stage 2</strong></span>.<br>Hold <span class="Highlight"><strong>Resonance Skill</strong></span> while casting this skill to continuously attack and pull in nearby targets. Release the <span class="Highlight"><strong>Resonance Skill</strong></span> button in the duration or keep holding it for a certain period of time to cast <span class="Highlight"><strong>Sawring - Blitz Stage 1</strong></span>.</size=40></size=10></size=40></div>`,
  attacks: [
  {
    key: "EyeofUnravelingDMG",
    label: "Eye of Unraveling DMG",
    type: "Skill",
    talents: {
      "1": "18.00%",
      "2": "19.48%",
      "3": "20.96%",
      "4": "23.02%",
      "5": "24.50%",
      "6": "26.20%",
      "7": "28.56%",
      "8": "30.92%",
      "9": "33.28%",
      "10": "35.79%",
    },
  },
  {
    key: "SerratedLoopDMG",
    label: "Serrated Loop DMG",
    type: "Skill",
    talents: {
      "1": "8.78%*8",
      "2": "9.50%*8",
      "3": "10.22%*8",
      "4": "11.22%*8",
      "5": "11.94%*8",
      "6": "12.77%*8",
      "7": "13.92%*8",
      "8": "15.07%*8",
      "9": "16.22%*8",
      "10": "17.45%*8",
    },
  },
  {
    key: "SerratedLoopHoldDMG",
    label: "Serrated Loop Hold DMG",
    type: "Skill",
    talents: {
      "1": "3.76%*16",
      "2": "4.06%*16",
      "3": "4.37%*16",
      "4": "4.80%*16",
      "5": "5.11%*16",
      "6": "5.46%*16",
      "7": "5.96%*16",
      "8": "6.45%*16",
      "9": "6.94%*16",
      "10": "7.46%*16",
    },
  },
],
};
