export const basicAttacks = {
  name: "Normal Attack: Mix-'n'-Match",
  description: `<div><span style="color:#a89969"><strong>Basic Attack - Huntress</strong></span><br>Perform up to 3 consecutive attacks, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Heavy Attack - Huntress</strong></span><br><span style="color:#f7ca2f"><strong>Hold Normal Attack</strong></span> to continuously fire at enemies at the cost of STA, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>, considered Basic Attack DMG.<br>- Hold and then release <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> while Rebecca is not casting <span style="color:#f7ca2f"><strong>Tactical Dodge - Huntress</strong></span> to cast <span style="color:#f7ca2f"><strong>Heavy Attack - Eat Lead!: Huntress</strong></span><br><br><span style="color:#a89969"><strong>Heavy Attack - Eat Lead!: Huntress</strong></span><br>Deal <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Comin' in Hot! - Huntress</strong></span><br>Somersault in mid-air and land.<br><span style="color:#f7ca2f"><strong>Keep holding Normal Attack</strong></span> after casting this skill to follow up with <span style="color:#f7ca2f"><strong>Heavy Attack - Huntress</strong></span> without consuming STA.<br><br><span style="color:#a89969"><strong>Mid-air Plunging Attack - Huntress</strong></span><br>Consume STA to perform a Plunging Attack, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter - Huntress</strong></span><br><span style="color:#f7ca2f"><strong>Press Normal Attack</strong></span> shortly after a successful Dodge to strike the target, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Tactical Dodge - Huntress</strong></span><br><span style="color:#f7ca2f"><strong>Press Dodge</strong></span> to attack the target while dodging, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br>Can be cast during the following actions (while on the ground):<br>- Performing <span style="color:#f7ca2f"><strong>Basic Attack - Huntress</strong></span>.<br>- Performing <span style="color:#f7ca2f"><strong>Heavy Attack - Huntress</strong></span>.<br>- Performing <span style="color:#f7ca2f"><strong>Heavy Attack - Eat Lead!: Huntress</strong></span><br>- Casting <span style="color:#f7ca2f"><strong>Comin' in Hot! - Huntress</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Tactical Dodge - Huntress</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Intro Skill</strong></span>.<br>Additional <span style="color:#b45bff"><strong>Electro DMG</strong></span> is dealt upon a successful Dodge during <span style="color:#f7ca2f"><strong>Tactical Dodge - Huntress</strong></span>.<br><span style="color:#f7ca2f"><strong>Keep holding Normal Attack</strong></span> after casting this skill to follow up with <span style="color:#f7ca2f"><strong>Heavy Attack - Huntress</strong></span> without consuming STA.<br><br><span style="color:#a89969"><strong>Basic Attack - Guts</strong></span><br>Perform up to 3 consecutive attacks, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br>Casting <span style="color:#f7ca2f"><strong>Tactical Dodge - Guts</strong></span> does not reset <span style="color:#f7ca2f"><strong>Basic Attack - Huntress's</strong></span> attack cycle within a certain time.<br><br><span style="color:#a89969"><strong>Heavy Attack - Guts</strong></span><br>Consume STA and attack the target, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Mid-air Plunging Attack - Guts</strong></span><br>Consume STA to perform a Plunging Attack, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter - Guts</strong></span><br><span style="color:#f7ca2f"><strong>Press Normal Attack</strong></span> shortly after a successful Dodge to strike the target, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Tactical Dodge - Guts</strong></span><br><span style="color:#f7ca2f"><strong>Press Dodge</strong></span> and attack the target while dodging, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br>Can be cast during the following actions (while on the ground):<br>- Performing <span style="color:#f7ca2f"><strong>Basic Attack - Guts</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Tactical Dodge - Guts</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span>.<br>- Casting <span style="color:#f7ca2f"><strong>Intro Skill</strong></span>.<br>Additional <span style="color:#b45bff"><strong>Electro DMG</strong></span> is dealt upon a successful Dodge during <span style="color:#f7ca2f"><strong>Tactical Dodge - Guts</strong></span>.</div>`,
  attacks: [
    {
      key: "Stage1DMG",
      label: "Stage 1 DMG",
      talents: {
        "1": "40.00%",
        "2": "43.28%",
        "3": "46.56%",
        "4": "51.16%",
        "5": "54.44%",
        "6": "58.21%",
        "7": "63.46%",
        "8": "68.70%",
        "9": "73.95%",
        "10": "79.53%",
      },
      type: "Basic",
    },
    {
      key: "Stage2DMG",
      label: "Stage 2 DMG",
      talents: {
        "1": "18.33%*4",
        "2": "19.83%*4",
        "3": "21.34%*4",
        "4": "23.44%*4",
        "5": "24.94%*4",
        "6": "26.67%*4",
        "7": "29.07%*4",
        "8": "31.48%*4",
        "9": "33.88%*4",
        "10": "36.44%*4",
      },
      type: "Basic",
    },
    {
      key: "Stage3DMG",
      label: "Stage 3 DMG",
      talents: {
        "1": "36.50%*2",
        "2": "39.50%*2",
        "3": "42.49%*2",
        "4": "46.68%*2",
        "5": "49.67%*2",
        "6": "53.12%*2",
        "7": "57.90%*2",
        "8": "62.69%*2",
        "9": "67.48%*2",
        "10": "72.57%*2",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackDMG",
      label: "Heavy Attack DMG",
      talents: {
        "1": "28.76%*2",
        "2": "31.12%*2",
        "3": "33.48%*2",
        "4": "36.78%*2",
        "5": "39.14%*2",
        "6": "41.85%*2",
        "7": "45.63%*2",
        "8": "49.40%*2",
        "9": "53.17%*2",
        "10": "57.18%*2",
      },
      type: "Heavy",
    },
    {
      key: "DelusiveDiveDMG",
      label: "Delusive Dive DMG",
      talents: {
        "1": "26.68%*2",
        "2": "28.87%*2",
        "3": "31.06%*2",
        "4": "34.12%*2",
        "5": "36.31%*2",
        "6": "38.83%*2",
        "7": "42.33%*2",
        "8": "45.83%*2",
        "9": "49.33%*2",
        "10": "53.05%*2",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackDMG",
      label: "Mid-air Attack DMG",
      talents: {
        "1": "21.12% + 31.68%",
        "2": "22.86% + 34.28%",
        "3": "24.59% + 36.88%",
        "4": "27.01% + 40.52%",
        "5": "28.75% + 43.12%",
        "6": "30.74% + 46.10%",
        "7": "33.51% + 50.26%",
        "8": "36.28% + 54.42%",
        "9": "39.05% + 58.57%",
        "10": "41.99% + 62.99%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterDMG",
      label: "Dodge Counter DMG",
      talents: {
        "1": "26.66%*4",
        "2": "28.85%*4",
        "3": "31.04%*4",
        "4": "34.10%*4",
        "5": "36.28%*4",
        "6": "38.80%*4",
        "7": "42.30%*4",
        "8": "45.79%*4",
        "9": "49.29%*4",
        "10": "53.01%*4",
      },
      type: "Basic",
    }
  ],
};
