export const forteCircuitAttacks = {
  name: "Forte Circuit: Gloves Are Comin' Off!",
  description: `<div class="mt-3 text-sm leading-relaxed text-slate-200"><span style="color:#a89969"><strong>Switch Gears!</strong></span><br>Upon casting <span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> or <span style="color:#f7ca2f"><strong>Intro Skill</strong></span>, Rebecca can freely switch between the <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> and <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> modes.<br>- The <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> mode increases Rebecca's Crit. DMG by 30%.<br>- The <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> mode allows Rebecca to ignore 15% of the target's DEF.<br>By default, Rebecca starts in the <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> mode.<br><br><span style="color:#a89969"><strong>Hack - Shifting</strong></span><br>Rebecca inflicts <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span> upon dealing damage to the targets through the following skills. The same skill can trigger this effect once every 3s:<br><span style="color:#f7ca2f"><strong>Intro Skill - Yo, It's Big Boomin' Time!</strong></span>, <span style="color:#f7ca2f"><strong>Intro Skill - Hey, Leadhead, Come 'n' Get Me!</strong></span>, <span style="color:#f7ca2f"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span>, <span style="color:#f7ca2f"><strong>Heavy Attack - Bang-bang-bang!: Guts</strong></span>, and <span style="color:#f7ca2f"><strong>Resonance Liberation - BOOM! Fireworks!</strong></span>.<br><br><span style="color:#a89969"><strong>Hack Response - Meltdown</strong></span><br>Deal <span style="color:#b45bff"><strong>Electro DMG</strong></span> to all targets affected by <span style="color:#f7ca2f"><strong><a href="#WwLink151104" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151104">Hack - Interfered</a></strong></span> within the range, considered Hack DMG.<br><br><span style="color:#a89969"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span><br>At 120 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span>, <span style="color:#f7ca2f"><strong>Heavy Attack - Huntress</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span>. <span style="color:#f7ca2f"><strong>Hold Normal Attack</strong></span> to cast <span style="color:#f7ca2f"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span>, which consumes all <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span> to pull in nearby targets and deal <span style="color:#b45bff"><strong>Electro DMG</strong></span>, considered Basic Attack DMG.<br>During <span style="color:#f7ca2f"><strong>Heavy Attack - Huntress</strong></span>, if <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span> is at 120 points and Rebecca is not in the action of <span style="color:#f7ca2f"><strong>Tactical Dodge - Huntress</strong></span>, <span style="color:#f7ca2f"><strong>release Normal Attack</strong></span> to cast <span style="color:#f7ca2f"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span>.<br><br><span style="color:#a89969"><strong>Heavy Attack - Bang-bang-bang!: Guts</strong></span><br>At 120 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span>, <span style="color:#f7ca2f"><strong>Heavy Attack - Guts</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Heavy Attack - Bang-bang-bang!: Guts</strong></span>. <span style="color:#f7ca2f"><strong>Hold Normal Attack </strong></span> to cast <span style="color:#f7ca2f"><strong>Heavy Attack - Bang-bang-bang!: Guts</strong></span>, which consumes all <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span> to pull in nearby targets and deal <span style="color:#b45bff"><strong>Electro DMG</strong></span>, considered Basic Attack DMG.<br><br><span style="color:#a89969"><strong>Fervor</strong></span><br>Rebecca can hold up to 120 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span>.<br><span style="color:#f7ca2f"><strong>Normal Attacks</strong></span> restore <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span> upon damaging the target.<br><span style="color:#f7ca2f"><strong>Resonance Skill</strong></span> restores <span style="color:#f7ca2f"><strong><a href="#WwLink130805" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130805">Fervor</a></strong></span> upon damaging the target.<br>When <span style="color:#f7ca2f"><strong><a href="#WwLink130804" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130804">A Girl Gets What She Wants!</a></strong></span> is gained by casting <span style="color:#f7ca2f"><strong>Intro Skill - Yo, It's Big Boomin' Time!</strong></span> or <span style="color:#f7ca2f"><strong>Intro Skill - Hey, Leadhead, Come 'n' Get Me!</strong></span>, Rebecca restores 50 points of Fervor.<br><br><span style="color:#a89969"><strong>Hot Hand</strong></span><br>Rebecca can hold up to 120 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130806" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130806">Hot Hand</a></strong></span>.<br>Regenerates over time at a rate of 10 points per second.<br>Casting <span style="color:#f7ca2f"><strong>Heavy Attack - Rat-tat-tat!: Huntress</strong></span> or <span style="color:#f7ca2f"><strong>Heavy Attack - Bang-bang-bang!: Guts</strong></span> restores <saptag=a>40 points.<br><br><span style="color:#a89969"><strong>A Girl Gets What She Wants!</strong></span><br>At 120 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130806" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130806">Hot Hand</a></strong></span>, casting <span style="color:#f7ca2f"><strong>Intro Skill - Yo, It's Big Boomin' Time!</strong></span>, <span style="color:#f7ca2f"><strong>Intro Skill - Hey, Leadhead, Come 'n' Get Me!</strong></span>, <span style="color:#f7ca2f"><strong>Resonance Skill -  It's Big Boomin' Time!</strong></span>, or <span style="color:#f7ca2f"><strong>Resonance Skill - Come 'n' Get Me!</strong></span> grants the following effects for 12s:<br>Rebecca simultaneously gains the Stat Bonuses of both the <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> and <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> modes, regardless of which mode she's currently in.<br><span style="color:#f7ca2f"><strong><a href="#WwLink130806" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130806">Hot Hand</a></strong></span> cannot be restored during this period and is consumed by <saptag=b>10 points per second.</saptag=b></saptag=a></div>`,
  attacks: [
    {
      key: "RattattatHuntressDMG",
      label: "Rat-tat-tat!: Huntress DMG",
      talents: {
        "1": "10.00%+10.00%+10.00%+160.00%+10.00%",
        "2": "10.82%+10.82%+10.82%+173.12%+10.82%",
        "3": "11.64%+11.64%+11.64%+186.24%+11.64%",
        "4": "12.79%+12.79%+12.79%+204.61%+12.79%",
        "5": "13.61%+13.61%+13.61%+217.73%+13.61%",
        "6": "14.56%+14.56%+14.56%+232.82%+14.56%",
        "7": "15.87%+15.87%+15.87%+253.81%+15.87%",
        "8": "17.18%+17.18%+17.18%+274.80%+17.18%",
        "9": "18.49%+18.49%+18.49%+295.80%+18.49%",
        "10": "19.89%+19.89%+19.89%+318.10%+19.89%",
      },
      type: "Basic",
    },
    {
      key: "BangbangbangGutsDMG",
      label: "Bang-bang-bang!: Guts DMG",
      talents: {
        "1": "140.00%",
        "2": "151.48%",
        "3": "162.96%",
        "4": "179.04%",
        "5": "190.52%",
        "6": "203.72%",
        "7": "222.09%",
        "8": "240.45%",
        "9": "258.82%",
        "10": "278.34%",
      },
      type: "Basic",
    },
    {
      key: "HackResponseMeltdownDMG",
      label: "Hack Response - Meltdown DMG",
      talents: {
        "1": "1186.50%",
        "2": "1283.80%",
        "3": "1381.09%",
        "4": "1517.30%",
        "5": "1614.59%",
        "6": "1726.48%",
        "7": "1882.15%",
        "8": "2037.82%",
        "9": "2193.49%",
        "10": "2358.89%",
      },
      type: "Hack",
    },
    {
      key: "SequenceNode6MaybeJustMaybe",
      label: "S6: Maybe, Just Maybe... DMG",
      talents: {
        "1": "900.00%",
        "2": "900.00%",
        "3": "900.00%",
        "4": "900.00%",
        "5": "900.00%",
        "6": "900.00%",
        "7": "900.00%",
        "8": "900.00%",
        "9": "900.00%",
        "10": "900.00%",
      },
      type: "Basic",
      requiresResonanceChain: "SequenceNode6MaybeJustMaybe",
    },
  ],
};
