export const introAttacks = {
  name: "Intro Skill: My Turn!",
  description: `<div><span style="color:#a89969"><strong>Yo, It's Big Boomin' Time!</strong></span><br>When in the <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> mode, upon casting Intro Skill, Rebecca approaches the enemy and sprays lead with <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span>, then switches to the <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> mode to blast the target, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><br><span style="color:#a89969"><strong>Hey, Leadhead, Come 'n' Get Me!</strong></span><br>When in the <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> mode, upon casting Intro Skill, Rebecca approaches the enemy using the recoil of <span style="color:#f7ca2f"><strong><a href="#WwLink130802" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130802">Guts</a></strong></span> from shooting the ground and switches to the <span style="color:#f7ca2f"><strong><a href="#WwLink130801" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130801">Huntress</a></strong></span> mode to spray lead at the enemy, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>.<br><span style="color:#f7ca2f"><strong>Press or hold Normal Attack</strong></span> when close to the ground shortly after casting this skill to follow up with <span style="color:#f7ca2f"><strong>Comin' in Hot! - Huntress</strong></span>.</div>`,
  attacks: [
    {
      key: "RippleDMG",
      label: "Ripple DMG",
      talents: {
        "1": "21.25%*4",
        "2": "23.00%*4",
        "3": "24.74%*4",
        "4": "27.18%*4",
        "5": "28.92%*4",
        "6": "30.93%*4",
        "7": "33.71%*4",
        "8": "36.50%*4",
        "9": "39.29%*4",
        "10": "42.25%*4",
      },
      type: "Intro",
    },
    {
      key: "TidalSurgeCoordinatedDMG",
      label: "Tidal Surge DMG (Coordinated)",
      talents: {
        "1": "8.50%*3",
        "2": "9.20%*3",
        "3": "9.90%*3",
        "4": "10.87%*3",
        "5": "11.57%*3",
        "6": "12.37%*3",
        "7": "13.49%*3",
        "8": "14.60%*3",
        "9": "15.72%*3",
        "10": "16.90%*3",
      },
      type: "Intro",
      subType: "Coordinated",
    },
    {
      key: "TidalSurgeDMG",
      label: "Tidal Surge DMG",
      talents: {
        "1": "59.50%",
        "2": "64.38%",
        "3": "69.26%",
        "4": "76.09%",
        "5": "80.97%",
        "6": "86.58%",
        "7": "94.39%",
        "8": "102.20%",
        "9": "110.00%",
        "10": "118.30%",
      },
      type: "Intro",
    },
  ],
};
