export const liberationAttacks = {
  name: "Resonance Liberation: Party 'til Dawn!",
  description: `<div class="mt-3 text-sm leading-relaxed text-slate-200">Switching to <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> mode generates a field of Stagnation for 9.5s, in which:<br>Rebecca fires the <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> automatically, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>, considered Basic Attack DMG, while accumulating <span style="color:#f7ca2f"><strong><a href="#WwLink130803" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130803">Overload</a></strong></span>. <span style="color:#f7ca2f"><strong>Press or hold Normal Attack</strong></span> or <span style="color:#f7ca2f"><strong>press Resonance Liberation</strong></span> at intervals after Rebecca starts firing to enhance her <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span>'s firepower and accumulate <span style="color:#f7ca2f"><strong><a href="#WwLink130803" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130803">Overload</a></strong></span> faster. This effect can be triggered up to 2 times.<br>- The machine gun will only auto-lock onto the enemy closest to the crosshair in the aim down sight.<br>- Rebecca is immobile when firing the <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> and gains 50% DMG Reduction and Immunity to Interrruption.<br><br><span style="color:#a89969"><strong>Overload</strong></span><br>Rebecca can hold up to 90 points of <span style="color:#f7ca2f"><strong><a href="#WwLink130803" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130803">Overload</a></strong></span>.<br>Hitting targets with the standard firepower <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> grants 2 points.<br>Hitting targets with the enhanced firepower <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> grants 4 points.<br>Hitting targets with the twice-enhanced firepower <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> grants 6 points.<br><br><span style="color:#a89969"><strong>BOOM! Fireworks!</strong></span><br>After <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> mode ends or when <span style="color:#f7ca2f"><strong><a href="#WwLink130803" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130803">Overload</a></strong></span> is maxed, <span style="color:#f7ca2f"><strong>BOOM! Fireworks!</strong></span> is automatically cast, dealing <span style="color:#b45bff"><strong>Electro DMG</strong></span>. Casting <span style="color:#f7ca2f"><strong>BOOM! Fireworks!</strong></span> ends  <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span>.<br>- <span style="color:#f7ca2f"><strong>Hold Resonance Liberation</strong></span> while in <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> mode to immediatly cast <span style="color:#f7ca2f"><strong>BOOM! Fireworks!</strong></span>.<br>- Leaving the <span style="color:#f7ca2f"><strong>Mk. 31 HMG</strong></span> mode removes all <span style="color:#f7ca2f"><strong><a href="#WwLink130803" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="130803">Overload</a></strong></span>.</div>`,
  attacks: [
    {
      key: "Mk31HMGDMG",
      label: "Mk. 31 HMG DMG",
      talents: {
        "1": "12.23%",
        "2": "13.23%",
        "3": "14.23%",
        "4": "15.63%",
        "5": "16.64%",
        "6": "17.79%",
        "7": "19.39%",
        "8": "21.00%",
        "9": "22.60%",
        "10": "24.30%",
      },
      type: "Basic",
    },
    {
      key: "Mk31HMG1stEnhancementDMG",
      label: "Mk. 31 HMG 1st Enhancement DMG",
      talents: {
        "1": "24.45%",
        "2": "26.45%",
        "3": "28.46%",
        "4": "31.26%",
        "5": "33.27%",
        "6": "35.57%",
        "7": "38.78%",
        "8": "41.99%",
        "9": "45.20%",
        "10": "48.60%",
      },
      type: "Basic",
    },
    {
      key: "Mk31HMG2ndEnhancementDMG",
      label: "Mk. 31 HMG 2nd Enhancement DMG",
      talents: {
        "1": "36.67%",
        "2": "39.68%",
        "3": "42.68%",
        "4": "46.89%",
        "5": "49.90%",
        "6": "53.36%",
        "7": "58.17%",
        "8": "62.98%",
        "9": "67.79%",
        "10": "72.90%",
      },
      type: "Basic",
    },
    {
      key: "BOOMFireworksDMG",
      label: "BOOM! Fireworks! DMG",
      talents: {
        "1": "32.00%+288.00%",
        "2": "34.63%+311.62%",
        "3": "37.25%+335.24%",
        "4": "40.93%+368.30%",
        "5": "43.55%+391.92%",
        "6": "46.57%+419.07%",
        "7": "50.77%+456.86%",
        "8": "54.96%+494.64%",
        "9": "59.16%+532.43%",
        "10": "63.62%+572.58%",
      },
      type: "Basic",
    },
  ],  
};
