export const basicAttacks = {
  name: "Normal Attack: Locked Thread",
  description: `<div><span style="color:#a89969"><strong>Basic Attack</strong></span><br>Perform up to 4 consecutive attacks, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> right after <span style="color:#f7ca2f"><strong>Basic Attack Stage 1</strong></span> to continuously attack the targets, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>. Hold this skill for a certain amount of time to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 1</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after <span style="color:#f7ca2f"><strong>Basic Attack Stage 3</strong></span> lands to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Heavy Attack</strong></span><br>Consume STA to lash out against the enemies with Monowire, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> after <span style="color:#f7ca2f"><strong>Heavy Attack Stage 1</strong></span> lands to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 2</strong></span>, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting <span style="color:#f7ca2f"><strong>Heavy Attack Stage 1</strong></span> to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 3</strong></span>.<br><br><span style="color:#a89969"><strong>Mid-air Attack</strong></span><br>Consume STA to perform a Plunging Attack, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter</strong></span><br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after a successful <span style="color:#f7ca2f"><strong>Dodge</strong></span> to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 4</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after this skill lands to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Basic Attack - Thread Shredding</strong></span><br>When in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, Lucy's <span style="color:#f7ca2f"><strong>Basic Attack</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding</strong></span>.<br>Perform up to 4 consecutive attacks, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>, considered Heavy Attack DMG.<br><br><span style="color:#a89969"><strong>Heavy Attack - Single Threading</strong></span><br>When in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, Lucy's <span style="color:#f7ca2f"><strong>Heavy Attack</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Heavy Attack - Single Threading</strong></span>.<br>Consume STA to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill while airborne to cast <span style="color:#f7ca2f"><strong>Mid-air Attack - Algorithm Compaction</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill while on the ground to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Heavy Attack - Dual Threading</strong></span><br>When in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span> and <span style="color:#f7ca2f"><strong><a href="#WwLink151105" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151105">Root Access</a></strong></span> reaches 100 points, <span style="color:#f7ca2f"><strong>Heavy Attack - Single Threading</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Heavy Attack - Dual Threading</strong></span>.<br>Consume STA and all <span style="color:#f7ca2f"><strong><a href="#WwLink151105" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151105">Root Access</a></strong></span> to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press or hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill while airborne to cast <span style="color:#f7ca2f"><strong>Heavy Attack - Multi-threading</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill while on the ground to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Heavy Attack - Multi-threading</strong></span><br>Consume STA to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and inflicting <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span> on the target. <span style="color:#f7ca2f"><strong><a href="#WwLink151106" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151106">SQL</a></strong></span> can be consumed for a 270% increase in this attack's DMG Multiplier.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Mid-air Attack - Algorithm Compaction</strong></span><br>When in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, Mid-air Attack is replaced with <span style="color:#f7ca2f"><strong>Mid-air Attack - Algorithm Compaction</strong></span>.<br>Consume STA to perform a Plunging Attack, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Dodge Counter - Algorithm Compaction</strong></span><br>When in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, <span style="color:#f7ca2f"><strong>Dodge Counter</strong></span> is replaced with <span style="color:#f7ca2f"><strong>Dodge Counter - Algorithm Compaction</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after a successful <span style="color:#f7ca2f"><strong>Dodge</strong></span> to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span>.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 3</strong></span>.</div>`,
  attacks: [
    {
      key: "BasicAttackStagecraftFormStage1DMG",
      label: "Basic Attack - Stagecraft Form Stage 1 DMG",
      talents: {
        "1": "16.44%",
        "2": "17.79%",
        "3": "19.14%",
        "4": "21.03%",
        "5": "22.38%",
        "6": "23.93%",
        "7": "26.08%",
        "8": "28.24%",
        "9": "30.40%",
        "10": "32.69%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStagecraftFormStage2DMG",
      label: "Basic Attack - Stagecraft Form Stage 2 DMG",
      talents: {
        "1": "15.18%*2",
        "2": "16.43%*2",
        "3": "17.67%*2",
        "4": "19.42%*2",
        "5": "20.66%*2",
        "6": "22.09%*2",
        "7": "24.09%*2",
        "8": "26.08%*2",
        "9": "28.07%*2",
        "10": "30.18%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStagecraftFormStage3DMG",
      label: "Basic Attack - Stagecraft Form Stage 3 DMG",
      talents: {
        "1": "12.82%*3",
        "2": "13.88%*3",
        "3": "14.93%*3",
        "4": "16.40%*3",
        "5": "17.45%*3",
        "6": "18.66%*3",
        "7": "20.34%*3",
        "8": "22.02%*3",
        "9": "23.71%*3",
        "10": "25.49%*3",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackStagecraftFormStage4DMG",
      label: "Basic Attack - Stagecraft Form Stage 4 DMG",
      talents: {
        "1": "64.38%",
        "2": "69.66%",
        "3": "74.94%",
        "4": "82.33%",
        "5": "87.61%",
        "6": "93.68%",
        "7": "102.13%",
        "8": "110.58%",
        "9": "119.02%",
        "10": "128.00%",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackStagecraftFormDMG",
      label: "Heavy Attack - Stagecraft Form DMG",
      talents: {
        "1": "40.62%*2",
        "2": "43.96%*2",
        "3": "47.29%*2",
        "4": "51.95%*2",
        "5": "55.28%*2",
        "6": "59.11%*2",
        "7": "64.44%*2",
        "8": "69.77%*2",
        "9": "75.10%*2",
        "10": "80.76%*2",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackStagecraftFormDMG",
      label: "Mid-air Attack - Stagecraft Form DMG",
      talents: {
        "1": "14.88%+22.32%",
        "2": "16.11%+24.16%",
        "3": "17.33%+25.99%",
        "4": "19.03%+28.55%",
        "5": "20.25%+30.38%",
        "6": "21.66%+32.48%",
        "7": "23.61%+35.41%",
        "8": "25.56%+38.34%",
        "9": "27.51%+41.27%",
        "10": "29.59%+44.38%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterStagecraftFormDMG",
      label: "Dodge Counter - Stagecraft Form DMG",
      talents: {
        "1": "24.82%*3",
        "2": "26.86%*3",
        "3": "28.90%*3",
        "4": "31.74%*3",
        "5": "33.78%*3",
        "6": "36.12%*3",
        "7": "39.38%*3",
        "8": "42.63%*3",
        "9": "45.89%*3",
        "10": "49.35%*3",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackBreakdownFormStage1DMG",
      label: "Basic Attack - Breakdown Form Stage 1 DMG",
      talents: {
        "1": "18.36%",
        "2": "19.87%",
        "3": "21.38%",
        "4": "23.48%",
        "5": "24.99%",
        "6": "26.72%",
        "7": "29.13%",
        "8": "31.54%",
        "9": "33.95%",
        "10": "36.51%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackBreakdownFormStage2DMG",
      label: "Basic Attack - Breakdown Form Stage 2 DMG",
      talents: {
        "1": "18.87%+7.08%*4",
        "2": "20.42%+7.66%*4",
        "3": "21.96%+8.24%*4",
        "4": "24.13%+9.05%*4",
        "5": "25.68%+9.63%*4",
        "6": "27.45%+10.30%*4",
        "7": "29.93%+11.23%*4",
        "8": "32.40%+12.15%*4",
        "9": "34.88%+13.08%*4",
        "10": "37.51%+14.07%*4",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackBreakdownFormStage3DMG",
      label: "Basic Attack - Breakdown Form Stage 3 DMG",
      talents: {
        "1": "31.38%",
        "2": "33.96%",
        "3": "36.53%",
        "4": "40.13%",
        "5": "42.71%",
        "6": "45.67%",
        "7": "49.78%",
        "8": "53.90%",
        "9": "58.02%",
        "10": "62.39%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackBreakdownFormStage4DMG",
      label: "Basic Attack - Breakdown Form Stage 4 DMG",
      talents: {
        "1": "17.88%+41.71%",
        "2": "19.34%+45.13%",
        "3": "20.81%+48.55%",
        "4": "22.86%+53.34%",
        "5": "24.33%+56.76%",
        "6": "26.01%+60.69%",
        "7": "28.36%+66.16%",
        "8": "30.70%+71.64%",
        "9": "33.05%+77.11%",
        "10": "35.54%+82.92%",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackBreakdownFormDMG",
      label: "Heavy Attack - Breakdown Form DMG",
      talents: {
        "1": "68.94%",
        "2": "74.60%",
        "3": "80.25%",
        "4": "88.17%",
        "5": "93.82%",
        "6": "100.32%",
        "7": "109.36%",
        "8": "118.41%",
        "9": "127.45%",
        "10": "137.06%",
      },
      type: "Heavy",
    },
    {
      key: "MidAirHeavyAttackBreakdownFormDMG",
      label: "Mid-air Heavy Attack - Breakdown Form DMG",
      talents: {
        "1": "14.88%+22.32%",
        "2": "16.11%+24.16%",
        "3": "17.33%+25.99%",
        "4": "19.03%+28.55%",
        "5": "20.25%+30.38%",
        "6": "21.66%+32.48%",
        "7": "23.61%+35.41%",
        "8": "25.56%+38.34%",
        "9": "27.51%+41.27%",
        "10": "29.59%+44.38%",
      },
      type: "Heavy",
    },
    {
      key: "DodgeCounterBreakdownFormDMG",
      label: "Dodge Counter - Breakdown Form DMG",
      talents: {
        "1": "54.36%",
        "2": "58.82%",
        "3": "63.28%",
        "4": "69.52%",
        "5": "73.98%",
        "6": "79.10%",
        "7": "86.24%",
        "8": "93.37%",
        "9": "100.50%",
        "10": "108.08%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackBreakdownFormStage1DMG",
      label: "Mid-air Attack - Breakdown Form Stage 1 DMG",
      talents: {
        "1": "18.36%",
        "2": "19.87%",
        "3": "21.38%",
        "4": "23.48%",
        "5": "24.99%",
        "6": "26.72%",
        "7": "29.13%",
        "8": "31.54%",
        "9": "33.95%",
        "10": "36.51%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackBreakdownFormStage2DMG",
      label: "Mid-air Attack - Breakdown Form Stage 2 DMG",
      talents: {
        "1": "18.87%+7.08%*4",
        "2": "20.42%+7.66%*4",
        "3": "21.96%+8.24%*4",
        "4": "24.13%+9.05%*4",
        "5": "25.68%+9.63%*4",
        "6": "27.45%+10.30%*4",
        "7": "29.93%+11.23%*4",
        "8": "32.40%+12.15%*4",
        "9": "34.88%+13.08%*4",
        "10": "37.51%+14.07%*4",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackBreakdownFormStage3DMG",
      label: "Mid-air Attack - Breakdown Form Stage 3 DMG",
      talents: {
        "1": "31.38%",
        "2": "33.96%",
        "3": "36.53%",
        "4": "40.13%",
        "5": "42.71%",
        "6": "45.67%",
        "7": "49.78%",
        "8": "53.90%",
        "9": "58.02%",
        "10": "62.39%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackBreakdownFormStage4DMG",
      label: "Mid-air Attack - Breakdown Form Stage 4 DMG",
      talents: {
        "1": "17.88%+41.71%",
        "2": "19.34%+45.13%",
        "3": "20.81%+48.55%",
        "4": "22.86%+53.34%",
        "5": "24.33%+56.76%",
        "6": "26.01%+60.69%",
        "7": "28.36%+66.16%",
        "8": "30.70%+71.64%",
        "9": "33.05%+77.11%",
        "10": "35.54%+82.92%",
      },
      type: "Basic",
    },
  ],
};
