export const introAttacks = {
  name: "Intro Skill: Outdated Hallucination",
  description: `<div>Attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and granting Resonators in the team <span style="color:#f7ca2f"><strong>Involuntary Sharing</strong></span>, allowing them to see targets behind obstacles for 25s. Additionally, <span style="color:#f7ca2f"><strong>Involuntary Sharing</strong></span> is enhanced on Rebecca, allowing her to lock onto targets behind obstacles. If Rebecca's turret is on the field, its Overload effect is activated, increasing its DMG dealt for 4s.<br>If Lucy is not in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span> after casting this skill, press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain time to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br>If Lucy is in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span> after casting this skill, press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> within a certain time to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br>After casting this skill, the next <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span> additionally grants 20 points of <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span>.</div>`,
  attacks: [
    {
      key: "ItsBeenAWhileDMG",
      label: "It's Been A While! DMG",
      talents: {
        "1": "52.62%",
        "2": "56.94%",
        "3": "61.25%",
        "4": "67.30%",
        "5": "71.61%",
        "6": "76.57%",
        "7": "83.48%",
        "8": "90.38%",
        "9": "97.28%",
        "10": "104.62%",
      },
      type: "Intro",
    },
    {
      key: "KnockKnockDMG",
      label: "Knock Knock DMG",
      talents: {
        "1": "26.02%*3",
        "2": "28.16%*3",
        "3": "30.29%*3",
        "4": "33.28%*3",
        "5": "35.41%*3",
        "6": "37.87%*3",
        "7": "41.28%*3",
        "8": "44.69%*3",
        "9": "48.11%*3",
        "10": "51.74%*3",
      },
      type: "Intro",
    },
  ],
};
