export const rotations: RotationPreset[] = [];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Spectro Celestial Light + Eternal Radiance + Shadow of Shattered Dreams. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceNightmareAdamSmasher","echoSet":"ShadowofShatteredDreams","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"RocksteadyGuardian","echoSet":"CelestialLight","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"VitreumDancer","echoSet":"EternalRadiance","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"Cruisewing","echoSet":"CelestialLight","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"4":{"type":1,"echo":"DiggyDuggy","echoSet":"EternalRadiance","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ReminiscenceNightmareAdamSmasher","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Spectro Celestial Light + Eternal Radiance + Shadow of Shattered Dreams. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ReminiscenceNightmareAdamSmasher","echoSet":"ShadowofShatteredDreams","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"CyanFeatheredHeron","echoSet":"CelestialLight","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HeavyAttackDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"Capitaneus","echoSet":"EternalRadiance","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"ClangBang","echoSet":"CelestialLight","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"4":{"type":1,"echo":"DiggyDuggy","echoSet":"EternalRadiance","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ReminiscenceNightmareAdamSmasher","rank":5}}
    }
];

