export const skillAttacks = {
  name: "Resonance Skill: Protocol Breach",
  description: `<div><span style="color:#a89969"><strong>Resonance Skill - Payload</strong></span><br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Payload</strong></span> to charge forward, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and inflicting <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span>. Upon hitting the target, a follow-up attack is automatically triggered, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and activating <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span>. If no target is hit during the charge, reduce the skill CD by 70%. If the charge is interrupted or not successfully cast, the skill CD is not reduced.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after the follow-up attack to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after follow-up attack lands to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Resonance Skill - Pulse Interference</strong></span><br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span> to cut through the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and briefly Stagnating the target, before granting <span style="color:#f7ca2f"><strong>Digital Handshake</strong></span>. <br><span style="color:#f7ca2f"><strong>Digital Handshake</strong></span>: When Lucy is not in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span> and is the active Resonator in the team, she gains <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> every second. This effect is removed when <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> reaches 100 points or when <span style="color:#f7ca2f"><strong>Resonance Liberation - Netrunner</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Liberation - Old Net Deep Dive</strong></span> is cast.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Resonance Skill - Deadlock</strong></span><br>When <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> reaches 100 points or Lucy is in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, <span style="color:#f7ca2f"><strong>Resonance Skill - Payload</strong></span> and <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span> are replaced with <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span>.<br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span> to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and inflicting <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span>, considered Heavy Attack DMG.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br>Reset the CD of <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span> after casting <span style="color:#f7ca2f"><strong>Resonance Liberation - Netrunner</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Liberation - Old Net Deep Dive</strong></span>.</div>`,
  attacks: [
    {
      key: "PhantomBubbleStagecraftFormDMG",
      label: "Phantom Bubble - Stagecraft Form DMG",
      talents: {
        "1": "8.76%*3+26.28%",
        "2": "9.48%*3+28.44%",
        "3": "10.20%*3+30.59%",
        "4": "11.21%*3+33.61%",
        "5": "11.93%*3+35.77%",
        "6": "12.75%*3+38.25%",
        "7": "13.90%*3+41.69%",
        "8": "15.05%*3+45.14%",
        "9": "16.20%*3+48.59%",
        "10": "17.42%*3+52.25%",
      },
      type: "Skill",
    },
    {
      key: "BeckonBreakdownFormDMG",
      label: "Beckon - Breakdown Form DMG",
      talents: {
        "1": "15.65%+7.30%*5",
        "2": "16.93%+7.90%*5",
        "3": "18.21%+8.50%*5",
        "4": "20.01%+9.34%*5",
        "5": "21.29%+9.94%*5",
        "6": "22.77%+10.63%*5",
        "7": "24.82%+11.58%*5",
        "8": "26.87%+12.54%*5",
        "9": "28.92%+13.50%*5",
        "10": "31.10%+14.52%*5",
      },
      type: "Skill",
    },
    {
      key: "BanishBreakdownFormStage1DMG",
      label: "Banish - Breakdown Form Stage 1 DMG",
      talents: {
        "1": "17.44%*3",
        "2": "18.88%*3",
        "3": "20.31%*3",
        "4": "22.31%*3",
        "5": "23.74%*3",
        "6": "25.38%*3",
        "7": "27.67%*3",
        "8": "29.96%*3",
        "9": "32.25%*3",
        "10": "34.68%*3",
      },
      type: "Liberation",
    },
    {
      key: "BanishBreakdownFormStage2DMG",
      label: "Banish - Breakdown Form Stage 2 DMG",
      talents: {
        "1": "56.34%",
        "2": "60.96%",
        "3": "65.58%",
        "4": "72.05%",
        "5": "76.67%",
        "6": "81.99%",
        "7": "89.38%",
        "8": "96.77%",
        "9": "104.16%",
        "10": "112.01%",
      },
      type: "Liberation",
    },
  ],
};
