export const skillAttacks = {
  name: "Resonance Skill: Protocol Breach",
  description: `<div><span style="color:#a89969"><strong>Resonance Skill - Payload</strong></span><br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Payload</strong></span> to charge forward, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and inflicting <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span>. Upon hitting the target, a follow-up attack is automatically triggered, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and activating <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span>. If no target is hit during the charge, reduce the skill CD by 70%. If the charge is interrupted or not successfully cast, the skill CD is not reduced.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after the follow-up attack to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br>Hold <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after follow-up attack lands to cast <span style="color:#f7ca2f"><strong>Heavy Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Resonance Skill - Pulse Interference</strong></span><br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span> to cut through the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and briefly Stagnating the target, before granting <span style="color:#f7ca2f"><strong>Digital Handshake</strong></span>. <br><span style="color:#f7ca2f"><strong>Digital Handshake</strong></span>: When Lucy is not in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span> and is the active Resonator in the team, she gains <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> every second. This effect is removed when <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> reaches 100 points or when <span style="color:#f7ca2f"><strong>Resonance Liberation - Netrunner</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Liberation - Old Net Deep Dive</strong></span> is cast.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack Stage 2</strong></span>.<br><br><span style="color:#a89969"><strong>Resonance Skill - Deadlock</strong></span><br>When <span style="color:#f7ca2f"><strong><a href="#WwLink151103" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151103">TCP</a></strong></span> reaches 100 points or Lucy is in <span style="color:#f7ca2f"><strong><a href="#WwLink151102" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151102">Algorithm Compaction</a></strong></span>, <span style="color:#f7ca2f"><strong>Resonance Skill - Payload</strong></span> and <span style="color:#f7ca2f"><strong>Resonance Skill - Pulse Interference</strong></span> are replaced with <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span>.<br>Cast <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span> to attack the target, dealing <span style="color:#f8e56c"><strong>Spectro DMG</strong></span> and inflicting <span style="color:#f7ca2f"><strong><a href="#WwLink151101" class="underline decoration-dotted underline-offset-2 hover:cursor-help hover:text-accent" data-ww-link-id="151101">Hack - Shifting</a></strong></span>, considered Heavy Attack DMG.<br>Press <span style="color:#f7ca2f"><strong>Normal Attack</strong></span> shortly after casting this skill to cast <span style="color:#f7ca2f"><strong>Basic Attack - Thread Shredding Stage 2</strong></span>.<br>Reset the CD of <span style="color:#f7ca2f"><strong>Resonance Skill - Deadlock</strong></span> after casting <span style="color:#f7ca2f"><strong>Resonance Liberation - Netrunner</strong></span> or <span style="color:#f7ca2f"><strong>Resonance Liberation - Old Net Deep Dive</strong></span>.</div>`,
  attacks: [
    {
      key: "ResonanceSkillPayloadChargeDMG",
      label: "Resonance Skill - Payload Charge DMG",
      talents: {
        "1": "10.08%+5.04%",
        "2": "10.91%+5.46%",
        "3": "11.74%+5.87%",
        "4": "12.90%+6.45%",
        "5": "13.72%+6.86%",
        "6": "14.67%+7.34%",
        "7": "15.99%+8.00%",
        "8": "17.32%+8.66%",
        "9": "18.64%+9.32%",
        "10": "20.05%+10.03%",
      },
      type: "Basic",
    },
    {
      key: "ResonanceSkillPulseInterferenceDMG",
      label: "Resonance Skill - Pulse Interference DMG",
      talents: {
        "1": "15.52%*2+31.04%*3+31.04%",
        "2": "16.80%*2+33.59%*3+33.59%",
        "3": "18.07%*2+36.14%*3+36.14%",
        "4": "19.85%*2+39.70%*3+39.70%",
        "5": "21.12%*2+42.24%*3+42.24%",
        "6": "22.59%*2+45.17%*3+45.17%",
        "7": "24.62%*2+49.24%*3+49.24%",
        "8": "26.66%*2+53.32%*3+53.32%",
        "9": "28.70%*2+57.39%*3+57.39%",
        "10": "30.86%*2+61.72%*3+61.72%",
      },
      type: "Basic",
    },
    {
      key: "ResonanceSkillDeadlockDMG",
      label: "Resonance Skill - Deadlock DMG",
      talents: {
        "1": "26.00%+104.00%",
        "2": "28.14%+112.53%",
        "3": "30.27%+121.06%",
        "4": "33.25%+133.00%",
        "5": "35.39%+141.53%",
        "6": "37.84%+151.34%",
        "7": "41.25%+164.98%",
        "8": "44.66%+178.62%",
        "9": "48.07%+192.27%",
        "10": "51.70%+206.77%",
      },
      type: "Heavy",
    },
    {
      key: "ResonanceSkillPayloadFollowUpAttackDMG",
      label: "Resonance Skill - Payload Follow-Up Attack DMG",
      talents: {
        "1": "20.16%+5.04%+10.08%",
        "2": "21.82%+5.46%+10.91%",
        "3": "23.47%+5.87%+11.74%",
        "4": "25.79%+6.45%+12.90%",
        "5": "27.44%+6.86%+13.72%",
        "6": "29.34%+7.34%+14.67%",
        "7": "31.98%+8.00%+15.99%",
        "8": "34.63%+8.66%+17.32%",
        "9": "37.27%+9.32%+18.64%",
        "10": "40.09%+10.03%+20.05%",
      },
      type: "Basic",
    },
    {
      key: "SequenceNode2TheBlackwallthePasttheEscape",
      label: "S2: The Blackwall, the Past, the Escape",
      talents: {
        "1": "450.00%",
        "2": "450.00%",
        "3": "450.00%",
        "4": "450.00%",
        "5": "450.00%",
        "6": "450.00%",
        "7": "450.00%",
        "8": "450.00%",
        "9": "450.00%",
        "10": "450.00%",
      },
      type: "Heavy",
      requiresResonanceChain: "SequenceNode2TheBlackwallthePasttheEscape",
    },
  ],
};
