export const rotations: RotationPreset[] = [
  {
    name: `Prydwen: DMx3`,
    description: `TacticalKush was here :3`,
    author: `Tactical Kush
`,
    data: {
      name: "Prydwen: DMx3",
      description: "TacticalKush was here :3",
      actions: [
        {
          order: 1,
          key: "WantedOutlawSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "PhantomEtchingSkillDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "DeathMessengerDamage",
          type: "forteCircuit",
          count: "3",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "HoundsRoarPart1DMG",
          type: "liberation",
          count: "4",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "HoundsRoarPart2DMG",
          type: "liberation",
          count: "4",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "HoundsRoarPart3DMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "ExterminationOrderPart1DMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "ExterminationOrderPart2DMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "ShadowyRaidOutroSkillDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];
