export const forteCircuitAttacks = {
  name: "Forte Circuit: Ebb and Flow",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Lunar Cycle</span></span><br>Iuno can activate Lunar Cycle by casting <span class="ingame-Highlight">Resonance Skill - Closing Refrain</span> or <span class="ingame-Highlight">Resonance Liberation</span>.<br>Lunar Cycle has two states: <span class="ingame-Highlight">Half Moon</span> and <span class="ingame-Highlight">New Moon</span>. By default, Iuno enters the <span class="ingame-Highlight">Half Moon</span> state when activating Lunar Cycle and can switch between the two states by casting <span class="ingame-Highlight">Heavy Attack - Flux</span>.<br>When in Lunar Cycle:<br>- Iuno's Jump is replaced with <span class="ingame-Highlight">Heavy Attack - Flux</span>. STA won't recover when Iuno is in mid-air. <br>- Iuno's movement becomes <span class="ingame-Highlight">Meandering</span>, which consumes STA continuously in mid-air to move in a unique manner.<br>- Performing environmental interactions, using Utilities, or holding Jump will end <span class="ingame-Highlight">Lunar Cycle</span>.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Lunar Cycle - Half Moon</span></span><br>Iuno attacks using the Moonring, restoring <span class="ingame-Highlight"><a onclick="showTermExplan(141003)" class="ingame-term-desc">Sentience</a></span> on hit.<br>She can use <span class="ingame-Highlight">Heavy Attack - Flux: Moonbow</span> to deal <span class="ingame-Wind">Aero DMG</span> (considered as Resonance Liberation DMG) and switch to <span class="ingame-Highlight">Lunar Cycle - New Moon</span>.<br><span class="ingame-Highlight">Heavy Attack - Flux: Moonbow</span> can be cast in mid-air.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Lunar Cycle - New Moon</span></span><br>Iuno attacks using the Moonbow. While in this state, casting <span class="ingame-Highlight">Moonbow - Basic Attack</span>, <span class="ingame-Highlight">Resonance Skill - Arc Beyond the Edge</span>, or <span class="ingame-Highlight">Moonbow - Dodge Counter</span> consumes <span class="ingame-Highlight">Sentience</span> to increase the skill's DMG Multiplier, restore additional Concerto Energy, and heal nearby Resonators in the team.<br>Iuno can use <span class="ingame-Highlight">Heavy Attack - Flux: Moonring</span> to deal <span class="ingame-Wind">Aero DMG</span> (considered as Resonance Liberation DMG) and switch to <span class="ingame-Highlight">Lunar Cycle - Half Moon</span>.<br><span class="ingame-Highlight">Heavy Attack - Flux: Moonring</span> can be cast in mid-air.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Absolute Fullness</span></span><br>When Iuno's Concerto Energy is full, her Heavy Attack is replaced with <span class="ingame-Highlight">Absolute Fullness</span>.<br>Casting Absolute Fullness ends <span class="ingame-Highlight">Lunar Cycle</span>, provides healing for nearby Resonators in the team, deals <span class="ingame-Wind">Aero DMG</span> to nearby targets (considered as Resonance Liberation DMG), and conjures a <span class="ingame-Highlight">Full Moon</span> domain at her location. This effect can be triggered once every 25s.<br>Can be cast in mid-air.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Full Moon Domain</span></span><br>Resonators inside the domain periodically restore HP and STA.<br>Gaining a Shield inside the domain grants 1 stack of <span class="ingame-Highlight">Blessing of the Wan Light</span>. This effect can be triggered once every 0.5s.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Blessing of the Wan Light</span></span><br>The receiving Resonator gains 4% all DMG Amplification for 10s, stacking up to 10 times. Gaining new stacks resets the duration. This effect ends early if the receiving Resonator is switched off the field.<br><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Sentience</span></span><br>Iuno can hold up to 100 points of <span class="ingame-Highlight">Sentience</span>.<br>Casting Intro Skill restores 40 points of <span class="ingame-Highlight">Sentience</span>.<br>Casting Resonance Liberation restores 60 points of <span class="ingame-Highlight">Sentience</span>.<br>Casting <span class="ingame-Highlight">Closing Refrain</span> or <span class="ingame-Highlight">Unfinished Refrain</span> restores 25 points of <span class="ingame-Highlight">Sentience</span>.<br>When Iuno is in <span class="ingame-Highlight">Lunar Cycle</span>, Moonring - Basic Attack, Moonring - Dodge Counter, and Mid-air Attack restore <span class="ingame-Highlight">Sentience</span> on hit.</div>`,
  attacks: [
    {
      key: "FluxMoonbowDMG",
      label: "Flux - Moonbow DMG",
      talents: {
        "1": "126.00%",
        "2": "136.34%",
        "3": "146.67%",
        "4": "161.13%",
        "5": "171.47%",
        "6": "183.35%",
        "7": "199.88%",
        "8": "216.41%",
        "9": "232.94%",
        "10": "250.51%",
      },
      type: "Liberation",
    },
    {
      key: "FluxMoonringDMG",
      label: "Flux - Moonring DMG",
      talents: {
        "1": "39.83%*4",
        "2": "43.10%*4",
        "3": "46.36%*4",
        "4": "50.93%*4",
        "5": "54.20%*4",
        "6": "57.95%*4",
        "7": "63.18%*4",
        "8": "68.40%*4",
        "9": "73.63%*4",
        "10": "79.18%*4",
      },
      type: "Liberation",
    },
    {
      key: "EnhancedMoonbowBasicAttack1DMG",
      label: "Enhanced Moonbow - Basic Attack 1 DMG",
      talents: {
        "1": "103.60%",
        "2": "112.10%",
        "3": "120.60%",
        "4": "132.49%",
        "5": "140.98%",
        "6": "150.75%",
        "7": "164.35%",
        "8": "177.94%",
        "9": "191.53%",
        "10": "205.97%",
      },
      type: "Liberation",
    },
    {
      key: "EnhancedMoonbowBasicAttack2DMG",
      label: "Enhanced Moonbow - Basic Attack 2 DMG",
      talents: {
        "1": "48.00%*3",
        "2": "51.94%*3",
        "3": "55.88%*3",
        "4": "61.39%*3",
        "5": "65.32%*3",
        "6": "69.85%*3",
        "7": "76.15%*3",
        "8": "82.44%*3",
        "9": "88.74%*3",
        "10": "95.43%*3",
      },
      type: "Liberation",
    },
    {
      key: "EnhancedMoonbowBasicAttack3DMG",
      label: "Enhanced Moonbow - Basic Attack 3 DMG",
      talents: {
        "1": "134.00%*2",
        "2": "144.99%*2",
        "3": "155.98%*2",
        "4": "171.36%*2",
        "5": "182.35%*2",
        "6": "194.99%*2",
        "7": "212.57%*2",
        "8": "230.15%*2",
        "9": "247.73%*2",
        "10": "266.41%*2",
      },
      type: "Liberation",
    },
    {
      key: "EnhancedMoonbowDodgeCounterDMG",
      label: "Enhanced Moonbow - Dodge Counter DMG",
      talents: {
        "1": "78.67%*3",
        "2": "85.12%*3",
        "3": "91.57%*3",
        "4": "100.60%*3",
        "5": "107.05%*3",
        "6": "114.47%*3",
        "7": "124.79%*3",
        "8": "135.11%*3",
        "9": "145.44%*3",
        "10": "156.40%*3",
      },
      type: "Liberation",
    },
    {
      key: "EnhancedArcBeyondtheEdgeDMG",
      label: "Enhanced Arc Beyond the Edge DMG",
      talents: {
        "1": "160.55%*2",
        "2": "173.72%*2",
        "3": "186.89%*2",
        "4": "205.32%*2",
        "5": "218.48%*2",
        "6": "233.62%*2",
        "7": "254.69%*2",
        "8": "275.75%*2",
        "9": "296.81%*2",
        "10": "319.19%*2",
      },
      type: "Liberation",
    },
    {
      key: "MoonbowBasicAttack1Healing",
      label: "Moonbow - Basic Attack 1 Healing",
      talents: {
        "1": "13.03%",
        "2": "14.10%",
        "3": "15.17%",
        "4": "16.67%",
        "5": "17.73%",
        "6": "18.96%",
        "7": "20.67%",
        "8": "22.38%",
        "9": "24.09%",
        "10": "25.91%",
      },
      type: "Healing",
    },
    {
      key: "MoonbowBasicAttack2Healing",
      label: "Moonbow - Basic Attack 2 Healing",
      talents: {
        "1": "13.03%",
        "2": "14.10%",
        "3": "15.17%",
        "4": "16.67%",
        "5": "17.73%",
        "6": "18.96%",
        "7": "20.67%",
        "8": "22.38%",
        "9": "24.09%",
        "10": "25.91%",
      },
      type: "Healing",
    },
    {
      key: "MoonbowBasicAttack3Healing",
      label: "Moonbow - Basic Attack 3 Healing",
      talents: {
        "1": "24.43%",
        "2": "26.44%",
        "3": "28.44%",
        "4": "31.24%",
        "5": "33.25%",
        "6": "35.55%",
        "7": "38.75%",
        "8": "41.96%",
        "9": "45.16%",
        "10": "48.57%",
      },
      type: "Healing",
    },
    {
      key: "MoonbowDodgeCounterHealing",
      label: "Moonbow - Dodge Counter Healing",
      talents: {
        "1": "16.29%",
        "2": "17.63%",
        "3": "18.96%",
        "4": "20.83%",
        "5": "22.17%",
        "6": "23.70%",
        "7": "25.84%",
        "8": "27.97%",
        "9": "30.11%",
        "10": "32.38%",
      },
      type: "Healing",
    },
    {
      key: "ArcBeyondtheEdgeHealing",
      label: "Arc Beyond the Edge Healing",
      talents: {
        "1": "24.43%",
        "2": "26.44%",
        "3": "28.44%",
        "4": "31.24%",
        "5": "33.25%",
        "6": "35.55%",
        "7": "38.75%",
        "8": "41.96%",
        "9": "45.16%",
        "10": "48.57%",
      },
      type: "Healing",
    },
    {
      key: "AbsoluteFullnessDMG",
      label: "Absolute Fullness DMG",
      talents: {
        "1": "80.00%",
        "2": "86.56%",
        "3": "93.12%",
        "4": "102.31%",
        "5": "108.87%",
        "6": "116.41%",
        "7": "126.91%",
        "8": "137.40%",
        "9": "147.90%",
        "10": "159.05%",
      },
      type: "Liberation",
    },
    {
      key: "AbsoluteFullnessHealing",
      label: "Absolute Fullness Healing",
      talents: {
        "1": "97.71%",
        "2": "105.73%",
        "3": "113.74%",
        "4": "124.96%",
        "5": "132.97%",
        "6": "142.18%",
        "7": "155.00%",
        "8": "167.82%",
        "9": "180.64%",
        "10": "194.26%",
      },
      type: "Healing",
    },
    {
      key: "FullMoonDomainHealing",
      label: "Full Moon Domain Healing",
      talents: {
        "1": "16.29%",
        "2": "17.63%",
        "3": "18.96%",
        "4": "20.83%",
        "5": "22.17%",
        "6": "23.70%",
        "7": "25.84%",
        "8": "27.97%",
        "9": "30.11%",
        "10": "32.38%",
      },
      type: "Healing",
    },
    {
      key: "SequenceNode4RainySeasonDwellinMyEyes",
      label: "Waxing Ascent",
      talents: {
        "1": "160%",
        "2": "160%",
        "3": "160%",
        "4": "160%",
        "5": "160%",
        "6": "160%",
        "7": "160%",
        "8": "160%",
        "9": "160%",
        "10": "160%",
      },
      type: "Shield",
      requiresResonanceChain: "SequenceNode4RainySeasonDwellinMyEyes",
    },
  ],
};
