export const liberationAttacks = {
  name: "Resonance Liberation: Sunward Conquest",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Liberation - Sword of Eternal Oath</span></span><br><span class="ingame-Highlight">Press and release Resonance Liberation</span> to cast this skill. Augusta will sweep her Broadblade forward, dealing <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Liberation - Sublime is the Sun</span></span><br>When <a onclick="showTermExplan(130604)" class="ingame-term-desc">Majesty</a> reaches 2 stacks, <span class="ingame-Highlight">hold Resonance Liberation</span> to cast <span class="ingame-Highlight">Resonance Liberation - Sublime is the Sun</span>. Casting <span class="ingame-Highlight">Resonance Liberation - Sublime is the Sun</span> costs no Resonance Energy but 2 stacks of Majesty instead.<br>- When casting <span class="ingame-Highlight">Resonance Liberation - Sublime is the Sun</span>, Augusta generates the <span class="ingame-Highlight"><a onclick="showTermExplan(130605)" class="ingame-term-desc">Ruler's Realm</a></span> and enters the <span class="ingame-Highlight"><a onclick="showTermExplan(130606)" class="ingame-term-desc">Sworn Allegiance</a></span> state for 7s. Within this duration, time is temporarily stopped, and <span class="ingame-Highlight">Resonator switching</span> is disabled. Only <span class="ingame-Highlight">Sublime is the Sun - Sunborne</span>, <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span>, and <span class="ingame-Highlight">Dodge</span> can be performed in the <span class="ingame-Highlight">Sworn Allegiance</span> state. <span class="ingame-Highlight">Mid-air Attack</span> is available while airborne.<br>- In the <span class="ingame-Highlight">Sworn Allegiance</span> state, <span class="ingame-Highlight">press</span> or <span class="ingame-Highlight">hold Normal Attack</span> to cast <span class="ingame-Highlight">Sublime is the Sun - Sunborne</span>. Augusta can walk on water without consuming STA in this state.<br>- Performing <span class="ingame-Highlight">environmental, gameplay, or other interactions</span> ends <span class="ingame-Highlight">Sworn Allegiance</span> without triggering <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Sublime is the Sun - Sunborne</span></span><br>Deal <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG. After casting <span class="ingame-Highlight">Sublime is the Sun - Sunborne</span> 9 times, <span class="ingame-Highlight">press Normal Attack or Resonance Liberation</span> to perform <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Sublime is the Sun - Everbright Protector</span></span><br>Deal <span class="ingame-Thunder">Electro DMG</span>, considered as Heavy Attack DMG. Casting <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span> ends the <span class="ingame-Highlight"><a onclick="showTermExplan(130606)" class="ingame-term-desc">Sworn Allegiance</a></span> state and consumes all stacks of <a onclick="showTermExplan(130601)" class="ingame-term-desc">Crown of Wills</a> later. All other Resonators in the team will be made to leave the field.<br>- When <span class="ingame-Highlight">Sworn Allegiance</span> ends, <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span> is automatically cast.<br>- During <span class="ingame-Highlight">Sworn Allegiance</span>, <span class="ingame-Highlight">hold Resonance Liberation</span> to cast <span class="ingame-Highlight">Sublime is the Sun - Everbright Protector</span> early.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Ruler's Realm</span></span><br>- <span class="ingame-Highlight">Ruler's Realm</span> lasts for 30s.<br>- When Resonators in the team cast <span class="ingame-Highlight">Intro Skill</span> within <span class="ingame-Highlight">Ruler's Realm</span>, they gain a shield equal to 650 + 5% of Augusta's Max HP for 10s. This effect is unstackable. This Shield will not be passed on to the incoming Resonator.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Majesty</span></span><br>Augusta can hold up to 2 stacks of Majesty.<br>- 1 stack of Majesty is obtained when casting <span class="ingame-Highlight">Resonance Skill - Undying Sunlight: Plunge</span>.<br>- 1 stack of Majesty is obtained when other Resonators in the team cast <span class="ingame-Highlight">Outro Skill</span> under the effect of Augusta's <span class="ingame-Highlight">Outro Skill - Battlesong of the Unyielding</span>.</div>`,
  attacks: [
    {
      key: "SwordofEternalOathDMG",
      label: "Sword of Eternal Oath DMG",
      talents: {
        "1": "16.59%*2+66.36%*3+16.59%*2+287.56%",
        "2": "17.96%*2+71.81%*3+17.96%*2+311.14%",
        "3": "19.32%*2+77.25%*3+19.32%*2+334.72%",
        "4": "21.22%*2+84.87%*3+21.22%*2+367.74%",
        "5": "22.58%*2+90.31%*3+22.58%*2+391.32%",
        "6": "24.15%*2+96.57%*3+24.15%*2+418.43%",
        "7": "26.32%*2+105.27%*3+26.32%*2+456.16%",
        "8": "28.50%*2+113.98%*3+28.50%*2+493.89%",
        "9": "30.67%*2+122.68%*3+30.67%*2+531.62%",
        "10": "32.99%*2+131.94%*3+32.99%*2+571.7%",
      },
      type: "Heavy",
    },
    {
      key: "SublimeistheSunSunborneDMG",
      label: "Sublime is the Sun - Sunborne DMG",
      talents: {
        "1": "60.00%",
        "2": "64.92%",
        "3": "69.84%",
        "4": "76.73%",
        "5": "81.65%",
        "6": "87.31%",
        "7": "95.18%",
        "8": "103.05%",
        "9": "110.93%",
        "10": "119.29%",
      },
      type: "Heavy",
    },
    {
      key: "SublimeistheSunEverbrightProtectorDMG",
      label: "Sublime is the Sun - Everbright Protector DMG",
      talents: {
        "1": "120.00%+450.00%+3.00%*10",
        "2": "129.84%+486.90%+3.25%*10",
        "3": "139.68%+523.80%+3.50%*10",
        "4": "153.46%+575.46%+3.84%*10",
        "5": "163.30%+612.36%+4.09%*10",
        "6": "174.62%+654.80%+4.37%*10",
        "7": "190.36%+713.84%+4.76%*10",
        "8": "206.10%+772.88%+5.16%*10",
        "9": "221.85%+831.92%+5.55%*10",
        "10": "238.58%+894.65%+5.97%*10",
      },
      type: "Heavy",
    },
  ],
};
