export const rotations: RotationPreset[] = [
  {
    name: `Iuno w/ Sig (default 10 Blessing stacks 5 wp stacks)`,
    description: `Intro only 6 stacks: -(10-6)x4=-16 DMG Amplify\n(WP (Liberation DMG' DEF Ignore 7.2)+set Crown ATK 6 CD 4)' stacks to 5: Intro 1 ULT 2 Flux 3 Basic1 4: -7.2x3=-21.6 x2=-14.4`,
    author: `Liam`,
    data: {
      name: "Iuno w/ Sig (default 10 Blessing stacks 5 wp stacks)",
      description:
        "Intro only 6 stacks: -(10-6)x4=-16 DMG Amplify\n(WP (Liberation DMG' DEF Ignore 7.2)+set Crown ATK 6 CD 4)' stacks to 5: Intro 1 ULT 2 Flux 3 Basic1 4: -7.2x3=-21.6 x2=-14.4\n",
      actions: [
        {
          order: 1,
          key: "IlluminatedManifestationDMG",
          type: "intro",
          count: 1,
          buffs: [
            { modifier: "DMGDeepen", modifierValue: "-16" },
            { modifier: "ATK", modifierValue: "-24" },
            { modifier: "CritDMG", modifierValue: "-16" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "BeneathLunarTidesDMG",
          type: "liberation",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-21.6" },
            { modifier: "ATK", modifierValue: "-18" },
            { modifier: "CritDMG", modifierValue: "-12" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "FluxMoonbowDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-14.4" },
            { modifier: "ATK", modifierValue: "-12" },
            { modifier: "CritDMG", modifierValue: "-8" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "EnhancedMoonbowBasicAttack1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-7.2" },
            { modifier: "ATK", modifierValue: "-6" },
            { modifier: "CritDMG", modifierValue: "-4" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "EnhancedMoonbowBasicAttack2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "EnhancedMoonbowBasicAttack3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "AbsoluteFullnessDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "FromGloomtoGleamDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: `MDPS Rotation`,
    description: ``,
    author: `Prydwen`,
    data: {
      name: "MDPS Rotation",
      description: "",
      actions: [
        {
          order: 1,
          key: "IlluminatedManifestationDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "ClosingRefrainDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "FluxMoonbowDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "BeneathLunarTidesDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "EnhancedMoonbowBasicAttack1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "EnhancedMoonbowBasicAttack2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "EnhancedMoonbowBasicAttack3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "MoonbowBasicAttack1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "MoonbowBasicAttack2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "MoonbowBasicAttack3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "FromGloomtoGleamDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];

export const echoes = [];
