export const rotations: RotationPreset[] = [
  {
    name: `Iuno w/ Sig (default 10 Blessing stacks 5 wp stacks)`,
    description: `Intro only 6 stacks: -(10-6)x4=-16 DMG Amplify\n(WP (Liberation DMG' DEF Ignore 7.2)+set Crown ATK 6 CD 4)' stacks to 5: Intro 1 ULT 2 Flux 3 Basic1 4: -7.2x3=-21.6 x2=-14.4`,
    author: `Liam`,
    data: {
      name: "Iuno w/ Sig (default 10 Blessing stacks 5 wp stacks)",
      description:
        "Intro only 6 stacks: -(10-6)x4=-16 DMG Amplify\n(WP (Liberation DMG' DEF Ignore 7.2)+set Crown ATK 6 CD 4)' stacks to 5: Intro 1 ULT 2 Flux 3 Basic1 4: -7.2x3=-21.6 x2=-14.4\n",
      actions: [
        {
          order: 1,
          key: "IlluminatedManifestationDMG",
          type: "intro",
          count: 1,
          buffs: [
            { modifier: "DMGDeepen", modifierValue: "-16" },
            { modifier: "ATK", modifierValue: "-24" },
            { modifier: "CritDMG", modifierValue: "-16" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "BeneathLunarTidesDMG",
          type: "liberation",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-21.6" },
            { modifier: "ATK", modifierValue: "-18" },
            { modifier: "CritDMG", modifierValue: "-12" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "FluxMoonbowDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-14.4" },
            { modifier: "ATK", modifierValue: "-12" },
            { modifier: "CritDMG", modifierValue: "-8" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "EnhancedMoonbowBasicAttack1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [
            { modifier: "DefIgnore", modifierValue: "-7.2" },
            { modifier: "ATK", modifierValue: "-6" },
            { modifier: "CritDMG", modifierValue: "-4" },
          ],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "EnhancedMoonbowBasicAttack2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "EnhancedMoonbowBasicAttack3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "AbsoluteFullnessDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "FromGloomtoGleamDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: `MDPS Rotation`,
    description: ``,
    author: `Prydwen`,
    data: {
      name: "MDPS Rotation",
      description: "",
      actions: [
        {
          order: 1,
          key: "IlluminatedManifestationDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "ClosingRefrainDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "FluxMoonbowDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "BeneathLunarTidesDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "EnhancedMoonbowBasicAttack1DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "EnhancedMoonbowBasicAttack2DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "EnhancedMoonbowBasicAttack3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "EnhancedArcBeyondtheEdgeDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "MoonbowBasicAttack1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "MoonbowBasicAttack2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "MoonbowBasicAttack3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "FromGloomtoGleamDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Aero Crown of Valor + Gusts of Welkin. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"LadyoftheSea","echoSet":"CrownofValor","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Hurriclaw","echoSet":"CrownofValor","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"NightmareVioletFeatheredHeron","echoSet":"CrownofValor","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"AeroDrake","echoSet":"GustsofWelkin","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"LaGuardia","echoSet":"GustsofWelkin","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"LadyoftheSea","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Aero Crown of Valor + Gusts of Welkin. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"LadyoftheSea","echoSet":"CrownofValor","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Hurriclaw","echoSet":"CrownofValor","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"NightmareVioletFeatheredHeron","echoSet":"CrownofValor","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"AeroDrake","echoSet":"GustsofWelkin","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"Sacerdos","echoSet":"GustsofWelkin","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"LadyoftheSea","rank":5}}
    },
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Aero Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"ViridblazeSaurian","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"StonewallBracer","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"3":{"type":1,"echo":"Diamondclaw","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"Cruisewing","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Aero Moonlit Clouds Build 40.5% CR, 81% CD, 17.2% ATK, 17.2% Liberation, 100 ATK, 27.6% ER`,
        author: `thundertooth`,
        data: {"echoes":{"0":{"type":4,"echo":"ImpermanenceHeron","echoSet":"MoonlitClouds","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"1":{"type":3,"echo":"Carapace","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},"2":{"type":3,"echo":"StonewallBracer","echoSet":"MoonlitClouds","stat":"Aero","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"3":{"type":1,"echo":"GlacioPrism","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP","echoSubStatsValue4":8.6,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":50},"4":{"type":1,"echo":"FissionJunrock","echoSet":"MoonlitClouds","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9}},"mainEcho":{"echo":"ImpermanenceHeron","rank":5}}
    }
];
