export const forteCircuitAttacks = {
  name: "Forte Circuit: Forever Seeking",
  description: `<div class="text-sm font-normal">Resonance Skill - Decipher<br>When Capacity reaches 100, Resonance Skill <span class="Highlight"><strong>Deduction</strong></span> is replaced with Resonance Skill <span class="Highlight"><strong>Decipher</strong></span>.<br>Consume 100 Capacity to cast Resonance Skill <span class="Highlight"><strong>Decipher</strong></span>, dealing <span class="Thunder"><strong>Electro DMG</strong></span>, considered as Resonance Liberation DMG.<br>Resonance Skill - Law of Reigns<br>When in <span class="Highlight"><strong>Intuition</strong></span> triggered by Resonance Liberation and Performance Capacity reaches 5, Resonance Skill <span class="Highlight"><strong>Divergence</strong></span> is replaced with Resonance Skill <span class="Highlight"><strong>Law of Reigns</strong></span>.<br>Consume 5 Performance Capacity to cast Resonance Skill <span class="Highlight"><strong>Law of Reigns</strong></span>, dealing <span class="Thunder"><strong>Electro DMG</strong></span>, considered as Resonance Liberation DMG.<br>Mid-air Attack - Revamp<br>Shortly after casting Resonance Skill <span class="Highlight"><strong>Decipher</strong></span> or Resonance Skill <span class="Highlight"><strong>Divergence</strong></span>, use <span class="Highlight"><strong>Basic Attack</strong></span> to perform Mid-air Attack <span class="Highlight"><strong>Revamp</strong></span> at the cost of STA, dealing <span class="Thunder"><strong>Electro DMG</strong></span>, considered as Resonance Liberation DMG.<br>Capacity<br>Xiangli Yao can hold up to 100 Capacity.<br>Every Normal Attack <span class="Highlight"><strong>Probe</strong></span> on hit grants Capacity.<br>Every Resonance Skill <span class="Highlight"><strong>Deduction</strong></span> on hit grants Capacity.<br>Performance Capacity<br>Xiangli Yao can hold up to 5 Performance Capacity.<br>When in <span class="Highlight"><strong>Intuition</strong></span> triggered by Resonance Liberation:<br>Obtain 1 Performance Capacity when Stage 1 of Basic Attack <span class="Highlight"><strong>Pivot - Impale</strong></span> hits a target.<br>Obtain 2 Performance Capacity when Stage 2 or 3 of Basic Attack <span class="Highlight"><strong>Pivot - Impale</strong></span> hits a target.<br>Obtain 2 Performance Capacity for every Resonance Skill <span class="Highlight"><strong>Divergence</strong></span> on hit.<br>Obtain 3 Performance Capacity for every Mid-air Attack <span class="Highlight"><strong>Revamp</strong></span> on hit.<br>Obtain 2 Performance Capacity for every Dodge Counter <span class="Highlight"><strong>Unfathomed</strong></span> on hit.</div>`,
  attacks: [
    {
      key: "DecipherDMG",
      label: "Decipher DMG",
      talents: {
        "1": "200.10%",
        "2": "216.51%",
        "3": "232.92%",
        "4": "255.89%",
        "5": "272.30%",
        "6": "291.17%",
        "7": "317.42%",
        "8": "343.68%",
        "9": "369.93%",
        "10": "397.82%",
      },
      type: "Liberation",
    },
    {
      key: "LawofReignsDMG",
      label: "Law of Reigns DMG",
      talents: {
        "1": "48.15%*4 + 128.40%",
        "2": "52.10%*4 + 138.93%",
        "3": "56.05%*4 + 149.46%",
        "4": "61.58%*4 + 164.20%",
        "5": "65.53%*4 + 174.73%",
        "6": "70.07%*4 + 186.84%",
        "7": "76.39%*4 + 203.69%",
        "8": "82.70%*4 + 220.53%",
        "9": "89.02%*4 + 237.38%",
        "10": "95.73%*4 + 255.28%",
      },
      type: "Liberation",
    },
    {
      key: "RevampDMG",
      label: "Revamp DMG",
      talents: {
        "1": "11.00%*4 + 33.00%*2",
        "2": "11.91%*4 + 35.71%*2",
        "3": "12.81%*4 + 38.42%*2",
        "4": "14.07%*4 + 42.21%*2",
        "5": "14.97%*4 + 44.91%*2",
        "6": "16.01%*4 + 48.02%*2",
        "7": "17.45%*4 + 52.35%*2",
        "8": "18.90%*4 + 56.68%*2",
        "9": "20.34%*4 + 61.01%*2",
        "10": "21.87%*4 + 65.61%*2",
      },
      type: "Liberation",
    },
    {
      key: "SequenceNode1ProdigyofProteges",
      label: "Sequence Node 1: Prodigy of Protégés",
      talents: {
        "1": "25.68%*6",
        "2": "27.79%*6",
        "3": "29.90%*6",
        "4": "32.84%*6",
        "5": "34.95%*6",
        "6": "37.37%*6",
        "7": "40.74%*6",
        "8": "44.11%*6",
        "9": "47.48%*6",
        "10": "51.06%*6",
      },
      type: "Liberation",
      requiresResonanceChain: "SequenceNode1ProdigyofProteges",
    },
  ],
};
