export const forteCircuitAttacks = {
  name: "Forte Circuit: Forever Seeking",
  description: `<div class="skilldescription"><span class="Title">Resonance Skill - Decipher</span><br>When obtaining 100 Capacity, Resonance Skill <span class="Highlight">Deduction</span> is replaced with Resonance Skill <span class="Highlight">Decipher</span>.<br>Attack the target, dealing <span class="Thunder">Electro DMG</span>, considered as Resonance Liberation DMG.<br><span class="Title">Resonance Skill - Law of Reigns</span><br>When in <span class="Highlight">Intuition</span> triggered by Resonance Liberation and obtaining 5 Performance Capacity, Resonance Skill <span class="Highlight">Divergence</span> is replaced with Resonance Skill <span class="Highlight">Law of Reigns</span>.<br>Attack the target, dealing <span class="Thunder">Electro DMG</span>, considered as Resonance Liberation DMG.<br><span class="Title">Mid-air Attack - Revamp</span><br>Shortly after casting Resonance Skill <span class="Highlight">Law of Reigns</span> or Resonance Skill <span class="Highlight">Divergence</span>, use <span class="Highlight">Basic Attack</span> to perform Mid-air Attack <span class="Highlight">Revamp</span> at the cost of STA, dealing <span class="Thunder">Electro DMG</span>, considered as Resonance Liberation DMG.<br><span class="Title">Capacity</span><br>Xiangli Yao can hold up to 100 Capacity.<br>When in <span class="Highlight">Intuition</span> triggered by Resonance Liberation, Xiangli Yao cannot obtain Capacity.<br>Obtain Capacity for every Basic Attack <span class="Highlight">Probe</span> on hit.<br>Obtain Capacity for every Resonance Skill <span class="Highlight">Deduction</span> on hit.<br><span class="Title">Performance Capacity</span><br>Xiangli Yao can hold up to 5 Performance Capacity.<br>When in <span class="Highlight">Intuition</span> triggered by Resonance Liberation:<br>Obtain 1 Performance Capacity when Stage 1 of Basic Attack <span class="Highlight">Pivot - Impale</span> hits a target.<br>Obtain 2 Performance Capacity when Stage 2 and 3 of Basic Attack <span class="Highlight">Pivot - Impale</span> hit a target.<br>Obtain 2 Performance Capacity  for every Resonance Skill <span class="Highlight">Divergence</span> on hit.<br>Obtain 3 Performance Capacity  for every Mid-air Attack <span class="Highlight">Revamp</span> on hit.</div>`,
  attacks: [
    {
      key: "DecipherDMG",
      label: "Decipher DMG",
      talents: {
        "1": "200.10%",
        "2": "216.51%",
        "3": "232.92%",
        "4": "255.89%",
        "5": "272.30%",
        "6": "291.17%",
        "7": "317.42%",
        "8": "343.68%",
        "9": "369.93%",
        "10": "397.82%",
      },
      type: "Liberation",
    },
    {
      key: "LawofReignsDMG",
      label: "Law of Reigns DMG",
      talents: {
        "1": "48.15%*4 + 128.40%",
        "2": "52.10%*4 + 138.93%",
        "3": "56.05%*4 + 149.46%",
        "4": "61.58%*4 + 164.20%",
        "5": "65.53%*4 + 174.73%",
        "6": "70.07%*4 + 186.84%",
        "7": "76.39%*4 + 203.69%",
        "8": "82.70%*4 + 220.53%",
        "9": "89.02%*4 + 237.38%",
        "10": "95.73%*4 + 255.28%",
      },
      type: "Liberation",
    },
    {
      key: "RevampDMG",
      label: "Revamp DMG",
      talents: {
        "1": "11.00%*4 + 33.00%*2",
        "2": "11.91%*4 + 35.71%*2",
        "3": "12.81%*4 + 38.42%*2",
        "4": "14.07%*4 + 42.21%*2",
        "5": "14.97%*4 + 44.91%*2",
        "6": "16.01%*4 + 48.02%*2",
        "7": "17.45%*4 + 52.35%*2",
        "8": "18.90%*4 + 56.68%*2",
        "9": "20.34%*4 + 61.01%*2",
        "10": "21.87%*4 + 65.61%*2",
      },
      type: "Liberation",
    },
  ],
};
