// Generated by scripts/coverters/updatesToData.js from the legacy
// hand-written UpdatesView.vue markup - see docs/adr/0023-updates-page-search-and-grouping-redesign.md.
// Going forward, add new entries directly here (newest first), not as markup.

export interface UpdateEntry {
  /** ISO date, e.g. "2026-08-29" - sort/group key, do not derive from dateLabel at runtime. */
  date: string;
  /** Exact display text, e.g. "August 29, 2026". */
  dateLabel: string;
  items: string[];
}

export const updateEntries: UpdateEntry[] = [
  {
    date: "2026-09-04",
    dateLable: "September 4, 2026",
    items: [
      "v3 UI: Redesigned all of the modals, they're consistent now, provide more insights",
      "v3 UI: Cool new feature, when you're browsing for an echo from your inventory, it tells you if it's better or worse if you swap the existing echo with it 🎉",
    ],
  },
  {
    date: "2026-09-03",
    dateLable: "September 3, 2026",
    items: [
      "Fixed Luuk's self buff, it wasn't properly buffing the MV for Ichor Deposit",
      "Adds rotations for Denia and Jingran, and updated Qingxiao's rotation",
      "v3 UI: Updated the settings and info pages, added link to github, Fixed weapon button",
    ],
  },
  {
    date: "2026-09-02",
    dateLable: "September 2, 2026",
    items: [
      "Updated the v3.0 UI, i moved the basic character info to be in the anchored area for the damage monitor and stats. so you can see and adjust basic stuff on any sub page. that also de-duped some stuff across the pages, especially the main page for self buffs/chains where you had the avatar 3 times ",
      "In existing and v3.0 UI: fixed an issue where if you changed an echo and it changed the cost, it would always clear out your main stat. I changed it to where if the main stat could stay the same (e.g. ATK%), then it wouldn't clear it out. it was mostly to prevent a 1-cost echo from having elemental dmg bonus, etc.",
      "Updated v3 UI: reworked the enemy page UI",
    ],
  },
  {
    date: "2026-09-01",
    dateLable: "September 1, 2026",
    items: [
      "Updated QX substat priorities and included basic and lib along with heavy and made flat attack slightly higher",
      "v3 UI: Updated the optimizer and team buffs pages",
      "v3 UI: The mode switch is on the top bar throughout the character setup so you can toggle it without having to go back to the main character page. i also added a note in the builds if it's using a specific mode. If you use the toggle switch to enable a resonance chain, it'll activate the previous ones, and highlight the chain icons too. i moved Energy regen to the top of the substat priorities list on the echoes page. i removed the unnecessary pointer cursor on the build card page",
    ],
  },
  {
    date: "2026-08-31",
    dateLable: "August 31, 2026",
    items: [
      "More progress on the re-imagined UI: finished the weapons section. it now has a list of recommended weapons (slowly filling this out) from signature, other 5* weapons and 4* weapons. it also tells you how much better/worse those recommended weapons are as a quick reference. and it does the same in the weapon browser, it says how much more or less damage you'll do with that weapon against your target damage (rotation, or single attack), and you can get a quick preview of the weapon details and diffs before you equip it",
    ],
  },
  {
    date: "2026-08-30",
    dateLable: "August 30, 2026",
    items: [
      "More progress on the re-imagined UI: Reworked the custom buffs. it buckets buffs together for easier way to find what you're looking for, you can search to find a buff, it highlights what's used, summarizes what you put in, and similar to other things, it tells you exactly the effect of the buff on your damage, and you can hide the panels and it remembers if you hid/opened a panel",
    ],
  },
  {
    date: "2026-08-29",
    dateLabel: "August 29, 2026",
    items: [
      "Update to lab feature: UI v3.0: New character system. Udates to how you configure your character and resonance chains. resonance chains got moved to the main character screen, you can quickly select your sequence number, and it auto-enables any sequence up to that one (you click s3, it enables s1 through s3), added build score reference, quick glance at the weapon you're using, simplified the forte config and more, and some small thigns like it shows you when you last modified a character, and if you're missing some basic stuff (weapon setup, team setup)",
      "Updates Jingran s2 so it is split into two separate buffs.",
    ],
  },
  {
    date: "2026-08-28",
    dateLabel: "August 28, 2026",
    items: [
      "Fixed up some echo status issues, added a new status (temp)",
      "Updated preset management UI: has sorting, filtering, list and grid view, remove the old RV with build rating",
      "Locking an echo now disabled editing an echo too",
      "Adds confirmation before bulk deleting echoes with a quick summary of what will get removed",
    ],
  },
  {
    date: "2026-08-27",
    dateLabel: "August 27, 2026",
    items: [
      "Update to lab feature: UI v3.0: released an entirely new rotation system. You can now import a rotatoin just typing/pasting the text of actions and it creates your rotation from that. you can quick type to find actions to make it also easier to add actions. you can quickly see what buffs are active if you are customizing buffs in detail. you get a neat chart highlighting where your bigger hits are. and you can see in the rotation itself the damage and hit damages without needing to find the rotation in the damages panel. also cleaned up the UI so it's easier to manage and edit a rotation",
      "Added a \"max\" button for some team buffs so you can quickly max out the stacks",
      "Adjusted some substat priorities for characters like some characters needing energy regen",
      "Added the trash and lock icons to echoes when you are browsing for an echo",
      "Undid the echo set filter change. it's a list again instead of a selection",
      "App remembers if you open or close the filter panel, so when you come back it will be back to that state",
    ],
  },
  {
    date: "2026-08-26",
    dateLabel: "August 26, 2026",
    items: [
      "Released new lab feature: UI v3.0: it is a re-imagining of the app's UX and UI. You can enable it under Settings > Labs. It's a work in progress, and this works side by side the current UI. I'll be releasing more parts over time. This one comes with the top bar, damage monitor, echoes and echo add/edit, and inventory (partially).",
    ],
  },
  {
    date: "2026-08-25",
    dateLabel: "August 25, 2026",
    items: [
      "UX Update: some of the menus, filters, and action bars were getting a little crazy with how many options there were. so i started to organize and consolidate things to remove a lot of the clutter. so key actions are around, there are filter panels too.",
    ],
  },
  {
    date: "2026-08-24",
    dateLabel: "August 24, 2026",
    items: [
      "Adds an echo quality grade (E-SSS) and a per-character Substat Score, so you can see how well an echo's substats rolled overall and for a specific character.",
      "Moves Team Rotations' and Character Rotations' Import and List Presets into pop-up modals instead of stacking inline, so they don't pile up on the page.",
      "Fixes panel header buttons overflowing on narrow screens.",
      "Adds echo presets for Jingran.",
    ],
  },
  {
    date: "2026-08-23",
    dateLabel: "August 23, 2026",
    items: [
      "Releases the multi-build system for characters, so each character can have more than 1 build, and you can choose a build in the team setup",
      "You can now drag and drop rotation actions to re-order them",
      "Improved the performance of the teams feature when you have a lot of teams",
      "Added small website reference on build images",
      "Changes character level to a slider",
    ],
  },
  {
    date: "2026-08-22",
    dateLabel: "August 22, 2026",
    items: [
      "Fixed a bug in the rotations with per-action buffs using custom buffs were multiplied by 100",
      "Optimized the e2e tests, improving how fast they run in the CI pipeline",
      "Fixed Qingxiao's preset rotation, the echo attack wasn't working",
      "Fixed the alignment on the slider ticks, it got misaligned in some cases",
      "Removes duplicate Crit Damage breakdown in slide-out",
    ],
  },
  {
    date: "2026-08-21",
    dateLabel: "August 21, 2026",
    items: [
      "Removes duplicate Crit Damage breakdown in slide-out",
    ],
  },
  {
    date: "2026-08-20",
    dateLabel: "August 20, 2026",
    items: [
      "Adds new themes",
      "Fixes Qingxiao's S1 (missing extra attack), and S3 (multiplier adjustment)",
      "Upgraded to latest Node version",
    ],
  },
  {
    date: "2026-08-19",
    dateLabel: "August 19, 2026",
    items: [
      "Replaces the character rotation exclude-buffs checkboxes with per-buff advanced config, giving you finer control over which buffs apply to which actions.",
      "Adds a sync-status pill and resync button to rotation actions so you can spot and fix out-of-date buff overrides.",
      "Fixes Optimizer scoring for rotation actions that have buff overrides.",
      "Fixes the Optimizer's main-echo-buff warning firing when it shouldn't, for actions that aren't actually overriding the buff.",
      "Drops the Team Rotations Basic/Advanced mode toggle in favor of the unified per-buff config, and fixes an issue with per-action buff import.",
      "Adds search and a \"hide unused\" toggle to the Team Buffs panel.",
      "Releases 3.6 content.",
    ],
  },
  {
    date: "2026-08-17",
    dateLabel: "August 17, 2026",
    items: [
      "Fixes the Build Card so long character names no longer wrap and substat labels no longer get truncated.",
      "Self-hosts the Figtree font so Build Card exports actually embed it, lets substat labels wrap and use the full available width, and trims the echo banner to make more room for long names.",
      "Fixes Team Rotation action reordering so changing an action's order number actually reorders it, and resets action order correctly when overwriting a team rotation slot on import.",
    ],
  },
  {
    date: "2026-08-16",
    dateLabel: "August 16, 2026",
    items: [
      "Adds optional tick marks to range sliders that have a set list of values.",
      "Swaps the order of ATK and HP in the stats panel and optimizer results.",
      "Adds position, scale, and fit controls for images on the Build Card.",
    ],
  },
  {
    date: "2026-08-15",
    dateLabel: "August 15, 2026",
    items: [
      "Team Rotations and Build Card are no longer Labs features — both are now fully released and available to everyone, no toggle required.",
      "Adds ability to quickly equip sig, and highlights character signature in weapon chooser",
      "Fixes YYX's S2, it now properly applies DMG Bonus",
      "Fixed a text issue on Hiyuki's sig",
      "Adds a warning badge on echo cards that aren't fully configured (missing an echo, set, main stat, or a substat), and an \"Incomplete echoes\" filter (with count badge) to the Inventory so you can find and finish configuring them.",
      "Also shows that same incomplete-echo warning badge on a character's equipped echoes in the Calculator, so you can spot an unfinished build without leaving the page.",
    ],
  },
  {
    date: "2026-08-14",
    dateLabel: "August 14, 2026",
    items: [
      "Adds a custom primary color picker to the Build Card, which also drives the resonance chain nodes, weapon refinement pill, forte level badges, and echo cost badges.",
      "Fixes the Build Card's echo set summary to show 1pc and 3pc-threshold exclusive sets, not just 2pc sets.",
      "Makes the Build Card's custom primary color per-character instead of global, since different builds want different accent colors.",
      "Improves optimizer performance, especially for large-scale loadout runs, by removing unnecessary allocations from the calculation workers.",
    ],
  },
  {
    date: "2026-08-13",
    dateLabel: "August 13, 2026",
    items: [
      "Moves the Build Card's forte row out of the character portrait and into its own row between the weapon and stats panels, and enlarges the icons.",
      "Makes the Build Card compute its own stats from equipment and permanent unlocks instead of mirroring the Results tab's live buff toggles.",
      "Increases the Build Card's character name, rarity stars, username, and UID font sizes.",
      "Fixes the Build Card's resonance chain icons to dedupe per node, properly show permanent (always-on) nodes, and stop the UID and echo set name from wrapping onto two lines.",
    ],
  },
  {
    date: "2026-08-12",
    dateLabel: "August 12, 2026",
    items: [
      "Adds a Build Card (Labs feature, enable it in Settings > Labs) that generates a shareable image of your character's build, echoes, weapon, and forte stats.",
      "Adds Tune Strain - Interfered and negative status effect stacks (Spectro Frazzle, Aero Erosion, Havoc Bane, Fusion Burst, Electro Flare, Electro Rage, Glacio Chafe) to Team Rotation enemy settings.",
      "Increases max value of the Tune Strain input from 6 to 9.",
      "Fixes Sigrika's s6, it wasn't properly stacking with her base Runic DMG bonus.",
      "Adds a Normal/Average/Crit toggle to the Team Rotation \"View Damages\" pie chart, and a single toggle in the Team Rotation summary view that switches all of its damage charts between Normal, Average, and Crit. Both default to Average.",
      "Reworks the Build Card layout into three panels: character portrait with forte levels, weapon and stats, and echoes listed vertically with a bigger substat layout.",
      "Colorizes Build Card echo substat values based on their roll quality (green to yellow, low to high).",
      "Makes resonance chain icons and weapon refinement bigger and easier to read on the Build Card.",
      "Fixes character portraits used for the Build Card and CLI backfill, they were pulling a generic shared image instead of each character's own portrait art.",
      "Uses each character's own portrait art as the Build Card's default background, removes the extra padding around the card, and widens the character panel.",
      "Moves the forte level icons into the character portrait, using the actual skill icons instead of placeholders, aligned the same tight way as the resonance chain icons.",
      "Increases text size for the Build Card's weapon info, stats, and echo substats.",
      "Adds an equipped echo set summary (e.g. 2pc/5pc set names with icons) to the bottom of the Build Card's stats panel.",
      "Doubles the size of the Build Card's resonance chain and forte icons, and moves the forte level number underneath its icon.",
      "Doubles the width of the Build Card's echo art, and centers the echo set summary with a bit more breathing room from the bottom edge.",
      "Removes the resonance chain count from the Build Card, increases the text size for the echo name, main stat, username, and UID, and moves the echo set icon next to its cost badge in the top-right corner.",
      "Shrinks the Build Card's character panel a bit and widens the echo panel, shrinks the resonance chain circles while making their icons bigger to fill them, and matches the forte icon size to the resonance chain icons with more spacing between both.",
      "Makes the CV and RV text bigger on Build Card echoes, and changes the substats to a single list of 5 (icon and name on the left, value on the right) instead of a 3-then-2 grid.",
      "Fixes the Build Card export to no longer include the portrait's remove (x) button in the downloaded/copied image.",
      "Adds more spacing between each echo, and between each resonance chain and forte icon on the Build Card.",
      "Doubles the resolution of the Build Card's copied/downloaded image for a sharper export.",
      "Shrinks each echo's height on the Build Card, adds more spacing between them, and adds more padding around the substats.",
    ],
  },
  {
    date: "2026-08-09",
    dateLabel: "August 9, 2026",
    items: [
      "Fixes Suisui team buff to properly give DMG Bonus.",
    ],
  },
  {
    date: "2026-08-08",
    dateLabel: "August 8, 2026",
    items: [
      "All related to the Labs team feature:",
      "Added normal/average/crit for team damage on the list view and single-team view for quick reference of the total damage",
      "Moved the full breakdown of the team damage to a slide-out",
      "Made the total damage always present and a quick view of breakdown of damage by character Enabled you to import a rotation from a character to quickly setup a team rotation. you can choose to overwrite the full team rotation with a character one, or append it to the end (you can choose your own rotation or a preset)",
      "(Advanced mode) enabled you to be able to set a buff to start and end from one action to another action, or a set number of actions, so you have a quicker way to tell when a buff starts and ends so you don't need to set it up for each action.",
    ],
  },
  {
    date: "2026-08-07",
    dateLabel: "August 7, 2026",
    items: [
      "Adds a new Team Rotations page (Labs feature, enable it in Settings > Labs): build teams of up to 3 characters, chain their actions into a rotation, and see the team's total damage and DPS.",
      "Adds ability to set how many workers to use in the optimizer.",
    ],
  },
  {
    date: "2026-08-06",
    dateLabel: "August 6, 2026",
    items: [
      "Fixes weapon team buff name for Firstlight's Herald.",
      "Fixes last weapon buff refinement dropdown.",
    ],
  },
  {
    date: "2026-08-05",
    dateLabel: "August 5, 2026",
    items: [
      "More improvements to the optimizer stability at higher scale of loadouts.",
    ],
  },
  {
    date: "2026-08-04",
    dateLabel: "August 4, 2026",
    items: [
      "Fixes minimum stat requirements for optimizer, ATK, DEF, and HP weren't working properly.",
      "Improves the optimizer stability at higher scale of loadouts, and includes a timer in the UI.",
    ],
  },
  {
    date: "2026-08-03",
    dateLabel: "August 3, 2026",
    items: [
      "Adds ability to drag and drop to reorder rotations when you have more than one.",
      "Fixes Tune Strain to be Total DMG.",
    ],
  },
  {
    date: "2026-08-02",
    dateLabel: "August 2, 2026",
    items: [
      "Adds ability to change rotation damage chart to show Normal, Average, and Crit values.",
      "Adds ability to group rotation damage chart by damage type or by forte.",
      "Adds chart defaults in Settings → Preferences for damage value and grouping.",
      "Adds ability to import echoes directly into inventory from the inventory page.",
      "Damage charts can now switch between Normal, Average, and Crit values, and group by damage type or by forte.",
      "Adds chart defaults in Settings → Preferences for damage value and grouping.",
    ],
  },
  {
    date: "2026-08-01",
    dateLabel: "August 1, 2026",
    items: [
      "Adds more character status options (Won't build, wanted).",
      "Adds the ability to change the character status in the character browser.",
      "Adds ability to always hide unwatched characters in the character browser.",
      "Enhances all of the selection UI to make them easier to use with icons, searchability, and more.",
    ],
  },
  {
    date: "2026-07-31",
    dateLabel: "July 31, 2026",
    items: [
      "Adds ability to set loadout format in the optimizer.",
      "Fixes bug where the optimizer would not apply the correct loadout main echo stat.",
    ],
  },
  {
    date: "2026-07-30",
    dateLabel: "July 30, 2026",
    items: [
      "Improves pagination in the inventory page.",
      "Improves UX for selecting actions and buffs in rotations.",
      "Adds No Intro and Loop rotations for Suisui.",
    ],
  },
  {
    date: "2026-07-27",
    dateLabel: "July 27, 2026",
    items: [
      "Adds rotation action count to each attack in the rotation results and in the optimizer results.",
    ],
  },
  {
    date: "2026-07-23",
    dateLabel: "July 23, 2026",
    items: [
      "Fixes Yangyang Xuanling's s2 as it was missing some attacks from the buff.",
      "Checks for duplicates when importing echoes and asks you if you want to add them to your inventory and apply them to your character.",
      "Adds ability to find duplicates in your inventory.",
    ],
  },
  {
    date: "2026-07-22",
    dateLabel: "July 22, 2026",
    items: [
      "Added a new compact mode that makes the UI more condensed.",
      "Added more echo filters so you can filter by CV and RV.",
      "Added some bulk actions in the inventory page where you can select 1 to many echoes and make bulk changes to them.",
    ],
  },
  {
    date: "2026-07-21",
    dateLabel: "July 21, 2026",
    items: [
      "Fixes Suisui's Inherent Skill: Sky Over Water buff.",
    ],
  },
  {
    date: "2026-07-20",
    dateLabel: "July 20, 2026",
    items: [
      "Adds resistance ignore, which works with resist reduction for normal damage, but properly handles negative statuses damage.",
    ],
  },
  {
    date: "2026-07-18",
    dateLabel: "July 18, 2026",
    items: [
      "Adds ability to favorite echoes and filter by favorites in inventory and echo browsers.",
      "Adds favorite hearts on character cards in the character browser.",
      "Removes old Sun-Sinking Eclipse echo set.",
      "Adds migration system to help fix any data issues.",
      "Fixes Cantarella's echo presets not showing up.",
    ],
  },
  {
    date: "2026-07-11",
    dateLabel: "July 11, 2026",
    items: [
      "Adds echo presets for Cantarella, Chisa, Ciaccona, Denia, Iuno, Lucilla, Jianxin, Lucy.",
    ],
  },
  {
    date: "2026-07-10",
    dateLabel: "July 10, 2026",
    items: [
      "Releases Suisui and her sig.",
      "Improves echo preset UX.",
      "Improves performance of echo preset application.",
    ],
  },
  {
    date: "2026-07-09",
    dateLabel: "July 9, 2026",
    items: [
      "Phase 1 of Version 3.5 is now available",
    ],
  },
  {
    date: "2026-07-05",
    dateLabel: "July 5, 2026",
    items: [
      "Adds ability to lock and trash echoes and filter by locked and trash.",
      "Adds ability to duplicate echoes.",
      "Syncs echo set and main echo buffs when you equip a loadout from the optimizer.",
      "Adds ability to hide an echo from being used in the optimizer.",
    ],
  },
  {
    date: "2026-07-04",
    dateLabel: "July 4, 2026",
    items: [
      "Added ability to open weapon browser and enable and max all for weapons, echoes, resonance chains, character buffs, and custom buffs.",
      "Adds ability to favorite characters and filter by favorites in the character browser.",
    ],
  },
  {
    date: "2026-07-02",
    dateLabel: "July 2, 2026",
    items: [
      "Improved all of the notifications and confirmations",
    ],
  },
  {
    date: "2026-07-02",
    dateLabel: "July 2, 2026",
    items: [
      "Adds ability to change character from main navigation bar.",
      "Adds current character to main navigation bar.",
      "Adds \"in progress\", and \"complete\" statuses to character build status.",
      "Adds equipped echo references when you are looking for echoes.",
    ],
  },
  {
    date: "2026-06-14",
    dateLabel: "June 14, 2026",
    items: [
      "Fixes Lucilla's s6.",
    ],
  },
  {
    date: "2026-06-13",
    dateLabel: "June 13, 2026",
    items: [
      "Adds a couple of mising Lucilla team buffs.",
    ],
  },
  {
    date: "2026-06-12",
    dateLabel: "June 12, 2026",
    items: [
      "Releases Lucilla",
    ],
  },
  {
    date: "2026-06-08",
    dateLabel: "June 8, 2026",
    items: [
      "Fixes some Lucy and Rebecca buffs.",
    ],
  },
  {
    date: "2026-06-07",
    dateLabel: "June 7, 2026",
    items: [
      "Adds first phase of 3.4 content.",
    ],
  },
  {
    date: "2026-06-06",
    dateLabel: "June 6, 2026",
    items: [
      "Adds s6 multiplier to Glacio Bite DMG for Hiyuki.",
    ],
  },
  {
    date: "2026-06-03",
    dateLabel: "June 3, 2026",
    items: [
      "Ensures Hiyuki has both Glacio bite damages.",
    ],
  },
  {
    date: "2026-05-23",
    dateLabel: "May 23, 2026",
    items: [
      "Fixes Denia resonance chains.",
    ],
  },
  {
    date: "2026-05-21",
    dateLabel: "May 21, 2026",
    items: [
      "Adds Denia and her sig.",
    ],
  },
  {
    date: "2026-05-17",
    dateLabel: "May 17, 2026",
    items: [
      "Adds negative status amplify as custom buffs and action-level buffs in rotations.",
    ],
  },
  {
    date: "2026-05-16",
    dateLabel: "May 16, 2026",
    items: [
      "Fixes an issue where the optimizer would give the same build recommendation, just having the echoes in a different order.",
    ],
  },
  {
    date: "2026-05-12",
    dateLabel: "May 12, 2026",
    items: [
      "Fixes chart display issue for Glacio Chafe.",
    ],
  },
  {
    date: "2026-05-07",
    dateLabel: "May 7, 2026",
    items: [
      "Fixes Hiyuki's S4 healing to be HP based.",
    ],
  },
  {
    date: "2026-05-06",
    dateLabel: "May 6, 2026",
    items: [
      "Updates Hiyuki liberation additive buff to distribute the bonus, but the total damage is the same.",
    ],
  },
  {
    date: "2026-05-04",
    dateLabel: "May 4, 2026",
    items: [
      "Removes the extra Frostburn Glacio Chafe DMG amplify.",
    ],
  },
  {
    date: "2026-05-02",
    dateLabel: "May 2, 2026",
    items: [
      "Updates Glacio Bite DMG damage formula for Hiyuki.",
      "Makes Hiyuki's s6 special multiplier additive with the existing buffs.",
    ],
  },
  {
    date: "2026-05-01",
    dateLabel: "May 1, 2026",
    items: [
      "Fixes Hiyuki forte 1 on her Iai attack.",
      "Fixes Denia image in the team buffs.",
    ],
  },
  {
    date: "2026-04-30",
    dateLabel: "April 30, 2026",
    items: [
      "Fixes text issue on Hiyuki intro skill.",
      "Fixes s1, s2, and s5 Hiyuki resonance chains.",
    ],
  },
  {
    date: "2026-04-29",
    dateLabel: "April 29, 2026",
    items: [
      "Versions 3.3 phase 1 content is available!",
    ],
  },
  {
    date: "2026-04-24",
    dateLabel: "April 24, 2026",
    items: [
      "Fixes Spectro Rover team buffs.",
    ],
  },
  {
    date: "2026-04-23",
    dateLabel: "April 23, 2026",
    items: [
      "Adds enemy browser so you can choose enemies in the enemy settings.",
    ],
  },
  {
    date: "2026-04-19",
    dateLabel: "April 19, 2026",
    items: [
      "Adds icons to party buffs.",
      "Organized party echo buffs so echoes and sets are together",
      "Added empty state for party buffs when there are no buffs.",
      "Added visual way to choose teammates in team/party settings.",
      "Fixed character name labels in party buffs to show their friendly name instead of the key.",
    ],
  },
  {
    date: "2026-04-15",
    dateLabel: "April 15, 2026",
    items: [
      "Fixed Windcleaver DMG echo damage.",
      "Fixes Def Ignore being applied to negative statuses damage as it should not be applied.",
    ],
  },
  {
    date: "2026-04-12",
    dateLabel: "April 12, 2026",
    items: [
      "Improves UI layout for convene calculator.",
    ],
  },
  {
    date: "2026-04-11",
    dateLabel: "April 11, 2026",
    items: [
      "Adds events and weekly/monthly Astrite to convene calculator.",
    ],
  },
  {
    date: "2026-04-10",
    dateLabel: "April 10, 2026",
    items: [
      "Adds top-up, daily asterites, and initial bonuses to convene calculator.",
    ],
  },
  {
    date: "2026-04-09",
    dateLabel: "April 9, 2026",
    items: [
      "Adds Convene odds calculator.",
    ],
  },
  {
    date: "2026-04-04",
    dateLabel: "April 4, 2026",
    items: [
      "Adds message in optimizer when there are no loadouts based on your inventory and config.",
      "Fixes a bug where the optimizer minimum stat requirements were filtering out builds that exactly matched the requirements.",
    ],
  },
  {
    date: "2026-03-28",
    dateLabel: "March 28, 2026",
    items: [
      "Adds support for negative statuses in rotations and optimizer.",
    ],
  },
  {
    date: "2026-03-27",
    dateLabel: "March 27, 2026",
    items: [
      "Fixed a bug in the optimizer that was causing it to miss some echoes.",
    ],
  },
  {
    date: "2026-03-23",
    dateLabel: "March 23, 2026",
    items: [
      "Fixed Sigrika's Blessing of Runes buff in the optimizer",
    ],
  },
  {
    date: "2026-03-21",
    dateLabel: "March 21, 2026",
    items: [
      "Fixed Sigrika's Blessing of Runes buff in the optimizer",
    ],
  },
  {
    date: "2026-03-20",
    dateLabel: "March 20, 2026",
    items: [
      "Fixed damage breakdown for Fusion Burst, a couple of numbers weren't appearing correctly",
    ],
  },
  {
    date: "2026-03-19",
    dateLabel: "March 19, 2026",
    items: [
      "Fixes Sigrika self echo dmg bonus based on Energy Regen",
      "Add missing Sigrika team buff",
    ],
  },
  {
    date: "2026-03-18",
    dateLabel: "March 18, 2026",
    items: [
      "3.2 content is available",
    ],
  },
  {
    date: "2026-03-07",
    dateLabel: "March 7, 2026",
    items: [
      "Fixes Luuk's S1, it was buffing too many attacks.",
    ],
  },
  {
    date: "2026-02-26",
    dateLabel: "February 26, 2026",
    items: [
      "Stops Tune Strain Interfered from buffing Tune Break damage.",
    ],
  },
  {
    date: "2026-02-25",
    dateLabel: "February 25, 2026",
    items: [
      "Adds Electro Rage damages with breakdown.",
      "Adds Aemeath rotation.",
    ],
  },
  {
    date: "2026-02-22",
    dateLabel: "February 22, 2026",
    items: [
      "Adds Electro Flare damages with breakdown.",
    ],
  },
  {
    date: "2026-02-21",
    dateLabel: "February 21, 2026",
    items: [
      "Adds Fusion Burst damages with breakdown.",
    ],
  },
  {
    date: "2026-02-18",
    dateLabel: "February 18, 2026",
    items: [
      "Luuk and his sig are now available.",
    ],
  },
  {
    date: "2026-02-16",
    dateLabel: "February 16, 2026",
    items: [
      "Fixed Trailblazing Star 5pc set effect, it was always enabled.",
    ],
  },
  {
    date: "2026-02-08",
    dateLabel: "February 8, 2026",
    items: [
      "Fixed Camellya's self buff that overwrites Heavy attack to Basic.",
    ],
  },
  {
    date: "2026-02-06",
    dateLabel: "February 6, 2026",
    items: [
      "Fixed Amy's S2 to be a special multiplier, and fixes Seraphic Duet buffs.",
    ],
  },
  {
    date: "2026-02-05",
    dateLabel: "February 5, 2026",
    items: [
      "Fixed Amy's team buff selection bug and her buffs and resonance chains for tune rupture, it was incorrectly applying to tune break too",
    ],
  },
  {
    date: "2026-02-04",
    dateLabel: "February 4, 2026",
    items: [
      "Aemeath, her sig, 3.1 echoes and sets are available.",
    ],
  },
  {
    date: "2026-01-25",
    dateLabel: "January 25, 2026",
    items: [
      "Improves the echo importer. It is now 2-3x faster and much more accurate in finding the right echo and set.",
    ],
  },
  {
    date: "2026-01-24",
    dateLabel: "January 24, 2026",
    items: [
      "Adds Tune Break Boost to the list of stats on the stats panel, and enables the stats breakdown on it.",
      "Adds Tune Strain - Interfered Stacks support.",
    ],
  },
  {
    date: "2026-01-21",
    dateLabel: "January 21, 2026",
    items: [
      "Removed duplicate delete button for presets in inventory screen.",
      "Fixes Crownless buff in the optimizer, so it works properly with HRover.",
    ],
  },
  {
    date: "2026-01-20",
    dateLabel: "January 20, 2026",
    items: [
      "Adds missing self buff for Mornye.",
      "Fixes Dreamless buff for Havoc Rover.",
    ],
  },
  {
    date: "2026-01-18",
    dateLabel: "January 18, 2026",
    items: [
      "In the breakdown panel, healing and shield now has the MV breakdown and the total bonus.",
    ],
  },
  {
    date: "2026-01-17",
    dateLabel: "January 17, 2026",
    items: [
      "Fixes issue where Mornye's High Syntony healing buff wouldn't always apply.",
      "Change Mornye s4 to affect her healing multiplier.",
      "Improves echo importer accuracy for text finding for substats.",
    ],
  },
  {
    date: "2026-01-16",
    dateLabel: "January 16, 2026",
    items: [
      "Fixes Augusta s6, it was overbuffing.",
      "Updates Tune Break formula (physical damage one, not Tune Break as it was working) to support enemy resist (physical).",
      "Adds Def Reduction support to Tune Break DMG.",
    ],
  },
  {
    date: "2026-01-15",
    dateLabel: "January 15, 2026",
    items: [
      "Fixes Mornye Critical Protocol crit rate buff.",
    ],
  },
  {
    date: "2026-01-14",
    dateLabel: "January 14, 2026",
    items: [
      "Mornye and her sig are now available.",
      "Adds rotations for Ciaccona, Phrolova, Lynae, and Qiuyuan.",
    ],
  },
  {
    date: "2026-01-11",
    dateLabel: "January 11, 2026",
    items: [
      "Updates Hyvatia description.",
    ],
  },
  {
    date: "2026-01-10",
    dateLabel: "January 10, 2026",
    items: [
      "Enhances the optimizer to use web workers to make it support significantly more loadouts without causing issues and process large amounts of loadouts faster.",
      "Fixed a bug where Rite of Gilded Revelation 5pc 40% effect was overbuffing",
    ],
  },
  {
    date: "2026-01-09",
    dateLabel: "January 9, 2026",
    items: [
      "Rewrote the code for the attacks and damages handling.",
      "Fixes Def Ignore and Resist Reduction custom buffs in the optimizer, it was being left out.",
    ],
  },
  {
    date: "2026-01-07",
    dateLabel: "January 7, 2026",
    items: [
      "Fixed a small edge case issue on the optimizer. if you chose the Tune Break skill as your target, it wouldn't process, mostly because it's built in a unique way. not surprised it wasn't reported until now, why would you optimize for tune break? xD but i fixed it",
    ],
  },
  {
    date: "2026-01-06",
    dateLabel: "January 6, 2026",
    items: [
      "Echo importer now supports echoes that have missing substats.",
      "Fixes the importer where it would sometimes interpret a 7 as a 1.",
    ],
  },
  {
    date: "2026-01-04",
    dateLabel: "January 4, 2026",
    items: [
      "Adds rotation for Lynae.",
      "Updates the max stacks on NS on enemy page. you dont need to activate chisa, etc to get the max possible stacks. i dont have the dmg for them yet. ill try to figure that soon",
    ],
  },
  {
    date: "2026-01-03",
    dateLabel: "January 3, 2026",
    items: [
      "Fixes weapon affect on stats when you un-equip a weapon.",
    ],
  },
  {
    date: "2026-01-02",
    dateLabel: "January 2, 2026",
    items: [
      "Fixed an edge case stats processing bug that was happening with Camellya.",
    ],
  },
  {
    date: "2025-12-31",
    dateLabel: "December 31, 2025",
    items: [
      "Updates Cartethyia text.",
    ],
  },
  {
    date: "2025-12-30",
    dateLabel: "December 30, 2025",
    items: [
      "Implements Tune Break & Lynae's Tune Rupture Response formula.",
      "Updates Lynae s6 text and modifier, it is now Vulnerability due to the text changes made.",
    ],
  },
  {
    date: "2025-12-29",
    dateLabel: "December 29, 2025",
    items: [
      "Adds missing Halo of Starry Radiance to team buffs.",
      "Fixes Rite of Gilded Revelation 5pc effect for the Basic DMG Bonus, it now properly buffs attacks that are from the character's Liberation but does Basic DMG.",
    ],
  },
  {
    date: "2025-12-27",
    dateLabel: "December 27, 2025",
    items: [
      "Changes Lynae's Prismatic Overblast (self and team buff) to be hidden DMG bonus. The calculation is still the same.",
    ],
  },
  {
    date: "2025-12-25",
    dateLabel: "December 25, 2025",
    items: [
      "Adds missing new standard broadblade.",
      "Adds missing Spectrum Blaster team buff.",
    ],
  },
  {
    date: "2025-12-24",
    dateLabel: "December 24, 2025",
    items: [
      "Lynae, her sig, new standard weapons, new echoes and new echo are released.",
    ],
  },
  {
    date: "2025-12-21",
    dateLabel: "December 21, 2025",
    items: [
      "Fixes race condition in calculating stats, causing it to fail sometimes.",
    ],
  },
  {
    date: "2025-12-17",
    dateLabel: "December 17, 2025",
    items: [
      "Fixes Augusta s2/s6 in the optimizer.",
    ],
  },
  {
    date: "2025-12-14",
    dateLabel: "December 14, 2025",
    items: [
      "Fixes stats calculation in the optimizer for some unique buffs, notably affecting buffs based on stats.",
    ],
  },
  {
    date: "2025-12-11",
    dateLabel: "December 11, 2025",
    items: [
      "Releases Buling",
    ],
  },
  {
    date: "2025-12-08",
    dateLabel: "December 8, 2025",
    items: [
      "Updates Augusta so that her Crit Rate Overflow into Crit DMG in her resonance chains properly appears in the stats breakdown",
    ],
  },
  {
    date: "2025-12-06",
    dateLabel: "December 6, 2025",
    items: [
      "Fixes Crit DMG in the stats breakdown",
      "Updates Brant, Qiuyuan, Roccia, and Shorekeeper to have their buffs based on other stats properly reflect in the stats breakdown.",
    ],
  },
  {
    date: "2025-12-04",
    dateLabel: "December 4, 2025",
    items: [
      "Implements Defense Reduction into formula and various places to buff (custom, action, etc.).",
    ],
  },
  {
    date: "2025-12-01",
    dateLabel: "December 1, 2025",
    items: [
      "Fixes a spelling issue on Chisa.",
      "Fixes rotation action buff liberation dmg bonus, as it wasn't getting applied.",
    ],
  },
  {
    date: "2025-11-30",
    dateLabel: "November 30, 2025",
    items: [
      "Adds Aero Erosion and Spectro Frazzle to damage breakdown",
      "In the inventory section, it now pre-selects echo set for a new echo when you're creating echoes to make it easier. It also reset the modal used to find the echo scrollbar position when you choose an echo.",
      "When browsing for echoes in the echoes screen, it now remembers your filters when you re-open it. And the reset button now properly resets all filters.",
    ],
  },
  {
    date: "2025-11-29",
    dateLabel: "November 29, 2025",
    items: [
      "Adds breakdown of damages from the stats table.",
    ],
  },
  {
    date: "2025-11-26",
    dateLabel: "November 26, 2025",
    items: [
      "Adds breakdown of stats from the stats table.",
    ],
  },
  {
    date: "2025-11-24",
    dateLabel: "November 24, 2025",
    items: [
      "Fixed the bug I introduced yesterday for the rotation actions. it was auto-closing your action panel whenever you made a change. it has been fixed.",
      "Updated how Chisa uses the additive multiplier bonus for Eradication. it now splits the additive bonus by 20%/80% since it's a 2 hit MV",
    ],
  },
  {
    date: "2025-11-23",
    dateLabel: "November 23, 2025",
    items: [
      "Fixes reordering issue when you change an order number on a rotation action. It now properly updates the other actions.",
      "Implements the special multiplier/vulnerability effect for Core of Collapse for Reminiscence: Threnodian - Leviathan.",
    ],
  },
  {
    date: "2025-11-20",
    dateLabel: "November 20, 2025",
    items: [
      "Fixes Chisa's forte circuit to properly get Liberation DMG Bonus",
      "Fixes Reminiscence: Threnodian - Leviathan second damage name",
    ],
  },
  {
    date: "2025-11-19",
    dateLabel: "November 19, 2025",
    items: [
      "Adds Chisa, sig, and new echoes",
    ],
  },
  {
    date: "2025-11-15",
    dateLabel: "November 15, 2025",
    items: [
      "Adds new filters in echo browser for filtering out echoes equipped by the current character, or echoes equipped by any character.",
    ],
  },
  {
    date: "2025-11-14",
    dateLabel: "November 14, 2025",
    items: [
      "Fixes Aalto S6 to only apply to his liberation.",
    ],
  },
  {
    date: "2025-11-13",
    dateLabel: "November 13, 2025",
    items: [
      "Adds ability to delete a preset from the preset choosing window.",
    ],
  },
  {
    date: "2025-11-12",
    dateLabel: "November 12, 2025",
    items: [
      "Adds Special Multiplier (Vulnerability) as custom and rotation action level buff.",
    ],
  },
  {
    date: "2025-11-11",
    dateLabel: "November 11, 2025",
    items: [
      "Fixes Danjin's Forte Circuit label",
    ],
  },
  {
    date: "2025-11-10",
    dateLabel: "November 10, 2025",
    items: [
      "Adds echo presets for Galbrena and Qiuyuan.",
    ],
  },
  {
    date: "2025-11-09",
    dateLabel: "November 9, 2025",
    items: [
      "Adds ability to import a list of echoes so they can be generated externally (e.g. scanner) and imported into your inventory..",
    ],
  },
  {
    date: "2025-11-08",
    dateLabel: "November 8, 2025",
    items: [
      "Fixes Rocksteady Guardian shield action.",
      "Adds healing action for Cruisewing echo.",
    ],
  },
  {
    date: "2025-11-06",
    dateLabel: "November 6, 2025",
    items: [
      "Adds visual clarity on rotation main echo rank and action echo rank in the damages list and optimizer damages list.",
    ],
  },
  {
    date: "2025-11-05",
    dateLabel: "November 5, 2025",
    items: [
      "Adds visual clarity on rotation main echo rank and action echo rank. Will add this to the damages list soon.",
    ],
  },
  {
    date: "2025-11-02",
    dateLabel: "November 2, 2025",
    items: [
      "Releases echo attacks in rotations support.",
    ],
  },
  {
    date: "2025-11-01",
    dateLabel: "November 1, 2025",
    items: [
      "Fixes Qiuyuan's s2.",
    ],
  },
  {
    date: "2025-10-31",
    dateLabel: "October 31, 2025",
    items: [
      "Fixes Nightmare Kelpie Outro DMG, it is now properly doing Aero DMG.",
      "Fixes a bug where you couldn't add Qiuyuan's S3 Outro to a rotation.",
    ],
  },
  {
    date: "2025-10-20",
    dateLabel: "October 20, 2025",
    items: [
      "Loadouts from the optimizer are now sorted by cost, and will also equip sorted by cost when you equip a loadout from the optimizer.",
    ],
  },
  {
    date: "2025-10-18",
    dateLabel: "October 18, 2025",
    items: [
      "Fixes Jinhsi's s4 text.",
      "Updates the selected state for when you select an echo set to make it more clear.",
    ],
  },
  {
    date: "2025-10-16",
    dateLabel: "October 16, 2025",
    items: [
      "Adds rotations for Lupa and Galbrena.",
    ],
  },
  {
    date: "2025-10-15",
    dateLabel: "October 15, 2025",
    items: [
      "Fixed RV and CV when looking at the list of echo presets.",
      "Fixes Baby Roseshroom name.",
    ],
  },
  {
    date: "2025-10-13",
    dateLabel: "October 13, 2025",
    items: [
      "Fixed Flamewing's Shadow in the optimizer.",
      "Adds set icon to loadout echoes so you can quickly see the set of what it is.",
    ],
  },
  {
    date: "2025-10-11",
    dateLabel: "October 11, 2025",
    items: [
      "Releases optimizer.",
    ],
  },
  {
    date: "2025-10-10",
    dateLabel: "October 10, 2025",
    items: [
      "Adds missing Bamboo's Shade team buff.",
      "Fixed Qiuyuan's tooltip when his s3 is active. Note, that i just put the whole additive multiplier at the end. i don't know if/how the additive multiplier bonus is spread, and we may have to wait until his release to get the tooltip accurate. the row's damage is accurate regardless",
      "Fixes CR buff on Flamewing's Shadow set.",
    ],
  },
  {
    date: "2025-10-09",
    dateLabel: "October 9, 2025",
    items: [
      "Adds Qiuyuan.",
      "Fixes Galbrena S2.",
      "Updated custom buffs to allow the input arrows to go negative",
    ],
  },
  {
    date: "2025-10-05",
    dateLabel: "October 5, 2025",
    items: [
      "Adds ability to exclude equipped echoes when optimizing.",
      "Updates some \"Attack\", and \"Defense\" labels to use \"ATK\", and \"DEF\" for consistency.",
      "Fixes Verina's team buff text, it still said Deepen instead of Amplify.",
    ],
  },
  {
    date: "2025-10-03",
    dateLabel: "October 3, 2025",
    items: [
      "Adds showing the difference between each loadout against your current build in the optimizer.",
    ],
  },
  {
    date: "2025-09-27",
    dateLabel: "September 27, 2025",
    items: [
      "Adds support for using rotations as a target in the optimizer lab beta feature.",
    ],
  },
  {
    date: "2025-09-24",
    dateLabel: "September 24, 2025",
    items: [
      "Adds some missing text for Moongazer's Sigil.",
    ],
  },
  {
    date: "2025-09-23",
    dateLabel: "September 23, 2025",
    items: [
      "Adds 2 rotation presets for Iuno.",
      "Adds a new rotation preset for Rover (Havoc).",
    ],
  },
  {
    date: "2025-09-22",
    dateLabel: "September 22, 2025",
    items: [
      "Fixes a bug in the optimizer where it would sometimes use multiple copies of the same main echo.",
      "Fixes The False Sovereign summon damage modifiers and type.",
    ],
  },
  {
    date: "2025-09-21",
    dateLabel: "September 21, 2025",
    items: [
      "Releases Optimizer as a Lab beta feature.",
    ],
  },
  {
    date: "2025-09-18",
    dateLabel: "September 18, 2025",
    items: [
      "Fixes equipment references where it would not always clear them out when you changed your echoes.",
    ],
  },
  {
    date: "2025-09-17",
    dateLabel: "September 17, 2025",
    items: [
      "Fixes Lady of the Sea text, and some custom buff labels.",
    ],
  },
  {
    date: "2025-09-11",
    dateLabel: "September 11, 2025",
    items: [
      "Updates Jinhsi's text.",
    ],
  },
  {
    date: "2025-09-08",
    dateLabel: "September 8, 2025",
    items: [
      "Updates Shorekeeper's text.",
    ],
  },
  {
    date: "2025-09-07",
    dateLabel: "September 7, 2025",
    items: [
      "Fixes Fallacy's echo damage element.",
    ],
  },
  {
    date: "2025-09-03",
    dateLabel: "September 3, 2025",
    items: [
      "Fixed an issue when you change rotation action ordering, it causes the damages list for the rotation to duplicate rows, though the totals were correct.",
    ],
  },
  {
    date: "2025-08-31",
    dateLabel: "August 31, 2025",
    items: [
      "Fixed an issue with Danjin's Forte, two labels were mixed up.",
    ],
  },
  {
    date: "2025-08-30",
    dateLabel: "August 30, 2025",
    items: [
      "Adds Iuno and her signature weapon.",
      "Fixes Augusta's S6 attacks, they're considered Heavy DMG now.",
    ],
  },
  {
    date: "2025-08-29",
    dateLabel: "August 29, 2025",
    items: [
      "Reverts the change to the echo window to make it smaller again.",
      "Fixes Thunderflare Dominion DEF Ignore, it now properly only applies to Heavy attacks.",
      "Fixes RV and CV reactivity bug with custom presets, they were not always updating these when you changed echo stats.",
    ],
  },
  {
    date: "2025-08-28",
    dateLabel: "August 28, 2025",
    items: [
      "Added an echo presets guide to explain the feature and things to avoid.",
      "Added notice when saving a preset to let you know if you already have a preset with those echoes.",
      "Adds note in editing an echo to notify you if it's used in presets, so you know it'll affect those.",
      "Adds rotation for Augusta.",
    ],
  },
  {
    date: "2025-08-27",
    dateLabel: "August 27, 2025",
    items: [
      "Augusta, her signature weapon, the new 4* BP weapones, echoes, and echo sets are now available!",
    ],
  },
  {
    date: "2025-08-17",
    dateLabel: "August 17, 2025",
    items: [
      "You can now define and manage custom echo loadouts as presets and share them among characters.",
    ],
  },
  {
    date: "2025-07-31",
    dateLabel: "July 31, 2025",
    items: [
      "Fixes Phrolova S4 to properly be all attribute bonus instead of ATK.",
      "Adds 2 missing echoes to Dream of the Lost echo set.",
      "Updates Phrolova's text since there have been text patches.",
    ],
  },
  {
    date: "2025-07-30",
    dateLabel: "July 30, 2025",
    items: [
      "Removes the second S2 option for Phrolova.",
      "Adds another echo preset for Changli.",
    ],
  },
  {
    date: "2025-07-27",
    dateLabel: "July 27, 2025",
    items: [
      "Fixes Lumi's Energized Rebound DMG and Energized Pounce DMG to be Basic DMG.",
      "Updates Scarlet Coda DMG's individual hits. The additive multiplier bonus from Aftersound is distributed differently. It is now properly distrubted as: 2(5%) + 8(1.875%) + 75%. The overall damage is the same, but the individual hits will now better represent what would appear in game.",
      "Adds missing Lumi Counter DMG.",
    ],
  },
  {
    date: "2025-07-26",
    dateLabel: "July 26, 2025",
    items: [
      "Adds ability to disable weapon buffs in a rotation action.",
      "Adds Echo DMG Bonus to rotation action buffs.",
      "Adds rotation for Lupa and Cartethyia.",
      "Removes Echo DMG Amplify from applying to Scarlet Coda DMG.",
    ],
  },
  {
    date: "2025-07-25",
    dateLabel: "July 25, 2025",
    items: [
      "Adds echo presets for Brant and Encore.",
    ],
  },
  {
    date: "2025-07-24",
    dateLabel: "July 24, 2025",
    items: [
      "Fixes the Echo Skill buff in Phrolova S3, it now properly buffs Scarlet Coda DMG.",
      "Fixes Lethean Elegy main stat.",
    ],
  },
  {
    date: "2025-07-23",
    dateLabel: "July 23, 2025",
    items: [
      "Releases 2.5 content.",
    ],
  },
  {
    date: "2025-07-19",
    dateLabel: "July 19, 2025",
    items: [
      "Adds 3 missing echoes to the Flaming Clawprint set.",
      "Adds echo presets for Danjin and Jinhsi.",
    ],
  },
  {
    date: "2025-07-17",
    dateLabel: "July 17, 2025",
    items: [
      "Adds echo presets for Camellya and Changli.",
    ],
  },
  {
    date: "2025-07-16",
    dateLabel: "July 16, 2025",
    items: [
      "Adds icon and tooltip to explain CV and RV.",
      "Adds deeper explanation for CV and RV in the Info page.",
    ],
  },
  {
    date: "2025-07-15",
    dateLabel: "July 15, 2025",
    items: [
      "Adds echo presets for Carlotta and Cartethyia.",
      "Fixes a minor bug in importing settings.",
    ],
  },
  {
    date: "2025-07-14",
    dateLabel: "July 14, 2025",
    items: [
      "Echo presets are now available! There are presets currently for Zani and Lupa. More to come!",
    ],
  },
  {
    date: "2025-07-11",
    dateLabel: "July 11, 2025",
    items: [
      "Adds rotation presets for Aero Rover, Roccia, and Calcharo.",
      "Fixed R5 Rime-Draped Sprouts modifier",
    ],
  },
  {
    date: "2025-07-10",
    dateLabel: "July 10, 2025",
    items: [
      "Adds rotation presets for Zani, and Cantarella.",
    ],
  },
  {
    date: "2025-07-07",
    dateLabel: "July 7, 2025",
    items: [
      "Adds rotation presets for Cartethyia, and Encore.",
    ],
  },
  {
    date: "2025-07-06",
    dateLabel: "July 6, 2025",
    items: [
      "Fixes Lupa S6 and pre-S6. Pre-S6 Nowhere to Run! DMG now no longer gets Glory and Pack Hunt buffs. It now gets included in S6.",
      "Adds Ciaccona's outro to her own buffs.",
    ],
  },
  {
    date: "2025-07-05",
    dateLabel: "July 5, 2025",
    items: [
      "Adds Flaming Clawprint set to Aero Drake.",
    ],
  },
  {
    date: "2025-07-04",
    dateLabel: "July 4, 2025",
    items: [
      "Fixes Lupa team buffs, S3 now properly overwrites the resist reduction buffs.",
      "Changes Lupa Pack Hunt Enhanced buff to have max stacks of 2 to meet the 18% ATK cap.",
    ],
  },
  {
    date: "2025-07-03",
    dateLabel: "July 3, 2025",
    items: [
      "Adds note to Lupa team buffs since a couple of buffs don't appear in the in-game stats.",
    ],
  },
  {
    date: "2025-07-02",
    dateLabel: "July 2, 2025",
    items: [
      "Enables Aero Erosion for Ciaccona.",
      "Fixes Bell text by adding cooldown and duration.",
    ],
  },
  {
    date: "2025-06-30",
    dateLabel: "June 30, 2025",
    items: [
      "Fixes echo damage for Reminiscence: Fleurdelys, it now properly does Aero damage.",
    ],
  },
  {
    date: "2025-06-28",
    dateLabel: "June 28, 2025",
    items: [
      "Adds Lupa signature, Wildfire Mark.",
    ],
  },
  {
    date: "2025-06-26",
    dateLabel: "June 26, 2025",
    items: [
      "Changes the echo set override, when you disable it after using it to customize echoes, it will re-evaluate your sets based on what's equipped.",
    ],
  },
  {
    date: "2025-06-22",
    dateLabel: "June 22, 2025",
    items: [
      "Adds Aero Erosion data (stacks 1-6) for level 1, 20, and 40 characters.",
    ],
  },
  {
    date: "2025-06-21",
    dateLabel: "June 21, 2025",
    items: [
      "Adds Aero Erosion damages for stacks 7-9 for level 80 characters. Also adds Aero Erosion data (stacks 1-6) for level 50, 60, and 70 characters.",
    ],
  },
  {
    date: "2025-06-19",
    dateLabel: "June 19, 2025",
    items: [
      "Adds Aero Erosion damages, specifically for character levels 80, and 90. The rest are coming soon!",
    ],
  },
  {
    date: "2025-06-16",
    dateLabel: "June 16, 2025",
    items: [
      "Fixes tooltip breakdown of Cartethyia's damages for S6, it wasn't applying the special multiplier, but it's resolved now.",
    ],
  },
  {
    date: "2025-06-15",
    dateLabel: "June 15, 2025",
    items: [
      "Fixes Lupa S3 to override her Inherent Skill: Applause of Victory.",
      "Fixes Cartethyia S6, uses Special DMG multiplier now.",
    ],
  },
  {
    date: "2025-06-14",
    dateLabel: "June 14, 2025",
    items: [
      "Adds option for rotation duration and displays DPS if provided.",
    ],
  },
  {
    date: "2025-06-13",
    dateLabel: "June 13, 2025",
    items: [
      "Releases Lupa!",
    ],
  },
  {
    date: "2025-06-12",
    dateLabel: "June 12, 2025",
    items: [
      "Fixes Cartethyia S1 and S6, they now only apply to Fleurdelys.",
      "Adds Cartethyia to Reminiscence: Fleurdelys echo buff.",
    ],
  },
  {
    date: "2025-06-11",
    dateLabel: "June 11, 2025",
    items: [
      "Releases Cartethyia, her sig, and 2.4 echoes!",
    ],
  },
  {
    date: "2025-06-07",
    dateLabel: "June 7, 2025",
    items: [
      "Updates spacing in main nav and fixes minor pages to remove unnecessary mobile nav.",
    ],
  },
  {
    date: "2025-06-06",
    dateLabel: "June 6, 2025",
    items: [
      "Fixes the navigation to the top and some overall layout cleanup.",
      "If you are creating a new echo and you filter the list of echoes by set, it will automatically select that set for the echo you choose to save you a click.",
    ],
  },
  {
    date: "2025-06-05",
    dateLabel: "June 5, 2025",
    items: [
      "Enhanced the UI for the settings area.",
    ],
  },
  {
    date: "2025-06-03",
    dateLabel: "June 3, 2025",
    items: [
      "Updates Jiyan's buffs so you can no longer get both Forte Circuit: Qingloong at War buffs active since it's not possible in game to avoid misleading damage being displayed.",
    ],
  },
  {
    date: "2025-06-01",
    dateLabel: "June 1, 2025",
    items: [
      "Adds ability to clear a teammate.",
    ],
  },
  {
    date: "2025-05-31",
    dateLabel: "May 31, 2025",
    items: [
      "Fixed icons in a few views where the icon was filling up the whole button space.",
      "Fixed the highlighted color for black theme when choosing filters.",
      "Fixed Moonlit icon in light theme.",
    ],
  },
  {
    date: "2025-05-30",
    dateLabel: "May 30, 2025",
    items: [
      "Adds 2.4 echo sets.",
    ],
  },
  {
    date: "2025-05-28",
    dateLabel: "May 28, 2025",
    items: [
      "Updates team buffs page to group sections into accordions since the list of buffs was getting really long.",
      "Centered the character selections in team buffs.",
    ],
  },
  {
    date: "2025-05-27",
    dateLabel: "May 27, 2025",
    items: [
      "Changes app font.",
    ],
  },
  {
    date: "2025-05-26",
    dateLabel: "May 26, 2025",
    items: [
      "Adds new theme, and theme chooser.",
    ],
  },
  {
    date: "2025-05-22",
    dateLabel: "May 22, 2025",
    items: [
      "Adds Gusts of Welkin team buff.",
    ],
  },
  {
    date: "2025-05-21",
    dateLabel: "May 21, 2025",
    items: [
      "Adds support to save imported echoes to inventory upon import.",
    ],
  },
  {
    date: "2025-05-18",
    dateLabel: "May 18, 2025",
    items: [
      "Adds Ciaccona's signature weapon, Woodland Aria.",
      "Adds Woodland Aria team buff.",
    ],
  },
  {
    date: "2025-05-16",
    dateLabel: "May 16, 2025",
    items: [
      "Fixed display bug on mobile where the stats and damages were always showing.",
    ],
  },
  {
    date: "2025-05-15",
    dateLabel: "May 15, 2025",
    items: [
      "Adds rotation summary to the top of the rotation for quick access to see the total damage, shield, and healing.",
    ],
  },
  {
    date: "2025-05-11",
    dateLabel: "May 11, 2025",
    items: [
      "Adds Forte text to the rotation action to help clarify which forte an action is based off of.",
    ],
  },
  {
    date: "2025-05-10",
    dateLabel: "May 10, 2025",
    items: [
      "Adds validation to echo importer to ensure the image is the correct size.",
      "Adds percentage to the rotation pie chart, and adjusts legend color to make it easier to read in light and dark mode.",
    ],
  },
  {
    date: "2025-05-09",
    dateLabel: "May 9, 2025",
    items: [
      "Sorts the rotation chart data so it shows damage type from highest to lowest.",
    ],
  },
  {
    date: "2025-05-07",
    dateLabel: "May 7, 2025",
    items: [
      "Alphabetized the list of set bonuses for 2 and 5 set choices to make it easier to find the set you are looking for.",
    ],
  },
  {
    date: "2025-05-06",
    dateLabel: "May 6, 2025",
    items: [
      "Adds Def Ignore, DMG multiplier, and DMG multiplier additive to rotation action buffs.",
    ],
  },
  {
    date: "2025-05-05",
    dateLabel: "May 5, 2025",
    items: [
      "Automatically opens a new rotation, and rotation action when you create one, saving a click.",
    ],
  },
  {
    date: "2025-05-04",
    dateLabel: "May 4, 2025",
    items: [
      "Adds a quick way to reset all of your custom buffs.",
      "Fixed minor text issue on Phoebe S4.",
    ],
  },
  {
    date: "2025-05-03",
    dateLabel: "May 3, 2025",
    items: [
      "Ciaccona is now available since she is in the in-game gallery.",
    ],
  },
  {
    date: "2025-05-02",
    dateLabel: "May 2, 2025",
    items: [
      "Adds a note on how to use the wuwa bot for importing echoes.",
    ],
  },
  {
    date: "2025-05-01",
    dateLabel: "May 1, 2025",
    items: [
      "Update Zani Nightfall damages. The numbers displayed in the forte stats are misleading in-game. It does 9 hits instead of 2. And it also changes how the Blaze stacks are applied. At best (40 stacks), it's actually broken into 5+5+15+15, and if you have less it takes away from the end.",
    ],
  },
  {
    date: "2025-04-30",
    dateLabel: "April 30, 2025",
    items: [
      "Fixed where to put additive multipliers in multi-hits in the tooltip. The total damage was correct.",
      "Adds buffs and damage for echoes: Abyssal Patricius, and Vitreum Dancer.",
      "Updates Zani Dawning and Daybreak skill details percentages to reflect the game damage instances.",
    ],
  },
  {
    date: "2025-04-29",
    dateLabel: "April 29, 2025",
    items: [
      "Fixed Zani's Nightfall DMG, it was getting overbuffed.",
      "Updates Blazing Justice text.",
    ],
  },
  {
    date: "2025-04-28",
    dateLabel: "April 28, 2025",
    items: [
      "Releases Zani and her signature.",
    ],
  },
  {
    date: "2025-04-27",
    dateLabel: "April 27, 2025",
    items: [
      "Hides normal and average damage when a damage will always crit.",
    ],
  },
  {
    date: "2025-04-25",
    dateLabel: "April 25, 2025",
    items: [
      "Fixes light mode icons in echoes and inventory pages.",
    ],
  },
  {
    date: "2025-04-22",
    dateLabel: "April 22, 2025",
    items: [
      "Changes Roll Value to start at 0%, not 100%.",
    ],
  },
  {
    date: "2025-04-20",
    dateLabel: "April 20, 2025",
    items: [
      "Adds attack damage type, and any sub type (e.g. Coordinated) to the list of actions in your rotation.",
      "Fixes an edge case where if you import echoes when you already have echoes equipped, it can sometimes throw an issue where your cost is more than 12.",
      "Fixes an edge case where sometimes your cost isn't found in echo importer, it will use the cost from the found echo.",
    ],
  },
  {
    date: "2025-04-19",
    dateLabel: "April 19, 2025",
    items: [
      "Adds missing non-damage based resonance chains for Aalto, Baizhi, Chixia, and Mortefi.",
    ],
  },
  {
    date: "2025-04-18",
    dateLabel: "April 18, 2025",
    items: [
      "Fixed the resist modifier. It wasn't properly handling the resist shred if you ended up having more shred than base resist. it was supposed to half it, but it was missing that part.",
      "Fixes echo sets on Reminiscence: Fleurdelys.",
    ],
  },
  {
    date: "2025-04-17",
    dateLabel: "April 17, 2025",
    items: [
      "Adds missing non-damage based resonance chains for Verina, Taoqi, and Sanhua.",
    ],
  },
  {
    date: "2025-04-16",
    dateLabel: "April 16, 2025",
    items: [
      "Supports copy and paste, and drag n drop on echo importer.",
    ],
  },
  {
    date: "2025-04-13",
    dateLabel: "April 13, 2025",
    items: [
      "Releases echo importer through wuwabot build images.",
      "Fixes some minor navigation issues.",
      "Adds formulas to Info page.",
    ],
  },
  {
    date: "2025-04-07",
    dateLabel: "April 7, 2025",
    items: [
      "Adds Rover Aero to Shorekeeper's team buff.",
    ],
  },
  {
    date: "2025-04-06",
    dateLabel: "April 6, 2025",
    items: [
      "Updates Aalto's S3 MVs, they were too high before.",
      "Fixed some bugs in the navigation on secondary pages and optimized the code for the navigation systems.",
    ],
  },
  {
    date: "2025-04-04",
    dateLabel: "April 4, 2025",
    items: [
      "Adds a few missing resonance chains for Youhu.",
    ],
  },
  {
    date: "2025-04-03",
    dateLabel: "April 3, 2025",
    items: [
      "Adds missing non-damage resonance chains for Yangyang, and Yuanwu.",
    ],
  },
  {
    date: "2025-04-02",
    dateLabel: "April 2, 2025",
    items: [
      "Adds the Enabled text and checkbox to any buff that's automatically enabled, and disables it, to make it more apparent that it is enabled.",
    ],
  },
  {
    date: "2025-03-31",
    dateLabel: "March 31, 2025",
    items: [
      "Updates spectro frazzle MVs due to the 2.2 nerf in the spectro frazzle damage.",
      "Adds missing Nightmare: Lampylumen Myriad echo.",
    ],
  },
  {
    date: "2025-03-29",
    dateLabel: "March 29, 2025",
    items: [
      "Adds resist reduction/shred to the list of rotation action level buffs.",
    ],
  },
  {
    date: "2025-03-28",
    dateLabel: "March 28, 2025",
    items: [
      "Adds a preset rotation for Verina.",
    ],
  },
  {
    date: "2025-03-26",
    dateLabel: "March 26, 2025",
    items: [
      "Updates a Brant preset rotation.",
      "Releases 2.2 content: characters, weapons, echoes, and new echo set.",
    ],
  },
  {
    date: "2025-03-24",
    dateLabel: "March 24, 2025",
    items: [
      "Adds missing forte description for Shorekeeper, and a new Shorekeeper rotation.",
    ],
  },
  {
    date: "2025-03-23",
    dateLabel: "March 23, 2025",
    items: [
      "Adds 2.2 weapons: Bloodpact's Pledge, and Whispers of Sirens.",
    ],
  },
  {
    date: "2025-03-21",
    dateLabel: "March 21, 2025",
    items: [
      "Fixes Brant's Heavy Attack - Rhapsodic Riff DMG damage type, it now properly does Heavy.",
    ],
  },
  {
    date: "2025-03-20",
    dateLabel: "March 20, 2025",
    items: [
      "Adds a preset rotations for Changli, Chixia, Sanhua.",
    ],
  },
  {
    date: "2025-03-18",
    dateLabel: "March 18, 2025",
    items: [
      "Fixes an action in a new preset rotation for Aalto.",
      "Adds a preset rotation for Carlotta.",
    ],
  },
  {
    date: "2025-03-17",
    dateLabel: "March 17, 2025",
    items: [
      "Adds new rotations for Aalto.",
    ],
  },
  {
    date: "2025-03-16",
    dateLabel: "March 16, 2025",
    items: [
      "Adds new rotation for Chixia.",
    ],
  },
  {
    date: "2025-03-15",
    dateLabel: "March 15, 2025",
    items: [
      "Adds presets for rotations and many rotations from TCers to various characters.",
    ],
  },
  {
    date: "2025-03-14",
    dateLabel: "March 14, 2025",
    items: [
      "In rotations, when a rotation action is in a rotation it now always appears in the list. However, if the chain is not unlocked (e.g. resonance chain), then it is not added to the final aggregation, and it is has less opacity, and a tooltip explaining it.",
    ],
  },
  {
    date: "2025-03-13",
    dateLabel: "March 13, 2025",
    items: [
      "In rotations, it now shows all possible actions including ones locked behind resonance chains. If you have not activated that resonance chain, the action will be disabled until you unlock it.",
    ],
  },
  {
    date: "2025-03-11",
    dateLabel: "March 11, 2025",
    items: [
      "Changes rotation damage chart to use average damage.",
      "Fixes rotation damage chart to support attack type overrides like Camellya. The damage was correct, it was just incorrectly categorized.",
    ],
  },
  {
    date: "2025-03-10",
    dateLabel: "March 10, 2025",
    items: [
      "Updates a lot of Changli text with latest text changes.",
      "Merges Changli S5 buffs into one.",
    ],
  },
  {
    date: "2025-03-09",
    dateLabel: "March 9, 2025",
    items: [
      "Adds data visualization for rotation's damages broken down by type.",
    ],
  },
  {
    date: "2025-03-08",
    dateLabel: "March 8, 2025",
    items: [
      "Revert fix for Brant's S2 Crit Rate buff.",
      "Updates Brant flat attack buffs for My Moment and Theatrical Moment, to give you attack for decimals in your ER, so it doesn't require full integers to get ATK.",
    ],
  },
  {
    date: "2025-03-07",
    dateLabel: "March 7, 2025",
    items: [
      "Fixes Brant's S2 Crit Rate buff.",
      "Fixes small typo on Red Spring sword.",
    ],
  },
  {
    date: "2025-03-06",
    dateLabel: "March 6, 2025",
    items: [
      "Adds non-damage related sequences for Shorekeeper. Fixes some of her sequence text.",
      "Adds better timezone support for the filename for exporting data.",
    ],
  },
  {
    date: "2025-03-03",
    dateLabel: "March 3, 2025",
    items: [
      "Fixes Brant's Forte Circuit healing numbers.",
    ],
  },
  {
    date: "2025-03-02",
    dateLabel: "March 2, 2025",
    items: [
      "Adds Brant's weapon",
    ],
  },
  {
    date: "2025-02-23",
    dateLabel: "February 23, 2025",
    items: [
      "Fixes Camellya's Epiphyte buff.",
      "Rounds the spectro frazzle damage in the tooltip.",
    ],
  },
  {
    date: "2025-02-22",
    dateLabel: "February 22, 2025",
    items: [
      "Fixes Phoebe S2, it now does amplify instead of a multiplier change.",
      "Enables you to disable an action in a rotation.",
      "Fixes minor bug with changing rotation sequence and hits.",
      "Allows you to override the echo sets and manually set them.",
    ],
  },
  {
    date: "2025-02-20",
    dateLabel: "February 20, 2025",
    items: [
      "Adds roll value to echoes.",
    ],
  },
  {
    date: "2025-02-17",
    dateLabel: "February 17, 2025",
    items: [
      "Adds 2.1 echoes.",
    ],
  },
  {
    date: "2025-02-16",
    dateLabel: "February 16, 2025",
    items: [
      "Fixes energy regen label on echo modal.",
      "Fixes Epiphyte buff for Camellya.",
      "Fixes some base stats for Brant.",
    ],
  },
  {
    date: "2025-02-15",
    dateLabel: "February 15, 2025",
    items: [
      "Releases Brant.",
    ],
  },
  {
    date: "2025-02-14",
    dateLabel: "February 14, 2025",
    items: [
      "Fixes Phoebe's S6, it is now correctly 10% ATK, it was 20% before.",
    ],
  },
  {
    date: "2025-02-13",
    dateLabel: "February 13, 2025",
    items: [
      "Fixes Phoebe's Starflash buff from Absolution.",
    ],
  },
  {
    date: "2025-02-12",
    dateLabel: "February 12, 2025",
    items: [
      "Releases Phoebe.",
    ],
  },
  {
    date: "2025-02-10",
    dateLabel: "February 10, 2025",
    items: [
      "Adds Luminous Hymn and Ocean's Gift weapons.",
    ],
  },
  {
    date: "2025-02-09",
    dateLabel: "February 9, 2025",
    items: [
      "Adds CV to echoes in the echoes screen and inventory.",
    ],
  },
  {
    date: "2025-02-08",
    dateLabel: "February 8, 2025",
    items: [
      "Adds home page E2E test suites, more to come. You won't see these changes, but they'll help prevent bugs from getting released.",
    ],
  },
  {
    date: "2025-02-07",
    dateLabel: "February 7, 2025",
    items: [
      "Fixes Roccia base stats.",
    ],
  },
  {
    date: "2025-02-05",
    dateLabel: "February 5, 2025",
    items: [
      "Adds the ability to filter echo lists by cost.",
    ],
  },
  {
    date: "2025-02-04",
    dateLabel: "February 4, 2025",
    items: [
      "Adds visual distinction for different rarities in weapons and characters in the browser and the display.",
    ],
  },
  {
    date: "2025-02-02",
    dateLabel: "February 2, 2025",
    items: [
      "Adds visual weapon selection.",
      "Adds missing stacks to Sanhua's S6.",
    ],
  },
  {
    date: "2025-02-01",
    dateLabel: "February 1, 2025",
    items: [
      "Adds visual character selection.",
    ],
  },
  {
    date: "2025-01-31",
    dateLabel: "January 31, 2025",
    items: [
      "Updates Changli forte text.",
    ],
  },
  {
    date: "2025-01-27",
    dateLabel: "January 27, 2025",
    items: [
      "Adds Def Ignore, and Coordinated DMG Bonus as custom buffs options.",
    ],
  },
  {
    date: "2025-01-26",
    dateLabel: "January 26, 2025",
    items: [
      "Updates Sanhua's outro text.",
      "Makes Empyrean Anthem set bonus for coordinated dmg bonus automatically enabled.",
    ],
  },
  {
    date: "2025-01-25",
    dateLabel: "January 25, 2025",
    items: [
      "Minor feature: you can now exclude team buffs in a rotation action.",
    ],
  },
  {
    date: "2025-01-24",
    dateLabel: "January 24, 2025",
    items: [
      "Adds missing enery recharge on standard 5* weapons that were missing it (broadblade, gauntlet, and recitifer).",
      "Updates Magic Box DMG to be set to 5.",
      "Fixed weapon name for Overture.",
    ],
  },
  {
    date: "2025-01-23",
    dateLabel: "January 23, 2025",
    items: [
      "Updates a few Nightmare echoes. Some text and attack motion values were off.",
      "Fixes an S4 bug on Baizhi, removes the 20% multiplier change from the damage. And fixes her S4 to properly add a new coordianted attack.",
    ],
  },
  {
    date: "2025-01-21",
    dateLabel: "January 21, 2025",
    items: [
      "Releases Spectro Frazzle support",
    ],
  },
  {
    date: "2025-01-17",
    dateLabel: "January 17, 2025",
    items: [
      "Adds resist shred and damage amplify to custom buffs",
    ],
  },
  {
    date: "2025-01-15",
    dateLabel: "January 15, 2025",
    items: [
      "Adds Rover Spectro missing S3 and S4",
    ],
  },
  {
    date: "2025-01-13",
    dateLabel: "January 13, 2025",
    items: [
      "Updates Bell text",
      "Re-adds the Empyrean Anthem team buffs, accidentally got rid of it.",
    ],
  },
  {
    date: "2025-01-12",
    dateLabel: "January 12, 2025",
    items: [
      "Fixes Empyrean Anthem, no longer a team buff.",
      "Changes the flat attack and def ranges for substats",
    ],
  },
  {
    date: "2025-01-11",
    dateLabel: "January 11, 2025",
    items: [
      "Updates Carlotta's S6",
      "Fixes Nightmare Crownless damages",
    ],
  },
  {
    date: "2025-01-10",
    dateLabel: "January 10, 2025",
    items: [
      "Fixes Lorelei buffs",
      "Fixes Cosmic Ripples ATK% on level 1 and 90, it was off by .1%",
    ],
  },
  {
    date: "2025-01-08",
    dateLabel: "January 8, 2025",
    items: [
      "Adds Vitreum Dancer echo",
    ],
  },
  {
    date: "2025-01-06",
    dateLabel: "January 6, 2025",
    items: [
      "Fixes Lorelei sets",
      "Fixes new set icons in light mode",
    ],
  },
  {
    date: "2025-01-05",
    dateLabel: "January 5, 2025",
    items: [
      "Adds Roccia signature.",
      "Fixes Roccia s5. It no longer affects her forte circuit attacks.",
      "Removes stacks from Undying Flame.",
    ],
  },
  {
    date: "2025-01-04",
    dateLabel: "January 4, 2025",
    items: [
      "Adds Roccia! Note that her Magic Box damage is innacurate right now, we're trying to finalize the damage on it.",
      "Updates Carlotta s2. It now multiplies against the other multipliers which is accurate against in-game damages.",
    ],
  },
  {
    date: "2025-01-03",
    dateLabel: "January 3, 2025",
    items: [
      "Fixes minor character capitalization issues in the echo sets.",
    ],
  },
  {
    date: "2025-01-02",
    dateLabel: "January 2, 2025",
    items: [
      "Adds Jiyan S1. It is a quality of life resonance chain, so it has no effect on his damage.",
      "Added clarifying text to Aalto's Gate of Quandry. The ATK amount isn't in the official description, but since it doesn't change from the talent increase, the description has been updated to make it more clear.",
      "Adds all 1.0 echo sets to Hecate as there's a box that allows that echo to have the new set plus all old sets.",
    ],
  },
  {
    date: "2025-01-01",
    dateLabel: "January 1, 2025",
    items: [
      "Content for 2.0 has been released! Carlotta, her sig, new 4* weapons, new echoes, new echo sets, supports echo sets having independent passives, and more!",
    ],
  },
  {
    date: "2024-12-31",
    dateLabel: "December 31, 2024",
    items: [
      "Adds missing Jinhsi S2 resonance chain. This does not affect her damage output, it is a quality of life resonance chain.",
    ],
  },
  {
    date: "2024-12-30",
    dateLabel: "December 30, 2024",
    items: [
      "Removes Moonlit echo set buff from self-buffs since it only affects the next character. You still can enable it from team buffs.",
      "Changes Stringmaster passives. They work differently than expected. The second passive adds to the first passive only, it does not work independently.",
    ],
  },
  {
    date: "2024-12-29",
    dateLabel: "December 29, 2024",
    items: [
      "Adds missing Jianxin resonance chains. This does not affect her damage output, they were quality of life resonance chains.",
    ],
  },
  {
    date: "2024-12-28",
    dateLabel: "December 28, 2024",
    items: [
      "Updates Calcharo: small label updates, and adds his missing inherit skill and S1 which don't affect his damages, and also organizes his stat bonuses better.",
      "Updates Encore: adds missing S2, but it does not affect her output as it's a quality of life resonance chain.",
      "Updates Rime-Draped Sprouts text format, and adds description.",
      "Adds missing ER passive on Static Mist",
      "Fixes Rover Havoc S6, it was not applying the Crit Rate to Liberation, Intro, and Outro attacks.",
    ],
  },
  {
    date: "2024-12-27",
    dateLabel: "December 27, 2024",
    items: [
      "Updates Lumi text, and fixed Lumi S5.",
    ],
  },
  {
    date: "2024-12-26",
    dateLabel: "December 26, 2024",
    items: [
      "Updates to legal and info pages.",
    ],
  },
  {
    date: "2024-12-17",
    dateLabel: "December 17, 2024",
    items: [
      "Fixes spelling error on notice for enemy settings.",
      "Fixes Yuanwu's 1st set of DEF stat bonuses. The percent was slightly off.",
    ],
  },
  {
    date: "2024-12-06",
    dateLabel: "December 6, 2024",
    items: [
      "Fixes browsing saved echoes pagination when you apply a filter, it now resets the page to 1.",
    ],
  },
  {
    date: "2024-12-04",
    dateLabel: "December 4, 2024",
    items: [
      "Major release: Releases inventory system to manage and house echoes.",
    ],
  },
  {
    date: "2024-11-30",
    dateLabel: "November 30, 2024",
    items: [
      "Fixes Stellar Symphony second passive. It was using the old beta version. The effect doesn't change, just the text.",
      "Enables text highlighting on weapon passives and team buffs.",
    ],
  },
  {
    date: "2024-11-29",
    dateLabel: "November 29, 2024",
    items: [
      "Updated damage deepen label on rotation actions to be damage amplify for clarity.",
      "Updates Lingyang's inherit skill attack multiplier, it was doing two hits when it should have been doing just one.",
    ],
  },
  {
    date: "2024-11-28",
    dateLabel: "November 28, 2024",
    items: [
      "Fixes Calcharo S6. It is now behind a toggle.",
      "Updates Calcharo's skill formats to include coloring and highlighting.",
    ],
  },
  {
    date: "2024-11-24",
    dateLabel: "November 24, 2024",
    items: [
      "Fixes small bug with echo sets where 2-2-1 would result in no sets being given. Should be fixed now.",
    ],
  },
  {
    date: "2024-11-20",
    dateLabel: "November 20, 2024",
    items: [
      "Adds colors to the echo sets in the various echo UI.",
    ],
  },
  {
    date: "2024-11-17",
    dateLabel: "November 17, 2024",
    items: [
      "Adjusts the background color on the talent descriptions so it's easier to read.",
      "Behind the scenes code optimizations, removed 200 redundant LoC.",
      "Fixed Camellya's R5 text. The calculations were correct.",
      "Changes Camellya R3 to be a global ATK buff given video evidence.",
    ],
  },
  {
    date: "2024-11-15",
    dateLabel: "November 15, 2024",
    items: [
      "Minor adjustment to Camellya's Outro multiplier numbers. It was missing decimals, so the change will be largely unnoticed in terms of damage calculated.",
      "Fixes Verina BA1 talents. It had two hits, it should only have one.",
    ],
  },
  {
    date: "2024-11-14",
    dateLabel: "November 14, 2024",
    items: [
      "Updates Yinlin talent descriptions since they were updated in the game in 1.4.",
      "Adds new 1.4 weapon: Somnoire Anchor",
      "Updates Camellya sig to use 1.4 release text and image.",
      "Updates Camellya text across the board.",
    ],
  },
  {
    date: "2024-11-12",
    dateLabel: "November 12, 2024",
    items: [
      "Adds legal page.",
    ],
  },
  {
    date: "2024-11-10",
    dateLabel: "November 10, 2024",
    items: [
      "Fixes issue when you change weapons, sometimes the buffs wouldn't clear out from the previous weapon.",
    ],
  },
  {
    date: "2024-11-09",
    dateLabel: "November 9, 2024",
    items: [
      "Fixes issue when you change characters and sometimes the weapon passives do not load properly.",
    ],
  },
  {
    date: "2024-11-07",
    dateLabel: "November 7, 2024",
    items: [
      "Adds browser and finder for choosing echoes to streamline setting up your echoes.",
    ],
  },
  {
    date: "2024-11-05",
    dateLabel: "November 5, 2024",
    items: [
      "UI adjustments for legibility.",
    ],
  },
  {
    date: "2024-11-04",
    dateLabel: "November 4, 2024",
    items: [
      "Updates Camellya signature for 1.4.7 beta updates.",
      "UI Update: Adjusts the hidden text to be more legible.",
      "Fixes flat HP value, had a typo.",
      "Adds missing flat ATK and DEF (30).",
    ],
  },
  {
    date: "2024-11-03",
    dateLabel: "November 3, 2024",
    items: [
      "Major release: UI overhaul! Enjoy the new UI! Everything should be backwards compatible, but a lot easier to use. It also includes saving your echo enemy data, and automatically figures out your echo sets, and your main echo based on your echoes.",
    ],
  },
  {
    date: "2024-10-31",
    dateLabel: "October 31, 2024",
    items: [
      "Fixes Camellya S6 Eternal Flower damage. It was missing the S2 buff.",
      "Updates Camellya S3 to include Dayflower and Eternal Flower in the ATK buff.",
    ],
  },
  {
    date: "2024-10-30",
    dateLabel: "October 30, 2024",
    items: [
      "Updates Camellya for 1.4.6 changes.",
      "Updates Camellya S6 to set her multiplier to 250% instead of being additive 250%.",
    ],
  },
  {
    date: "2024-10-25",
    dateLabel: "October 25, 2024",
    items: [
      "Updates Camellya, adds Ashen Blossom Vine Dance from Deep Slumber buffs after confirming it gets buffed.",
    ],
  },
  {
    date: "2024-10-20",
    dateLabel: "October 20, 2024",
    items: [
      "Updates Camellya, removes Ashen Blossom Vine Dance from Deep Slumber buffs.",
    ],
  },
  {
    date: "2024-10-19",
    dateLabel: "October 19, 2024",
    items: [
      "Updates Camellya for 1.4.3 beta changes.",
      "Text change for Lumi for 1.4.3 beta changes.",
    ],
  },
  {
    date: "2024-10-18",
    dateLabel: "October 18, 2024",
    items: [
      "Adds 0% enemy resist option.",
      "Fixes Camellya s6, s3 ATK buff to not be a global buff, and adds her basic attacks to her self buff.",
    ],
  },
  {
    date: "2024-10-12",
    dateLabel: "October 12, 2024",
    items: [
      "Releases Lumi.",
    ],
  },
  {
    date: "2024-10-11",
    dateLabel: "October 11, 2024",
    items: [
      "Releases Camellya and her signature.",
    ],
  },
  {
    date: "2024-10-10",
    dateLabel: "October 10, 2024",
    items: [
      "Adds echo set descriptions for 2pc and 5pc, and adds enabled toggle for 5pc set effect.",
    ],
  },
  {
    date: "2024-10-08",
    dateLabel: "October 8, 2024",
    items: [
      "Adds a few missing common echo actions, more to come.",
    ],
  },
  {
    date: "2024-10-04",
    dateLabel: "October 4, 2024",
    items: [
      "Removes Shorekeeper old S4 from team buffs.",
    ],
  },
  {
    date: "2024-10-03",
    dateLabel: "October 3, 2024",
    items: [
      "Prevents echo and echo set bonus from exceeding max possible stacks when you change echoes and bonus sets.",
      "Fixes Shorekeeper S4, it changed on release.",
    ],
  },
  {
    date: "2024-10-02",
    dateLabel: "October 2, 2024",
    items: [
      "Adds tooltip to show breakdown of ATK, HP, and DEF on stats.",
    ],
  },
  {
    date: "2024-10-01",
    dateLabel: "October 1, 2024",
    items: [
      "Fixes 1-cost echo HP%",
      "Enables choosing the current character in party buffs.",
      "Updates the title and text for when a character does not have an echo with attacks.",
    ],
  },
  {
    date: "2024-09-30",
    dateLabel: "September 30, 2024",
    items: [
      "Fixes missing outro attacks in damages list.",
      "Fixes custom buffs where it greatly alters stats if you have blank Flat HP, ATK, DEF values.",
    ],
  },
  {
    date: "2024-09-18",
    dateLabel: "September 18, 2024",
    items: [
      "Echo damages are now available! It includes Calamity, Overlord, and elite. Common echoes will come later.",
    ],
  },
  {
    date: "2024-09-11",
    dateLabel: "September 11, 2024",
    items: [
      "Updates when rotation action hit count takes affect. It updates the calculations on blur instead of on value change so you can enter the value easier.",
    ],
  },
  {
    date: "2024-09-10",
    dateLabel: "September 10, 2024",
    items: [
      "For 1 and 2 star weapons, changes the list of levels and default level since they cap at level 70.",
      "Weapon level and refinements are finally remembered per-weapon.",
      "Bug fix: Fixes Shorekeeper self-buff for CD. It was incorrectly applying it to CR, this got patched.",
      "Adds Lava Larva echo",
    ],
  },
  {
    date: "2024-09-09",
    dateLabel: "September 9, 2024",
    items: [
      "Adds weapon images to weapons UI.",
      "Adds Glacio Dreadmane echo",
      "Updates Shorekeeper for 1.3.9 beta changes",
    ],
  },
  {
    date: "2024-09-08",
    dateLabel: "September 8, 2024",
    items: [
      "Tweak mobile experience by giving it more space, which should alleviate some elements getting cut off.",
      "Bug fix: Adds missing aggregations on custom rotations. The refactor yesterday, Sept 7, removed it on accident.",
      "Adds ability to quickly reset echoes back to blank",
    ],
  },
  {
    date: "2024-09-07",
    dateLabel: "September 7, 2024",
    items: [
      "Refactors stats and damages code",
      "Adds ability to see talent details",
    ],
  },
  {
    date: "2024-09-06",
    dateLabel: "September 6, 2024",
    items: [
      "Fixes 4-slot DEF% on echoes",
      "Changes Taoqi BA3. Technically it hits twice in-game, but the talent percent in-game, and on the wiki, have 1 values. But I've changed it to hit twice and each hit have half the value.",
      "Updates Shorekeeper buff for 1.3.9 beta, and adds Stellar Symphony to team buffs.",
    ],
  },
  {
    date: "2024-09-05",
    dateLabel: "September 5, 2024",
    items: [
      "Rounds the ATK, HP, and DEF. Floors the numbers after confirming that's how the game handles decimals.",
    ],
  },
  {
    date: "2024-09-04",
    dateLabel: "September 4, 2024",
    items: [
      "Custom buffs are available.",
    ],
  },
  {
    date: "2024-09-02",
    dateLabel: "September 2, 2024",
    items: [
      "Updates Shorekeeper signature to use updated EN name.",
      "Minor: Changes rotations icon",
    ],
  },
  {
    date: "2024-09-01",
    dateLabel: "September 1, 2024",
    items: [
      "Major update: Custom rotations has been released! You can now make your own rotations and add buffs per action in a rotation to help you understand how much damage you do more accurately.",
      "Adds Taoqi's healing on her skill.",
      "Bug fix: DEF% on 1-slot echoes were off, fixes them.",
    ],
  },
  {
    date: "2024-08-30",
    dateLabel: "August 30, 2024",
    items: [
      "Youhu is now available.",
    ],
  },
  {
    date: "2024-08-29",
    dateLabel: "August 29, 2024",
    items: [
      "Adds 1.3 new 4* weapons.",
      "Adds new 1.3 echo, Fallacy of No Return to personal echo and team buffs list.",
    ],
  },
  {
    date: "2024-08-28",
    dateLabel: "August 28, 2024",
    items: [
      "Fixes Xiangli Yao's S5 to only affect the first hit of damage, not all liberation actions.",
      "Updates Shorekeeper ER calculation buffs to be inclusive of base ER based on latest translations.",
    ],
  },
  {
    date: "2024-08-27",
    dateLabel: "August 27, 2024",
    items: [
      "Adds Shorekeeper and Shorekeeper signature (name TBD)",
    ],
  },
  {
    date: "2024-08-20",
    dateLabel: "August 20, 2024",
    items: [
      "Adds missing cursor change to resonance chains to indicate you can click the whole box to activate it.",
      "Shields are now supported. Jianxin, Verina, Yuanwu, and Toaqi have their shields added.",
    ],
  },
  {
    date: "2024-08-19",
    dateLabel: "August 19, 2024",
    items: [
      "You can now delete/empty your stored data in the settings.",
    ],
  },
  {
    date: "2024-08-18",
    dateLabel: "August 18, 2024",
    items: [
      "Quality of life: you can now click the box of a buff and it toggles it.",
      "Adds notice for enemy resist for ToA to make it more clear for people.",
      "Changes enemy resist to be % for the user but still decimal in code to make it more accessible.",
      "Refactors enemy code.",
    ],
  },
  {
    date: "2024-08-17",
    dateLabel: "August 17, 2024",
    items: [
      "Jianxin is now avilable. All characters are done!",
      "Adds the name of the type of attacks instead of generically saying \"Liberation Attack\", it'll say \"Resonance Liberation: Unmovable\"",
      "Bug fix: Fixes Aalto S3, it was not properly enabling his new hits. It works again.",
    ],
  },
  {
    date: "2024-08-16",
    dateLabel: "August 16, 2024",
    items: [
      "Baizhi is now available.",
      "Moves assets to external service.",
      "Updates Lingyang S6 to only affect his Forte.",
    ],
  },
  {
    date: "2024-08-15",
    dateLabel: "August 15, 2024",
    items: [
      "Verina is now available.",
    ],
  },
  {
    date: "2024-08-14",
    dateLabel: "August 14, 2024",
    items: [
      "Bug fix: Fixed some weapon passives not resetting when changing weapons.",
    ],
  },
  {
    date: "2024-08-13",
    dateLabel: "August 13, 2024",
    items: [
      "Updates Zhezhi and Xiangli Yao's talent descriptions to match official 1.2. Note: if you had previous saved states for some buffs, it may have been reset (just this once) due to these changes.",
    ],
  },
  {
    date: "2024-08-12",
    dateLabel: "August 12, 2024",
    items: [
      "Aalto has been released.",
      "Bug fix: Fixes Spectro Rover HP, DEF, ATK stats.",
      "Updates XY S1 talents",
    ],
  },
  {
    date: "2024-08-11",
    dateLabel: "August 11, 2024",
    items: [
      "Updates XY's S2 to be Crit Damage instead of Crit Rate.",
    ],
  },
  {
    date: "2024-08-10",
    dateLabel: "August 10, 2024",
    items: [
      "Updates XY, Jiyan, Rover Havoc, and Encore outro skill labels for clarity",
      "UI Enhancement to stats and damages list",
      "Removes some stats that weren't ever going to show values properly (e.g. Def Shred)",
    ],
  },
  {
    date: "2024-08-09",
    dateLabel: "August 9, 2024",
    items: [
      "Outro damages are now supported.",
      "Weapon stats (attack, main stat, and main stat value) are now shown so it's clear what you're getting from the weapon.",
    ],
  },
  {
    date: "2024-08-08",
    dateLabel: "August 8, 2024",
    items: [
      "Adds Zhezi and Xiangli Yao's weapons.",
      "Updates Xiangli Yao for 1.2.6 beta changes",
    ],
  },
  {
    date: "2024-08-07",
    dateLabel: "August 7, 2024",
    items: [
      "Adds team weapon buffs.",
      "Bug fix: Fixes Amity Discord passive",
    ],
  },
  {
    date: "2024-08-06",
    dateLabel: "August 6, 2024",
    items: [
      "Adjusts Xiangli Yao's Resonance Chain 5 to only affect his Liberation talents.",
    ],
  },
  {
    date: "2024-08-05",
    dateLabel: "August 5, 2024",
    items: [
      "Yangyang is now available.",
      "Adds Healing Bonus and Energy Regen attributes.",
    ],
  },
  {
    date: "2024-08-03",
    dateLabel: "August 3, 2024",
    items: [
      "Lingyang is now available.",
    ],
  },
  {
    date: "2024-08-02",
    dateLabel: "August 2, 2024",
    items: [
      "Bug fix: Fixes weapon passives not always syncing on reload correctly.",
    ],
  },
  {
    date: "2024-08-01",
    dateLabel: "August 1, 2024",
    items: [
      "Rover Spectro is now available.",
    ],
  },
  {
    date: "2024-07-31",
    dateLabel: "July 31, 2024",
    items: [
      "Chixia is now available.",
    ],
  },
  {
    date: "2024-07-30",
    dateLabel: "July 30, 2024",
    items: [
      "Fixed rare edge case loading issues when you warm reload the page the echoes weren't loading correctly. This may still occur, but it should be resolved for more users.",
    ],
  },
  {
    date: "2024-07-29",
    dateLabel: "July 29, 2024",
    items: [
      "New feature: ability to import and export your calculator data.",
    ],
  },
  {
    date: "2024-07-26",
    dateLabel: "July 26, 2024",
    items: [
      "Updates Xiangli Yao, and Zhezhi for latest 1.2 beta changes.",
      "Bug fix: Xiangli Yao forte circuit attacks are now correctly liberation based.",
    ],
  },
  {
    date: "2024-07-25",
    dateLabel: "July 25, 2024",
    items: [
      "Xiangli Yao is now available.",
    ],
  },
  {
    date: "2024-07-23",
    dateLabel: "July 23, 2024",
    items: [
      "Rover Havoc is now available.",
    ],
  },
  {
    date: "2024-07-21",
    dateLabel: "July 21, 2024",
    items: [
      "Sanhua is now available.",
      "Yuanwu is now available.",
    ],
  },
  {
    date: "2024-07-20",
    dateLabel: "July 20, 2024",
    items: [
      "Makes weapon selection easier by grouping by rarity, and fixing names.",
      "Bug fix: Fixes default character when one hasn't been set in state",
    ],
  },
  {
    date: "2024-07-19",
    dateLabel: "July 19, 2024",
    items: [
      "Mortefi is now available.",
    ],
  },
  {
    date: "2024-07-18",
    dateLabel: "July 18, 2024",
    items: [
      "Makes character selection easier by grouping by 4/5* and alphabetized",
      "Fixes decimal issues on stats (except HP, ATK, DEF: coming soon)",
    ],
  },
  {
    date: "2024-07-17",
    dateLabel: "July 17, 2024",
    items: [
      "Yinlin's resonance chain 6 attack now requires the resonance chain to be unlocked for it to available.",
      "Adds notification if you exceed the maximum amount of echo cost.",
      "Updates Zhezhi outro to latest from beta.",
    ],
  },
  {
    date: "2024-07-16",
    dateLabel: "July 16, 2024",
    items: [
      "Released Zhezhi",
      "Now supports attacks based on resonance chains",
      "Bug fix: where weapon passives from previous weapon were applied when changing weapons",
      "Bug fix: where the substat range on echoes weren't set correctly",
    ],
  },
  {
    date: "2024-07-15",
    dateLabel: "July 15, 2024",
    items: [
      "Weapon passives now persist for all weapons for all characters. Soon every weapon will persist their level and refinment per-character too. (Inventory system has been added to the roadmap to streamline equipment for characters)",
    ],
  },
  {
    date: "2024-07-14",
    dateLabel: "July 14, 2024",
    items: [
      "Encore is now available!",
    ],
  },
  {
    date: "2024-07-13",
    dateLabel: "July 13, 2024",
    items: [
      "Major release: All data is stored in the browser so when you refresh the page, or come back, all data will come back. And it applies to all characters, even if they're azctive or not.",
    ],
  },
  {
    date: "2024-07-12",
    dateLabel: "July 12, 2024",
    items: [
      "Fixes Changli Fiery Feather buff to only apply to her forte",
    ],
  },
  {
    date: "2024-07-06",
    dateLabel: "July 6, 2024",
    items: [
      "Fixes character level bug when using ascension level (with a +)",
      "Fixes Changli outro team buff with proper translation and resulting deepen buff",
    ],
  },
  {
    date: "2024-07-03",
    dateLabel: "July 3, 2024",
    items: [
      "Fixes weapon issues where if you changed weapons or adjusts passives the stats wouldn't be accurate",
      "Fixed Jinhsi's intro buff",
    ],
  },
  {
    date: "2024-07-02",
    dateLabel: "July 2, 2024",
    items: [
      "Releases Yinlin",
    ],
  },
  {
    date: "2024-07-01",
    dateLabel: "July 1, 2024",
    items: [
      "Adds Impermanence Heron to team buffs",
      "Text fix for Jinhsi S3, it was calculating properly though",
    ],
  },
  {
    date: "2024-06-30",
    dateLabel: "June 30, 2024",
    items: [
      "Releases main echo buffs",
      "Simplify and merge Jinhsi S6 into one toggle",
      "Fix Jue echo, and add a missing echo",
    ],
  },
  {
    date: "2024-06-29",
    dateLabel: "June 29, 2024",
    items: [
      "Adjust Jinhsi R6 Incandescence 45%.",
      "Fixes Changli Inherit skill Inherent Skill: Secret Strategist to only apply to the noted skills.",
    ],
  },
  {
    date: "2024-06-28",
    dateLabel: "June 28, 2024",
    items: [
      "Fixes Jinhsi R6 45% multiplier with how it interacts with Incandescence",
    ],
  },
  {
    date: "2024-06-27",
    dateLabel: "June 27, 2024",
    items: [
      "Fixes Jinhsi intro buff",
      "Supports negative enemy resist shred handling now that resist shred effects are in",
    ],
  },
  {
    date: "2024-06-26",
    dateLabel: "June 26, 2024",
    items: [
      "Danjin is implemented",
      "Minor UI: Alphabetized the team character list",
    ],
  },
  {
    date: "2024-06-25",
    dateLabel: "June 25, 2024",
    items: [
      "Released team buffs!",
      "Fixes Changli inherit skill and S1 to only affect specific skills stated in the description",
    ],
  },
  {
    date: "2024-06-23",
    dateLabel: "June 23, 2024",
    items: [
      "Simplified the selection of echo set bonuses",
      "Adjusts some min/max values in echo substats to match latest research",
    ],
  },
  {
    date: "2024-06-22",
    dateLabel: "June 22, 2024",
    items: [
      "Jiyan and Taoqi has been added!",
      "Fix new buff background on light mode",
      "Enable you to de-select items in echo screen",
      "Removes errant flat values from main stat echo choices",
    ],
  },
  {
    date: "2024-06-21",
    dateLabel: "June 21, 2024",
    items: [
      "Updates to Changli and Jinhsi for latest beta changes",
      "Fixes R5 for both Changli and Jinshi, uses proper base talent multiplier",
    ],
  },
  {
    date: "2024-06-20",
    dateLabel: "June 20, 2024",
    items: [
      "Calculator is now mobile-friendly!",
      "Fixes Jinhsi R1, it has the stacks now.",
      "Ages of Harvest weapon passives fixed. It adds the elemental damage bonus now too.",
      "Adds context note on Jinhsi R6 due to current limitation. Will fix later so you won't need to re-enter the stacks.",
      "Adds Discord link",
      "Changes Blazing Brilliance passive to ATK from CR due to correction",
    ],
  },
  {
    date: "2024-06-19",
    dateLabel: "June 19, 2024",
    items: [
      "Resonance chains have been implemented! ⚡",
      "Ages of Harvest weapon passives split so you can control if you have one or both passives active",
      "Prevents users from entering stacks beyond the max amount of stacks",
      "UI enhancement to the final stats",
    ],
  },
  {
    date: "2024-06-18",
    dateLabel: "June 18, 2024",
    items: [
      "Jinhsi is now available",
      "Adds support for talent modifiers through buffs",
      "Updates for 1.1.6 (Hotfix: 1.1.6) for Changli's weapon, Jinhsi, and Jinhsi's weapon.",
      "Minor UI updates: Adds character avatar, cleans up character selection. Makes clicking \"Enabled\" easier.",
    ],
  },
  {
    date: "2024-06-17",
    dateLabel: "June 17, 2024",
    items: [
      "Added stat bonuses from talent tree",
      "UI update to make managing stats while looking at damages easier",
    ],
  },
  {
    date: "2024-06-16",
    dateLabel: "June 16, 2024",
    items: [
      "Behind the scenes update: I refactored how the stats are added which will make adding constellations / resonance chains, team buffs, inherit skills, etc. a lot faster to implement.",
      "Makes main nav a little easier to use",
      "Moves talents to main screen, makes talent level UI easier to use",
    ],
  },
  {
    date: "2024-06-15",
    dateLabel: "June 15, 2024",
    items: [
      "Finished Calcharo",
      "Finished almost all Broadblades. There's only one that is missing passives and that is one with HP thresholds (coming soon)",
      "Fixed bonus damage modifers, it as over-buffing",
      "Fixed weapon passive, and display for Def Ignore (it was calculating correctly, it was just a visual issue)",
      "Update to the echo selection UI",
      "Makes update page to make updates more visible",
    ],
  },
];
