export const rotations: RotationPreset[] = [
  {
    name: `TacticalKush was here :3`,
    description: `Standard rotation`,
    author: `TacticalKush`,
    data: {
      name: "TacticalKush was here :3",
      description: "",
      actions: [
        {
          order: 1,
          key: "InstantofAnnihilationSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
        },
        {
          order: 2,
          key: "WingbladeSkillDMG",
          type: "skill",
          count: 1,
          buffs: [],
        },
        {
          order: 3,
          key: "DevastationDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [],
        },
        {
          order: 4,
          key: "UmbraBasicAttack1DMG",
          type: "forteCircuit",
          count: "2",
          buffs: [],
        },
        {
          order: 5,
          key: "UmbraBasicAttack2DMG",
          type: "forteCircuit",
          count: 2,
          buffs: [],
        },
        {
          type: "forteCircuit",
          order: 6,
          count: 2,
          buffs: [],
          key: "UmbraBasicAttack3DMG",
        },
        {
          type: "forteCircuit",
          order: 7,
          count: "2",
          buffs: [],
          key: "UmbraBasicAttack4DMG",
        },
        {
          type: "forteCircuit",
          order: 8,
          count: "2",
          buffs: [],
          key: "UmbraBasicAttack5DMG",
        },
        {
          order: 9,
          key: "UmbraLifetakerDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [],
        },
        {
          order: 10,
          key: "DeadeningAbyssSkillDMG",
          type: "liberation",
          count: 1,
          buffs: [],
        },
        { order: 11, key: "OutroSkillDMG", type: "outro", count: 1, buffs: [] },
        {
          order: 12,
          key: "SequenceNode5AeonSymphony",
          type: "forteCircuit",
          count: 2,
          buffs: [],
        },
      ],
    },
  },
  {
    name: `Optimised rotation`,
    description: `Do some BA before intro to stack echo set and BB buffs. Use nightmare crownless echo to dash cancel the 2nd half of BA 5. Crownless attacks arent included because i cant put them into my rotation here for some reason. enhanced skill is used at start to be able to use a skill after end of enhanced state as well.`,
    author: `Legend`,
    data: {
      name: "Optimised rotation",
      description:
        "Do some BA before intro to stack echo set and BB buffs. Use nightmare crownless echo to dash cancel the 2nd half of BA 5. Crownless attacks arent included because i cant put them into my rotation here for some reason. enhanced skill is used at start to be able to use a skill after end of enhanced state as well.",
      actions: [
        {
          order: 1,
          key: "TuneslayerBasicAttack1DMG",
          type: "basic",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "TuneslayerBasicAttack2DMG",
          type: "basic",
          count: 2,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "InstantofAnnihilationSkillDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "WingbladeSkillDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "DevastationDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "DeadeningAbyssSkillDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "UmbraLifetakerDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "UmbraBasicAttack1DMG",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "UmbraBasicAttack2DMG",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "UmbraBasicAttack3DMG",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "UmbraBasicAttack4DMG",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "UmbraBasicAttack5DMG",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "SequenceNode5AeonSymphony",
          type: "forteCircuit",
          count: 3,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 14,
          key: "WingbladeSkillDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 15,
          key: "OutroSkillDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
];
