export const forteCircuitAttacks = {
  name: "Forte Circuit: Signal Light",
  description: `<div class="skilldescription"><span class="Title">Energized Pounce</span><br>When Yellow Light Spark is fully recovered, replace Resonance Skill with Resonance Skill <span class="Highlight">Energized Pounce</span> that deals <span class="Thunder">Electro DMG</span> and enter <span class="Highlight">Red Spotlight Mode</span>. The DMG dealt is considered Basic Attack DMG.<br>When in <span class="Highlight">Red Spotlight Mode</span>, the DMG Multiplier of <span class="Highlight">Red Light: Basic Attack</span> and <span class="Highlight">Red Light: Heavy Attack</span> is increased, with an extra amount of Sparks recovered.<br><span class="Highlight">Red Spotlight Mode</span> ends after performing altogether 4 Basic Attacks and/or Heavy Attacks.<br><span class="Title">Energized Rebound</span><br>When Red Light Spark is fully recovered, replace Resonance Skill with Resonance Skill <span class="Highlight">Energized Rebound</span> that deals <span class="Thunder">Electro DMG</span> and enter <span class="Highlight">Yellow Spotlight Mode</span>. The DMG dealt is considered Basic Attack DMG.<br>When in <span class="Highlight">Yellow Spotlight Mode</span>, <span class="Highlight">Glitter</span> is replaced by <span class="Highlight">Glare</span>, with an increased DMG Multiplier and an extra amount of Sparks recovered.<br><span class="Highlight">Yellow Spotlight Mode</span> ends after shooting 6 <span class="Highlight">Glares</span>.<br><span class="Title">Laser</span><br>Casting Outro Skill consumes all Sparks obtained in the current mode.<br>Laser can be cast when the amount of consumed Sparks is greater than or equal to 25, dealing <span class="Thunder">Electro DMG</span>.  The DMG dealt is considered Basic Attack DMG. <br>Every 25 Sparks consumed generates 1 extra Laser beam, up to 4 Laser beams.<br><span class="Title">Yellow Light Spark</span><br>Lumi can hold up to 100 Yellow Light Sparks.<br>Lumi obtains Yellow Light Spark under the following conditions: <br>When <span class="Highlight">Yellow Light: Basic Attack</span> hits the target;<br>When <span class="Highlight">Glitter</span> hits the target;<br>When <span class="Highlight">Glare</span> hits the target;<br>When Resonance Skill <span class="Highlight">Energized Rebound</span> hits the target;<br>When casting Intro Skill <span class="Highlight">Special Delivery</span>.<br><span class="Title">Red Light Spark</span><br>Lumi can hold up to 100 Red Light Sparks.<br>Lumi obtains Red Light Spark under the following conditions:<br>When Normal Attack <span class="Highlight">Navigation Support</span> hits the target in <span class="Highlight">Red Light Mode</span> or <span class="Highlight">Red Spotlight Mode</span>.</div>`,
  attacks: [
    {
      key: "GlareDMG",
      label: "Glare DMG",
      talents: {
        "1": "41.00%",
        "2": "44.37%",
        "3": "47.73%",
        "4": "52.44%",
        "5": "55.80%",
        "6": "59.66%",
        "7": "65.04%",
        "8": "70.42%",
        "9": "75.80%",
        "10": "81.52%",
      },
      type: "Basic",
    },
    {
      key: "RedSpotlightBasicAttack1DMG",
      label: "Red Spotlight: Basic Attack 1 DMG",
      talents: {
        "1": "60.48%",
        "2": "65.44%",
        "3": "70.40%",
        "4": "77.35%",
        "5": "82.31%",
        "6": "88.01%",
        "7": "95.94%",
        "8": "103.88%",
        "9": "111.81%",
        "10": "120.25%",
      },
      type: "Basic",
    },
    {
      key: "RedSpotlightBasicAttack2DMG",
      label: "Red Spotlight: Basic Attack 2 DMG",
      talents: {
        "1": "69.57% + 13.92%*5",
        "2": "75.28% + 15.06%*5",
        "3": "80.98% + 16.20%*5",
        "4": "88.97% + 17.80%*5",
        "5": "94.68% + 18.94%*5",
        "6": "101.24% + 20.25%*5",
        "7": "110.36% + 22.08%*5",
        "8": "119.49% + 23.90%*5",
        "9": "128.62% + 25.73%*5",
        "10": "138.32% + 27.67%*5",
      },
      type: "Basic",
    },
    {
      key: "RedSpotlightBasicAttack3DMG",
      label: "Red Spotlight: Basic Attack 3 DMG",
      talents: {
        "1": "47.15% + 110.00%",
        "2": "51.01% + 119.02%",
        "3": "54.88% + 128.04%",
        "4": "60.29% + 140.67%",
        "5": "64.16% + 149.69%",
        "6": "68.60% + 160.06%",
        "7": "74.79% + 174.49%",
        "8": "80.97% + 188.93%",
        "9": "87.16% + 203.36%",
        "10": "93.73% + 218.69%",
      },
      type: "Basic",
    },
    {
      key: "RedSpotlightHeavyAttackDMG",
      label: "Red Spotlight: Heavy Attack DMG",
      talents: {
        "1": "44.35%*2",
        "2": "47.99%*2",
        "3": "51.63%*2",
        "4": "56.72%*2",
        "5": "60.36%*2",
        "6": "64.54%*2",
        "7": "70.36%*2",
        "8": "76.18%*2",
        "9": "81.99%*2",
        "10": "88.18%*2",
      },
      type: "Basic",
    },
    {
      key: "EnergizedPounceDMG",
      label: "Energized Pounce DMG",
      talents: {
        "1": "92.20%*2",
        "2": "99.77%*2",
        "3": "107.33%*2",
        "4": "117.91%*2",
        "5": "125.47%*2",
        "6": "134.17%*2",
        "7": "146.26%*2",
        "8": "158.36%*2",
        "9": "170.46%*2",
        "10": "183.31%*2",
      },
      type: "Basic",
    },
    {
      key: "EnergizedReboundDMG",
      label: "Energized Rebound DMG",
      talents: {
        "1": "126.60%",
        "2": "136.99%",
        "3": "147.37%",
        "4": "161.90%",
        "5": "172.28%",
        "6": "184.22%",
        "7": "200.83%",
        "8": "217.43%",
        "9": "234.03%",
        "10": "251.79%",
      },
      type: "Basic",
    },
    {
      key: "SingleLaserBeamDMG",
      label: "Single Laser Beam DMG",
      talents: {
        "1": "37.50%",
        "2": "40.58%",
        "3": "43.65%",
        "4": "47.96%",
        "5": "51.03%",
        "6": "54.57%",
        "7": "59.49%",
        "8": "64.41%",
        "9": "69.33%",
        "10": "74.56%",
      },
      type: "Basic",
    },
  ],
};
