export const skillAttacks = {
  name: "Resonance Skill: Searchlight Service",
  description: `<div class="skilldescription"><span class="Title">Pounce</span><br>When in <span class="Highlight">Yellow Light Mode</span>, use Resonance Skill to perform Pounce, which consumes STA to pounce on the target before switching to <span class="Highlight">Red Light Mode</span>.<br>Lumi will perform a <span class="Highlight">Pounce</span> without STA cost when switched onto the field.<br><span class="Title">Rebound</span><br>When in <span class="Highlight">Red Light Mode</span>, use Resonance Skill to perform Rebound, which consumes STA to leap backward and attack the target before switching to <span class="Highlight">Yellow Light Mode</span>.<br><span class="Title">Yellow Light Mode</span><br>Perform ranged attacks when in Yellow Light Mode.<br><span class="Title">Red Light Mode</span><br>Perform melee attacks when in Red Light Mode.</div>`,
  attacks: [
    {
      key: "PounceDMG",
      label: "Pounce DMG",
      talents: {
        "1": "91.20%",
        "2": "98.68%",
        "3": "106.16%",
        "4": "116.63%",
        "5": "124.11%",
        "6": "132.71%",
        "7": "144.68%",
        "8": "156.64%",
        "9": "168.61%",
        "10": "181.32%",
      },
      type: "Skill",
    },
    {
      key: "ReboundDMG",
      label: "Rebound DMG",
      talents: {
        "1": "87.40%",
        "2": "94.57%",
        "3": "101.74%",
        "4": "111.77%",
        "5": "118.94%",
        "6": "127.18%",
        "7": "138.65%",
        "8": "150.11%",
        "9": "161.58%",
        "10": "173.76%",
      },
      type: "Skill",
    },
  ],
};
