export const forteCircuitAttacks = {
  name: "Forte Circuit: Poetic Essence",
  description: `<div class="skilldescription">At four Auspices, hold <span class="Highlight">Normal Attack</span> to release <span class="Highlight">Poetic Essence</span>, dealing <span class="Ice">Glacio DMG</span>, considered as Skill DMG, while restoring HP for all nearby party members.<br>Youhu can hold up to four Auspices.<br> <br><span class="Title">Poetic Essence</span><br>Deal <span class="Ice">Glacio DMG</span> to enemies within the range and additionally obtain one of the following effects based on the Auspice combination:<br>- <span class="Highlight">Free Verse</span>: Four different types Auspices. Additionally reduce the Vibration Strength of hit enemies.<br>- <span class="Highlight">Antithesis</span>: A pair of Auspices. Increase <span class="Highlight">Poetic Essence</span>'s DMG by 70%.<br>- <span class="Highlight">Double Pun</span>: Two pairs of Auspices. Additionally restore HP for all nearby party members.<br>- <span class="Highlight">Triplet</span>: Three identical Auspices. Increase <span class="Highlight">Poetic Essence</span>'s DMG by 175%.<br>- <span class="Highlight">Perfect Rhyme</span>: Four identical Auspices. Simultaneously activate the effects of <span class="Highlight">Free Verse</span>, <span class="Highlight">Double Pun</span>, and <span class="Highlight">Triplet</span> at the same time.<br>Casting <span class="Highlight">Poetic Essence</span> removes all Auspices.<br> <br><span class="Title">Auspice</span><br>- Youhu gains an Auspice through <span class="Highlight">Antique Apprasial</span>. Use <span class="Highlight">Basic Attack</span> while holding an <span class="Highlight">Antique</span> to receive the corresponding Auspice.<br>- Youhu unlocks <span class="Highlight">Antiques</span> by casting Resonance Skill <span class="Highlight">Scroll Divination</span>, Intro Skill <span class="Highlight">Scroll of Wonders</span>, Heavy Attack <span class="Highlight">Frostfall</span>, Resonance Liberation <span class="Highlight">Fortune's Favor</span>, and <span class="Highlight">Dodge Counter</span>.</div>`,
  attacks: [
    {
      key: "PoeticEssenceSkillDMG",
      label: "Poetic Essence Skill DMG",
      talents: {
        "1": "18.72%*10",
        "2": "20.26%*10",
        "3": "21.79%*10",
        "4": "23.94%*10",
        "5": "25.47%*10",
        "6": "27.24%*10",
        "7": "29.69%*10",
        "8": "32.15%*10",
        "9": "34.60%*10",
        "10": "37.21%*10",
      },
      type: "Skill",
    },
    {
      key: "PoeticEssenceHealing",
      label: "Poetic Essence Healing",
      talents: {
        "1": "1180 + 44.20%",
        "2": "1243 + 45.97%",
        "3": "1317 + 47.74%",
        "4": "1475 + 50.39%",
        "5": "1665 + 53.92%",
        "6": "1844 + 57.46%",
        "7": "1876 + 64.09%",
        "8": "1918 + 71.60%",
        "9": "1949 + 79.56%",
        "10": "2002 + 92.82%",
      },
      type: "Healing",
    },
    {
      key: "DoublePunBonusHealing",
      label: "Double Pun Bonus Healing",
      talents: {
        "1": "694 + 26.00%",
        "2": "731 + 27.04%",
        "3": "775 + 28.08%",
        "4": "868 + 29.64%",
        "5": "979 + 31.72%",
        "6": "1085 + 33.80%",
        "7": "1103 + 37.70%",
        "8": "1128 + 42.12%",
        "9": "1147 + 46.80%",
        "10": "1178 + 54.60%",
      },
      type: "Healing",
    },
  ],
};
