export const forteCircuitAttacks = {
  name: "Forte Circuit: Lambent Gold",
  description: `<div><span class="Title">Zephyr Stance</span></span><br><br>Suisui is in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span> by default. When in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span>, Suisui can obtain <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span> through certain skills.<br><size=10></span><br><br><span class="Title">Drizzle Stance</span></span><br><br>Entering <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span> clears all <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span>.<br>During <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>:<br>- Suisui unlocks new combat moves and restores <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> through certain skills.<br>-Suisui gains increased resistance to interruption.<br>- Press <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> within a certain time after triggering a successful Dodge via <span style="color:#ffd12f;" class="font-bold">Dodge skills</span> to cast <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance Stage 1</span>.<br>After entering <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span> for 15s, Suisui ends <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span> and clears all <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> upon exiting the state.<br><size=10></span><br><br><span class="Title">Dodge - Parting Mist</span></span><br><br>While performing attacks on the ground, press <span style="color:#ffd12f;" class="font-bold">Dodge</span> to cast <span style="color:#ffd12f;" class="font-bold">Dodge - Parting Mist</span> at the cost of STA.<br>When in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span>, triggering a successful Dodge while casting <span style="color:#ffd12f;" class="font-bold">Dodge - Parting Mist</span> restores <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span>. Press <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> shortly after triggering the Dodge to cast <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Zephyr Stance</span>.<br>- When in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, triggering a successful Dodge while casting <span style="color:#ffd12f;" class="font-bold">Dodge - Parting Mist</span> restores <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span>, and does not reset the cycle of <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance</span> within a certain period.<br><size=10></span><br><br><span class="Title">Basic Attack - Drizzle Stance</span></span><br><br>When in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Zephyr Stance</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> repeatedly to perform up to 4 consequtive attacks, dealing <span style="color:#a2fbfc;">Glacio DMG</span> and restoring <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> on hit.<br>When casting <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance Stage 3</span>,  continuously pull in nearby targets.<br><span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance Stage 4</span> inflicts <span style="color:#ffd12f;" class="font-bold">Glacio Chafe</span> 1 time on the target on hit.<br><size=10></span><br><br><span class="Title">Heavy Attack - Drizzle Stance</span></span><br><br>Consume STA to attack the target, dealing <span style="color:#a2fbfc;">Glacio DMG</span>, and restoring <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> on hit.<br><size=10></span><br><br><span class="Title">Illuminating Dew</span></span><br><br>When in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, keep holding <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> after casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Drizzle Stance</span> to cast this skill.<br>Consume STA to perform Plunging Attack, dealing <span style="color:#a2fbfc;">Glacio DMG</span>.<br><size=10></span><br><br><span class="Title">Swallow's Cut</span></span><br><br>When in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, cast this skill one of the following ways:<br>- Release the <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> button while casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Drizzle Stance</span>.<br>- Press <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> while Suisui is mid-air.<br>Consume STA to perform Plunging Attack, dealing <span style="color:#a2fbfc;">Glacio DMG</span>.<br><size=10></span><br><br><span class="Title">Cloud Breath</span></span><br><br>Max 120 points.<br>When in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span>: <br>- <span style="color:#ffd12f;" class="font-bold">Basic Attack - Zephyr Stance</span> and <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Zephyr Stance</span> restores <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span> on hit.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Zephyr Stance</span> restores 40 points of <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span> when Suisui is the active Resonator in the team.<br>- Triggering a successful Dodge while casting <span style="color:#ffd12f;" class="font-bold">Dodge - Parting Mist</span> restores 35 points of <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span>.<br><size=10></span><br><br><span class="Title">Floral Epistle</span></span><br><br>Max 600 points.<br>When in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>:<br>- <span style="color:#ffd12f;" class="font-bold">Basic Attack - Drizzle Stance</span> and <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Drizzle Stance</span> restores  <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> on hit.<br>- Casting <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Drizzle Stance</span> restores 100 points of <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> when Suisui is the active Resonator in the team.<br>- Triggering a successful Dodge while casting <span style="color:#ffd12f;" class="font-bold">Dodge - Parting Mist</span> restores 102 points of <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span>.</div>`,
  attacks: [
    {
      key: "BasicAttackDrizzleStanceStage1DMG",
      label: "Basic Attack - Drizzle Stance Stage 1 DMG",
      talents: {
        "1": "9.84%*2+9.84%*2",
        "2": "10.65%*2+10.65%*2",
        "3": "11.46%*2+11.46%*2",
        "4": "12.59%*2+12.59%*2",
        "5": "13.40%*2+13.40%*2",
        "6": "14.32%*2+14.32%*2",
        "7": "15.61%*2+15.61%*2",
        "8": "16.91%*2+16.91%*2",
        "9": "18.20%*2+18.20%*2",
        "10": "19.57%*2+19.57%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackDrizzleStanceStage2DMG",
      label: "Basic Attack - Drizzle Stance Stage 2 DMG",
      talents: {
        "1": "16.00%+8.00%*2+8.00%*2+16.00%+16.00%",
        "2": "17.32%+8.66%*2+8.66%*2+17.32%+17.32%",
        "3": "18.63%+9.32%*2+9.32%*2+18.63%+18.63%",
        "4": "20.47%+10.24%*2+10.24%*2+20.47%+20.47%",
        "5": "21.78%+10.89%*2+10.89%*2+21.78%+21.78%",
        "6": "23.29%+11.65%*2+11.65%*2+23.29%+23.29%",
        "7": "25.39%+12.70%*2+12.70%*2+25.39%+25.39%",
        "8": "27.48%+13.74%*2+13.74%*2+27.48%+27.48%",
        "9": "29.58%+14.79%*2+14.79%*2+29.58%+29.58%",
        "10": "31.81%+15.91%*2+15.91%*2+31.81%+31.81%",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackDrizzleStanceStage3DMG",
      label: "Basic Attack - Drizzle Stance Stage 3 DMG",
      talents: {
        "1": "6.92%*3+6.92%*3+6.92%*3+6.92%*3",
        "2": "7.49%*3+7.49%*3+7.49%*3+7.49%*3",
        "3": "8.06%*3+8.06%*3+8.06%*3+8.06%*3",
        "4": "8.85%*3+8.85%*3+8.85%*3+8.85%*3",
        "5": "9.42%*3+9.42%*3+9.42%*3+9.42%*3",
        "6": "10.07%*3+10.07%*3+10.07%*3+10.07%*3",
        "7": "10.98%*3+10.98%*3+10.98%*3+10.98%*3",
        "8": "11.89%*3+11.89%*3+11.89%*3+11.89%*3",
        "9": "12.80%*3+12.80%*3+12.80%*3+12.80%*3",
        "10": "13.76%*3+13.76%*3+13.76%*3+13.76%*3",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackDrizzleStanceStage4DMG",
      label: "Basic Attack - Drizzle Stance Stage 4 DMG",
      talents: {
        "1": "80.00%",
        "2": "86.56%",
        "3": "93.12%",
        "4": "102.31%",
        "5": "108.87%",
        "6": "116.41%",
        "7": "126.91%",
        "8": "137.40%",
        "9": "147.90%",
        "10": "159.05%",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackDrizzleStance",
      label: "Heavy Attack - Drizzle Stance",
      talents: {
        "1": "6.00%*10+60.00%",
        "2": "6.50%*10+64.92%",
        "3": "6.99%*10+69.84%",
        "4": "7.68%*10+76.73%",
        "5": "8.17%*10+81.65%",
        "6": "8.74%*10+87.31%",
        "7": "9.52%*10+95.18%",
        "8": "10.31%*10+103.05%",
        "9": "11.10%*10+110.93%",
        "10": "11.93%*10+119.29%",
      },
      type: "Heavy",
    },
    {
      key: "IlluminatingDewDMG",
      label: "Illuminating Dew DMG",
      talents: {
        "1": "52.80%",
        "2": "57.13%",
        "3": "61.46%",
        "4": "67.53%",
        "5": "71.86%",
        "6": "76.83%",
        "7": "83.76%",
        "8": "90.69%",
        "9": "97.62%",
        "10": "104.98%",
      },
      type: "Basic",
    },
    {
      key: "SwallowSCutDMG",
      label: "Swallow's Cut DMG",
      talents: {
        "1": "54.15%",
        "2": "58.59%",
        "3": "63.03%",
        "4": "69.24%",
        "5": "73.68%",
        "6": "78.79%",
        "7": "85.89%",
        "8": "93.00%",
        "9": "100.10%",
        "10": "107.65%",
      },
      type: "Basic",
    }
  ],
};
