export const rotations: RotationPreset[] = [
  {
    name: "No Intro Rotation",
    description: "No Intro Rotation",
    author: "Lavasnake",
    data: {"name":"No Intro Rotation","description":"Basic: Zephyr 1\nBasic: Zephyr 2\nBasic: Zephyr 3\nSkill: Awakening Spring\nBasic: Swallow's Cut\nBasic: Drizzle 1\nBasic: Drizzle 2\nBasic: Drizzle 3\nBasic: Drizzle 4 (Cancel animation endlag via Ultimate)\nUltimate\nOutro","actions":[{"order":1,"key":"BasicAttackZephyrStanceStage1DMG","type":"basic","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":2,"key":"BasicAttackZephyrStanceStage2DMG","type":"basic","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":3,"key":"BasicAttackZephyrStanceStage3DMG","type":"basic","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":4,"key":"AwakeningSpringDMG","type":"skill","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":5,"key":"SwallowSCutDMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":6,"key":"BasicAttackDrizzleStanceStage1DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":7,"key":"BasicAttackDrizzleStanceStage2DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":8,"key":"BasicAttackDrizzleStanceStage3DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":9,"key":"BasicAttackDrizzleStanceStage4DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":10,"key":"HealingPerPlumeStep","type":"liberation","count":3,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":11,"key":"ForbiddenBastionBashDMG","type":"echoAttacks","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0,"mainEcho":"ForbiddenBastion","mainEchoRank":5}],"echo":"ForbiddenBastion"},
  },
  {
    name: "Loop Rotation",
    description: "Loop Rotation",
    author: "Lavasnake",
    data: {"name":"Loop Rotation","description":"Intro\nSkill: Drizzle (Cancel animation via Dash on 1st hit)\nBasic: Drizzle 1\nBasic: Drizzle 2\nBasic: Drizzle 3\nBasic: Drizzle 4 (Cancel animation endlag via Ultimate)\nUltimate\nOutro","actions":[{"order":1,"key":"TinklingJadeDMG","type":"intro","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":2,"key":"ResonanceSkillDrizzleStanceDMG","type":"skill","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":3,"key":"BasicAttackDrizzleStanceStage1DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":4,"key":"BasicAttackDrizzleStanceStage2DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":5,"key":"BasicAttackDrizzleStanceStage3DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":6,"key":"BasicAttackDrizzleStanceStage4DMG","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":7,"key":"HealingPerPlumeStep","type":"liberation","count":3,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0},{"order":8,"key":"ForbiddenBastionBashDMG","type":"echoAttacks","count":1,"buffs":[],"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"negativeStatusStacks":1,"electroRageStacks":0,"mainEcho":"ForbiddenBastion","mainEchoRank":5}],"echo":"ForbiddenBastion"},
  },
];
export const echoes = [];
