export const resonanceChains = [
  {
    key: `SequenceNode1MountainsWashedIntoPaintings`,
    name: `Sequence Node 1: Mountains Washed Into Paintings`,
    details: `<div>The ATK bonus effect gained by consuming at least 600 <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span> while casting <span style="color:#ffd12f;" class="font-bold">Outro Skill - Rippling Waters</span>, can also be triggered by applying <span style="color:#ffd12f;" class="font-bold">Negative Status</span> or dealing <span style="color:#ffd12f;" class="font-bold">Negative Status DMG</span>.<br>The duration of <span style="color:#ffd12f;" class="font-bold">Ceaseless Landscape</span> is extended to 30s, and the duration of <span style="color:#ffd12f;" class="font-bold">Reflecting Shadows</span> obtained through the third interaction is extended by 100%.<br><span style="color:#ffd12f;" class="font-bold">Basic Attack - Cleansing Rain</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Cleansing Rain</span>, and <span style="color:#ffd12f;" class="font-bold">[Enhanced Plunging Attack- Enhanced State]</span> are immune to interruption.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode2CloudsPourLikeMoltenGold`,
    name: `Sequence Node 2: Clouds Pour Like Molten Gold`,
    details: `<div>When inside the effect's radius, Resonators in the team gain 40% All-Attribute DMG Bonus.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode3SparseCurtainsInviteEveningGlow`,
    name: `Sequence Node 3: Sparse Curtains Invite Evening Glow`,
    details: `<div>Casting <span style="color:#ffd12f;" class="font-bold">Illuminating Dew</span> additionally restores 18 Concerto Energy and 350 <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span>. This effect can be triggered once every 25s.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode4AutumnMountainsIChantTogether`,
    name: `Sequence Node 4: Autumn Mountains I Chant Together`,
    details: `<div>Healing provided by <span style="color:#ffd12f;" class="font-bold">Enrichment</span> and  <span style="color:#ffd12f;" class="font-bold">Spring’s Birth</span> are increased by 50%.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode5ILongToRideTheEasternWind`,
    name: `Sequence Node 5: I Long To Ride The Eastern Wind`,
    details: `<div>The DMG Multipliers of <span style="color:#ffd12f;" class="font-bold">Basic Attack - Cleansing Rain</span> and <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Cleansing Rain</span> are increased by 100%.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `SequenceNode6StayingTrueToThisSpledidRealm`,
    name: `Sequence Node 6: Staying True To This Spledid Realm`,
    details: `<div>The Crit. DMG of <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tinkling Jade</span> and <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Awakening Spring</span> are increased by 500%.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  }
];
