export const skillAttacks = {
  name: "Resonance Skill: Vernal Screen",
  description: `<span class="Title">Resonance Skill - Zephyr Stance</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span> and <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span> is not full, press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to have Suisui thrust forward, dealing <span style="color:#a2fbfc;">Glacio DMG</span>. If Suisui is the active Resonator while casting the skill, restore <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span>.<br>Can be cast in mid-air close to the ground<br>This skill shares a Cooldown with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Drizzle Stance</span>.<br><size=10></span><br><br><span class="Title">Awakening Spring</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Zephyr Stance</span> and at full <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Zephyr Stance</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Awakening Spring</span>. Casting this skill consumes all <span style="color:#ffd12f;" class="font-bold">Cloud Breath</span>, pulls in nearby targets, and sends Suisui into <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, dealing <span style="color:#a2fbfc;">Glacio DMG</span> and inflicting <span style="color:#ffd12f;" class="font-bold">Glacio Chafe</span> on the target 1 time on hit.<br><size=10></span><br><br><span class="Title">Enrichment</span></span><br><br>Casting <span style="color:#ffd12f;" class="font-bold">Awakening Spring</span> or <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tinkling Jade</span> grants all nearby Resonators in the team 1 stack of <span style="color:#ffd12f;" class="font-bold">Enrichment</span>. This effect can be triggered once every 25s. Incoming Resonators receive healing from Suisui at the cost of <span style="color:#ffd12f;" class="font-bold">Enrichment</span>.<br><size=10></span><br><br><span class="Title">Resonance Skill - Drizzle Stance</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Drizzle Stance</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Zephyr Stance</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Drizzle Stance</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to have Suisui thrust forward, dealing <span style="color:#a2fbfc;">Glacio DMG</span>. If Suisui is the active Resonator while casting the skill, restore <span style="color:#ffd12f;" class="font-bold">Floral Epistle</span>.<br>Can be cast in mid-air close to the ground<br>This skill shares a Cooldown with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Zephyr Stance</span>.`,
  attacks: [
    {
      key: "ResonanceSkillZephyrStanceDMG",
      label: "Resonance Skill - Zephyr Stance DMG",
      talents: {
        "1": "12.00%*6",
        "2": "12.99%*6",
        "3": "13.97%*6",
        "4": "15.35%*6",
        "5": "16.33%*6",
        "6": "17.47%*6",
        "7": "19.04%*6",
        "8": "20.61%*6",
        "9": "22.19%*6",
        "10": "23.86%*6",
      },
      type: "Skill",
    },
    {
      key: "AwakeningSpringDMG",
      label: "Awakening Spring DMG",
      talents: {
        "1": "14.40%",
        "2": "15.59%",
        "3": "16.77%",
        "4": "18.42%",
        "5": "19.60%",
        "6": "20.96%",
        "7": "22.85%",
        "8": "24.74%",
        "9": "26.63%",
        "10": "28.63%",
      },
      type: "Skill",
      attribute: "hp",
    },
    {
      key: "ResonanceSkillDrizzleStanceDMG",
      label: "Resonance Skill - Drizzle Stance DMG",
      talents: {
        "1": "6.00%*6+36.00%",
        "2": "6.50%*6+38.96%",
        "3": "6.99%*6+41.91%",
        "4": "7.68%*6+46.04%",
        "5": "8.17%*6+48.99%",
        "6": "8.74%*6+52.39%",
        "7": "9.52%*6+57.11%",
        "8": "10.31%*6+61.83%",
        "9": "11.10%*6+66.56%",
        "10": "11.93%*6+71.58%",
      },
      type: "Skill",
    },
    {
      key: "EnrichmentHealing",
      label: "Enrichment Healing",
      talents: {
        "1": "330+1.62%",
        "2": "369+1.69%",
        "3": "412+1.75%",
        "4": "462+1.85%",
        "5": "521+1.98%",
        "6": "577+2.11%",
        "7": "587+2.36%",
        "8": "600+2.63%",
        "9": "610+2.93%",
        "10": "627+3.42%",
      },
      type: "Healing",
      attribute: "hp",
    }
  ],
};
