export const skillAttacks = {
  name: "Resonance Skill: Droplet Screen",
  description: `<span class="Title">Resonance Skill - Cleansing</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Cleansing</span> and at partial <span style="color:#ffd12f;" class="font-bold">Stillness</span>, press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to have Suisui thrust forward, dealing <span style="color:#a2fbfc;">Glacio DMG</span>.<br>This skill shares a Cooldown with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Cleansing Rain</span>.<br><size=10></span><br><br><span class="Title">Awakening Spring</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Cleansing</span> and at full <span style="color:#ffd12f;" class="font-bold">Stillness</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Cleansing</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Awakening Spring</span>. Casting this skill consumes all <span style="color:#ffd12f;" class="font-bold">Stillness</span>, pulls in nearby targets, and enters <span style="color:#ffd12f;" class="font-bold">Cleansing Rain</span>, dealing <span style="color:#a2fbfc;">Glacio DMG</span> and apply <span style="color:#ffd12f;" class="font-bold">Glacio Chafe</span> 1 time on hit.<br>Casting <span style="color:#ffd12f;" class="font-bold">Awakening Spring</span> grants all nearby Resonators in the team 1 stack of <span style="color:#ffd12f;" class="font-bold">Enrichment</span>. This effect can be triggered once every 25s. Incoming Resonators receive healing from Suisui at the cost of <span style="color:#ffd12f;" class="font-bold">Enrichment</span>.<br><size=10></span><br><br><span class="Title">Resonance Skill - Cleansing Rain</span></span><br><br>While in <span style="color:#ffd12f;" class="font-bold">Cleansing Rain</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Cleansing</span> is replaced with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Cleansing Rain</span>.<br>Press <span style="color:#ffd12f;" class="font-bold">Resonance Skill</span> to have Suisui thrust forward, dealing <span style="color:#a2fbfc;">Glacio DMG</span>.<br>This skill shares a Cooldown with <span style="color:#ffd12f;" class="font-bold">Resonance Skill - Cleansing</span>.`,
  attacks: [
    {
      key: "ResonanceSkillCleansingDMG",
      label: "Resonance Skill - Cleansing DMG",
      talents: {
        "1": "13.47%*6",
        "2": "14.58%*6",
        "3": "15.68%*6",
        "4": "17.23%*6",
        "5": "18.33%*6",
        "6": "19.60%*6",
        "7": "21.37%*6",
        "8": "23.13%*6",
        "9": "24.90%*6",
        "10": "26.78%*6",
      },
      type: "Skill",
    },
    {
      key: "AwakeningSpringDMG",
      label: "Awakening Spring DMG",
      talents: {
        "1": "14.40%",
        "2": "15.59%",
        "3": "16.77%",
        "4": "18.42%",
        "5": "19.60%",
        "6": "20.96%",
        "7": "22.85%",
        "8": "24.74%",
        "9": "26.63%",
        "10": "28.63%",
      },
      type: "Skill",
      attribute: "hp",
    },
    {
      key: "ResonanceSkillCleansingRainDMG",
      label: "Resonance Skill - Cleansing Rain DMG",
      talents: {
        "1": "10.00%*6+60.00%",
        "2": "10.82%*6+64.92%",
        "3": "11.64%*6+69.84%",
        "4": "12.79%*6+76.73%",
        "5": "13.61%*6+81.65%",
        "6": "14.56%*6+87.31%",
        "7": "15.87%*6+95.18%",
        "8": "17.18%*6+103.05%",
        "9": "18.49%*6+110.93%",
        "10": "19.89%*6+119.29%",
      },
      type: "Skill",
    },
    {
      key: "EnrichmentHealing",
      label: "Enrichment Healing",
      talents: {
        "1": "330+1.62%",
        "2": "369+1.69%",
        "3": "412+1.75%",
        "4": "462+1.85%",
        "5": "521+1.98%",
        "6": "577+2.11%",
        "7": "587+2.36%",
        "8": "600+2.63%",
        "9": "610+2.93%",
        "10": "627+3.42%",
      },
      type: "Healing",
      attribute: "hp",
    },
    {
      key: "SkyOverWaterHealing",
      label: "Sky Over Water Healing",
      talents: {
        "1": "62+0.34%",
        "2": "62+0.34%",
        "3": "62+0.34%",
        "4": "62+0.34%",
        "5": "62+0.34%",
        "6": "62+0.34%",
        "7": "62+0.34%",
        "8": "62+0.34%",
        "9": "62+0.34%",
        "10": "62+0.34%",
      },
      type: "Healing",
      attribute: "hp",
      requiresResonanceChain: "InherentSkillSkyOverWater",
    },
  ],
};
