/**
 * Updates Changelog -> Structured Data
 *
 * One-time extraction script: parses the hand-written <h3>Month Day, Year</h3>
 * + <ul><li>...</li></ul> blocks out of src/pages/UpdatesView.vue's legacy
 * template and emits src/content/updates.ts as a typed array. Not shipped/run
 * in CI - run manually if the legacy markup is ever hand-edited again in a
 * way that needs re-syncing to the data file (it shouldn't be, going
 * forward - new entries should be added directly to updates.ts).
 *
 * Usage: node scripts/coverters/updatesToData.js
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { JSDOM } from "jsdom";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = path.join(__dirname, "../../src/pages/UpdatesView.vue");
const OUTPUT_PATH = path.join(__dirname, "../../src/content/updates.ts");

const MONTHS = {
  January: "01",
  February: "02",
  March: "03",
  April: "04",
  May: "05",
  June: "06",
  July: "07",
  August: "08",
  September: "09",
  October: "10",
  November: "11",
  December: "12",
};

function toIsoDate(dateLabel) {
  const match = dateLabel.match(/^([A-Za-z]+) (\d{1,2}), (\d{4})$/);
  if (!match) {
    throw new Error(`Unrecognized date label: "${dateLabel}"`);
  }
  const [, month, day, year] = match;
  const monthNum = MONTHS[month];
  if (!monthNum) {
    throw new Error(`Unrecognized month in date label: "${dateLabel}"`);
  }
  return `${year}-${monthNum}-${day.padStart(2, "0")}`;
}

function extractEntries(html) {
  const dom = new JSDOM(html);
  const article = dom.window.document.querySelector("article.page-updates");
  if (!article) {
    throw new Error("Could not find <article class=\"prose page-updates\"> in source");
  }

  const entries = [];
  let node = article.firstElementChild;
  while (node) {
    if (node.tagName === "H3") {
      const dateLabel = node.textContent.trim();
      const ul = node.nextElementSibling;
      if (!ul || ul.tagName !== "UL") {
        throw new Error(`<h3>${dateLabel}</h3> not immediately followed by a <ul>`);
      }
      const items = Array.from(ul.querySelectorAll("li")).map((li) =>
        li.textContent.replace(/\s+/g, " ").trim(),
      );
      entries.push({ date: toIsoDate(dateLabel), dateLabel, items });
      node = ul;
    }
    node = node.nextElementSibling;
  }
  return entries;
}

function formatAsTs(entries) {
  const body = entries
    .map((e) => {
      const items = e.items.map((i) => `      ${JSON.stringify(i)},`).join("\n");
      return `  {\n    date: ${JSON.stringify(e.date)},\n    dateLabel: ${JSON.stringify(
        e.dateLabel,
      )},\n    items: [\n${items}\n    ],\n  },`;
    })
    .join("\n");

  return `// Generated by scripts/coverters/updatesToData.js from the legacy
// hand-written UpdatesView.vue markup - see docs/adr/0023-updates-page-search-and-grouping-redesign.md.
// Going forward, add new entries directly here (newest first), not as markup.

export interface UpdateEntry {
  /** ISO date, e.g. "2026-08-29" - sort/group key, do not derive from dateLabel at runtime. */
  date: string;
  /** Exact display text, e.g. "August 29, 2026". */
  dateLabel: string;
  items: string[];
}

export const updateEntries: UpdateEntry[] = [
${body}
];
`;
}

function main() {
  const source = fs.readFileSync(SOURCE_PATH, "utf8");
  const templateMatch = source.match(/<template>([\s\S]*)<\/template>/);
  if (!templateMatch) {
    throw new Error("Could not find <template> block in UpdatesView.vue");
  }

  const expectedCount = (templateMatch[1].match(/<h3>/g) || []).length;
  const entries = extractEntries(templateMatch[1]);

  if (entries.length !== expectedCount) {
    throw new Error(
      `Extracted ${entries.length} entries but source has ${expectedCount} <h3> tags - aborting without writing output.`,
    );
  }

  fs.writeFileSync(OUTPUT_PATH, formatAsTs(entries));
  console.log(`Wrote ${entries.length} update entries to ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

main();
