export const forteCircuitAttacks = {
  name: "Forte Circuit: Ink and Wash",
  description: `<div class="skilldescription">Phantasmic Imprint<br>Zhezhi may summon <span class="Highlight"><strong>Phantasmic Imprint</strong></span> at the cost of Afflatus when casting Resonance Skill <span class="Highlight"><strong>Manifestation</strong></span> or Heavy Attack <span class="Highlight"><strong>Conjuration</strong></span>.<br>Up to 1 of each of <span class="Highlight"><strong>Phantasmic Imprint - Left</strong></span>, <span class="Highlight"><strong>Phantasmic Imprint - Middle</strong></span>, and <span class="Highlight"><strong>Phantasmic Imprint - Right</strong></span> can exist at the same time, each lasting for 15s.<br>Heavy Attack - Conjuration<br>The 5 moves below consume STA to perform <span class="Highlight"><strong>Conjuration</strong></span> to attack the target, dealing <span class="Ice"><strong>Glacio DMG</strong></span>.<br>-Hold the <span class="Highlight"><strong>Basic Attack button</strong></span> shortly after <span class="Highlight"><strong>Basic Attack Stage 3</strong></span>.<br>-Press the <span class="Highlight"><strong>Basic Attack button</strong></span> shortly after casting Resonance Skill <span class="Highlight"><strong>Manifestation</strong></span>.<br>-Hold the <span class="Highlight"><strong>Basic Attack button</strong></span> shortly after casting Resonance Skill <span class="Highlight"><strong>Stroke of Genius</strong></span> or Resonance Skill <span class="Highlight"><strong>Creation's Zenith</strong></span>.<br>-Hold the <span class="Highlight"><strong>Basic Attack button</strong></span> while in mid-air.<br>-Hold the <span class="Highlight"><strong>Basic Attack button</strong></span> after a successful <span class="Highlight"><strong>Dodge</strong></span>.<br>If Zhezhi has at least 30 Afflatus when performing any of these, consume 30 Afflatus to summon <span class="Highlight"><strong>Phantasmic Imprint - Middle</strong></span>.<br>Resonance Skill - Stroke of Genius<br>When a <span class="Highlight"><strong>Phatasmic Imprint</strong></span> is nearby, the Resonance Skill is replaced with <span class="Highlight"><strong>Stroke of Genius</strong></span>, which can be cast while in mid-air. When it is cast, Zhezhi will:<br>-Move to the location of the <span class="Highlight"><strong>Phatasmic Imprint</strong></span>, remove it, and then summon an Ivory Herald to attack the target, dealing <span class="Ice"><strong>Glacio DMG</strong></span>, considered as Basic Attack DMG. Refresh the mid-air Dodge counter if the target <span class="Highlight"><strong>Phatasmic Imprint</strong></span> is in mid-air.<br>-Gain 1 stack of Painter's Delight, lasting for 8s and stacking up to 2 times.<br>Resonance Skill - Creation's Zenith<br>When a <span class="Highlight"><strong>Phantasmic Imprint</strong></span> is nearby and there are 2 stacks of Painter's Delight, <span class="Highlight"><strong>Stroke of Genius</strong></span> is replaced with <span class="Highlight"><strong>Creation's Zenith</strong></span>, which can be cast while in mid-air. When it is cast, Zhezhi will:<br>-Lose all stacks of Painter's Delight<br>-Move to the location of the <span class="Highlight"><strong>Phantasmic Imprint</strong></span>, remove it, and then summon an Ivory Herald to attack the target, dealing greater <span class="Ice"><strong>Glacio DMG</strong></span>, considered as Basic Attack DMG, additionally increasing the Basic Attack DMG Bonus by 18% for 27s. Refresh the mid-air Dodge counter if the target <span class="Highlight"><strong>Phatasmic Imprint</strong></span> is in mid-air.<br>Afflatus<br>Zhezhi can hold up to 90 Afflatus.<br>Normal Attacks grant Afflatus on hit.<br>Casting Intro Skill grants Afflatus.</div>`,
  attacks: [
    {
      key: "CompositionDMG",
      label: "HA: Conjuration DMG",
      talents: {
        "1": "41.75%*3",
        "2": "45.18%*3",
        "3": "48.60%*3",
        "4": "53.39%*3",
        "5": "56.82%*3",
        "6": "60.76%*3",
        "7": "66.23%*3",
        "8": "71.71%*3",
        "9": "77.19%*3",
        "10": "83.01%*3",
      },
      type: "Heavy",
    },
    {
      key: "StrokeOfGeniusDMG",
      label: "Stroke of Genius DMG",
      talents: {
        "1": "150.00%",
        "2": "162.30%",
        "3": "174.60%",
        "4": "191.82%",
        "5": "204.12%",
        "6": "218.27%",
        "7": "237.95%",
        "8": "257.63%",
        "9": "277.31%",
        "10": "298.22%",
      },
      type: "Basic",
    },
    {
      key: "CreationsZenithDMG",
      label: "Creation's Zenith DMG",
      talents: {
        "1": "60.00%*3",
        "2": "64.92%*3",
        "3": "69.84%*3",
        "4": "76.73%*3",
        "5": "81.65%*3",
        "6": "87.31%*3",
        "7": "95.18%*3",
        "8": "103.05%*3",
        "9": "110.93%*3",
        "10": "119.29%*3",
      },
      type: "Basic",
    },
  ],
};
