export const forteCircuitAttacks = {
  name: "Forte Circuit: Starflower Blooms",
  description: `<div class="skilldescription"><span class="Title">Heavy Attack: Starflower Blooms</span><br>When casting <span class="Highlight">Heavy Attack</span>, if Verina carries "Photosynthesis Energy", Verina consumes 1 stack of "Photosynthesis Energy" to recover Concerto Energy and heal all characters on a nearby team.<br><span class="Highlight">Heavy Attack: Starflower Blooms</span> deals <span class="Light">Spectro DMG</span>, considered as Heavy Attack DMG.<br> <br><span class="Title">Mid-air Attack: Starflower Blooms</span><br>When casting <span class="Highlight">Mid-air Attack</span>, if Verina carries "Photosynthesis Energy", Verina consumes 1 stack of "Photosynthesis Energy" to recover Concerto Energy and heal all characters on a nearby team.<br><span class="Highlight">Mid-air Attack: Starflower Blooms</span> deals <span class="Light">Spectro DMG</span>, considered as Basic Attack DMG.<br>Verina can cast <span class="Highlight">Mid-air Attack: Starflower Blooms</span> by using <span class="Highlight">Basic Attack</span> after casting <span class="Highlight">Heavy Attack: Starflower Blooms</span>.<br> <br><span class="Title">Photosynthesis Energy</span><br>Verina can hold up to 4 "Photosynthesis Energy".<br>Verina obtains 1 stack of "Photosynthesis Energy" for every <span class="Highlight">Basic Attack 5</span> on hit.<br>Verina obtains 1 stack of "Photosynthesis Energy" for every Resonance Skill <span class="Highlight">Botany Experiment</span> on hit.<br>Verina obtains 1 stack of "Photosynthesis Energy" for every Intro Skill <span class="Highlight">Verdant Growth</span> on hit.</div>`,
  attacks: [
    {
      key: "HeavyAttackStarflowerBloomsDMG",
      label: "Heavy Attack: Starflower Blooms DMG",
      talents: {
        "1": "16.34% + 24.50%",
        "2": "17.68% + 26.51%",
        "3": "19.02% + 28.52%",
        "4": "20.89% + 31.34%",
        "5": "22.23% + 33.34%",
        "6": "23.77% + 35.65%",
        "7": "25.91% + 38.87%",
        "8": "28.06% + 42.08%",
        "9": "30.20% + 45.29%",
        "10": "32.48% + 48.71%",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage1DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 1 DMG",
      talents: {
        "1": "17.01%",
        "2": "18.41%",
        "3": "19.80%",
        "4": "21.75%",
        "5": "23.15%",
        "6": "24.76%",
        "7": "26.98%",
        "8": "29.22%",
        "9": "31.45%",
        "10": "33.82%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage2DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 2 DMG",
      talents: {
        "1": "16.05%",
        "2": "17.37%",
        "3": "18.69%",
        "4": "20.53%",
        "5": "21.84%",
        "6": "23.36%",
        "7": "25.47%",
        "8": "27.57%",
        "9": "29.67%",
        "10": "31.91%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage3DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 3 DMG",
      talents: {
        "1": "7.67%*3",
        "2": "8.30%*3",
        "3": "8.93%*3",
        "4": "9.81%*3",
        "5": "10.44%*3",
        "6": "11.17%*3",
        "7": "12.17%*3",
        "8": "13.17%*3",
        "9": "14.18%*3",
        "10": "15.25%*3",
      },
      type: "Basic",
    },
    {
      key: "StarflowerBloomsHealing",
      label: "Starflower Blooms Healing",
      talents: {
        "1": "312.5 + 7.09%",
        "2": "375 + 8.15%",
        "3": "437.5 + 8.86%",
        "4": "500 + 9.92%",
        "5": "516 + 10.63%",
        "6": "556.5 + 11.34%",
        "7": "562.5 + 12.04%",
        "8": "572 + 12.75%",
        "9": "581.5 + 13.46%",
        "10": "594 + 14.88%",
      },
      type: "Healing",
    },
    {
      key: "SequenceNode6JoyousHarvestDMG",
      label: "S6: Joyous Harvest DMG",
      talents: {
        "1": "2.50%",
        "2": "2.71%",
        "3": "2.91%",
        "4": "3.20%",
        "5": "3.41%",
        "6": "3.64%",
        "7": "3.97%",
        "8": "4.30%",
        "9": "4.62%",
        "10": "4.98%",
      },
      type: "Liberation",
      requiresResonanceChain: "SequenceNode6JoyousHarvest",
    },
    {
      key: "SequenceNode6JoyousHarvestHealing",
      label: "S6: Joyous Harvest Healing",
      talents: {
        "1": "2.50%",
        "2": "2.71%",
        "3": "2.91%",
        "4": "3.20%",
        "5": "3.41%",
        "6": "3.64%",
        "7": "3.97%",
        "8": "4.30%",
        "9": "4.62%",
        "10": "4.98%",
      },
      type: "Healing",
      requiresResonanceChain: "SequenceNode6JoyousHarvest",
    },
  ],
};
