export const forteCircuitAttacks = {
  name: "Forte Circuit: Starflower Blooms",
  description: `<div class="skilldescription"><span class="Title">Heavy Attack: Starflower Blooms</span><br>When casting <span class="Highlight">Heavy Attack</span>, if Verina carries "Photosynthesis Energy", Verina consumes 1 stack of "Photosynthesis Energy" to recover Concerto Energy and heal all characters on a nearby team.<br><span class="Highlight">Heavy Attack: Starflower Blooms</span> deals <span class="Light">Spectro DMG</span>, considered as Heavy Attack DMG.<br> <br><span class="Title">Mid-air Attack: Starflower Blooms</span><br>When casting <span class="Highlight">Mid-air Attack</span>, if Verina carries "Photosynthesis Energy", Verina consumes 1 stack of "Photosynthesis Energy" to recover Concerto Energy and heal all characters on a nearby team.<br><span class="Highlight">Mid-air Attack: Starflower Blooms</span> deals <span class="Light">Spectro DMG</span>, considered as Basic Attack DMG.<br>Verina can cast <span class="Highlight">Mid-air Attack: Starflower Blooms</span> by using <span class="Highlight">Basic Attack</span> after casting <span class="Highlight">Heavy Attack: Starflower Blooms</span>.<br> <br><span class="Title">Photosynthesis Energy</span><br>Verina can hold up to 4 "Photosynthesis Energy".<br>Verina obtains 1 stack of "Photosynthesis Energy" for every <span class="Highlight">Basic Attack 5</span> on hit.<br>Verina obtains 1 stack of "Photosynthesis Energy" for every Resonance Skill <span class="Highlight">Botany Experiment</span> on hit.<br>Verina obtains 1 stack of "Photosynthesis Energy" for every Intro Skill <span class="Highlight">Verdant Growth</span> on hit.</div>`,
  attacks: [
    {
      key: "HeavyAttackStarflowerBloomsDMG",
      label: "Heavy Attack: Starflower Blooms DMG",
      talents: {
        "1": "32.67% + 49.00%",
        "2": "35.35% + 53.02%",
        "3": "38.03% + 57.04%",
        "4": "41.78% + 62.67%",
        "5": "44.46% + 66.68%",
        "6": "47.54% + 71.30%",
        "7": "51.82% + 77.73%",
        "8": "56.11% + 84.16%",
        "9": "60.40% + 90.59%",
        "10": "64.95% + 97.42%",
      },
      type: "Heavy",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage1DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 1 DMG",
      talents: {
        "1": "34.02%",
        "2": "36.81%",
        "3": "39.60%",
        "4": "43.51%",
        "5": "46.30%",
        "6": "49.51%",
        "7": "53.97%",
        "8": "58.43%",
        "9": "62.90%",
        "10": "67.64%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage2DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 2 DMG",
      talents: {
        "1": "32.10%",
        "2": "34.74%",
        "3": "37.37%",
        "4": "41.05%",
        "5": "43.69%",
        "6": "46.71%",
        "7": "50.93%",
        "8": "55.14%",
        "9": "59.35%",
        "10": "63.82%",
      },
      type: "Basic",
    },
    {
      key: "MidAirAttackStarflowerBloomsStage3DMG",
      label: "Mid-air Attack: Starflower Blooms Stage 3 DMG",
      talents: {
        "1": "15.34%*3",
        "2": "16.60%*3",
        "3": "17.86%*3",
        "4": "19.62%*3",
        "5": "20.88%*3",
        "6": "22.33%*3",
        "7": "24.34%*3",
        "8": "26.35%*3",
        "9": "28.36%*3",
        "10": "30.50%*3",
      },
      type: "Basic",
    },
    {
      key: "StarflowerBloomsHealing",
      label: "Starflower Blooms Healing",
      talents: {
        "1": "625 + 14.17%",
        "2": "750 + 16.29%",
        "3": "875 + 17.71%",
        "4": "1000 + 19.83%",
        "5": "1032 + 21.25%",
        "6": "1113 + 22.67%",
        "7": "1125 + 24.08%",
        "8": "1144 + 25.50%",
        "9": "1163 + 26.92%",
        "10": "1188 + 29.75%",
      },
      type: "Healing",
    },
    {
      key: "SequenceNode6JoyousHarvestDMG",
      label: "S6: Joyous Harvest DMG",
      talents: {
        "1": "5.00%",
        "2": "5.41%",
        "3": "5.82%",
        "4": "6.40%",
        "5": "6.81%",
        "6": "7.28%",
        "7": "7.94%",
        "8": "8.59%",
        "9": "9.25%",
        "10": "9.95%",
      },
      type: "Liberation",
      requiresResonanceChain: "SequenceNode6JoyousHarvest",
    },
    {
      key: "SequenceNode6JoyousHarvestHealing",
      label: "S6: Joyous Harvest Healing",
      talents: {
        "1": "225 + 5.10%",
        "2": "270 + 5.87%",
        "3": "315 + 6.38%",
        "4": "360 + 7.14%",
        "5": "372 + 7.65%",
        "6": "401 + 8.16%",
        "7": "405 + 8.67%",
        "8": "412 + 9.18%",
        "9": "419 + 9.69%",
        "10": "428 + 10.71%",
      },
      type: "Healing",
      requiresResonanceChain: "SequenceNode6JoyousHarvest",
    },
  ],
};
