export const forteCircuitAttacks = {
  name: "Forte Circuit: Formless Heart Sword",
  description: `<div><span class="Title">Ephemeral Transcendence</span></span><br><br>While Qingxiao is in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state, unlocks <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span> and <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span>.<br><size=10></span><br><br><span class="Title">Basic Attack - Ephemeral Transcendence</span></span><br><br>Press repeatedly or hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to unleash up to 4 consecutive strikes, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>Before <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> is unlocked, this skill gains a 100% DMG Multiplier increase.<br>Can be cast while in mid-air.<br><size=10></span><br><br><span class="Title">Dodge Counter - Ephemeral Transcendence</span></span><br><br>{Cus:Ipt,Touch=Tapping PC=Pressing Gamepad=Pressing} <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> within a certain time after a successful Dodge will strike the target, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>Before <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> is unlocked, this skill gains a 100% DMG Multiplier increase.<br>Can be cast while in mid-air.<br><size=10></span><br><br><span class="Title">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span> is full, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> is unlocked. Hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to cast this skill, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>During this skill, all <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span> will be consumed and Qingxiao exits the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.<br><size=10></span><br><br><span class="Title">Mindlock</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Mindlock</span> has a maximum of 15 stacks.<br>When Resonators in the team inflict <span style="color:#ffd12f;" class="font-bold">Tune Strain - Interfered</span>, apply 1 stacks of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> to the target.<br>For each stack of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> on the target, DMG taken by the target from the following Qingxiao skills is Amplified by 2%. This effect increases by 5% per stack for the first 7 stacks.<br>- <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Billows Beneath Heaven</span>.<br><size=10></span><br><br><span class="Title">Heaven's Clarity</span></span><br><br>Upon entering combat or casting <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Billows Beneath Heaven</span>, gain <span style="color:#ffd12f;" class="font-bold">Heaven's Clarity</span>.<br>- When casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, apply 2 stacks of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> to nearby targets. The DMG Multiplier of the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> is increased by 100%. Switching to another Resonator ends DMG Multiplier increase effect.<br>Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> removes <span style="color:#ffd12f;" class="font-bold">Heaven's Clarity</span>.<br><size=10></span><br><br><span class="Title">Swordlight Ward</span></span><br><br>Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tonic Shift</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span> grants 1 stacks of <span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span>.<br><span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span> has a maximum of 1 stacks. When taking DMG from an enemy's attack, <SapTag=A>1</SapTag> {Cus:Sap,S=stack P=stacks SapTag=A} of <span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span> can be consumed to grant immunity to interruption and reduce DMG taken by 60%, lasting 1s. This effect can trigger once per second.<br><size=10></span><br><br><span class="Title">Sword Flight</span></span><br><br>While in the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state, Qingxiao moves in a special way.<br>During <span style="color:#ffd12f;" class="font-bold">Sword Flight</span>, <span style="color:#ffd12f;" class="font-bold">Flight Qi</span> is continuously consumed.<br>- Qingxiao enters the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state after casting the following skills:<br><span style="color:#ffd12f;" class="font-bold">Sword Dodge</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 1</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 2</span>, <span style="color:#ffd12f;" class="font-bold">Severing Note: Ascendant</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span>, and <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tonic Shift</span>.<br>Qingxiao leaves the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state via the following ways:<br>- Casting <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 3</span> and <span style="color:#ffd12f;" class="font-bold">Plunging Attack</span>.<br>- Triggering environmental interactions or using Utilities<br>- Returning to the ground.<br><size=10></span><br><br><span class="Title">Sword Step</span></span><br><br>While in the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state, hold <span style="color:#ffd12f;" class="font-bold">Jump</span> to leap and dash forward a short distance.<br>During <span style="color:#ffd12f;" class="font-bold">Sword Step</span>, <span style="color:#ffd12f;" class="font-bold">Flight Qi</span> is continuously consumed.<br><size=10></span><br><br><span class="Title">Qin Heart</span></span><br><br>Qingxiao can hold up to 100 points of Qin Heart.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Sheathed Stance</span> grants <span style="color:#ffd12f;" class="font-bold">Qin Heart</span>.<br><span style="color:#ffd12f;" class="font-bold">Qin Heart</span> cannot be gained while in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.<br><size=10></span><br><br><span class="Title">Sword Spirit</span></span><br><br>Qingxiao can hold up to 100 points of Sword Spirit.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Drawn Stance</span> grants <span style="color:#ffd12f;" class="font-bold">Sword Spirit</span>.<br><span style="color:#ffd12f;" class="font-bold">Sword Spirit</span> cannot be gained while in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.<br><size=10></span><br><br><span class="Title">Heart Sword Intent</span></span><br><br>Qingxiao can hold up to 100 points of Heart Sword Intent.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span> or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span> grants <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span>.</div>`,
  attacks: [
    {
      key: "BasicAttackEphemeralTranscendenceStage1DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 1 DMG",
      talents: {
        "1": "22.58%+11.29%*2",
        "2": "24.43%+12.22%*2",
        "3": "26.28%+13.14%*2",
        "4": "28.87%+14.44%*2",
        "5": "30.73%+15.37%*2",
        "6": "32.85%+16.43%*2",
        "7": "35.82%+17.91%*2",
        "8": "38.78%+19.39%*2",
        "9": "41.74%+20.87%*2",
        "10": "44.89%+22.45%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage2DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 2 DMG",
      talents: {
        "1": "11.62%*5",
        "2": "12.58%*5",
        "3": "13.53%*5",
        "4": "14.86%*5",
        "5": "15.82%*5",
        "6": "16.91%*5",
        "7": "18.44%*5",
        "8": "19.96%*5",
        "9": "21.49%*5",
        "10": "23.11%*5",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage3DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 3 DMG",
      talents: {
        "1": "10.50%*3+15.75%*2",
        "2": "11.37%*3+17.05%*2",
        "3": "12.23%*3+18.34%*2",
        "4": "13.43%*3+20.15%*2",
        "5": "14.29%*3+21.44%*2",
        "6": "15.28%*3+22.92%*2",
        "7": "16.66%*3+24.99%*2",
        "8": "18.04%*3+27.06%*2",
        "9": "19.42%*3+29.12%*2",
        "10": "20.88%*3+31.32%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage4DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 4 DMG",
      talents: {
        "1": "9.10%*4+54.60%",
        "2": "9.85%*4+59.08%",
        "3": "10.60%*4+63.56%",
        "4": "11.64%*4+69.83%",
        "5": "12.39%*4+74.30%",
        "6": "13.25%*4+79.45%",
        "7": "14.44%*4+86.62%",
        "8": "15.63%*4+93.78%",
        "9": "16.83%*4+100.94%",
        "10": "18.10%*4+108.56%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterEphemeralTranscendenceDMG",
      label: "Dodge Counter - Ephemeral Transcendence DMG",
      talents: {
        "1": "13.30%*4+79.80%",
        "2": "14.40%*4+86.35%",
        "3": "15.49%*4+92.89%",
        "4": "17.01%*4+102.05%",
        "5": "18.10%*4+108.60%",
        "6": "19.36%*4+116.12%",
        "7": "21.10%*4+126.59%",
        "8": "22.85%*4+137.06%",
        "9": "24.59%*4+147.53%",
        "10": "26.45%*4+158.66%",
      },
      type: "Basic",
    },
    {
      key: "HeavenSReckoningEphemeralTranscendenceDMG",
      label: "Heaven's Reckoning: Ephemeral Transcendence DMG",
      talents: {
        "1": "14.00%*9+224.00%",
        "2": "15.15%*9+242.37%",
        "3": "16.30%*9+260.74%",
        "4": "17.91%*9+286.46%",
        "5": "19.06%*9+304.82%",
        "6": "20.38%*9+325.95%",
        "7": "22.21%*9+355.34%",
        "8": "24.05%*9+384.72%",
        "9": "25.89%*9+414.11%",
        "10": "27.84%*9+445.34%",
      },
      type: "Heavy",
    }
  ],
};
