export const forteCircuitAttacks = {
  name: "Forte Circuit: Formless Heart Sword",
  description: `<div><span class="Title">Ephemeral Transcendence</span></span><br><br>While Qingxiao is in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span> and <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span> become available.</span><br><br><span class="Title">Basic Attack - Ephemeral Transcendence</span></span><br><br>Press repeatedly or hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to perform up to 4 consecutive attacks, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>Before <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> becomes available, this skill's DMG Multiplier is increased by 100%.<br>Can be cast in mid-air.</span><br><br><span class="Title">Dodge Counter - Ephemeral Transcendence</span></span><br><br>Press or hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> within a certain time after a successful Dodge to attack the target, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>Before <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> becomes available, this skill's DMG Multiplier is increased by 100%.<br>Can be cast in mid-air.</span><br><br><span class="Title">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span></span><br><br>When <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span> is full, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> becomes available. Hold <span style="color:#ffd12f;" class="font-bold">Normal Attack</span> to cast the skill, dealing <span style="color:#c7ffed";>Aero DMG</span>.<br>Casting this skill consumes all <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span> and ends the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.</span><br><br><span class="Title">Mindlock</span></span><br><br><span style="color:#ffd12f;" class="font-bold">Mindlock</span> stacks up to 15 times.<br>Each time when a Resonator in the team inflicts <span style="color:#ffd12f;" class="font-bold">Tune Strain - Interfered</span> on a target, inflict 1 stacks of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> on the target.<br>For each stack of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> on the target, DMG taken from Qingxiao's following skills is Amplified by 2%, with an additional 5% per stack for the first 7 stacks.<br>- <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Resonance Liberation - Billows Beneath Heaven</span>.</span><br><br><span class="Title">Heaven's Clarity</span></span><br><br>Upon entering combat or casting Resonance Liberation <span style="color:#ffd12f;" class="font-bold">Billows Beneath Heaven</span>, gain <span style="color:#ffd12f;" class="font-bold">Heaven's Clarity</span>.<br>When <span style="color:#ffd12f;" class="font-bold">Sheathed Stance</span>/<span style="color:#ffd12f;" class="font-bold">Drawn Stance</span> moves deal damage, the rates at which <span style="color:#ffd12f;" class="font-bold">Qin Heart</span>/<span style="color:#ffd12f;" class="font-bold">Sword Cadence</span> are obtained increase by 100%.<br>When casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, inflict 3 stacks of <span style="color:#ffd12f;" class="font-bold">Mindlock</span> on nearby targets, and enhance the next <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span>: its DMG Multiplier is increased by 100% and it builds additional Off-Tune Level on the target. Switching to another Resonator ends the <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> enhancement.<br>Casting <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span> removes <span style="color:#ffd12f;" class="font-bold">Heaven's Clarity</span>.</span><br><br><span class="Title">Swordlight Ward</span></span><br><br>Casting <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tonality Shift</span> or <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span> grants 1 stacks of <span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span>.<br><span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span> stacks up to 1 times. When taking DMG from an enemy's attack, <SapTag=A>1</SapTag> {Cus:Sap,S=stack P=stacks SapTag=A} of <span style="color:#ffd12f;" class="font-bold">Swordlight Ward</span> can be consumed to grant immunity to interruption and reduce DMG taken by 60% for 1s. This effect can be triggered once per second.</span><br><br><span class="Title">Sword Flight</span></span><br><br>While in the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state, Qingxiao moves with a special animation.<br>Moving in <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> continuously consumes <span style="color:#ffd12f;" class="font-bold">Flight Qi</span>.<br>- Casting the following skills sends Qingxiao into the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state:<br><span style="color:#ffd12f;" class="font-bold">Sword Dodge</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Stringblade</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 1</span>, <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 2</span>, <span style="color:#ffd12f;" class="font-bold">Severing Note: Ascendant</span>, <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span>, <span style="color:#ffd12f;" class="font-bold">Heavy Attack - Heaven's Reckoning: Ephemeral Transcendence</span>, and <span style="color:#ffd12f;" class="font-bold">Intro Skill - Tonality Shift</span>.<br>- Exit the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state by:<br>1. Casting <span style="color:#ffd12f;" class="font-bold">Mid-air Attack - Stringblade Stage 3</span> or <span style="color:#ffd12f;" class="font-bold">Plunging Attack</span>.<br>2. Triggering certain environmental interactions or Utilities.<br>3. Returning to the ground.<br>4. Switching to another Resonator.<br>5. Depleting all <span style="color:#ffd12f;" class="font-bold">Flight Qi</span>.</span><br><br><span class="Title">Sword Step</span></span><br><br>While in the <span style="color:#ffd12f;" class="font-bold">Sword Flight</span> state, hold <span style="color:#ffd12f;" class="font-bold">Jump</span> to leap up and dash forward a short distance.<br><span style="color:#ffd12f;" class="font-bold">Sword Step</span> can only be cast once during <span style="color:#ffd12f;" class="font-bold">Sword Flight</span>.</span><br><br><span class="Title">Qin Heart</span></span><br><br>Can hold up to 100 points.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Sheathed Stance</span> skills grants <span style="color:#ffd12f;" class="font-bold">Qin Heart</span>.<br><span style="color:#ffd12f;" class="font-bold">Qin Heart</span> cannot be gained while in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.</span><br><br><span class="Title">Sword Cadence</span></span><br><br>Can hold up to 100 points.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Drawn Stance</span> skills grants <span style="color:#ffd12f;" class="font-bold">Sword Cadence</span>.<br><span style="color:#ffd12f;" class="font-bold">Sword Cadence</span> cannot be gained while in the <span style="color:#ffd12f;" class="font-bold">Ephemeral Transcendence</span> state.</span><br><br><span class="Title">Heart Sword Intent</span></span><br><br>Can hold up to 100 points.<br>Dealing damage with <span style="color:#ffd12f;" class="font-bold">Basic Attack - Ephemeral Transcendence</span> or <span style="color:#ffd12f;" class="font-bold">Dodge Counter - Ephemeral Transcendence</span> grants <span style="color:#ffd12f;" class="font-bold">Heart Sword Intent</span>.</div>`,
  icon: "https://api.encore.moe/resource/Data/Game/Aki/UI/UIResources/Common/Atlas/SkillIcon/SkillIconQingxiao/SP_IconQingxiaoY.webp",
  attacks: [
    {
      key: "BasicAttackEphemeralTranscendenceStage1DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 1 DMG",
      talents: {
        "1": "22.58%+11.29%*2",
        "2": "24.43%+12.22%*2",
        "3": "26.28%+13.14%*2",
        "4": "28.87%+14.44%*2",
        "5": "30.73%+15.37%*2",
        "6": "32.85%+16.43%*2",
        "7": "35.82%+17.91%*2",
        "8": "38.78%+19.39%*2",
        "9": "41.74%+20.87%*2",
        "10": "44.89%+22.45%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage2DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 2 DMG",
      talents: {
        "1": "11.62%*5",
        "2": "12.58%*5",
        "3": "13.53%*5",
        "4": "14.86%*5",
        "5": "15.82%*5",
        "6": "16.91%*5",
        "7": "18.44%*5",
        "8": "19.96%*5",
        "9": "21.49%*5",
        "10": "23.11%*5",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage3DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 3 DMG",
      talents: {
        "1": "10.50%*3+15.75%*2",
        "2": "11.37%*3+17.05%*2",
        "3": "12.23%*3+18.34%*2",
        "4": "13.43%*3+20.15%*2",
        "5": "14.29%*3+21.44%*2",
        "6": "15.28%*3+22.92%*2",
        "7": "16.66%*3+24.99%*2",
        "8": "18.04%*3+27.06%*2",
        "9": "19.42%*3+29.12%*2",
        "10": "20.88%*3+31.32%*2",
      },
      type: "Basic",
    },
    {
      key: "BasicAttackEphemeralTranscendenceStage4DMG",
      label: "Basic Attack - Ephemeral Transcendence Stage 4 DMG",
      talents: {
        "1": "9.10%*4+54.60%",
        "2": "9.85%*4+59.08%",
        "3": "10.60%*4+63.56%",
        "4": "11.64%*4+69.83%",
        "5": "12.39%*4+74.30%",
        "6": "13.25%*4+79.45%",
        "7": "14.44%*4+86.62%",
        "8": "15.63%*4+93.78%",
        "9": "16.83%*4+100.94%",
        "10": "18.10%*4+108.56%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterEphemeralTranscendenceDMG",
      label: "Dodge Counter - Ephemeral Transcendence DMG",
      talents: {
        "1": "13.30%*4+79.80%",
        "2": "14.40%*4+86.35%",
        "3": "15.49%*4+92.89%",
        "4": "17.01%*4+102.05%",
        "5": "18.10%*4+108.60%",
        "6": "19.36%*4+116.12%",
        "7": "21.10%*4+126.59%",
        "8": "22.85%*4+137.06%",
        "9": "24.59%*4+147.53%",
        "10": "26.45%*4+158.66%",
      },
      type: "Basic",
    },
    {
      key: "HeavenSReckoningEphemeralTranscendenceDMG",
      label: "Heaven's Reckoning: Ephemeral Transcendence DMG",
      talents: {
        "1": "14.00%*9+224.00%",
        "2": "15.15%*9+242.37%",
        "3": "16.30%*9+260.74%",
        "4": "17.91%*9+286.46%",
        "5": "19.06%*9+304.82%",
        "6": "20.38%*9+325.95%",
        "7": "22.21%*9+355.34%",
        "8": "24.05%*9+384.72%",
        "9": "25.89%*9+414.11%",
        "10": "27.84%*9+445.34%",
      },
      type: "Heavy",
    }
  ],
};
