export const rotations: RotationPreset[] = [
  {
    name: `For Static Mist by Genezis`,
    description: `Turn on everything for the character, I took into account the gradual increase in attack in the rotation.`,
    author: `Genezis`,
    data: {
      name: "For Static Mist by Genezis",
      description:
        "Turn on everything for the character, I took into account the gradual increase in attack in the rotation.",
      actions: [
        {
          order: 1,
          key: "WhizzingFightSpiritSkillDMG",
          type: "skill",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-60" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "WhizzingFightSpiritSkillDMG",
          type: "skill",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-60" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "GrandEntranceSkillDMG",
          type: "intro",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-60" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-59" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-58" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-57" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-56" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-55" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-54" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-53" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-52" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 14,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-51" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 15,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-50" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 20,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-49" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 21,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-48" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 22,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: -47 }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 23,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-46" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 24,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-45" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 25,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-44" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 26,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-43" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 27,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-42" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 28,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-41" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 30,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-40" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 50,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-39" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 51,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-38" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 52,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-37" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 53,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-36" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 54,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-35" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 55,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-34" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 56,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-33" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 57,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-32" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 58,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: 1,
          buffs: [{ modifier: "ATK", modifierValue: "-31" }],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 62,
          key: "ThermobaricBulletsDamage",
          type: "forteCircuit",
          count: "31",
          buffs: [],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 63,
          key: "BoomBoomDamage",
          type: "forteCircuit",
          count: "2",
          buffs: [],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 64,
          key: "BlazingFlamesSkillDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
        {
          order: 65,
          key: "OutroSkillDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeTeamBuffs: false,
          isDisabled: false,
        },
      ],
    },
  },
  {
    name: `DPS Rotation (On-Field Role)`,
    description: `Skill → Echo Swap → Intro → DkDk ×30 → Ult → Boom → DkDk ×30 → Boom → Outro`,
    author: `Namelag`,
    data: {"name":"DPS Rotation (On-Field Role)","description":"Skill → Echo Swap → Intro → DkDk ×30 → Ult → Boom → DkDk ×30 → Boom → Outro","actions":[{"order":1,"key":"WhizzingFightSpiritSkillDMG","type":"skill","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":2,"key":"GrandEntranceSkillDMG","type":"intro","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"ThermobaricBulletsDamage","type":"forteCircuit","count":"30","buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"BlazingFlamesSkillDMG","type":"liberation","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"BoomBoomDamage","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"ThermobaricBulletsDamage","type":"forteCircuit","count":"30","buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"BoomBoomDamage","type":"forteCircuit","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"OutroSkillDMG","type":"outro","count":1,"buffs":[],"excludeTeamBuffs":false,"isDisabled":false}]}
  }
];
