export const buffs = [
  {
    key: `Afterflame`,
    name: `Afterflame`,
    details: `<div class="skilldescription">While in <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>, every point of <span class="ingame-Highlight"><te href="120801">Afterflame</te></span> increases the DMG of <span class="ingame-Highlight">Basic Attack - Seraphic Execution</span>, <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict</span>, <span class="ingame-Highlight">Mid-air Attack - Hellsent Barrage</span>, <span class="ingame-Highlight">Resonance Skill - Ravage</span>, and <span class="ingame-Highlight">Dodge Counter - Purgatory Scourge</span> by 1.5%, up to 60%, which is removed upon exiting <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span></div>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "specialMultiplier",
        modifySpecificTalents: [
          "BasicAttackSeraphicExecutionStage1DMG",
          "BasicAttackSeraphicExecutionStage2DMG",
          "BasicAttackSeraphicExecutionStage3DMG",
          "BasicAttackSeraphicExecutionStage4DMG",
          "BasicAttackSeraphicExecutionStage5DMG",
          "HeavyAttackFlamewingVerdictStage1DMG",
          "HeavyAttackFlamewingVerdictStage2DMG",
          "HeavyAttackFlamewingVerdictStage3DMG",
          "MidairAttackHellsentBarragePlungingAttackDMG",
          "MidairAttackHellsentBarrageSustainedFireDMG",
          "ResonanceSkillRavageDMG",
          "DodgeCounterPurgatoryScourgeDMG",
        ],
        modifierValue: 0.015,
      },
    ],
    minStacks: 0,
    maxStacks: 40,
    alwaysEnabled: false,
  },
  {
    key: `BurningDrive`,
    name: `Burning Drive`,
    details: `<div class="skilldescription"><span class="ingame-Title">Burning Drive</span></span><br>Casting <span class="ingame-Highlight">Intro Skill</span>, <span class="ingame-Highlight">Hellstride</span>, <span class="ingame-Highlight">Normal Attack - Seraphic Execution Basic Attack Stage 4</span>, <span class="ingame-Highlight">Resonance Skill - Encroach</span>, <span class="ingame-Highlight">Resonance Skill - Ascent of Malice</span>, and <span class="ingame-Highlight">Resonance Skill - Ravage</span> increases Galbrena's resistance to interruptions and ATK by 20% for 4s.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `HellfireAbsolution`,
    name: `Hellfire Absolution`,
    details: `<div class="skilldescription">Attack the target and deal <span class="ingame-Fire">Fusion DMG</span>, considered <span class="ingame-Highlight">Echo Skill DMG</span>. Gain 85% DMG Multiplier increase for <span class="ingame-Highlight">Basic Attack - Seraphic Execution</span>, <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict</span>, <span class="ingame-Highlight">Mid-air Attack - Hellsent Barrage</span>, and <span class="ingame-Highlight">Dodge Counter - Purgatory Scourge</span> for 14s while in <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "BasicAttackSeraphicExecutionStage1DMG",
          "BasicAttackSeraphicExecutionStage2DMG",
          "BasicAttackSeraphicExecutionStage3DMG",
          "BasicAttackSeraphicExecutionStage4DMG",
          "BasicAttackSeraphicExecutionStage5DMG",
          "HeavyAttackFlamewingVerdictStage1DMG",
          "HeavyAttackFlamewingVerdictStage2DMG",
          "HeavyAttackFlamewingVerdictStage3DMG",
          "MidairAttackHellsentBarragePlungingAttackDMG",
          "MidairAttackHellsentBarrageSustainedFireDMG",
          "DodgeCounterPurgatoryScourgeDMG",
        ],
        modifierValue: 0.85,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillOathboundHunt`,
    name: `Inherent Skill: Oathbound Hunt`,
    details: `<div>1 stack of <span class="ingame-Highlight">Fated End</span> is inflicted on the target when the following skills hit: <span class="ingame-Highlight">Intro Skill</span>, <span class="ingame-Highlight">Basic Attack</span>, <span class="ingame-Highlight">Basic Attack - Seraphic Execution</span>, <span class="ingame-Highlight">Dodge Counter</span>, <span class="ingame-Highlight">Heavy Attack - Volley of Death</span>, <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict</span>, <span class="ingame-Highlight">Mid-air Attack</span>, <span class="ingame-Highlight">Hellstride</span>, <span class="ingame-Highlight">Resonance Skill - Encroach</span>, <span class="ingame-Highlight">Resonance Skill - Ascent of Malice</span>, <span class="ingame-Highlight">Resonance Skill - Ravage</span> and <span class="ingame-Highlight">Resonance Liberation</span>, up to 4 stacks. Each stack Amplifies the DMG directly dealt by Galbrena's <span class="ingame-Highlight">Normal Attack</span>, <span class="ingame-Highlight">Resonance Skill</span>, <span class="ingame-Highlight">Forte Circuit</span>, <span class="ingame-Highlight">Resonance Liberation</span>, <span class="ingame-Highlight">Intro Skill</span>, and <span class="ingame-Highlight">Outro Skill</span> by 5% for 5.5s. The same type of skill can trigger this effect on the same target once every 5s.<br><span class="ingame-Highlight">Resonance Skill - Encroach</span> and <span class="ingame-Highlight">Resonance Skill - Ravage</span> are considered the same type of skill.</div>`,
    hasStacks: true,
    modifiers: [
      {
        // this affects every attack she has, no use listing them all
        modifier: "DMGDeepen",
        modifierValue: 0.05,
      },
    ],
    minStacks: 0,
    maxStacks: 4,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillSinFeaster`,
    name: `Inherent Skill: Sin Feaster`,
    details: `<div>Casting <span class="ingame-Highlight">Basic Attack Stage 4</span>, <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 5</span>, <span class="ingame-Highlight">Heavy Attack - Volley of Death Stage 3</span>, and <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict Stage 3</span> recovers 10 points of STA.</div>`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG1",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 2.40%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.024,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG2",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 2.40%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.024,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG3",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 5.60%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.056,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritDMG4",
    name: "Stat Bonus: Crit. DMG+",
    details: `<div class="skilldescription">Crit. DMG increased by 5.60%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritDMG",
        modifierValue: 0.056,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK1",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK2",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK3",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK4",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
