export const forteCircuitAttacks = {
  name: "Forte Circuit: Beyond Threshold",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Threshold State</span></span><br>By default, Galbrena is in <span class="ingame-Highlight"><te href="120804">Threshold State</te></span>, and in this state, she accumulates <span class="ingame-Highlight"><te href="120801">Afterflame</te></span> and <span class="ingame-Highlight"><te href="120802">Sinflame</te></span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Demon Hypostasis</span></span><br>While in <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>, Basic Attack, Heavy Attack - Volley of Death, Mid-air Attack - Ashfall Barrage, Dodge Counter - Blood for Blood, and Resonance Skill - Encroach are replaced with Basic Attack - Seraphic Execution, Heavy Attack - Flamewing Verdict, Mid-air Attack - Hellsent Barrage, Dodge Counter - Purgatory Scourge, and Resonance Skill - Ravage. During this period, consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit.<br>While in <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>, every point of <span class="ingame-Highlight"><te href="120801">Afterflame</te></span> increases the DMG of <span class="ingame-Highlight">Basic Attack - Seraphic Execution</span>, <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict</span>, <span class="ingame-Highlight">Mid-air Attack - Hellsent Barrage</span>, <span class="ingame-Highlight">Resonance Skill - Ravage</span>, and <span class="ingame-Highlight">Dodge Counter - Purgatory Scourge</span> by 1.5%, up to 60%, which is removed upon exiting <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>.<br>When <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> depletes or after staying in <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span> for over 50s, <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span> ends automatically.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Basic Attack - Seraphic Execution</span></span><br>Perform up to 5 consecutive attacks, dealing <span class="ingame-Fire">Fusion DMG</span>. Consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit. Stage 1 to 3 DMG are considered <span class="ingame-Highlight">Heavy Attack DMG</span>, and Stage 4 &amp; 5 DMG <span class="ingame-Highlight">Echo Skill DMG</span>.<br>Press Normal Attack after casting <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 5</span> to cast <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 3</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack - Flamewing Verdict</span></span><br>Consume STA to attack the target and perform up to 3 consecutive attacks, dealing <span class="ingame-Fire">Fusion DMG</span>. Consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit. Stage 3 DMG is considered <span class="ingame-Highlight">Echo Skill DMG</span>.<br>Press Normal Attack after casting <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict Stage 1</span> to cast <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 2</span>. <br>Press Normal Attack after casting <span class="ingame-Highlight">Heavy Attack - Flamewing Verdict Stage 2 &amp; 3</span> to cast <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 3</span>. <br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Mid-air Attack - Hellsent Barrage</span></span><br>While in mid-air, press Normal Attack to consume STA to perform aerial attacks, dealing <span class="ingame-Fire">Fusion DMG</span>, considered <span class="ingame-Highlight">Heavy Attack DMG</span>. Consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit.<br>While in mid-air, hold Normal Attack to continuously consume STA to launch a barrage of shots at targets, dealing <span class="ingame-Fire">Fusion DMG</span>, considered <span class="ingame-Highlight">Heavy Attack DMG</span>. Consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit. If Galbrena does not land when interrupted during the barrage, she cannot immediately cast this skill again. Release Normal Attack during the barrage to cast Plunging Attack. <br>Press Normal Attack after the Plunging Attack to cast <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 3</span>. <br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter - Purgatory Scourge</span></span><br>Press Normal Attack right after a successful Dodge to attack the target, dealing <span class="ingame-Fire">Fusion DMG</span>, considered <span class="ingame-Highlight">Heavy Attack DMG</span>.<br>Press Normal Attack right after casting this skill to cast <span class="ingame-Highlight">Basic Attack - Seraphic Execution Stage 4</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Skill - Ravage</span></span><br>Dash forward and leap into the air. Flip backward upon hitting the target, dealing <span class="ingame-Fire">Fusion DMG</span>, considered <span class="ingame-Highlight">Heavy Attack DMG</span>. Consume <span class="ingame-Highlight"><te href="120803">Purging Flame</te></span> on hit. <span class="ingame-Highlight">Resonance Skill - Ravage</span> and <span class="ingame-Highlight">Resonance Skill - Encroach</span> share a cooldown.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Hellstride</span></span><br>Press Dodge on the ground while casting <span class="ingame-Highlight">Galbrena's own skills</span> to cast <span class="ingame-Highlight">Hellstride</span> to deal a fixed amount of <span class="ingame-Fire">Fusion DMG</span>, considered Basic Attack DMG that does not bear any effect from DMG buffs. <span class="ingame-Highlight">Hellstride</span> can trigger successful Dodges. <span class="ingame-Highlight">Hellstride</span> cannot be cast consecutively.<br>Casting this skill does not reset the attack cycles within a short period of time.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Burning Drive</span></span><br>Casting <span class="ingame-Highlight">Intro Skill</span>, <span class="ingame-Highlight">Hellstride</span>, <span class="ingame-Highlight">Normal Attack - Seraphic Execution Basic Attack Stage 4</span>, <span class="ingame-Highlight">Resonance Skill - Encroach</span>, <span class="ingame-Highlight">Resonance Skill - Ascent of Malice</span>, and <span class="ingame-Highlight">Resonance Skill - Ravage</span> increases Galbrena's resistance to interruptions and ATK by 20% for 4s.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Afterflame</span></span><br>Galbrena can hold up to 40 points of <span class="ingame-Highlight"><te href="120801">Afterflame</te></span>.<br>While in <span class="ingame-Highlight"><te href="120804">Threshold State</te></span>, Galbrena recovers 8 points of <span class="ingame-Highlight"><te href="120801">Afterflame</te></span> when Resonators in the nearby team cast Echo Skill. Echoes with the same name can only trigger this effect once. This effect resets when Galbrena exits <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>.<br>All <span class="ingame-Highlight"><te href="120801">Afterflame</te></span> is removed upon exiting <span class="ingame-Highlight"><te href="120805">Demon Hypostasis</te></span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Sinflame</span></span><br>Galbrena can hold up to 100 points of <span class="ingame-Highlight"><te href="120802">Sinflame</te></span>.<br>While in <span class="ingame-Highlight"><te href="120804">Threshold State</te></span>, hitting an enemy with Basic Attack, Heavy Attack - Volley of Death, Mid-air Attack - Ashfall Barrage, Resonance Skill - Encroach, and Intro Skill - Hellflare Overload recovers <span class="ingame-Highlight"><te href="120802">Sinflame</te></span>.</div>`,
  attacks: [
    {
      key: "HellstrideDMG",
      label: "Hellstride DMG",
      type: "Basic",
      talents: {
        "1": "666",
        "2": "666",
        "3": "666",
        "4": "666",
        "5": "666",
        "6": "666",
        "7": "666",
        "8": "666",
        "9": "666",
        "10": "666",
      },
      isFixed: true,
    },
    {
      key: "BasicAttackSeraphicExecutionStage1DMG",
      label: "Basic Attack - Seraphic Execution Stage 1 DMG",
      type: "Heavy",
      talents: {
        "1": "29.67%",
        "2": "32.11%",
        "3": "34.54%",
        "4": "37.95%",
        "5": "40.38%",
        "6": "43.18%",
        "7": "47.07%",
        "8": "50.96%",
        "9": "54.86%",
        "10": "58.99%",
      },
    },
    {
      key: "BasicAttackSeraphicExecutionStage2DMG",
      label: "Basic Attack - Seraphic Execution Stage 2 DMG",
      type: "Heavy",
      talents: {
        "1": "14.00%+14.00%+42.00%",
        "2": "15.15%+15.15%+45.45%",
        "3": "16.30%+16.30%+48.89%",
        "4": "17.91%+17.91%+53.71%",
        "5": "19.06%+19.06%+57.16%",
        "6": "20.38%+20.38%+61.12%",
        "7": "22.21%+22.21%+66.63%",
        "8": "24.05%+24.05%+72.14%",
        "9": "25.89%+25.89%+77.65%",
        "10": "27.84%+27.84%+83.51%",
      },
    },
    {
      key: "BasicAttackSeraphicExecutionStage3DMG",
      label: "Basic Attack - Seraphic Execution Stage 3 DMG",
      type: "Heavy",
      talents: {
        "1": "12.23%*3+85.61%",
        "2": "13.24%*3+92.64%",
        "3": "14.24%*3+99.66%",
        "4": "15.64%*3+109.48%",
        "5": "16.65%*3+116.50%",
        "6": "17.80%*3+124.58%",
        "7": "19.41%*3+135.81%",
        "8": "21.01%*3+147.04%",
        "9": "22.61%*3+158.27%",
        "10": "24.32%*3+170.21%",
      },
    },
    {
      key: "BasicAttackSeraphicExecutionStage4DMG",
      label: "Basic Attack - Seraphic Execution Stage 4 DMG",
      type: "Echo",
      talents: {
        "1": "9.13%*3+63.89%",
        "2": "9.88%*3+69.13%",
        "3": "10.63%*3+74.37%",
        "4": "11.68%*3+81.71%",
        "5": "12.43%*3+86.95%",
        "6": "13.29%*3+92.97%",
        "7": "14.48%*3+101.35%",
        "8": "15.68%*3+109.73%",
        "9": "16.88%*3+118.12%",
        "10": "18.15%*3+127.02%",
      },
    },
    {
      key: "BasicAttackSeraphicExecutionStage5DMG",
      label: "Basic Attack - Seraphic Execution Stage 5 DMG",
      type: "Echo",
      talents: {
        "1": "33.84%+78.96%",
        "2": "36.62%+85.44%",
        "3": "39.39%+91.91%",
        "4": "43.28%+100.98%",
        "5": "46.05%+107.45%",
        "6": "49.25%+114.90%",
        "7": "53.69%+125.26%",
        "8": "58.13%+135.62%",
        "9": "62.57%+145.98%",
        "10": "67.28%+156.99%",
      },
    },
    {
      key: "HeavyAttackFlamewingVerdictStage1DMG",
      label: "Heavy Attack - Flamewing Verdict Stage 1 DMG",
      type: "Heavy",
      talents: {
        "1": "29.79%+29.79%",
        "2": "32.23%+32.23%",
        "3": "34.67%+34.67%",
        "4": "38.09%+38.09%",
        "5": "40.54%+40.54%",
        "6": "43.35%+43.35%",
        "7": "47.25%+47.25%",
        "8": "51.16%+51.16%",
        "9": "55.07%+55.07%",
        "10": "59.22%+59.22%",
      },
    },
    {
      key: "HeavyAttackFlamewingVerdictStage2DMG",
      label: "Heavy Attack - Flamewing Verdict Stage 2 DMG",
      type: "Heavy",
      talents: {
        "1": "19.29%*2",
        "2": "20.87%*2",
        "3": "22.45%*2",
        "4": "24.67%*2",
        "5": "26.25%*2",
        "6": "28.07%*2",
        "7": "30.60%*2",
        "8": "33.13%*2",
        "9": "35.66%*2",
        "10": "38.35%*2",
      },
    },
    {
      key: "HeavyAttackFlamewingVerdictStage3DMG",
      label: "Heavy Attack - Flamewing Verdict Stage 3 DMG",
      type: "Echo",
      talents: {
        "1": "8.90%*3+62.26%",
        "2": "9.63%*3+67.36%",
        "3": "10.36%*3+72.47%",
        "4": "11.38%*3+79.62%",
        "5": "12.11%*3+84.72%",
        "6": "12.95%*3+90.59%",
        "7": "14.11%*3+98.76%",
        "8": "15.28%*3+106.93%",
        "9": "16.45%*3+115.09%",
        "10": "17.69%*3+123.77%",
      },
    },
    {
      key: "DodgeCounterPurgatoryScourgeDMG",
      label: "Dodge Counter - Purgatory Scourge DMG",
      type: "Heavy",
      talents: {
        "1": "16.15%*3+113.03%",
        "2": "17.47%*3+122.29%",
        "3": "18.80%*3+131.56%",
        "4": "20.65%*3+144.54%",
        "5": "21.98%*3+153.81%",
        "6": "23.50%*3+164.46%",
        "7": "25.62%*3+179.29%",
        "8": "27.74%*3+194.12%",
        "9": "29.85%*3+208.95%",
        "10": "32.10%*3+224.70%",
      },
    },
    {
      key: "MidairAttackHellsentBarragePlungingAttackDMG",
      label: "Mid-air Attack - Hellsent Barrage Plunging Attack DMG",
      type: "Heavy",
      talents: {
        "1": "80.00%",
        "2": "86.56%",
        "3": "93.12%",
        "4": "102.31%",
        "5": "108.87%",
        "6": "116.41%",
        "7": "126.91%",
        "8": "137.40%",
        "9": "147.90%",
        "10": "159.05%",
      },
    },
    {
      key: "MidairAttackHellsentBarrageSustainedFireDMG",
      label: "Mid-air Attack - Hellsent Barrage Sustained Fire DMG",
      type: "Heavy",
      talents: {
        "1": "15.00%",
        "2": "16.23%",
        "3": "17.46%",
        "4": "19.19%",
        "5": "20.42%",
        "6": "21.83%",
        "7": "23.80%",
        "8": "25.77%",
        "9": "27.74%",
        "10": "29.83%",
      },
    },
    {
      key: "ResonanceSkillRavageDMG",
      label: "Resonance Skill - Ravage DMG",
      type: "Heavy",
      talents: {
        "1": "5.40%+12.60%",
        "2": "5.85%+13.63%",
        "3": "6.29%+14.66%",
        "4": "6.91%+16.11%",
        "5": "7.35%+17.14%",
        "6": "7.86%+18.33%",
        "7": "8.57%+19.98%",
        "8": "9.28%+21.64%",
        "9": "9.98%+23.29%",
        "10": "10.74%+25.04%",
      },
    },
  ],
};
