export const basicAttacks = {
  name: "Normal Attack: Movement of Life and Death",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Basic Attack</span></span><br>Perform up to 3 consecutive attacks, dealing <span class="ingame-Dark">Havoc DMG</span>.<br>When performing <span class="ingame-Highlight">Basic Attack Stage 3</span>, enter <span class="ingame-Highlight">Reincarnate</span> state.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Heavy Attack</span></span><br>Consume STA to attack the target, dealing <span class="ingame-Dark">Havoc DMG</span>.<br>Press <span class="ingame-Highlight">Normal Attack</span> shortly after casting this skill to cast <span class="ingame-Highlight">Basic Attack Stage 2</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Scarlet Coda</span></span><br>When the following 3 conditions are met, <span class="ingame-Highlight">Heavy Attack</span> is replaced with <span class="ingame-Highlight">Scarlet Coda</span>.<br>- Has 6 <span class="ingame-Highlight">Volatile Notes</span>.<br>- In the <span class="ingame-Highlight">Compose</span> state.<br>- Not in the <span class="ingame-Highlight">Resolving Chord</span> state.<br><span class="ingame-Highlight">Scarlet Coda</span>: Consume STA to deal <span class="ingame-Dark">Havoc DMG</span>, Stagnating and pulling in nearby targets. This instance of damage is considered <span class="ingame-Highlight">Resonance Skill DMG</span>.<br>Each stack of <span class="ingame-Highlight">Aftersound</span> additionally increases the DMG Multiplier of this instance of damage.<br>Casting this skill is considered as casting <span class="ingame-Highlight">Echo Skill</span>.<br>After casting this skill, Phrolova enters <span class="ingame-Highlight">Resolving Chord</span> and ends <span class="ingame-Highlight">Compose</span> state.<br>Re-enter the <span class="ingame-Highlight">Compose</span> state after 25s.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Mid-air Attack</span></span><br>Consume STA to perform a Plunging Attack, dealing <span class="ingame-Dark">Havoc DMG</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Dodge Counter</span></span><br>Press <span class="ingame-Highlight">Normal Attack</span> after a successful <span class="ingame-Highlight">Dodge</span> to attack the target, dealing <span class="ingame-Dark">Havoc DMG</span>.<br>Press <span class="ingame-Highlight">Normal Attack</span> shortly after casting this skill to cast <span class="ingame-Highlight">Basic Attack Stage 3</span>.</div>`,
  attacks: [
    {
      key: "Stage1DMG",
      label: "Stage 1 DMG",
      talents: {
        "1": "26.88%*2",
        "2": "29.09%*2",
        "3": "31.29%*2",
        "4": "34.38%*2",
        "5": "36.58%*2",
        "6": "39.12%*2",
        "7": "42.64%*2",
        "8": "46.17%*2",
        "9": "49.70%*2",
        "10": "53.45%*2",
      },
      type: "Basic",
    },
    {
      key: "Stage2DMG",
      label: "Stage 2 DMG",
      talents: {
        "1": "48.00%",
        "2": "51.94%",
        "3": "55.88%",
        "4": "61.39%",
        "5": "65.32%",
        "6": "69.85%",
        "7": "76.15%",
        "8": "82.44%",
        "9": "88.74%",
        "10": "95.43%",
      },
      type: "Basic",
    },
    {
      key: "Stage3DMG",
      label: "Stage 3 DMG",
      talents: {
        "1": "16.44%*6",
        "2": "17.79%*6",
        "3": "19.14%*6",
        "4": "21.03%*6",
        "5": "22.38%*6",
        "6": "23.93%*6",
        "7": "26.08%*6",
        "8": "28.24%*6",
        "9": "30.40%*6",
        "10": "32.69%*6",
      },
      type: "Basic",
    },
    {
      key: "HeavyAttackDMG",
      label: "Heavy Attack DMG",
      talents: {
        "1": "40.16%*2",
        "2": "43.46%*2",
        "3": "46.75%*2",
        "4": "51.36%*2",
        "5": "54.65%*2",
        "6": "58.44%*2",
        "7": "63.71%*2",
        "8": "68.98%*2",
        "9": "74.25%*2",
        "10": "79.85%*2",
      },
      type: "Heavy",
    },
    {
      key: "ScarletCodaDMG",
      label: "Scarlet Coda DMG",
      talents: {
        "1": "16.61%*2+6.23%*8+249.03%",
        "2": "17.97%*2+6.74%*8+269.46%",
        "3": "19.33%*2+7.25%*8+289.88%",
        "4": "21.24%*2+7.97%*8+318.46%",
        "5": "22.60%*2+8.48%*8+338.89%",
        "6": "24.16%*2+9.06%*8+362.37%",
        "7": "26.34%*2+9.88%*8+395.04%",
        "8": "28.52%*2+10.70%*8+427.71%",
        "9": "30.70%*2+11.51%*8+460.39%",
        "10": "33.01%*2+12.38%*8+495.10%",
      },
      type: "Skill",
      subType: "Echo",
    },
    {
      key: "MidairAttackDMG",
      label: "Mid-air Attack DMG",
      talents: {
        "1": "64.00%",
        "2": "69.25%",
        "3": "74.50%",
        "4": "81.85%",
        "5": "87.10%",
        "6": "93.13%",
        "7": "101.53%",
        "8": "109.92%",
        "9": "118.32%",
        "10": "127.24%",
      },
      type: "Basic",
    },
    {
      key: "DodgeCounterDMG",
      label: "Dodge Counter DMG",
      talents: {
        "1": "61.36%",
        "2": "66.40%",
        "3": "71.43%",
        "4": "78.47%",
        "5": "83.50%",
        "6": "89.29%",
        "7": "97.34%",
        "8": "105.39%",
        "9": "113.44%",
        "10": "121.99%",
      },
      type: "Basic",
    },
  ],
};
