export const forteCircuitAttacks = {
  name: "Forte Circuit: Rhapsody of a New World",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Basic Attack - Movement of Fate and Finality</span></span><br>When in <span class="ingame-Highlight">Reincarnate</span>, press <span class="ingame-Highlight">Normal Attack</span> on the ground to cast <span class="ingame-Highlight">Movement of Fate and Finality</span>, which deals <span class="ingame-Dark">Havoc DMG</span> (considered <span class="ingame-Highlight">Resonance Skill DMG</span>), Stagnates the target, and ends <span class="ingame-Highlight">Reincarnate</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Resonance Skill - Murmurs in a Haunting Dream</span></span><br>When in <span class="ingame-Highlight">Reincarnate</span>, press <span class="ingame-Highlight">Resonance Skill</span> on the ground to cast <span class="ingame-Highlight">Murmurs in a Haunting Dream</span>, dealing <span class="ingame-Dark">Havoc DMG</span> (considered <span class="ingame-Highlight">Resonance Skill DMG</span>) and ending <span class="ingame-Highlight">Reincarnate</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Aftersound</span></span><br>Phrolova can hold up to 24 stacks of Aftersound.<br>When Phrolova is not on the field, casting <span class="ingame-Highlight">Enhanced Attack - Hecate: Strings</span>, <span class="ingame-Highlight">Enhanced Attack - Hecate: Winds</span>, and <span class="ingame-Highlight">Enhanced Attack - Hecate: Cadenza</span> grants 1 stack of Aftersound.<br>When Phrolova is not in the combat state for over 30s, remove all stacks of Aftersound.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Volatile Note</span></span><br>Phrolova can hold up to 6 <span class="ingame-Highlight">Volatile Notes</span>. When <span class="ingame-Highlight">Volatile Notes</span> reach the max number, gaining new <span class="ingame-Highlight">Volatile Notes</span> moves all <span class="ingame-Highlight">Volatile Notes</span> one slot to the left, and the leftmost <span class="ingame-Highlight">Volatile Note - Strings</span> and <span class="ingame-Highlight">Volatile Note - Winds</span> will be removed.<br>Hitting a target with <span class="ingame-Highlight">Basic Attack Stage 3</span> and <span class="ingame-Highlight">Movement of Fate and Finality</span> grants 1 <span class="ingame-Highlight">Volatile Note - Strings</span>.<br>Hitting a target with Resonance Skill <span class="ingame-Highlight">Whispers in a Fleeting Dream</span> and Resonance Skill <span class="ingame-Highlight">Murmurs in a Haunting Dream</span> grants 1 <span class="ingame-Highlight">Volatile Note - Winds</span>.<br>When <span class="ingame-Highlight">Inherent Skill - Accidental</span> is activated, casting Suite of Quietus, Suite of Immortality, and Echo Skill grants 1 <span class="ingame-Highlight">Volatile Note - Cadenza</span>.<br>Phrolova cannot obtain <span class="ingame-Highlight">Volatile Notes</span> during <span class="ingame-Highlight">Resolving Chord</span>.</div>`,
  attacks: [
    {
      key: "MovementOfFateAndFinalityDMG",
      label: "Movement of Fate and Finality DMG",
      talents: {
        "1": "19.05%*4+59.27%*3",
        "2": "20.62%*4+64.13%*3",
        "3": "22.18%*4+68.99%*3",
        "4": "24.37%*4+75.80%*3",
        "5": "25.93%*4+80.66%*3",
        "6": "27.72%*4+86.24%*3",
        "7": "30.22%*4+94.02%*3",
        "8": "32.72%*4+101.80%*3",
        "9": "35.22%*4+109.57%*3",
        "10": "37.88%*4+117.83%*3",
      },
      type: "Skill",
    },
    {
      key: "MurmursInAHauntingDreamDMG",
      label: "Murmurs in a Haunting Dream DMG",
      talents: {
        "1": "11.67%*4+23.34%+163.38%",
        "2": "12.63%*4+25.26%+176.78%",
        "3": "13.59%*4+27.17%+190.18%",
        "4": "14.93%*4+29.85%+208.94%",
        "5": "15.89%*4+31.77%+222.33%",
        "6": "16.99%*4+33.97%+237.74%",
        "7": "18.52%*4+37.03%+259.17%",
        "8": "20.05%*4+40.09%+280.61%",
        "9": "21.58%*4+43.15%+302.05%",
        "10": "23.21%*4+46.41%+324.82%",
      },
      type: "Skill",
    },
    {
      key: "ApparitionofBeyondHecate",
      label: "S6 Apparition of Beyond - Hecate",
      talents: {
        "1": "216.42%",
        "2": "216.42%",
        "3": "216.42%",
        "4": "216.42%",
        "5": "216.42%",
        "6": "216.42%",
        "7": "216.42%",
        "8": "216.42%",
        "9": "216.42%",
        "10": "216.42%",
      },
      type: "Skill",
      requiresResonanceChain: "SequenceNode6ANighttoDepartFromEternalRest",
    },
  ],
};
