export const liberationAttacks = {
  name: "Resonance Liberation: A Knight's Heartfelt Prayers",
  description: `<div><span class="ww-wiki-font-bold"><span class="ingame-Title">Waltz of Forsaken Depths</span></span><br>Phrolova's max Resonance Energy is 0. <span class="ingame-Highlight">Waltz of Forsaken Depths</span> does not consume Resonance Energy.<br>When in the <span class="ingame-Highlight">Resolving Chord</span> state, <span class="ingame-Highlight">Waltz of Forsaken Depths</span> becomes available.<br>Casting this skill ends the <span class="ingame-Highlight">Resolving Chord</span> state, and Phrolova enters the <span class="ingame-Highlight">Maestro State</span> for 24s.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Maestro State</span></span><br>Gain 120% ATK increase.<br>Phrolova floats in the air and commands Hecate to attack. Hecate shares Phrolova's attributes, and Hecate's attacks will not remove the target's Hazy Dream state.<br>During this period, Phrolova plays the <span class="ingame-Highlight">Volatile Notes</span> in the order of acquisition, each <span class="ingame-Highlight">Volatile Note</span> sustains for 4s.<br>If Phrolova is the active Resonator on the field, she can give the following cues to Hectate. Any damage taken by Hectate in this state affects Phrolova as well.<br>- <span class="ingame-Highlight">Cue - Basic Attack</span>: Press Normal Attack to command Hecate to cast <span class="ingame-Highlight">Basic Attack - Hecate</span>. When Phrolova is the active Resonator on the field, every 2 times Hectate casts <span class="ingame-Highlight">Basic Attack - Hecate</span>, the next <span class="ingame-Highlight">Basic Attack - Hecate</span> is replaced with <span class="ingame-Highlight">Enhanced Attack - Hectate</span>.<br>- <span class="ingame-Highlight">Cue - Dodge</span>: Press Dodge to command Hecate to dodge an attack. Hecate takes no damage from a hit successfully Dodged.<br>- <span class="ingame-Highlight">Cue - Reset</span>: Press Jump to command Hecate to return to her starting position.<br>- <span class="ingame-Highlight">Cue - Curtain Call</span>: Press Resonance Liberation to command Hecate to cast <span class="ingame-Highlight">Curtain Call - Hectate</span> and end the <span class="ingame-Highlight">Maestro State</span>.<br>When Phrolova is not the active Resonator, Hecate takes no damage and automatically casts <span class="ingame-Highlight">Basic Attack - Hecate</span> to attack the target. When Resonators in the team cast Echo Skill, Hecate casts <span class="ingame-Highlight">Enhanced Attack - Hecate</span> to attack the target.<br>During Phrolova's <span class="ingame-Highlight">Maestro State</span>, Echoes of the same name can trigger this effect up to 1 time , up to 10 times in total.<br>Switching back to Phrolova ends <span class="ingame-Highlight">Maestro State</span>.<br>Ending <span class="ingame-Highlight">Maestro State</span> removes all <span class="ingame-Highlight">Volatile Notes</span>.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Basic Attack - Hecate</span></span><br>Perform up to 2 consecutive attacks, dealing <span class="ingame-Dark">Havoc DMG</span> (considered <span class="ingame-Highlight">Echo Skill DMG</span>).<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Enhanced Attack - Hecate: Strings</span></span><br>When Phrolova performs <span class="ingame-Highlight">Volatile Note - Strings</span>, Hecate casts <span class="ingame-Highlight">Enhanced Attack - Hectate: Strings</span> when casting <span class="ingame-Highlight">Enhanced Attack - Hectate</span>, dealing <span class="ingame-Dark">Havoc DMG</span> and Stagnating the targets (considered <span class="ingame-Highlight">Echo Skill DMG</span>).<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Enhanced Attack - Hecate: Winds</span></span><br>When Phrolova performs <span class="ingame-Highlight">Volatile Note - Winds</span>, Hecate casts <span class="ingame-Highlight">Enhanced Attack - Hectate: Winds</span> when casting <span class="ingame-Highlight">Enhanced Attack - Hectate</span>, dealing <span class="ingame-Dark">Havoc DMG</span>, pulling the targets in (considered <span class="ingame-Highlight">Echo Skill DMG</span>).<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Enhanced Attack - Hecate: Cadenza</span></span><br>When Phrolova performs <span class="ingame-Highlight">Volatile Note - Cadenza</span>, Hecate casts <span class="ingame-Highlight">Enhanced Attack - Hectate: Cadenza</span> when casting <span class="ingame-Highlight">Enhanced Attack - Hectate</span>, dealing <span class="ingame-Dark">Havoc DMG</span>, Stagnating and pulling the targets in (considered <span class="ingame-Highlight">Echo Skill DMG</span>).<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Curtain Call - Hecate</span></span><br><span class="ingame-Highlight">Curtain Call</span> can be cast via the following 4 ways, Stagnating the targets and dealing <span class="ingame-Dark">Havoc DMG</span>.<br>- When Phrolova is the active Resonator on the field, end the <span class="ingame-Highlight">Maestro State</span>.<br>- When Phrolova is in the <span class="ingame-Highlight">Maestro State</span>, switch to Phrolova without casting Intro Skill.<br>- When Phrolova is not the active Resonator and the <span class="ingame-Highlight">Maestro State</span> ends, switch to Phrolova without casting Intro Skill.<br>- When Phrolova is in the <span class="ingame-Highlight">Resolving Chord</span> state, hold Resonance Liberation.<br>When in <span class="ingame-Highlight">Resolving Chord</span> state, casting <span class="ingame-Highlight">Curtain Call</span> removes all <span class="ingame-Highlight">Volatile Notes</span> and ends the <span class="ingame-Highlight">Resolving Chord</span> state.</div>`,
  attacks: [
    {
      key: "BasicAttackHecateStage1DMG",
      label: "Basic Attack - Hecate Stage 1 DMG",
      talents: {
        "1": "14.00%",
        "2": "15.15%",
        "3": "16.30%",
        "4": "17.91%",
        "5": "19.06%",
        "6": "20.38%",
        "7": "22.21%",
        "8": "24.05%",
        "9": "25.89%",
        "10": "27.84%",
      },
      type: "Echo",
    },
    {
      key: "BasicAttackHecateStage2DMG",
      label: "Basic Attack - Hecate Stage 2 DMG",
      talents: {
        "1": "7.00%*2",
        "2": "7.58%*2",
        "3": "8.15%*2",
        "4": "8.96%*2",
        "5": "9.53%*2",
        "6": "10.19%*2",
        "7": "11.11%*2",
        "8": "12.03%*2",
        "9": "12.95%*2",
        "10": "13.92%*2",
      },
      type: "Echo",
    },
    {
      key: "EnhancedAttackHecateStringsDMG",
      label: "Enhanced Attack - Hecate: Strings DMG",
      talents: {
        "1": "52.50%+122.50%",
        "2": "56.81%+132.55%",
        "3": "61.11%+142.59%",
        "4": "67.14%+156.66%",
        "5": "71.45%+166.70%",
        "6": "76.40%+178.25%",
        "7": "83.29%+194.33%",
        "8": "90.17%+210.40%",
        "9": "97.06%+226.47%",
        "10": "104.38%+243.55%",
      },
      type: "Echo",
    },
    {
      key: "EnhancedAttackHecateWindsDMG",
      label: "Enhanced Attack - Hecate: Winds DMG",
      talents: {
        "1": "49.88%+116.38%",
        "2": "53.97%+125.92%",
        "3": "58.06%+135.47%",
        "4": "63.79%+148.83%",
        "5": "67.87%+158.37%",
        "6": "72.58%+169.34%",
        "7": "79.12%+184.61%",
        "8": "85.67%+199.88%",
        "9": "92.21%+215.15%",
        "10": "99.16%+231.37%",
      },
      type: "Echo",
    },
    {
      key: "EnhancedAttackHecateCadenzaDMG",
      label: "Enhanced Attack - Hecate: Cadenza DMG",
      talents: {
        "1": "52.50%+122.50%",
        "2": "56.81%+132.55%",
        "3": "61.11%+142.59%",
        "4": "67.14%+156.66%",
        "5": "71.45%+166.70%",
        "6": "76.40%+178.25%",
        "7": "83.29%+194.33%",
        "8": "90.17%+210.40%",
        "9": "97.06%+226.47%",
        "10": "104.38%+243.55%",
      },
      type: "Echo",
    },
    {
      key: "CurtainCallHecateDMG",
      label: "Curtain Call - Hecate DMG",
      talents: {
        "1": "234.00%",
        "2": "253.19%",
        "3": "272.38%",
        "4": "299.24%",
        "5": "318.43%",
        "6": "340.50%",
        "7": "371.20%",
        "8": "401.90%",
        "9": "432.60%",
        "10": "465.22%",
      },
      type: "Liberation",
    },
  ],
};
