export const rotations: RotationPreset[] = [
  {
    name: `Standard Rotation`,
    description: `From Prydwen`,
    author: `lavasnake`,
    data: {
      name: "Standard Rotation",
      description: "From Prydwen",
      actions: [
        {
          order: 1,
          key: "SuiteofQuietusDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "Stage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "MovementOfFateAndFinalityDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "WhispersinaFleetingDreamDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "MovementOfFateAndFinalityDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "NightmareHecateSmashDMG",
          type: "echoAttacks",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
          mainEcho: "NightmareHecate",
          mainEchoRank: 5,
        },
        {
          order: 7,
          key: "Stage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "Stage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "Stage3DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "MovementOfFateAndFinalityDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "ScarletCodaDMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "EnhancedAttackHecateCadenzaDMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 13,
          key: "BasicAttackHecateStage1DMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 14,
          key: "BasicAttackHecateStage2DMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 15,
          key: "EnhancedAttackHecateStringsDMG",
          type: "liberation",
          count: "4",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 16,
          key: "BasicAttackHecateStage1DMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 17,
          key: "BasicAttackHecateStage2DMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 18,
          key: "EnhancedAttackHecateStringsDMG",
          type: "liberation",
          count: "2",
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
      echo: "NightmareHecate",
    },
  },
];

export const echoes = [
  {
    name: `Standard Build`,
    description: `43311 CD Dream of the Lost + Havoc Eclipse build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 15.2% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "NightmareHecate",
          echoSet: "DreamoftheLost",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "ResonanceSkillDMGBonus",
          echoSubStatsValue5: 8.6,
          stat: "CritDMG",
        },
        "1": {
          type: 3,
          echo: "NightmareTambourinist",
          echoSet: "DreamoftheLost",
          stat: "Havoc",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "ResonanceSkillDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "2": {
          type: 3,
          echo: "Tambourinist",
          echoSet: "SunSinkingEclipse",
          stat: "Havoc",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 7.6,
          echoSubStatsType4: "DEF",
          echoSubStatsValue4: 10.9,
          echoSubStatsType5: "HP",
          echoSubStatsValue5: 8.6,
        },
        "3": {
          type: 1,
          echo: "NightmareHavocWarrior",
          echoSet: "DreamoftheLost",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 7.6,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "HavocWarrior",
          echoSet: "SunSinkingEclipse",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "HP_FLAT",
          echoSubStatsValue3: 430,
          echoSubStatsType4: "DEF",
          echoSubStatsValue4: 10.9,
          echoSubStatsType5: "DEF_FLAT",
          echoSubStatsValue5: 60,
        },
      },
    },
  },
];
