export const rotations: RotationPreset[] = [];

export const echoes = [
  {
    name: `Standard Build`,
    description: `43311 CD Dream of the Lost + Havoc Eclipse build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Skill, 100 ATK, 15.2% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "NightmareHecate",
          echoSet: "DreamoftheLost",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "ResonanceSkillDMGBonus",
          echoSubStatsValue5: 8.6,
          stat: "CritDMG",
        },
        "1": {
          type: 3,
          echo: "NightmareTambourinist",
          echoSet: "DreamoftheLost",
          stat: "Havoc",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "ResonanceSkillDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "2": {
          type: 3,
          echo: "Tambourinist",
          echoSet: "SunSinkingEclipse",
          stat: "Havoc",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 7.6,
          echoSubStatsType4: "DEF",
          echoSubStatsValue4: 10.9,
          echoSubStatsType5: "HP",
          echoSubStatsValue5: 8.6,
        },
        "3": {
          type: 1,
          echo: "NightmareHavocWarrior",
          echoSet: "DreamoftheLost",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 7.6,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "HavocWarrior",
          echoSet: "SunSinkingEclipse",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "HP_FLAT",
          echoSubStatsValue3: 430,
          echoSubStatsType4: "DEF",
          echoSubStatsValue4: 10.9,
          echoSubStatsType5: "DEF_FLAT",
          echoSubStatsValue5: 60,
        },
      },
    },
  },
];
