export const rotations: RotationPreset[] = [
  {
    name: `Qiuyun Prydwen Rotation`,
    description: `Qiuyuan Prydwen Rotation`,
    author: `Kashi`,
    data: {
      name: "Qiuyun Prydwen Rotation",
      description: "",
      actions: [
        {
          order: 1,
          key: "AttacktheMustDefendDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 2,
          key: "ThusSpoketheBladeInkwashStage3DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 3,
          key: "ThusSpoketheBladeInkwashStage4DMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "SunderingStrikeDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "ThusSpoketheBladeToTeachDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "ThusSpoketheBladeToSaveDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "ThusSpoketheBladeToSacrificeDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "ThroughtheGrovesDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "StrikeBeforeReadyDMG",
          type: "outro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
      echo: "FeilianBeringal",
    },
  },
];

export const echoes = [
  {
    name: `Standard Build (CR)`,
    description: `43311 CR Law of Harmony + Sierra Gale. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 27.6% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "ReminiscenceFenrico",
          echoSet: "LawofHarmony",
          stat: "CritRate",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "HeavyAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "1": {
          type: 3,
          echo: "NightmareCyanFeatheredHeron",
          echoSet: "LawofHarmony",
          stat: "Aero",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "HeavyAttackDMGBonus",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "ATK_FLAT",
          echoSubStatsValue5: 50,
        },
        "2": {
          type: 1,
          echo: "GoldenJunrock",
          echoSet: "LawofHarmony",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "3": {
          type: 3,
          echo: "Hoochief",
          echoSet: "SierraGale",
          stat: "Aero",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "DwarfCassowary",
          echoSet: "SierraGale",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
      },
    },
  },
  {
    name: `Standard Build (CD)`,
    description: `43311 CD Law of Harmony + Sierra Gale. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 27.6% ER`,
    author: `lavasnake`,
    data: {
      echoes: {
        "0": {
          type: 4,
          echo: "ReminiscenceFenrico",
          echoSet: "LawofHarmony",
          stat: "CritDMG",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "ATK_FLAT",
          echoSubStatsValue4: 50,
          echoSubStatsType5: "HeavyAttackDMGBonus",
          echoSubStatsValue5: 8.6,
        },
        "1": {
          type: 3,
          echo: "NightmareCyanFeatheredHeron",
          echoSet: "LawofHarmony",
          stat: "Aero",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "ATK",
          echoSubStatsValue3: 8.6,
          echoSubStatsType4: "HeavyAttackDMGBonus",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "ATK_FLAT",
          echoSubStatsValue5: 50,
        },
        "2": {
          type: 1,
          echo: "GoldenJunrock",
          echoSet: "LawofHarmony",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "3": {
          type: 3,
          echo: "Hoochief",
          echoSet: "SierraGale",
          stat: "Aero",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
        "4": {
          type: 1,
          echo: "DwarfCassowary",
          echoSet: "SierraGale",
          stat: "ATK",
          echoSubStatsType1: "CritRate",
          echoSubStatsValue1: 8.1,
          echoSubStatsType2: "CritDMG",
          echoSubStatsValue2: 16.2,
          echoSubStatsType3: "EnergyRegen",
          echoSubStatsValue3: 9.2,
          echoSubStatsType4: "HP",
          echoSubStatsValue4: 8.6,
          echoSubStatsType5: "DEF",
          echoSubStatsValue5: 10.9,
        },
      },
    },
  },
];
