export const skillAttacks = {
  name: "Resonance Skill: Through the Groves",
  description: `<div>Press <span class="ingame-Highlight">Resonance Skill</span> to dash forward for a distance, dealing <span class="ingame-Wind">Aero DMG</span>, considered as Echo Skill DMG. If Resonance Skill is cast upon being attacked by an enemy target, Qiuyuan slows down nearby enemies and takes 100% less DMG while gaining immunity to interruptions during the action.<br>Switching to other Resonators removes the slowdown effect from enemies.<br><span class="ww-wiki-font-bold"></span><br><span class="ww-wiki-font-bold"><span class="ingame-Title">Undaunted Wayfarer</span></span><br>Hold <span class="ingame-Highlight">Resonance Skill</span> to dash forward for a distance at the cost of STA, dealing <span class="ingame-Wind">Aero DMG</span> to the target, considered as Echo Skill DMG.<br>If there are no targets nearby, Qiuyuan will leap up and dash through the air by continuously consuming STA until it runs out. Release <span class="ingame-Highlight">Resonance Skill</span> to immediately end the dash and land. If there are targets nearby when Qiuyuan lands, deal <span class="ingame-Wind">Aero DMG</span> to nearby targets, considered as Echo Skill DMG. This skill can be cast in mid-air.</div>`,
  attacks: [
    {
      key: "ThroughtheGrovesDMG",
      label: "Through the Groves DMG",
      type: "Echo",
      talents: {
        "1": "36.14%*3",
        "2": "39.10%*3",
        "3": "42.06%*3",
        "4": "46.21%*3",
        "5": "49.18%*3",
        "6": "52.58%*3",
        "7": "57.32%*3",
        "8": "62.06%*3",
        "9": "66.80%*3",
        "10": "71.84%*3",
      },
    },
    {
      key: "Undaunted ayfarerDMG",
      label: "Undaunted Wayfarer DMG",
      type: "Echo",
      talents: {
        "1": "16.26%+16.26%*3+43.36%",
        "2": "17.60%+17.60%*3+46.92%",
        "3": "18.93%+18.93%*3+50.48%",
        "4": "20.80%+20.80%*3+55.45%",
        "5": "22.13%+22.13%*3+59.01%",
        "6": "23.66%+23.66%*3+63.10%",
        "7": "25.80%+25.80%*3+68.79%",
        "8": "27.93%+27.93%*3+74.48%",
        "9": "30.06%+30.06%*3+80.16%",
        "10": "32.33%+32.33%*3+86.21%",
      },
    },
    {
      key: "SequenceNode3OBladeIWhoSaveNoMore",
      label: "S3 Quietude Within DMG",
      talents: {
        "1": "500%",
        "2": "500%",
        "3": "500%",
        "4": "500%",
        "5": "500%",
        "6": "500%",
        "7": "500%",
        "8": "500%",
        "9": "500%",
        "10": "500%",
      },
      type: "Echo",
      requiresResonanceChain: "SequenceNode3OBladeIWhoSaveNoMore",
    },
  ],
};
