export const forteCircuitAttacks = {
  description: `<div><span class="Title"><strong>Seraphic Duo</strong></span><br>When casting <span class="Highlight"><strong>Basic Attack - Aemeath Stage 4</strong></span> or <span class="Highlight"><strong>Basic Attack - Mech Stage 4</strong></span>, enter <span class="Highlight"><strong>Seraphic Duo</strong></span> for 5s. <br><br><span class="Title"><strong>Resonance Skill - Seraphic Duet: Overture</strong></span><br>When Aemeath is in <span class="Highlight"><strong>Seraphic Duo</strong></span> and the <span class="Highlight"><strong>Synchronization Rate</strong></span> is no less than 100 points, press <span class="Highlight"><strong>Resonance Skill</strong></span> to cast Resonance Skill <span class="Highlight"><strong>Seraphic Duet: Overture</strong></span> at the cost of 100 points of <span class="Highlight"><strong>Synchronization Rate</strong></span>, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>, considered <span class="Highlight"><strong>Resonance Liberation DMG</strong></span>.<br>Can be cast in mid-air.<br>Switch into the Mech form after casting this skill and exit <span class="Highlight"><strong>Seraphic Duo</strong></span>. Press <span class="Highlight"><strong>Normal Attack</strong></span> within a certain period of time to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 2</strong></span>.<br><br><span class="Title"><strong>Resonance Skill - Seraphic Duet: Encore</strong></span><br>In the Mech form, when in <span class="Highlight"><strong>Seraphic Duo</strong></span> and the <span class="Highlight"><strong>Synchronization Rate</strong></span> is no less than 100 points, press <span class="Highlight"><strong>Resonance Skill</strong></span> to cast Resonance Skill <span class="Highlight"><strong>Seraphic Duet: Encore</strong></span> at the cost of 100 points of <span class="Highlight"><strong>Synchronization Rate</strong></span>, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>, considered <span class="Highlight"><strong>Resonance Liberation DMG</strong></span>.<br>Can be cast in mid-air.<br>Switch back to Aemeath and exit the <span class="Highlight"><strong>Seraphic Duo</strong></span> state. Press <span class="Highlight"><strong>Normal Attack</strong></span> shortly afterward to cast <span class="Highlight"><strong>Basic Attack - Aemeath Stage 2</strong></span>.<br><br><span class="Title"><strong>Resonance Mode</strong></span><br>- In <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>, when Resonators in the team respond to <span class="Highlight"><strong>Tune Rupture - Interfered</strong></span>, inflict 10 stacks of <span class="Highlight"><strong>Rupturous Trail</strong></span> on the target for 30s, stacking up to 30 times.<br><br>- In <span class="Highlight"><strong>Resonance Mode - Fusion Burst</strong></span>, when Resonators in the team inflict <span class="Highlight"><strong>Fusion Burst</strong></span>, inflict 1 stack of <span class="Highlight"><strong>Fusion Trail</strong></span> for 30s, stacking up to 30 times.<br>While in combat, when the <span class="Highlight"><strong>Fusion Burst</strong></span> on targets near the active Resonator reaches 0 stacks, inflict 1 stack of <span class="Highlight"><strong>Fusion Burst</strong></span>. If the targets have more than 5 stacks of <span class="Highlight"><strong>Fusion Burst</strong></span>, trigger <span class="Highlight"><strong>Fusion Burst</strong></span> based on their max stack limit and remove all of their stacks.<br><br>In <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>/<span class="Highlight"><strong>Resonance Mode - Fusion Burst</strong></span>, inflict <span class="Highlight"><strong>Tune Rupture - Shifting</strong></span>/<span class="Highlight"><strong>Fusion Burst</strong></span> when the following skills deal damage. The same skill can only trigger this effect on the same target once every 3s:<br><span class="Highlight"><strong>Basic Attack - Aemeath Stage 3 &amp; 4</strong></span>, <span class="Highlight"><strong>Basic Attack - Mech Stage 3 &amp; 4</strong></span>, Resonance Skill <span class="Highlight"><strong>Sync Strike: Armament Merge</strong></span>, Resonance Skill <span class="Highlight"><strong>Sync Strike: Call of Dawn</strong></span>, Intro Skill <span class="Highlight"><strong>Songs Across the Universe</strong></span>, and Intro Skill <span class="Highlight"><strong>Debut of Meteoric Radiance</strong></span>.<br><br>Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> gains the following enhancements based on Aemeath's <span class="Highlight"><strong>Resonance Mode</strong></span>:<br>- In <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>, casting Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> additionally deals 5 instances of <span class="Highlight"><strong>Tune Rupture DMG</strong></span>, with each instance dealt to a random target within range. The target's <span class="Highlight"><strong>Off-Tune Level</strong></span> does not affect these instances of Tune Rupture DMG. When <span class="Highlight"><strong>Seraphic Duet</strong></span> deals damage, remove the target's <span class="Highlight"><strong>Rupturous Trail</strong></span> and increase the DMG Multiplier of Tune Rupture based on the number of stacks removed, each stack increasing the DMG Multiplier by 4% for 2.5s.<br>- In <span class="Highlight"><strong>Resonance Mode - Fusion Burst</strong></span>, when Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> hits the target, if they are inflicted with <span class="Highlight"><strong>Fusion Trail</strong></span>, remove the <span class="Highlight"><strong>Fusion Trail</strong></span> stacks, and trigger the <span class="Highlight"><strong>Fusion Burst</strong></span> on the target based on its max stack limit without removing its stacks. Each stack of <span class="Highlight"><strong>Fusion Trail</strong></span> removed increases the DMG Multiplier of <span class="Highlight"><strong>Fusion Burst</strong></span> on the main target by 10%.<br><br>When in <span class="Highlight"><strong>Stardust Resonance</strong></span>, Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> gains the following enhancements based on Aemeath's <span class="Highlight"><strong>Resonance Mode</strong></span>:<br>- In <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>, casting Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> additionally deal 10 instances of <span class="Highlight"><strong>Tune Rupture DMG</strong></span>.<br>- In <span class="Highlight"><strong>Resonance Mode - Fusion Burst</strong></span>, the DMG Multiplier of <span class="Highlight"><strong>Fusion Burst</strong></span> triggered by Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> on the main target is additionally increased by 200%. The DMG Multiplier increase effect is stackable with that provided by <span class="Highlight"><strong>Fusion Trail</strong></span>.<br><br><span class="Title"><strong>Tune Rupture Response - Starburst</strong></span><br>Active in <span class="Highlight"><strong>Resonance Mode - Tune Rupture</strong></span>. Deal <span class="Fusion"><strong>Fusion DMG</strong></span> to targets within range that are affected by<span class="Highlight"><strong>Tune Rupture - Interfered</strong></span>, considered Tune Rupture DMG.<br><br><span class="Title"><strong>Starflux Thrust</strong></span><br>When in the Mech form and <span class="Highlight"><strong>Starflux</strong></span> is more than 200, use the Utility button to cast <span class="Highlight"><strong>Starflux Thrust</strong></span> and soar in the air by continuously consuming <span class="Highlight"><strong>Starflux</strong></span>.<br><br><span class="Title"><strong>Synchronization Rate</strong></span><br><span class="Highlight"><strong>Synchronization Rate</strong></span> is capped at 200 points.<br>- Dealing damage with <span class="Highlight"><strong>Basic Attack - Aemeath</strong></span>, <span class="Highlight"><strong>Mid-air Attack - Aemeath</strong></span>, <span class="Highlight"><strong>Dodge Counter - Aemeath</strong></span>, <span class="Highlight"><strong>Basic Attack - Mech</strong></span>, <span class="Highlight"><strong>Mid-air Attack - Mech</strong></span>, <span class="Highlight"><strong>Dodge Counter - Mech</strong></span>, Resonance Skill <span class="Highlight"><strong>Sync Strike: Armament Merge</strong></span>, and Resonance Skill <span class="Highlight"><strong>Sync Strike: Call of Dawn</strong></span> recovers <span class="Highlight"><strong>Synchronization Rate</strong></span>.<br>- Casting Intro Skill <span class="Highlight"><strong>Songs Across the Universe</strong></span> and <span class="Highlight"><strong>Debut of Meteoric Radiance</strong></span> recovers 40 points of <span class="Highlight"><strong>Synchronization Rate</strong></span>.<br>- Casting Resonance Liberation <span class="Highlight"><strong>Heavenfall Edict: Overdrive</strong></span> recovers 30 points of <span class="Highlight"><strong>Synchronization Rate</strong></span>.<br>- When in <span class="Highlight"><strong>Instant Response</strong></span> and <span class="Highlight"><strong>Heavenfall Edict: Unbound</strong></span> at the same time, casting <span class="Highlight"><strong>Heavy Attack - Aemeath Charged II</strong></span> or <span class="Highlight"><strong>Heavy Attack - Mech Charged II</strong></span> recovers 200 points of <span class="Highlight"><strong>Synchronization Rate</strong></span>.<br><br><span class="Title"><strong>Resonance Rate</strong></span><br><span class="Highlight"><strong>Resonance Rate</strong></span> is capped at 4 points.<br>- Casting Resonance Skill <span class="Highlight"><strong>Seraphic Duet</strong></span> recovers 1 points of <span class="Highlight"><strong>Resonance Rate</strong></span>.<br>- Casting Resonance Liberation <span class="Highlight"><strong>Heavenfall Edict: Overdrive</strong></span> recovers 1 points of <span class="Highlight"><strong>Resonance Rate</strong></span>.<br>- When in <span class="Highlight"><strong>Starlume Acceleration</strong></span>, casting Resonance Liberation <span class="Highlight"><strong>Heavenfall Edict: Overdrive</strong></span> additionally recovers 1 points of <span class="Highlight"><strong>Resonance Rate</strong></span>.<br><br><span class="Title"><strong>Starflux</strong></span><br><span class="Highlight"><strong>Starflux</strong></span> is capped at 600 points.<br><span class="Highlight"><strong>Starflux</strong></span> recovers naturally over time.<br>When in combat, <span class="Highlight"><strong>Starflux</strong></span> recovers at a slower rate.</div>`,
  name: "Forte Circuit: To Sculpt the Silence",
  attacks: [
    {
      key: "SeraphicDuetEncoreDMG",
      label: "Seraphic Duet: Encore DMG",
      type: "Liberation",
      talents: {
        "1": "9.00%*4+18.00%*3+90.00%",
        "2": "9.74%*4+19.48%*3+97.38%",
        "3": "10.48%*4+20.96%*3+104.76%",
        "4": "11.51%*4+23.02%*3+115.10%",
        "5": "12.25%*4+24.50%*3+122.48%",
        "6": "13.10%*4+26.20%*3+130.96%",
        "7": "14.28%*4+28.56%*3+142.77%",
        "8": "15.46%*4+30.92%*3+154.58%",
        "9": "16.64%*4+33.28%*3+166.39%",
        "10": "17.90%*4+35.79%*3+178.93%",
      },
    },
    {
      key: "SeraphicDuetOvertureDMG",
      label: "Seraphic Duet: Overture DMG",
      type: "Liberation",
      talents: {
        "1": "9.00%+7.50%*6+12.00%*3+30.00%*3",
        "2": "9.74%+8.12%*6+12.99%*3+32.46%*3",
        "3": "10.48%+8.73%*6+13.97%*3+34.92%*3",
        "4": "11.51%+9.60%*6+15.35%*3+38.37%*3",
        "5": "12.25%+10.21%*6+16.33%*3+40.83%*3",
        "6": "13.10%+10.92%*6+17.47%*3+43.66%*3",
        "7": "14.28%+11.90%*6+19.04%*3+47.59%*3",
        "8": "15.46%+12.89%*6+20.61%*3+51.53%*3",
        "9": "16.64%+13.87%*6+22.19%*3+55.47%*3",
        "10": "17.90%+14.92%*6+23.86%*3+59.65%*3",
      },
    },
    {
      key: "TuneRuptureResponseStarburstDMG",
      label: "Tune Rupture Response - Starburst DMG",
      type: "TuneBreak",
      talents: {
        "1": "300.00%",
        "2": "324.60%",
        "3": "349.20%",
        "4": "383.64%",
        "5": "408.24%",
        "6": "436.53%",
        "7": "475.89%",
        "8": "515.25%",
        "9": "554.61%",
        "10": "596.43%",
      },
    },
    {
      key: "SeraphicDuetBonusDMGPerInstance",
      label: "Seraphic Duet Bonus DMG",
      type: "TuneBreak",
      talents: {
        "1": "55.00%",
        "2": "59.51%",
        "3": "64.02%",
        "4": "70.34%",
        "5": "74.85%",
        "6": "80.04%",
        "7": "87.25%",
        "8": "94.47%",
        "9": "101.68%",
        "10": "109.35%",
      },
    },
  ],
};
