export const skillAttacks = {
  name: "Resonance Skill: Shared Voyage",
  description: `<div><span class="Title"><strong>Form Switch</strong></span><br>Aemeath can switch forms between herself and her Mech. The Mech inherits Aemeath's Stats and unlocks new moves.<br>Aemeath automatically casts <span class="Highlight"><strong>Basic Attack - Stage 1</strong></span> upon casting <span class="Highlight"><strong>Form Switch</strong></span>.<br>While in the Mech form, Aemeath casts <span class="Highlight"><strong>Mid-air Attack</strong></span> automatically upon casting <span class="Highlight"><strong>Form Switch</strong></span> in mid-air.<br><br><span class="Title"><strong>Sync Strike: Armament Merge</strong></span><br>Press <span class="Highlight"><strong>Resonance Skill</strong></span> shortly after casting <span class="Highlight"><strong>Basic Attack - Aemeath Stage 2, 3 &amp; 4</strong></span>, <span class="Highlight"><strong>Heavy Attack - Aemeath</strong></span>, or <span class="Highlight"><strong>Dodge Counter - Aemeath</strong></span> to cast <span class="Highlight"><strong>Sync Strike: Armament Merge</strong></span>, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Switch into the Mech form after casting this skill. Press the <span class="Highlight"><strong>Normal Attack</strong></span> button shortly after to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 2</strong></span>.<br><br><span class="Title"><strong>Sync Strike: Call of Dawn</strong></span><br>Press <span class="Highlight"><strong>Resonance Skill</strong></span> shortly after casting <span class="Highlight"><strong>Basic Attack - Mech Stage 2, 3 &amp; 4</strong></span>, <span class="Highlight"><strong>Heavy Attack - Mech</strong></span>, or <span class="Highlight"><strong>Dodge Counter - Mech</strong></span> to cast <span class="Highlight"><strong>Sync Strike: Call of Dawn</strong></span>, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Can be cast in mid-air.<br>Switch into Aemeath after casting this skill. Press the <span class="Highlight"><strong>Normal Attack</strong></span> button to cast <span class="Highlight"><strong>Basic Attack - Aemeath Stage 2</strong></span>.<br><br><span class="Title"><strong>Basic Attack - Mech</strong></span><br>Perform up to 4 consecutive attacks, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Can be cast in mid-air close to the ground.<br><br><span class="Title"><strong>Heavy Attack - Mech</strong></span><br>Hold the <span class="Highlight"><strong>Normal Attack</strong></span> button to charge by consuming STA, release to cast <span class="Highlight"><strong>Heavy Attack - Mech: Charged I</strong></span> to attack the target, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Hold the <span class="Highlight"><strong>Normal Attack</strong></span> button longer to cast <span class="Highlight"><strong>Heavy Attack - Mech: Charged II</strong></span>, dealing higher <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>When in <span class="Highlight"><strong>Instant Response</strong></span>, <span class="Highlight"><strong>Heavy Attack - Mech: Charged II</strong></span> charges more quickly. Casting <span class="Highlight"><strong>Heavy Attack - Aemeath: Charged II</strong></span>, <span class="Highlight"><strong>Heavy Attack - Mech: Charged II</strong></span>, or Resonance Liberation <span class="Highlight"><strong>Heavenfall Edict: Finale</strong></span> ends <span class="Highlight"><strong>Instant Response</strong></span>.<br>This Skill DMG is considered <span class="Highlight"><strong>Resonance Liberation DMG</strong></span>.<br>Can be cast in mid-air close to the ground.<br>Press <span class="Highlight"><strong>Normal Attack</strong></span> shortly after casting <span class="Highlight"><strong>Heavy Attack - Mech: Charged I</strong></span> to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 2</strong></span>.<br>Press <span class="Highlight"><strong>Normal Attack</strong></span> shortly after casting <span class="Highlight"><strong>Heavy Attack - Mech: Charged II</strong></span> to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 3</strong></span>.<br><br><span class="Title"><strong>Mid-air Attack - Mech</strong></span><br>Consume STA to perform Plunging Attack, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Press the <span class="Highlight"><strong>Normal Attack</strong></span> button shortly after casting this skill to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 2</strong></span>.<br><br><span class="Title"><strong>Dodge Counter - Mech</strong></span><br>Press the <span class="Highlight"><strong>Normal Attack</strong></span> button shortly after a successful Dodge to attack the target, dealing <span class="Fusion"><strong>Fusion DMG</strong></span>.<br>Press the <span class="Highlight"><strong>Normal Attack</strong></span> button shortly after casting this skill to cast <span class="Highlight"><strong>Basic Attack - Mech Stage 4</strong></span>.<br>Can be cast in mid-air close to the ground</div>`,
  attacks: [
    {
      key: "SyncStrikeArmamentMergeDMG",
      label: "Sync Strike: Armament Merge DMG",
      type: "Basic",
      talents: {
        "1": "13.54%+20.31%+33.85%",
        "2": "14.65%+21.98%+36.63%",
        "3": "15.76%+23.64%+39.40%",
        "4": "17.32%+25.97%+43.29%",
        "5": "18.43%+27.64%+46.06%",
        "6": "19.70%+29.55%+49.25%",
        "7": "21.48%+32.22%+53.69%",
        "8": "23.26%+34.88%+58.13%",
        "9": "25.03%+37.55%+62.57%",
        "10": "26.92%+40.38%+67.29%",
      },
    },
    {
      key: "SyncStrikeCallofDawnDMG",
      label: "Sync Strike: Call of Dawn DMG",
      type: "Skill",
      talents: {
        "1": "8.22%*3+57.48%",
        "2": "8.89%*3+62.20%",
        "3": "9.56%*3+66.91%",
        "4": "10.51%*3+73.51%",
        "5": "11.18%*3+78.22%",
        "6": "11.95%*3+83.64%",
        "7": "13.03%*3+91.18%",
        "8": "14.11%*3+98.72%",
        "9": "15.18%*3+106.26%",
        "10": "16.33%*3+114.28%",
      },
    },
    {
      key: "BasicAttackMechStage1DMG",
      label: "Basic Attack - Mech Stage 1 DMG",
      type: "Basic",
      talents: {
        "1": "11.67%*3",
        "2": "12.63%*3",
        "3": "13.58%*3",
        "4": "14.92%*3",
        "5": "15.88%*3",
        "6": "16.98%*3",
        "7": "18.51%*3",
        "8": "20.04%*3",
        "9": "21.57%*3",
        "10": "23.20%*3",
      },
    },
    {
      key: "BasicAttackMechStage2DMG",
      label: "Basic Attack - Mech Stage 2 DMG",
      type: "Basic",
      talents: {
        "1": "9.34%+37.36%",
        "2": "10.11%+40.42%",
        "3": "10.87%+43.48%",
        "4": "11.95%+47.77%",
        "5": "12.71%+50.83%",
        "6": "13.59%+54.36%",
        "7": "14.82%+59.26%",
        "8": "16.04%+64.16%",
        "9": "17.27%+69.06%",
        "10": "18.57%+74.26%",
      },
    },
    {
      key: "BasicAttackMechStage3DMG",
      label: "Basic Attack - Mech Stage 3 DMG",
      type: "Basic",
      talents: {
        "1": "1.96%*6+41.02%+5.86%",
        "2": "2.12%*6+44.38%+6.34%",
        "3": "2.28%*6+47.74%+6.82%",
        "4": "2.50%*6+52.45%+7.50%",
        "5": "2.66%*6+55.82%+7.98%",
        "6": "2.85%*6+59.68%+8.53%",
        "7": "3.10%*6+65.06%+9.30%",
        "8": "3.36%*6+70.44%+10.07%",
        "9": "3.62%*6+75.83%+10.84%",
        "10": "3.89%*6+81.54%+11.65%",
      },
    },
    {
      key: "BasicAttackMechStage4DMG",
      label: "Basic Attack - Mech Stage 4 DMG",
      type: "Basic",
      talents: {
        "1": "20.31%+47.39%",
        "2": "21.98%+51.27%",
        "3": "23.64%+55.16%",
        "4": "25.97%+60.60%",
        "5": "27.64%+64.48%",
        "6": "29.55%+68.95%",
        "7": "32.22%+75.17%",
        "8": "34.88%+81.39%",
        "9": "37.55%+87.60%",
        "10": "40.38%+94.21%",
      },
    },
    {
      key: "HeavyAttackMechChargedIDMG",
      label: "Heavy Attack - Mech Charged I DMG",
      type: "Liberation",
      talents: {
        "1": "46.69%",
        "2": "50.52%",
        "3": "54.35%",
        "4": "59.71%",
        "5": "63.54%",
        "6": "67.94%",
        "7": "74.07%",
        "8": "80.20%",
        "9": "86.32%",
        "10": "92.83%",
      },
    },
    {
      key: "HeavyAttackMechChargedIIDMG",
      label: "Heavy Attack - Mech Charged II DMG",
      type: "Liberation",
      talents: {
        "1": "116.69%",
        "2": "126.26%",
        "3": "135.83%",
        "4": "149.23%",
        "5": "158.80%",
        "6": "169.80%",
        "7": "185.11%",
        "8": "200.42%",
        "9": "215.73%",
        "10": "232.00%",
      },
    },
    {
      key: "MidAirAttackMechDMG",
      label: "Mid-air Attack - Mech DMG",
      type: "Basic",
      talents: {
        "1": "36.89%+2.17%*3",
        "2": "39.92%+2.35%*3",
        "3": "42.94%+2.53%*3",
        "4": "47.18%+2.78%*3",
        "5": "50.20%+2.96%*3",
        "6": "53.68%+3.16%*3",
        "7": "58.52%+3.45%*3",
        "8": "63.36%+3.73%*3",
        "9": "68.20%+4.02%*3",
        "10": "73.35%+4.32%*3",
      },
    },
    {
      key: "DodgeCounterMechDMG",
      label: "Dodge Counter - Mech DMG",
      type: "Basic",
      talents: {
        "1": "4.76%*6+99.82%+14.26%",
        "2": "5.15%*6+108.00%+15.43%",
        "3": "5.54%*6+116.19%+16.60%",
        "4": "6.08%*6+127.65%+18.24%",
        "5": "6.47%*6+135.83%+19.41%",
        "6": "6.92%*6+145.24%+20.75%",
        "7": "7.54%*6+158.34%+22.62%",
        "8": "8.17%*6+171.43%+24.49%",
        "9": "8.79%*6+184.53%+26.37%",
        "10": "9.45%*6+198.44%+28.35%",
      },
    },
  ],
};
