export const buffs = [
  {
    key: `Sunburst`,
    name: `Sunburst`,
    details: `The <span class="Highlight">Spectro Frazzle</span> DMG dealt by Zani to the target is Amplified by 20%.`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "DMGDeepen:SpectroFrazzle",
        modifierValue: 0.2,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InfernoMode`,
    name: `Inferno Mode`,
    details: `When in <span class="Highlight">Inferno Mode</span>, the DMG Multiplier of Basic Attack is increased.`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "talentModifierMultiply",
        modifySpecificTalents: [
          "Stage1DMG",
          "Stage2DMG",
          "Stage3DMG",
          "Stage4DMG",
          "BreakthroughDMG",
          "PlungingAttackDMG",
          "DodgeCounterDMG",
        ],
        modifierValue: 0.25,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `HeliacalEmber`,
    name: `Heliacal Ember`,
    details: `Outro Skill: Beacon For the Future - Each stack increases the DMG dealt by 10%.`,
    hasStacks: true,
    modifiers: [
      {
        modifySpecificTalents: ["OutroSkillBeaconFortheFutureDMG"],
        modifierValue: 0.1,
      },
    ],
    minStacks: 0,
    maxStacks: 60,
    alwaysEnabled: false,
  },
  {
    key: `HeavySlashNightfallBlazeStacks`,
    name: `Heavy Slash - Nightfall Blaze Stacks`,
    details: `Consuming up to 40 Blazes on hit, with each Blaze increasing the DMG Multiplier of <span class="Highlight">Heavy Slash - Nightfall</span>`,
    hasStacks: true,
    modifiers: [
      {
        modifier: "Talent",
        modifierTalentKey: "HeavySlashNightfallDMG",
        modifierValue: {
          "1": 0.05,
          "2": 0.0541,
          "3": 0.0582,
          "4": 0.064,
          "5": 0.0681,
          "6": 0.0728,
          "7": 0.0794,
          "8": 0.0859,
          "9": 0.0925,
          "10": 0.0995,
        },
        modifierValueTalentRef: "forte",
      },
    ],
    minStacks: 0,
    maxStacks: 40,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillTrueNamesInvoked`,
    name: `Inherent Skill: True Names Invoked`,
    details: `test`,
    hasStacks: false,
    modifiers: [],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: `InherentSkillTrueNamesAligned`,
    name: `Inherent Skill: True Names Aligned`,
    details: `test`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "Aero",
        modifierValue: 0.03,
      },
      {
        modifier: "EchoDMGBonus",
        modifierValue: 0.03,
      },
    ],
    minStacks: 0,
    maxStacks: 6,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate1",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate2",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 1.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.012,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate3",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusCritRate4",
    name: "Stat Bonus: Crit. Rate+",
    details: `<div class="skilldescription">Crit. Rate increased by 2.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "CritRate",
        modifierValue: 0.028,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK1",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK2",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 1.80%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.018,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK3",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
  {
    key: "StatBonusATK4",
    name: "Stat Bonus: ATK+",
    details: `<div class="skilldescription">ATK increased by 4.20%.</div>`,
    hasStacks: false,
    modifiers: [
      {
        modifier: "ATK",
        modifierValue: 0.042,
      },
    ],
    minStacks: 0,
    maxStacks: 0,
    alwaysEnabled: false,
  },
];
