export const forteCircuitAttacks = {
  name: "Forte Circuit: Within Infinity's Embrace",
  description: `<div><span class="Title">Heavy Attack - Schemata of Runes</span><br><span class="Highlight">Hold Normal Attack</span> to consume two <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141201">Runes</span></span> and cast <span class="Highlight">Heavy Attack - Schemata of Runes</span>, dealing <span style="color:#c7ffed" ;="">Aero DMG</span>. Based on the types of the <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141201">Runes</span></span> consumed, Sigrika gains the following effects:<br>- When consuming <span class="Highlight">Rune: Trust</span> and <span class="Highlight">Rune: Answer</span>, this skill gains the effect of <span class="Highlight">Runic Outburst</span>.<br>- When consuming two <span class="Highlight">Runes: Trust</span>, this skill gains the effect of <span class="Highlight">Runic Chain Whip</span>.<br>- When consuming two <span class="Highlight">Runes: Answer</span>, this skill gains the effect of <span class="Highlight">Runic Soliskin</span>.<br>When consuming <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141201">Runes</span></span>, if Sigrika holds at least 30 points of <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141206">Soliskin Vitality</span></span>, consume 30 points to increase the DMG Multipliers of the current <span class="Highlight">Runic Outburst</span>, <span class="Highlight">Runic Chain Whip</span>, and <span class="Highlight">Runic Soliskin</span> by 50%. Obtain a stack of <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141203">Innate Gift?</span></span>.<br>When consuming <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141201">Runes</span></span>, if <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141206">Soliskin Vitality</span></span> is lower than 30 points, consume all <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141206">Soliskin Vitality</span></span>. Every 10 points of <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141206">Soliskin Vitality</span></span> consumed grants the current <span class="Highlight">Runic Outburst</span>, <span class="Highlight">Runic Chain Whip</span>, and <span class="Highlight">Runic Soliskin</span> 15% DMG Amplification.<br><span class="Highlight">Heavy Attack - Schemata of Runes</span> deals Echo Skill DMG.<br><br><span class="Title">Runic Outburst</span><br>Deal <span style="color:#c7ffed" ;="">Aero DMG</span> (considered Echo Skill DMG).<br><br><span class="Title">Runic Chain Whip</span><br>Stagnate nearby targets and deal <span style="color:#c7ffed" ;="">Aero DMG</span> (considered Echo Skill DMG).<br><br><span class="Title">Runic Soliskin</span><br>Pull in nearby targets and deal <span style="color:#c7ffed" ;="">Aero DMG</span> (considered Echo Skill DMG).<br><br><span class="Title">Forte Circuit - Learn My True Name</span><br>When <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141202">Full Stop</span></span> reaches 100 points, if <span class="Highlight">Forte Circuit - Learn My True Name</span> is not on Cooldown, press Resonance Skill to cast <span class="Highlight">Resonance Skill - BOOMY BOOM!</span> or <span class="Highlight">Resonance Skill - Soliskin to the Aid</span>. <span class="Highlight">Hold Resonance Skill</span> to consume all <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141202">Full Stop</span></span> to cast <span class="Highlight">Forte Circuit - Learn My True Name</span>, dealing <span style="color:#c7ffed" ;="">Aero DMG</span> (considered Echo Skill DMG).<br><br><span class="Title">Innate Gift?</span><br>Sigrika can hold up to 2 stacks of <span class="Highlight">Innate Gift?</span>. Each stack grants <span class="Highlight">Runic Outburst</span>, <span class="Highlight">Runic Chain Whip</span>, <span class="Highlight">Runic Soliskin</span> and <span class="Highlight">Forte Circuit - Learn My True Name</span> 30% DMG Amplification.<br>This effect ends after Sigrika casts <span class="Highlight">Forte Circuit - Learn My True Name</span> or is switched off the field.<br><br><span class="Title">Rune</span><br>Sigrika holds up to <span class="Highlight">4 Runes</span>. Without <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141202">Full Stop</span></span>, Sigrika can only hold up to <span class="Highlight">2 Runes</span>. When Sigrika gains a new <span class="Highlight">Rune</span> at max capacity, the existing <span class="Highlight">Runes</span> shift one slot to the left, removing the leftmost <span class="Highlight">Rune</span>. With at least 50 points of <span class="Highlight"><span class="term-reference-link cursor-pointer" data-term-id="141202">Full Stop</span></span>, Sigrika can hold 2 additional Runes.<br>Hitting a target with <span class="Highlight">Basic Attack - Elucidated</span> or <span class="Highlight">Dodge Counter - Decipher</span> grants one <span class="Highlight">Rune: Trust</span>.<br>Hitting a target with <span class="Highlight">Resonance Skill - BIG BOOMY BOOM!</span> or <span class="Highlight">Resonance Skill - Soliskin to the Aid</span> grants one <span class="Highlight">Rune: Answer</span>.<br><br><span class="Title">Full Stop</span><br>After casting <span class="Highlight">Heavy Attack - Schemata of Runes</span>, gain 50 points of <span class="Highlight">Full Stop</span>.<br><br><span class="Title">Soliskin Vitality</span><br>When any nearby Resonators in the team cast Echo Skill, Sigrika gains 10 points of <span class="Highlight">Soliskin Vitality</span>, up to 60 points. Echoes with the same name can only trigger this effect once. Casting <span class="Highlight">Outro Skill - In This Very Moment</span> resets the record of Echo triggering this effect.</div>`,
  attacks: [
    {
      key: "HeavyAttackSchemataofRunesDMG",
      label: "Heavy Attack - Schemata of Runes DMG",
      talents: {
        "1": "66.65%",
        "2": "72.12%",
        "3": "77.59%",
        "4": "85.24%",
        "5": "90.70%",
        "6": "96.99%",
        "7": "105.73%",
        "8": "114.48%",
        "9": "123.22%",
        "10": "132.51%",
      },
      type: "Echo",
    },
    {
      key: "RunicOutburstDMG",
      label: "Runic Outburst DMG",
      talents: {
        "1": "59.19%+103.58%+133.17%",
        "2": "64.04%+112.07%+144.09%",
        "3": "68.90%+120.57%+155.01%",
        "4": "75.69%+132.46%+170.30%",
        "5": "80.54%+140.95%+181.22%",
        "6": "86.13%+150.72%+193.78%",
        "7": "93.89%+164.30%+211.25%",
        "8": "101.66%+177.89%+228.72%",
        "9": "109.42%+191.48%+246.19%",
        "10": "117.67%+205.92%+264.75%",
      },
      type: "Echo",
    },
    {
      key: "RunicChainWhipDMG",
      label: "Runic Chain Whip DMG",
      talents: {
        "1": "25.00%*4+33.33%*3",
        "2": "27.05%*4+36.06%*3",
        "3": "29.10%*4+38.80%*3",
        "4": "31.97%*4+42.62%*3",
        "5": "34.02%*4+45.35%*3",
        "6": "36.37%*4+48.50%*3",
        "7": "39.65%*4+52.87%*3",
        "8": "42.93%*4+57.24%*3",
        "9": "46.21%*4+61.61%*3",
        "10": "49.70%*4+66.26%*3",
      },
      type: "Echo",
    },
    {
      key: "RunicSoliskinDMG",
      label: "Runic Soliskin DMG",
      talents: {
        "1": "20.00%+30.00%*4+59.99%",
        "2": "21.64%+32.46%*4+64.91%",
        "3": "23.28%+34.92%*4+69.83%",
        "4": "25.57%+38.36%*4+76.71%",
        "5": "27.21%+40.82%*4+81.63%",
        "6": "29.10%+43.65%*4+87.29%",
        "7": "31.72%+47.58%*4+95.16%",
        "8": "34.35%+51.52%*4+103.03%",
        "9": "36.97%+55.45%*4+110.90%",
        "10": "39.76%+59.63%*4+119.26%",
      },
      type: "Echo",
    },
    {
      key: "ForteCircuitLearnMyTrueNameDMG",
      label: "Forte Circuit - Learn My True Name DMG",
      talents: {
        "1": "152.35%+457.03%",
        "2": "164.84%+494.50%",
        "3": "177.33%+531.98%",
        "4": "194.82%+584.44%",
        "5": "207.31%+621.92%",
        "6": "221.68%+665.02%",
        "7": "241.66%+724.98%",
        "8": "261.65%+784.94%",
        "9": "281.64%+844.90%",
        "10": "302.87%+908.61%",
      },
      type: "Echo",
    },
  ],
};
