export const rotations: RotationPreset[] = [
  {
      name: `Standard rotation`,
      description: `Standard rotation`,
      author: `Prydwen`,
      data: {"name":"Standard rotation","description":"","actions":[{"order":1,"key":"SolswornEtymologyDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":2,"key":"BasicAttackStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":3,"key":"BasicAttackStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":4,"key":"BasicAttackStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":5,"key":"BasicAttackElucidatedDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":6,"key":"RunicChainWhipDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":7,"key":"WhereTrustLeadsMeDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":8,"key":"BasicAttackStage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":9,"key":"BasicAttackStage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":10,"key":"BasicAttackStage4DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":11,"key":"BasicAttackElucidatedDMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":12,"key":"RunicOutburstDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":13,"key":"ForteCircuitLearnMyTrueNameDMG","type":"forteCircuit","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":14,"key":"InThisVeryMomentDMG","type":"outro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":15,"key":"TuneBreakDMG","type":"tuneBreak","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false},{"order":16,"key":"NamelessExplorerAttacksDMG","type":"echoAttacks","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"excludeWeaponBuffs":false,"isDisabled":false,"mainEcho":"NamelessExplorer","mainEchoRank":5}],"echo":"NamelessExplorer"}
  },
];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x ATK Sound of True Name Build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 46% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"NamelessExplorer","echoSet":"SoundofTrueName","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2},"1":{"type":3,"echo":"SabercatProwler","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2},"2":{"type":3,"echo":"SpacetrekExplorer","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"BasicAttackDMGBonus","echoSubStatsValue3":8.6,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"FloraDrone","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"BasicAttackDMGBonus","echoSubStatsValue3":8.6,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"4":{"type":1,"echo":"ZipZap","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"NamelessExplorer","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x ATK Sound of True Name Build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Basic, 100 ATK, 46% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":4,"echo":"NamelessExplorer","echoSet":"SoundofTrueName","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2},"1":{"type":3,"echo":"SabercatProwler","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":9.2},"2":{"type":3,"echo":"SpacetrekExplorer","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"BasicAttackDMGBonus","echoSubStatsValue3":8.6,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"3":{"type":1,"echo":"FloraDrone","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"BasicAttackDMGBonus","echoSubStatsValue3":8.6,"echoSubStatsType4":"EnergyRegen","echoSubStatsValue4":9.2,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6},"4":{"type":1,"echo":"ZipZap","echoSet":"SoundofTrueName","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"EnergyRegen","echoSubStatsValue3":9.2,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP","echoSubStatsValue5":8.6}},"mainEcho":{"echo":"NamelessExplorer","rank":5}}
    },
];
