export const rotations: RotationPreset[] = [
    {
        name: `Untitled Rotation`,
        description: ``,
        author: `dragonhunter0782`,
        data: {"name":"Untitled Rotation","description":"","actions":[{"order":1,"key":"StandardDefenseProtocolDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":true,"isDisabled":false},{"order":2,"key":"ImmediateExecutionDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"StandardDefenseProtocolDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"Stage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"Stage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"Stage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"RekindleDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"HeavySlashDaybreakDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"HeavySlashDawningDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"HeavySlashNightfallDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"TheLastStandDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"OutroSkillBeaconFortheFutureDMG","type":"outro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    },
];

export const echoes = [
    {
        name: `Standard CR Build`,
        description: `43311 CR / 2x Spectro Eternal Radiance Build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 15.2% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":3,"echo":"Capitaneus","echoSet":"EternalRadiance","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":7.6,"stat":"Spectro"},"1":{"type":4,"echo":"NightmareMourningAix","echoSet":"EternalRadiance","stat":"CritRate","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"HeavyAttackDMGBonus","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"2":{"type":3,"echo":"AbyssalMercator","echoSet":"EternalRadiance","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HeavyAttackDMGBonus","echoSubStatsValue4":8.6,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":7.6},"3":{"type":1,"echo":"AeroPrism","echoSet":"EternalRadiance","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":430,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9,"stat":"ATK"},"4":{"type":1,"echo":"FaeIgnis","echoSet":"EternalRadiance","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":430}},"mainEcho":{"echo":"Capitaneus","rank":5}}
    },
    {
        name: `Standard CD Build`,
        description: `43311 CD / 2x Spectro Eternal Radiance Build. 40.5% CR, 81% CD, 17.2% ATK, 17.2% Heavy, 100 ATK, 15.2% ER`,
        author: `lavasnake`,
        data: {"echoes":{"0":{"type":3,"echo":"Capitaneus","echoSet":"EternalRadiance","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"ATK_FLAT","echoSubStatsValue4":50,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":7.6,"stat":"Spectro"},"1":{"type":4,"echo":"NightmareMourningAix","echoSet":"EternalRadiance","stat":"CritDMG","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK","echoSubStatsValue3":8.6,"echoSubStatsType4":"HeavyAttackDMGBonus","echoSubStatsValue4":8.6,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9},"2":{"type":3,"echo":"AbyssalMercator","echoSet":"EternalRadiance","stat":"Spectro","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"ATK_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"HeavyAttackDMGBonus","echoSubStatsValue4":8.6,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":7.6},"3":{"type":1,"echo":"AeroPrism","echoSet":"EternalRadiance","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"HP","echoSubStatsValue3":8.6,"echoSubStatsType4":"HP_FLAT","echoSubStatsValue4":430,"echoSubStatsType5":"DEF","echoSubStatsValue5":10.9,"stat":"ATK"},"4":{"type":1,"echo":"FaeIgnis","echoSet":"EternalRadiance","stat":"ATK","echoSubStatsType1":"CritRate","echoSubStatsValue1":8.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"DEF","echoSubStatsValue4":10.9,"echoSubStatsType5":"HP_FLAT","echoSubStatsValue5":430}},"mainEcho":{"echo":"Capitaneus","rank":5}}
    }
];