export const rotations: RotationPreset[] = [
    {
        name: `Untitled Rotation`,
        description: ``,
        author: `dragonhunter0782`,
        data: {"name":"Untitled Rotation","description":"","actions":[{"order":1,"key":"StandardDefenseProtocolDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":true,"isDisabled":false},{"order":2,"key":"ImmediateExecutionDMG","type":"intro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":3,"key":"StandardDefenseProtocolDMG","type":"skill","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":4,"key":"Stage1DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":5,"key":"Stage2DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":6,"key":"Stage3DMG","type":"basic","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":7,"key":"RekindleDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":8,"key":"HeavySlashDaybreakDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":9,"key":"HeavySlashDawningDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":10,"key":"HeavySlashNightfallDMG","type":"forteCircuit","count":"2","buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":11,"key":"TheLastStandDMG","type":"liberation","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false},{"order":12,"key":"OutroSkillBeaconFortheFutureDMG","type":"outro","count":1,"buffs":[],"excludeSelfBuffs":false,"excludeTeamBuffs":false,"isDisabled":false}]}
    },
];

export const echoes = [
    {
        name: `Standard TC`,
        description: `Standard TC echo build`,
        author: `lavasnake`,
        data: {"echoes":[{"echo":"Capitaneus","type":3,"rank":5,"stat":"Spectro","echoId":null,"echoSet":"GustsofWelkin","echoSubStatsType1":"CritDMG","echoSubStatsValue1":12.6,"echoSubStatsType2":"BasicAttackDMGBonus","echoSubStatsValue2":6.4,"echoSubStatsType3":"HP","echoSubStatsValue3":6.4,"echoSubStatsType4":"CritRate","echoSubStatsValue4":7.5,"echoSubStatsType5":"ResonanceLiberationDMGBonus","echoSubStatsValue5":8.6},{"echo":"NightmareMourningAix","type":4,"rank":5,"stat":"CritDMG","echoId":null,"echoSet":"EternalRadiance","echoSubStatsType1":"ResonanceLiberationDMGBonus","echoSubStatsValue1":7.1,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":13.8,"echoSubStatsType3":"ResonanceSkillDMGBonus","echoSubStatsValue3":10.1,"echoSubStatsType4":"BasicAttackDMGBonus","echoSubStatsValue4":11.6,"echoSubStatsType5":"EnergyRegen","echoSubStatsValue5":7.6},{"echo":"DiurnusKnight","type":3,"rank":5,"stat":"Spectro","echoId":null,"echoSet":"EternalRadiance","echoSubStatsType1":"ATK_FLAT","echoSubStatsValue1":50,"echoSubStatsType2":"CritDMG","echoSubStatsValue2":16.2,"echoSubStatsType3":"DEF_FLAT","echoSubStatsValue3":50,"echoSubStatsType4":"ATK","echoSubStatsValue4":7.9,"echoSubStatsType5":"CritRate","echoSubStatsValue5":10.5},{"echo":"FaeIgnis","type":1,"rank":5,"stat":"ATK","echoId":null,"echoSet":"EternalRadiance","echoSubStatsType1":"CritDMG","echoSubStatsValue1":21,"echoSubStatsType2":"ResonanceSkillDMGBonus","echoSubStatsValue2":11.6,"echoSubStatsType3":"ATK","echoSubStatsValue3":7.9,"echoSubStatsType4":"ResonanceLiberationDMGBonus","echoSubStatsValue4":9.4,"echoSubStatsType5":"CritRate","echoSubStatsValue5":9.3},{"echo":"ChopChopHeadless","type":1,"rank":5,"stat":"ATK","echoId":null,"echoSet":"EternalRadiance","echoSubStatsType1":"DEF_FLAT","echoSubStatsValue1":60,"echoSubStatsType2":"EnergyRegen","echoSubStatsValue2":10,"echoSubStatsType3":"CritDMG","echoSubStatsValue3":12.6,"echoSubStatsType4":"CritRate","echoSubStatsValue4":7.5,"echoSubStatsType5":"HP","echoSubStatsValue5":7.9}],"mainEcho":{"echo":"Capitaneus","rank":5}}
    }
]