export const rotations: RotationPreset[] = [
  {
    name: `Ciaconna Prydwen Rotation`,
    description: ``,
    author: `Kashi`,
    data: {
      name: "Ciaconna Prydwen Rotation",
      description: "",
      actions: [
        {
          order: 3,
          key: "MidairAttackStage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 4,
          key: "MidairAttackStage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 5,
          key: "Stage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 6,
          key: "MidairAttackStage1DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 7,
          key: "MidairAttackStage2DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 8,
          key: "Stage4DMG",
          type: "basic",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 9,
          key: "RoamingwiththeWindDMG",
          type: "intro",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 10,
          key: "WindcleaverDMG",
          type: "echoAttacks",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
          mainEcho: "ReminiscenceFleurdelys",
          mainEchoRank: 5,
        },
        {
          order: 11,
          key: "HarmonicAllegroDMG",
          type: "skill",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "QuadrupleDownbeatDMG",
          type: "forteCircuit",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 11,
          key: "ImprovisedSymphonicPoemSkillDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
        {
          order: 12,
          key: "SymphonicPoemTonicDMG",
          type: "liberation",
          count: 1,
          buffs: [],
          excludeSelfBuffs: false,
          excludeTeamBuffs: false,
          excludeWeaponBuffs: false,
          isDisabled: false,
        },
      ],
      echo: "ReminiscenceFleurdelys",
    },
  },
];

export const echoes = [];
