export const forteCircuitAttacks = {
  name: "Forte Circuit: Ignis Lupa",
  description: `<div class="skilldescription"><span class="Title">Wildfire Banner</span><br>Lupa's ATK is increased by 12% by 8s when performing the following actions:<br>- Casting Resonance Skill <span class="Highlight">Feral Fang</span>.<br>- Casting <span class="Highlight">Heavy Attack - Wolf's Gnawing</span>, <span class="Highlight">Heavy Attack - Wolf's Claw</span>, or <span class="Highlight">Mid-air Attack - Firestrike</span>.<br>- Casting Resonance Liberation <span class="Highlight">Fire-Kissed Glory</span>.<br>- Casting <span class="Highlight">Dance With the Wolf</span> and <span class="Highlight">Dance With the Wolf - Climax</span>.<br><span class="Title">Dance With the Wolf</span><br>When Wolfaith reaches 2 points, Resonance Skill is replaced with <span class="Highlight">Dance With the Wolf</span>. Performing <span class="Highlight">Dance With the Wolf</span> consumes all Wolfaith, dealing <span class="Fire">Fusion DMG</span> (considered Resonance Liberation DMG).<br>Can be performed in mid-air close to the ground.<br><span class="Title">Dance With the Wolf - Climax</span><br>When Wolfaith reaches 2 points in the <span class="Highlight">Burning Matchpoint</span> state, Resonance Skill is replaced with <span class="Highlight">Dance With the Wolf - Climax</span>. Performing <span class="Highlight">Dance With the Wolf - Climax</span> consumes all Wolfaith, dealing <span class="Fire">Fusion DMG</span> (considered Resonance Liberation DMG). <span class="Highlight">Burning Matchpoint</span> is removed when the skill ends.<br>Can be performed in mid-air close to the ground.<br><span class="Title">Set the Arena Ablaze</span><br>Within 8s after performing <span class="Highlight">Dance With the Wolf</span> or <span class="Highlight">Dance With the Wolf - Climax</span>, Lupa will remain on the field and back up the active Resonator when they perform <span class="Highlight">Resonance Liberation</span>, dealing <span class="Fire">Fusion DMG</span>, considered Resonance Skill DMG. This effect can only be triggered once in the duration.<br><span class="Title">Wolflame</span><br>Lupa can hold up to 100 points of Wolflame.<br>- Restore Wolflame when Normal Attacks hit the target.<br>- Restore Wolflame while casting Resonance Skill.<br>- Restore Wolflame while casting Resonance Liberation.<br><span class="Title">Wolfaith</span><br>Lupa can hold up to 2 points of Wolfaith.<br>Wolfaith lasts for 10s. The duration is reset when Wolfaith is restored. At the end of its duration, each remaining point of Wolfaith becomes 50 points of Wolflame.<br>- Restore 1 points of Wolfaith when casting <span class="Highlight">Heavy Attack - Wolf's Gnawing</span>, <span class="Highlight">Heavy Attack - Wolf's Claw</span>, or <span class="Highlight">Mid-air Attack - Firestrike</span>.</div>`,
  attacks: [
    {
      key: "DanceWiththeWolfDMG",
      label: "Dance With the Wolf DMG",
      talents: {
        "1": "28.18% + 21.14%*4 + 169.06%",
        "2": "30.49% + 22.87%*4 + 182.93%",
        "3": "32.80% + 24.60%*4 + 196.79%",
        "4": "36.04% + 27.03%*4 + 216.20%",
        "5": "38.35% + 28.76%*4 + 230.06%",
        "6": "41.00% + 30.75%*4 + 246.00%",
        "7": "44.70% + 33.53%*4 + 268.18%",
        "8": "48.40% + 36.30%*4 + 290.36%",
        "9": "52.09% + 39.07%*4 + 312.54%",
        "10": "56.02% + 42.02%*4 + 336.11%",
      },
      type: "Liberation",
    },
    {
      key: "DanceWiththeWolfClimaxDMG",
      label: "Dance With the Wolf - Climax DMG",
      talents: {
        "1": "38.04% + 28.53%*4 + 228.23%",
        "2": "41.16% + 30.87%*4 + 246.95%",
        "3": "44.28% + 33.21%*4 + 265.66%",
        "4": "48.65% + 36.49%*4 + 291.86%",
        "5": "51.77% + 38.83%*4 + 310.58%",
        "6": "55.35% + 41.52%*4 + 332.10%",
        "7": "60.34% + 45.26%*4 + 362.04%",
        "8": "65.34% + 49.00%*4 + 391.99%",
        "9": "70.33% + 52.75%*4 + 421.93%",
        "10": "75.63% + 56.72%*4 + 453.75%",
      },
      type: "Liberation",
    },
    {
      key: "SettheArenaAblazeDMG",
      label: "Set the Arena Ablaze DMG",
      talents: {
        "1": "21.31% + 85.21%",
        "2": "23.05% + 92.20%",
        "3": "24.80% + 99.18%",
        "4": "27.25% + 108.97%",
        "5": "28.99% + 115.95%",
        "6": "31.00% + 123.99%",
        "7": "33.80% + 135.17%",
        "8": "36.59% + 146.34%",
        "9": "39.38% + 157.52%",
        "10": "42.35% + 169.40%",
      },
      type: "Skill",
    },
  ],
};
