export const forteCircuitAttacks = {
  name: "Forte Circuit: Unification of Spirits",
  description: `<div class="skilldescription"><span class="Title">Heavy Attack: Glorious Plunge</span><br>When "Lion's Spirit" is full, use <span class="Highlight">Heavy Attack</span> to perform <span class="Highlight">Glorious Plunge</span>, dealing <span class="Ice">Glacio DMG</span>.<br> <br><span class="Title">Mid-air Attack: Tail Strike</span><br>When "Lion's Spirit" is not full, use <span class="Highlight">Basic Attack</span> after <span class="Highlight">Heavy Attack</span> to perform <span class="Highlight">Tail Strike</span>, dealing <span class="Ice">Glacio DMG</span>.<br> <br><span class="Title">Striding Lion</span><br>After casting Heavy Attack <span class="Highlight">Glorious Plunge</span>, enter <span class="Highlight">Striding Lion</span> state;<br>After casting Intro Skill <span class="Highlight">Lion Awakens</span> or Resonance Liberation <span class="Highlight">Strive: Lion's Vigor</span>, if "Lion's Spirit" is full, use <span class="Highlight">Basic Attack</span> to enter <span class="Highlight">Striding Lion</span> state.<br>In the <span class="Highlight">Striding Lion</span> state:<br>-Attacks can be launched in mid-air. If Lingyang is on the ground, use Heavy Attack <span class="Highlight">Glorious Plunge</span> to get back in the air.<br>-"Lion's Spirit" is continuously consumed before running out in 5s, and when it runs out, <span class="Highlight">Striding Lion</span> ends;<br>- If Lingyang is in the Resonance Liberation <span class="Highlight">Lion's Vigor</span> state, the consumption speed of "Lion's Spirit" is reduced by 50%, extending <span class="Highlight">Striding Lion</span> state by up to 10s.<br>-Lingyang's <span class="Highlight">Basic Attack</span> is replaced with Basic Attack <span class="Highlight">Feral Gyrate</span>, which performs up to 2 consecutive attacks, dealing <span class="Ice">Glacio DMG</span>;<br>-Lingyang's <span class="Highlight">Resonance Skill</span> is replaced with <span class="Highlight">Mountain Roamer</span>, dealing <span class="Ice">Glacio DMG</span>;<br>-When "Lion's Spirit" is less than 10, use <span class="Highlight">Basic Attack</span> to perform <span class="Highlight">Stormy Kicks</span>, dealing <span class="Ice">Glacio DMG</span>; after performing Basic Attack <span class="Highlight">Stormy Kicks</span>, the Mid-air Attack <span class="Highlight">Tail Strike</span> becomes available.<br>Concerto Energy is restored when "Lion's Spirit" is consumed.<br> <br><span class="Title">Lion's Spirit</span><br>Lingyang can hold up to 100 "Lion's Spirit".<br>When casting Resonance Skill <span class="Highlight">Furious Punches</span>, "Lion's Spirit" is restored.<br>When casting Intro Skill <span class="Highlight">Lion Awakens</span>, "Lion's Spirit" is restored.<br>When casting Resonance Liberation <span class="Highlight">Strive: Lion's Vigor</span>, "Lion's Spirit" is restored.</div>`,
  attacks: [
    {
      key: "GloriousPlungeDMG",
      label: "Glorious Plunge DMG",
      talents: {
        "1": "86.70%",
        "2": "93.81%",
        "3": "100.92%",
        "4": "110.88%",
        "5": "117.99%",
        "6": "126.16%",
        "7": "137.54%",
        "8": "148.91%",
        "9": "160.29%",
        "10": "172.37%",
      },
      type: "Heavy",
    },
    {
      key: "FeralGyrateStage1DMG",
      label: "Feral Gyrate Stage 1 DMG",
      talents: {
        "1": "43.80%*2 + 58.40%",
        "2": "47.40%*2 + 63.19%",
        "3": "50.99%*2 + 67.98%",
        "4": "56.02%*2 + 74.69%",
        "5": "59.61%*2 + 79.48%",
        "6": "63.74%*2 + 84.98%",
        "7": "69.48%*2 + 92.64%",
        "8": "75.23%*2 + 100.31%",
        "9": "80.98%*2 + 107.97%",
        "10": "87.08%*2 + 116.11%",
      },
      type: "Basic",
    },
    {
      key: "FeralGyrateStage2DMG",
      label: "Feral Gyrate Stage 2 DMG",
      talents: {
        "1": "15.98%*6",
        "2": "17.29%*6",
        "3": "18.60%*6",
        "4": "20.44%*6",
        "5": "21.75%*6",
        "6": "23.26%*6",
        "7": "25.35%*6",
        "8": "27.45%*6",
        "9": "29.55%*6",
        "10": "31.77%*6",
      },
      type: "Basic",
    },
    {
      key: "MountainRoamerDMG",
      label: "Mountain Roamer DMG",
      talents: {
        "1": "41.69%*2",
        "2": "45.11%*2",
        "3": "48.53%*2",
        "4": "53.31%*2",
        "5": "56.73%*2",
        "6": "60.66%*2",
        "7": "66.13%*2",
        "8": "71.60%*2",
        "9": "77.07%*2",
        "10": "82.88%*2",
      },
      type: "Skill",
    },
    {
      key: "StormyKicksDMG",
      label: "Stormy Kicks DMG",
      talents: {
        "1": "18.13%*8 + 96.65%",
        "2": "19.61%*8 + 104.58%",
        "3": "21.10%*8 + 112.51%",
        "4": "23.18%*8 + 123.60%",
        "5": "24.67%*8 + 131.53%",
        "6": "26.37%*8 + 140.64%",
        "7": "28.75%*8 + 153.32%",
        "8": "31.13%*8 + 166.00%",
        "9": "33.51%*8 + 178.68%",
        "10": "36.03%*8 + 192.15%",
      },
      type: "Basic",
    },
    {
      key: "TailStrikeDMG",
      label: "Tail Strike DMG",
      talents: {
        "1": "88.00%*2",
        "2": "95.22%*2",
        "3": "102.44%*2",
        "4": "112.54%*2",
        "5": "119.76%*2",
        "6": "128.05%*2",
        "7": "139.60%*2",
        "8": "151.14%*2",
        "9": "162.69%*2",
        "10": "174.96%*2",
      },
      type: "Basic",
    },
    {
      key: "InherentSkillDiligentPractice",
      label: "Inherent Skill: Diligent Practice DMG",
      talents: {
        "1": "62.54%",
        "2": "67.67%",
        "3": "72.80%",
        "4": "79.97%",
        "5": "85.10%",
        "6": "90.99%",
        "7": "99.20%",
        "8": "107.40%",
        "9": "115.61%",
        "10": "124.32%",
      },
      type: "Skill",
      requiresResonanceChain: "InherentSkillDiligentPractice",
    },
  ],
};
