export const liberationAttacks = {
  name: "Resonance Liberation: Momentary Union",
  description: `<div class="skilldescription">Baizhi summons You'tan to heal all characters on nearby teams, generating 4 stacks of <span class="Highlight">Remnant Entities</span>.<br> <br><span class="Title">Remnant Entities</span><br>Remnant Entities follow the active team members. 1 stack(s) of <span class="Highlight">Remnant Entities</span> are automatically consumed to perform Coordinated Attacks every 2.5s, dealing <span class="Ice">Glacio DMG</span> on hit while healing all characters of the team when the active character is within the range.</div>`,
  attacks: [
    {
      key: "RemnantEntitiesDamage",
      label: "Remnant Entities Damage",
      talents: {
        "1": "2.05%",
        "2": "2.22%",
        "3": "2.39%",
        "4": "2.62%",
        "5": "2.79%",
        "6": "2.98%",
        "7": "3.25%",
        "8": "3.52%",
        "9": "3.79%",
        "10": "4.07%",
      },
      type: "Liberation",
      subType: "Coordinated",
      attribute: "hp",
    },
    {
      key: "RemnantEntitiesHealing",
      label: "Remnant Entities Healing",
      talents: {
        "1": "349 + 1.42%",
        "2": "378 + 1.53%",
        "3": "406 + 1.65%",
        "4": "446 + 1.81%",
        "5": "475 + 1.93%",
        "6": "508 + 2.06%",
        "7": "554 + 2.25%",
        "8": "599 + 2.43%",
        "9": "645 + 2.62%",
        "10": "694 + 2.82%",
      },
      type: "Healing",
      attribute: "hp",
    },
    {
      key: "MomentaryUnionHealing",
      label: "Momentary Union Healing",
      talents: {
        "1": "310 + 1.26%",
        "2": "336 + 1.36%",
        "3": "361 + 1.47%",
        "4": "397 + 1.61%",
        "5": "422 + 1.71%",
        "6": "452 + 1.83%",
        "7": "492 + 2.00%",
        "8": "533 + 2.16%",
        "9": "574 + 2.33%",
        "10": "617 + 2.51%",
      },
      type: "Healing",
      attribute: "hp",
    },
  ],
};
